ministryofjustice/hmpps-approved-premises-api

README.md, script/bootstrap, script/server, script/setup, script/test
This adds some simple scripts to aid running in development. We use these in the frontend application, so it’s useful to mirror this approach in the API too, to aid with context switch. Currently the bootsrap and server scripts are stubs, as there’s nothing we (yet) need to do to bootstrap / setup the app, but they’re worth having around as a reminder to update them when we do start introducing external dependencies, like a database etc.
=> Add scripts to rule them all

.adr-dir, doc/architecture/decisions/0001-use-problem-responses-to-handle-validation-errors.md
This documents the approach we'll take to handling validation errors, using the [RFC-7807 problem spec](https://datatracker.ietf.org/doc/html/rfc7807). This is already handled well in Spring Boot and gives us a reliable and predictable way of reporting errors back to the client
=> Document approach to handling validation errors

src/main/resources/static/mini-manage-api-stubs.yml
I had to upgrade to OpenAPI 3.0 to handle content-type headers on a per-response basis. It makes sense for us to use the latest version anyway.
Error responses now look like this:
=> Update the API response to show errors

src/main/resources/static/mini-manage-api-stubs.yml
We need to return a person's name with a Booking and Arrival
I thought it would make sense to return a Person object which consists of a name and CRN
I'm not sure whether it would make sense to add a Person to the other events whilst I'm here (EG Nonarrival, Departure) - I feel they will need a Person too
[Trello ticket](https://trello.com/c/73Y1jvej/497-displaying-person-on-probations-name-against-a-booking-arrival)
=> (497) Add Person to Arrival and Booking schemas

src/main/resources/static/mini-manage-api-stubs.yml
Rather than providing only the IDs of `probationRegion`, `apArea` and
`localAuthorityArea` we now define schemas for representing these entities
by which premises are grouped.
The UI can now both display their human-readable names and use their IDs
in communications with the API.
```
{
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"name": "Hope House",
"apCode": "NEHOPE1",
"postcode": "LS1 3AD",
"bedCount": 22,
"probationRegion": {
"id": "1500123456",
"name": "NPS North East Central Referrals"
},
"apArea": {
"id": "1500001234",
"name": "Yorkshire & The Humber"
},
"localAuthorityArea": {
"id": "LEEDS",
"name": "Leeds City Council"
}
}
```
=> Refine premises representation

src/main/resources/static/mini-manage-api-stubs.yml
We add endpoints for the following "reference" data:
- `/departure-reasons`
- `/move-on-categories`
- `/destination-providers`
- `/supervising-providers`
- `/supervising-teams`
- `/supervising-officers`
- `/key-workers`
- `/lost-bed-reasons`
This PR also adds "tags" to group the endpoints (in the docs) into
endpoints concerned with:
- premises
- operations on premises
- operations on bookings
- reference data
=> Add "reference data" endpoints

build.gradle.kts, script/generate_migration, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LocalAuthorityAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationRegionEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/repository/PremisesRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApAreaTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/LocalAuthorityAreaTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ProbationRegionTransformer.kt, src/main/resources/db/migration/20220803121537__premises_tables.sql, src/main/resources/logback-spring.xml, src/main/resources/static/mini-manage-api-stubs.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApAreaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LocalAuthorityEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PersistedFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationRegionEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ApAreaTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/LocalAuthorityAreaTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/PremisesTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ProbationRegionTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RandomData.kt
Add migration that creates tables for Premises, Bed, Ap Area, Local Authority Area, Probation Region.
Add JPA entities for those tables.
Implement the GET all premises endpoint.
Also added kotlin-jpa/allOpen plugins which allow JPA to instantiate data classes without us providing a no-args constructor and making all properties nullable.
=> 525 - Add get all premises endpoint

src/main/resources/static/mini-manage-api-stubs.yml
So that OpenAPI generate creates models with correct nullability, set the required properties for the schemas in mini-manage-api-stubs.yml.
=> Add required properties to OpenAPI spec

.circleci/config.yml, README.md, build.gradle.kts, doc/how-to/add_new_endpoint.md, docker-compose.yml, script/get_client_credentials_jwt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ForbiddenProblem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/UnauthenticatedProblem.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AuthTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/JwtAuthHelper.kt, src/test/resources/application-test.yml
Setup Spring Security to protect endpoints, must now present a valid HMPPS Auth JWT.
Added way of generating arbitrary JWTs with the private key that HMPPS Auth uses in the containerized version to be used in the tests - setup tests to use containerized HMPPS Auth.
Added convenience script to get a client_credentials JWT from containerized HMPPS Auth.
=> 528  - Secure endpoints with HMPPS Auth tokens

helm_deploy/approved-premises-api/values.yaml
This adds the `SPRING_DATASOURCE_DRIVERCLASSNAME` as a plaintext env var, and loads the `SPRING_DATASOURCE_URL` secret in the format `jdbc:postgres://${username}:${password}@${endpoint}/${dbname}`
=> Add datasource related env vars

helm_deploy/approved-premises-api/values.yaml
I missed that the JPA datasource urls work differently from the format I’m used to, so rather than tweak it in the cloud platform again, I’dget the individual connection vars from the secret and build the datasource url using interpolation. This also gives us more flexibility further down the line.
=> Specify Datasource url manually

helm_deploy/approved-premises-api/values.yaml
We should be using `${foo}`, not `$(foo)`, as `(` executes
=> Fix interpolation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ArrivalEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DestinationProviderEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LocalAuthorityAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/MoveOnCategoryEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PersonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationRegionEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/repository/BookingRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/repository/DestinationProviderRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/repository/PersonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/repository/PremisesRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/db/migration/20220811100325__pluralize_table_names.sql
Pluralise all of the tables names for consistency with other HMPPS projects.
Move the spring-data interfaces to live alongside their respective JPA models.
=> Table names pluralise

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/CancellationReasonTransformer.kt, src/main/resources/db/migration/20220816105005__create_cancellation_reason.sql, src/main/resources/static/mini-manage-api-stubs.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/CancellationReasonTestRepository.kt
This adds an API endpoint for Cancellation Reasons, following the pattern we already have for reference data. My first Kotlin PR, so be kind! 😄
=> (607) Add a cancellation reasons api endpoint

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApAreaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ArrivalEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DestinationProviderEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/KeyWorkerEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LocalAuthorityEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LostBedsEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/MoveOnCategoryEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NonArrivalEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PersistedFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationRegionEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
Change our derived Factory classes to derive from KFactory's factory directly instead of PersistedFactory.  Change PersistedFactory to be a standalone class that composes a KFactory and a repository.  Configure the factory and produceAndPersist objects in one call which takes a configuration block as second argument.
=> Changes to allow using existing kfactories in both integration and unit tests.

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/static/mini-manage-api-stubs.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
Change get all premises and get premises by ID endpoints to include availableBedsForToday field in response
=> 549 - Add available beds for today field to Premises responses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ExtensionEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ExtensionTransformer.kt, src/main/resources/db/migration/20220817152352__add_booking_extension_table.sql, src/main/resources/static/mini-manage-api-stubs.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ExtensionEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ExtensionTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
Add Extension tables to DB - extend the GET /premises/{id}/bookings endpoint to return the current extensions in the body.
Add POST /premises/{id}/bookings/{booking id}/extensions endpoint to create an extension:
- Extension must be to a date later than the current departure date
=> 599 - Extend Bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/resources/static/mini-manage-api-stubs.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
This adds a `/premises/{premisesId}/bookings/{bookingid}` endpoint to fetch an individual booking for a premises
=> Add an endpoint to fetch a single booking

src/main/resources/application.yml
When a longer-lived-branch is merged after a shorter-lived-branch where both contain a migration a timestamp can be skipped over (i.e. an earlier timestamped migration is deployed later) - this should allow them to still be run.
=> Enable out of order flyway migrations.

helm_deploy/values-dev.yaml
This should be overridden per environment, and is called `approved-premises-api-dev-cert` in dev.
=> Update the certificate secret name

docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/AssessRisksAndNeedsApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/HMPPSTierApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PersonController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/AuthorisableActionResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/PersonRisks.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/assessrisksandneeds/RoshRisks.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/Registrations.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/hmppstier/Tier.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RisksTransformer.kt, src/main/resources/application.yml, src/main/resources/static/mini-manage-api-stubs.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RegistrationClientResponseFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoshRisksClientResponseFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt, src/test/resources/application-test.yml, wiremock/mappings/AssessmentApi_GetLatestCompletedAssessmentNeeds.json, wiremock/mappings/AssessmentApi_GetLatestCompletedAssessmentRoshSectionAnswers.json, wiremock/mappings/HMPPSTier_GetTierForCrn.json
Implement GET /person/{crn}/risks endpoint + tests
This endpoint returns the information needed to populate the [risk widget](https://github.com/ministryofjustice/hmpps-risk-ui-elements) on the frontend.  Each section of the response is enveloped so as to convey any problems fetching each section from the relevant upstream service.
- RoSH data comes from ARNS
- Tier comes from hmpps-tier
- MAPPA comes from Community API
- Flags come from Community API
=> 684 - Expose risk information

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/LostBedReasonTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/LostBedsTransformer.kt, src/main/resources/db/migration/all/20220914094758__add_lost_bed_reasons.sql, src/main/resources/db/migration/all/20220914100140__seed_lost_bed_reasons.sql, src/main/resources/db/migration/all/20220914110825__add_lost_bed_reason_id_to_lost_beds.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LostBedReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LostBedsEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/LostBedReasonTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
This adds the missing `reference-data/lost-bed-reasons` endpoint, as well as seed data to import the reasons.
=> Add lost bed reasons

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/LoggingHandlerInterceptor.kt
/health/liveness and /health/readiness are called by Kubernetes so pollute the logs
=> Don't log health requests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/OffenderDetailSummary.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenderDetailsSummaryFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
Community API returns an empty object for these rather a null (which is actually an object where each property is null, but Jackson is configured to omit null properties on Community API), so nullability needs to be pushed down into the properties on our side.
=> Fix for missing PreviousConvictions & OffenderLanguages in OffenderDetailSummary failing to deserialize

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
Will now return a 403 rather than a 500 when LAO restricted offender requested
=> Handle 403 from Community API userAccess point correctly

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
This ensures they are consistent with the values in the actual Booking model
=> Rename NewBooking arrival and departure dates

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/ContentCachingFilter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeserializationValidationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProblemResponsesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
**Return more detailed problem responses when request bodies that don't conform to the OpenAPI spec are provided**
Jackson (the deserializer used by Spring) fails fast when deserializing into POJO, so it's only possible out of the box to provide the first error encountered during deserialization back to the caller.  This catches those exceptions then uses reflection to check each property and provide more detailed responses.  For this to work, we need to read the input stream more than once, so this also uses ContentCachingRequestWrapper to read the input stream once and cache it for reuse.
**Update existing validation responses to return a JSON Path parameter name**
Currently, all request bodies are simple non-nested objects, but its likely this won't always be the case.  The type …
=> Return detailed problem responses when request body does not conform to OpenAPI spec

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationSchemaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonSchemaService.kt, src/main/resources/db/migration/all/20220921104726__missing_application_primary_key.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonSchemaServiceTest.kt
**Validate against JSON schema when fetching applications**
When retrieving all JSON schemas for a user, test any that were created with an earlier version of the applications schema against the newest version of the application schema.  If they pass the validation, bump their version to the newest schema.
=> 717 - Validate json schema

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ValidatableActionResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ValidationErrors.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
**Added value type for ValidationErrors**
To make it clear that the MutableMap<String, String> we use in quite a lot of places are for validation errors
**Added a DSL for validation**
Reduces boilerplate around validation somewhat and provides a more semantic syntax.
=> Validation errors refactor

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/resources/application-local.yml, src/main/resources/application.yml
Add configuration option `log-client-credentials-jwt-info` which logs the authorities, scope and expiry of client_credentials tokens retrieved from HMPPS Auth.
This is useful for troubleshooting as we have no way currently of knowing for certain which authorities/scopes our service accounts have been given.
=> Config flag to log authorities & scopes

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeserializationValidationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProblemResponsesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
Rather than using sentences for error messages, this updates the error response `errorType`s  to return keys. This makes translating messages in the frontend easier, and gives us more flexibility.
=> Use keys for error messages

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeserializationValidationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProblemResponsesTest.kt
**Return accurate error when failing to deserialize special string types**
LocalDate, LocalDateTime, OffsetDateTime and UUID are all represented as strings in JSON so their deserialization process is different to the other types - handle this case by attempting to parse the values and returning "invalid" if a non-parsable value has been provided.
=> Return accurate error for special string types

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/resources/db/migration/all/20220928150557__add_delius_team_code.sql, src/main/resources/db/migration/local+dev/20220928153424__seed_delius_team_codes.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
**Add Delius Team code to the Premises Entity and add seed values for local+dev.**
This will allow us to query the staff for that team from Delius to support fetching key workers from Delius.
=> 710 - Add Delius Team Code to Premises

docker-compose.test.yml
This sometimes causes failures when switching between branches with different migrations.  Since there's no real utility in having this data be persistent across test runs (it is cleared at the start of every integration test anyway), best to simply remove the volume.
=> Remove persistent volume from test Postgres container

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenderDetailsSummaryFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
This adds the detail of a specific person to all of the Application responses. This involves us having to call the Community and Prisons APIs, so we have guards in place for if either API has problems returning the person detail(s).
This is done using a private method in the controller, the implementation of which is nicked from the BookingsController. I do wonder if this would be better placed in a service, but I think this is fine for now.
I’ve also added the `mockInmateDetailPrisonsApiCall` function, which is used in some other integration tests to the IntegrationTestBase file, so we can use it everywhere.
=> (762) Add person detail to Application responses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/resources/application.yml, src/main/resources/static/domain-events-api.yml
In order to support the flow of data back to Delius the new AP service will
publish [Domain Events](https://dsdmoj.atlassian.net/wiki/spaces/NDSS/pages/3732570166/ADR+-+Domain+Event+Schema)
A key design point is that the Domain Event `messages` published via
SNS/SQS should be "skinny" and provide a link (`"detailUrl"`) to full
Event information exposed via our service's API.
In this PR we make a first attempt at designing AP Domain Events which 
can support Delius' needs. Our understanding is that the highest priority
events are:
1. `application.assessed` -> the decision on eligibility for an AP place must be recorded in Delius
2. `person.arrived` -> the address must be updated in Delius 
3. `person.not-arrived` -> the COM needs to be notified within Delius 
4. `person.departed` -> the …
=> 436 Draft domain events

build.gradle.kts, docker-compose.test.yml, docker-compose.yml, helm_deploy/hmpps-approved-premises-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/config/ClientResultRedisSerializerTest.kt, src/test/resources/application-test.yml
**Add a distributed cache backed by Redis that sits over the Client layer**
The ClientResult values are serialized and stored in Redis.  The cache name is prefixed with the version of the application so that we don't have any issues when deploying a new version where the models we're deserializing into may have changed etc.
- Add a cache over Staff info for 6 hours
- Add a cache over Offender Details (Community API), User Access (Community API), Inmate Details (Prisons API) for 20 minutes
=> 765 - Redis caching for Staff and Offender data

src/main/resources/db/migration/all/20221005143000__add_placeholder_application_schema.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
At the moment, we don’t have a schema to match applications against, so the service fails. This adds a very basic one to get things moving while we define the shape of the schema.
=> Add a basic application schema

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/db/migration/all/20221013143323__add_document_to_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Add a `document` opaque JSON field to applications.
Return this field on the GET endpoints and accept on the PUT.
If `submitted_at` is set, then `document` must also be set.
=> 790 - Allow submitting document alongside application

build.gradle.kts
=> Force org.apache.commons:commons-text to 1.10.0

src/main/resources/static/api.yml
Derived from: https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4189880327/Tech+Day+in+Birmingham+Oct+12+2022#API-Design-for-%22Assess%22-transaction
One notable difference is using probationOfficerId (UUID) rather than Staff Id as we currently use this for the Applications.  This table is populated when an application is created.  We would likely need to switch this so that it's populated by an endpoint that is called each time a user with ROLE_PROBATION logs in to the application - perhaps the node backend could make this call to the API after the authorization code flow is completed?
=> OpenAPI spec for Assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/db/migration/all/20221018133055__extend_users_table.sql, src/main/resources/db/migration/local+dev/20221018133054__clear_existing_users.sql, src/main/resources/db/migration/local+dev/20221018133056__mock_users.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/StaffUserDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonSchemaServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
**Whenever we need a User's details or ID, get their info from Community API if we don't already have it.**
Their name and staff identifier specifically is info that won't change and we will need access to outside the context of them making a request (for allocation.)
=> Get user info from Community API

src/main/resources/static/domain-events-api.yml
This PR is in response to a number of requests which have come through from the Delius team who will be consuming these Domain Events.
There are some outstanding questions to clarify:
This identifies a conviction and is important, we understand, when processing `person.not-arrived` and `person.arrived` domain events. The event ID corresponds to a particular `convictionID` and `index` property as exposed by the Community API and perhaps could be represented in a Domain Event in the form:
```json
"convictionEvent": {
"convictionId": 1502724704,
"index": "7"
}
```
but we need clarification from the integration team that this is truly essential as at present the AP service is not recording this level of conviction information.
It's been suggested that the probation officer who made the …
=> Add legacy reference codes

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/UserOffenderAccess.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
Failing to deserialize because of additional property and default Jackon object mapper - the easiest route is just to include the missing property
=> Fix for 500 when requesting Limited Access Offender

src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
I spotted this whilst doing some work in the UI repo and thought I would fix it upstream.
=> Fix casing of 'address_line_1' so it's consistent with the rest of the spec

doc/architecture/decisions/0007-storing-service-specific-properties.md, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20221025120723__service_specific_properties.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CapacityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/PremisesTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
**Split out PremisesEntity into abstract base class + concrete derived classes**
Common properties remain on PremisesEntity but two derived classes `ApprovedPremisesEntity` and `TemporaryAccommodationPremisesEntity` are created.
There are several ways of achieving this as outlined here: https://thorben-janssen.com/complete-guide-inheritance-strategies-jpa-hibernate
Ultimately went with the `JOINED` option as:
- It allows us to keep referential integrity at the database level for other tables with foreign keys to the premises table - the `TABLE_PER_CLASS` option would have forced us to abandon the FK constraints
- It's neater to navigate and reason about than the `SINGLE_TABLE` option as you can easily see which properties belong to which type
- Performance impact of the join should be …
=> 831 - Service specific Premises types

src/main/resources/db/migration/local+dev/20220913131808__mock_premises.sql, src/main/resources/db/migration/local+dev/20221026113526__move_address_seed_data_to_own_migration.sql
Flyway checks the hash of the migration file on startup, since this migration had already been applied to the dev environment before being modified for address the instances are refusing to startup.
=> Move Address seed data to own migration

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/ConverterConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/convert/EnumConverterFactory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/convert/EnumConverterTest.kt
> See [ticket #445 on the CAS3 Trello board](https://trello.com/c/7gUPFXcB/445-cas1-properties-are-not-viewable-in-view-list-of-properties).
Currently the temporary accommodation landing page displays all properties in the database, regardless of whether they are intended for use by the CAS1 or CAS3 service.
~~This PR provides a way for clients of the API to filter premises by the desired service through the use of a query parameter on the `GET /premises/` endpoint:~~
- ~~`/premises/?service=cas1` returns only premises for CAS1~~
- ~~`/premises/?service=cas3` returns only premises for CAS3~~
This PR provides a way for clients of the API to filter premises by the desired service through the use of a header parameter on the `GET /premises/` endpoint:
- `X-Service-Name: approved-premises` …
=> Add 'X-Service-Name' header parameter to allow filtering of premises by service

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/NotImplementedProblem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20221026110536__make_q_code_required.sql, src/main/resources/db/migration/all/20221026120451__move_ap_code.sql, src/main/resources/db/migration/all/20221026141249__move_delius_team_code.sql, src/main/resources/db/migration/local+dev/20221026110535__seed_q_code.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
These fields aren't relevant for Temporary Accommodation Premises so move them to live only on Approved Premises
=> 831 - Move AP specific properties (Ap Code, Delius Team Code) to be AP specific

src/main/resources/db/migration/all/20220803121538__add_address_column_to_premises_table.sql, src/main/resources/db/migration/all/20221026113525__add_address_column_to_premises_table.sql, src/main/resources/db/migration/all/20221026113527__make_address_not_nullable.sql
First add address column, then run seed update on local/dev, then make column not null.  Because there are already entries in the premises table, cannot add a not null column without a default.
=> Add Address Column in 2 stages

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/static/api.yml
In a nutshell, split the response type from the get all premises and get premises by ID endpoints into 3 entities:
- One containing common properties
- One for AP specific properties that extends the common one
- Another for TA specific properties that extends the common one
Commit messages explain in more detail.
=> Split Premises response body into AP/TA types

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
The `Get All Bookings returns OK with correct body` test sometimes fails locally due to an equality failure:
```
[id=3d953164-7318-4920-aa6e-485747e372d3].departure.dateTime
Expected: 2022-10-30T20:20:34+01:00
got: 2022-10-30T19:20:34Z
```
Whilst these two OffsetDateTimes represent the same point in time - they are not equal as the comparison for OffsetDateTime compares the date-time and the offset parts individually.
This is happening because we are creating OffsetDateTimes in test setup code, then persisting them to the database.  Postgres `TIMESTAMP WITH TIME ZONE` does not actually store the offset but rather uses it to convert the date-time to UTC then discards it.  Consequently, when the application retrieves the values from the database during the test they will be in UTC rather …
=> Fix for OffsetDateTime issue in tests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/RoomEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BedTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RoomTransformer.kt, src/main/resources/db/migration/all/20221027144656__room_tables.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoomEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RoomServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket 418 on the CAS3 Trello board](https://trello.com/c/4qwDVVVa/418-add-a-bedspace-to-a-property).
This PR introduces the `POST /premises/{premisesId}/rooms` endpoint to allow clients to add rooms to a premises.
For CAS3, the concept of a room and a bed have been collapsed into a single concept known as a "bedspace", but are considered distinct for CAS1. To simplify the API interaction from a client's perspective, the `RoomService.createRoom` method will automatically create a bed at the same time as its containing room if the premises is a `TemporaryAccommodationPremisesEntity`. Otherwise, no beds will be created, but `RoomService` also exposes a `createBed` method to allow adding beds to a room at a later time.
=> Implement 'add new room' endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
> See [ticket 489 on the CAS3 Trello board](https://trello.com/c/eWl2EOlL/489-a-user-can-see-all-bedspaces-that-belong-to-a-property).
This PR introduces the `GET /premises/{premisesId}/rooms` endpoint to allow clients to get a list of rooms for a given premises.
=> Implement 'list rooms for premises' endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20220803121542__revise_service_column_default_value.sql, src/main/resources/db/migration/local+dev/20220913131811__temp_accommodation_mock_premises.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
So that properties can be differentiated, a service name is required to be stored against them on creation of a new one. 
This was a little more involved than just passing down the service name, that is now in the header rather than the body, as there has been some work done previously to split out the concrete implementations of a TA property or an AP property.
Where the POST method deals with the service name in the header, is calls down to the service layer which calls a save method on the repo, creating specifically an instance of a TA premises. At this point there's no need to tell it what service to persist as it knows it's a TA instance and so it saves the relevant service name by default.
=> Store service name against a property

src/main/resources/db/migration/local+dev/20220913131811__temp_accommodation_mock_premises.sql, src/main/resources/db/migration/local+dev/20221026113526_1__move_address_seed_data_to_own_migration.sql, src/main/resources/db/migration/local+dev/20221101100330__temporary_accommodation_premises.sql
We have out of order migrations turned on so that we don't need to adjust timestamps when two branches have both got a migration in them and were worked on at similar times such that the earlier timestamped migration ends up being merged into main after the later one.
The original migration to add temporay accommodation Premises was added with a timestamp in the past (`20220913131811__temp_accommodation_mock_premises.sql`) which works fine when running locally as people will just delete the postgres volume if they hit an error then it will work as the migration will be run where it's been slotted into the timeline.
In the dev environment however, all of the previous migrations have already been run so the new migration that's been inserted in the past will run on its own in the present - …
=> Fix ap_code migration issue on dev

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/RoomEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RoomTransformer.kt, src/main/resources/db/migration/all/20221031101732__add_room_characteristics.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CharacteristicEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoomEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RoomServiceTest.kt
> See [ticket #495 on the CAS3 Trello board](https://trello.com/c/YgJCtrWY/495-room-characteristics-can-be-saved).
Currently, when adding a new room to a premises, only a name and some optional notes can be given. To provide additional information about a room, the API will need to provide a way to attach characteristics to a room.
This PR provides support for room characteristics through the following API changes:
- The `NewRoom` schema used to define the request body of the `POST /premises/{premisesId}/rooms` endpoint has been extended to allow the client to specify a list of UUIDS representing characteristics.
- The `Room` schema used in the response body of the `POST /premises/{premisesId/rooms` and the `GET /premises/{premisesId}/rooms` endpoints have been extended to specify the …
=> Add support for room characteristics when getting a list of rooms/creating a new room

src/main/resources/db/migration/local+dev/20221101124300__add_ap_service_name_to_mock_premises.sql
This is a migration script that will update seeded example data so that the service name is 'approved-premises' rather than CAS1. 
By doing so means that example data is more meaningful and useful
=> update service name to be approved premises rather than cas1 so that example seeded data is useful

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
The use of `characteristics` to refer to a list of IDs in the `NewRoom` schema is inconsistently named compared to other situations where IDs are accepted as part of a request body.
This PR renames `NewRoom.characteristics` to `NewRoom.characteristicIds` in the API specification and performs similar renaming for adjacent parts of the code.
=> (Chore) Rename IDs named 'characteristic(s)' to 'characteristicId(s)'

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CharacteristicService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/CharacteristicServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RoomServiceTest.kt
> See [ticket #505 on the CAS3 Trello board](https://trello.com/c/ikNfvcs7/505-refactor-characteristics-to-support-wildcards).
Currently, the logic to validate a characteristic is the responsibility of the `RoomService`, and upcoming work to add characteristics to premises intends to add very similar validation to the `PremisesService`.
Additionally, when a new room is created, any characteristics it is given are only successfully applied if the model scope is `"room"` and the service scope is equal to the value of the `service` column on the relevant premises's table. Characteristics with wildcard scopes (which should always be considered valid) fail to apply.
This PR creates a single point of access for characteristic matching for entities. To do this, the current characteristic …
=> Refactor characteristic scope matching

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20221102102732__add_premises_characteristics.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CharacteristicEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
A premises can have characteristics associated with it such e.g Floor Level Access, etc. For a premises these characteristics need to be persisted in a separate link entity table called '**premises_characteristics**'. 
This is so that it can hold an id reference to the premises and an id reference to the particular characteristic. When a client makes a request to GET a premises then the list of characteristics will be included as it joins the tables together. Any entry present in the premises_characteristics table is implied that it is checked on the UI due to its presence in the table.
=> Premises characteristics can be saved

.circleci/config.yml
#approved-premises-team-dev is no more, and the events channel seems like a better fit
=> Send alerts to the events channel

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/db/migration/all/20221103105357__add_unique_constraint_on_premises_name_and_service.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
> See [ticket #419 on the CAS3 Trello board](https://trello.com/c/jEnXy9cF/491-property-references-are-mandatory).
When creating a new premises, the name is currently optional and if not supplied is set to a default of `"Unknown"`.
This PR removes this default and makes the name mandatory and unique within a service, as from a user perspective enforcing a unique name will assist with identification of premises and reporting metrics.
=> Make premises name mandatory and unique

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/db/migration/all/20221102125322__clarification_notes.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentClarificationNoteEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/JsonSchemaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/AssessmentClarificationNoteTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
**Few small changes to the Assessments Open API spec**
- Add a createdByUserId to clarification notes, so we can tell who has created each note in cases where assessment is reallocated or an admin adds a note to an assessment they are not allocated to
- Remove createdAt from NewClarificationNote - this should be determined by the API rather than trusting user input
- Make data optional on Assessment - this would be null until the first section of the assessment has been completed
**Groundwork for Application Clarification Notes**
Adds a table, entity etc. since these need to be returned with the assessment responses
**Implement GET /assessments**
Returns all assessments if the user is a workflow manager, otherwise returns the ones that are allocated to the user.  If any problems are …
=> 819 - Get all assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
> See [ticket #422 on the CAS3 Trello board](https://trello.com/c/WCaf76xE/422-a-user-can-edit-details-of-a-bedspace).
Currently, the API does not allow rooms to be modified after they have been created. However, a user may wish to update the notes on a room or alter its characteristics.
This PR implements the `PUT /premises/{premisesId}/rooms/{roomId}` endpoint to allow existing rooms to be modified. It accepts an `UpdateRoom` schema in the request body and returns the updated room.
Note that the name of the room is not able to be changed. The CAS3 team believe that this value should be immutable to avoid confusion caused by a change of name (such as in reporting, correspondence, etc.).
=> Implement an 'update room' endpoint

docker-compose.yml
Because Prison API is now using a replica datasource for certain read-only requests we need to point this at the persisted nomis-db directory too
=> Fix for Prison API docker container

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
> See [ticket #521 on the CAS3 Trello board](https://trello.com/c/HUy6KtN1/521-a-user-can-see-details-of-a-bedspace).
Currently, there is no way to get details of a single room in the API. This means that the client has to use the `GET /premises/{premisesId}/rooms` endpoint to get all rooms in a premises, and then filter this list to get a particular room. This is an inconvenience for the implementation of the 'view/edit room details' pages.
This PR provides the `GET /premises/{premisesId}/rooms/{roomId}` endpoint to allow the client to just request the details of a single room, which simplifies the client-side implementation for viewing and editing rooms.
=> Implement 'get room' endpoint

helm_deploy/values-dev.yaml
While we were setting up the new `hmpps-community-accommodation-dev` namespace, we had to temporarily change the domains. Now ministryofjustice/cloud-platform-environments#9190 is in, we can safely switch back
=> Remove `cas` prefix from domain

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20221110102259__add_status_column_to_premises_table.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket #482 on the CAS3 Trello board](https://trello.com/c/ewdT1APV/482-properties-can-have-a-status).
Currently, there is no way to distinguish between premises that are in active service from those that are not yet or no longer active.
This PR modifies the request bodies of the `POST /premises/` and `PUT /premises/{premisesId}/` endpoints to require a `status` field containing one of the following values:
- `"active"`
- `"pending"`
- `"archived"`
The `Premises` schema has also been updated to include this status with the effect that any endpoint that includes a `Premises` in its response body will include the provided status. In the case of premises that already exist on the database, this is given a default value of `"active"`.
=> Add 'status' property to Premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonSchemaService.kt, src/main/resources/db/migration/all/20221114110948__make_application_schema_version_required.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonSchemaServiceTest.kt
**Split out submission endpoint in OpenAPI spec**
No longer use the presence of `submittedAt` on a PUT request to indicate a submission - rather split out a dedicated /submission endpoint for this.  This endpoint also accepts the denormalised JSON document of the application.
**Remove submission logic from PUT endpoint**
Remove the code that creates an assessment when updating an application if `submittedAt` is true.
**Simplify schema outdated checks**
Enforce that all applications must have a schema version.  Do not attempt to upgrade schema versions anymore - this can't work because the JSON blob won't ever pass validation until it is 100% complete.  Instead, on GETs return that the schema is outdated if a new schema version has been released.  
Do not allow updates to applications with …
=> Split out submit endpoint for Applications / Simplify schema version checks

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt, src/main/resources/application.yml
**Change cache TTLs to be in seconds rather than minutes**
**Change team member cache to be 20s in dev**
So that the Integrations team can build their E2E test that adds key workers and asserts they exist in our UI
=> 865 - Reduce team cache to 20 seconds in dev

doc/architecture/decisions/0008-service-specific-applications.md
This is a first draft of an ADR following the work done on [this Spike task](https://trello.com/c/hL6aYQ29/542-spike-how-might-we-add-our-person-information-to-a-booking-in-harmony-with-cas1) to determine the best way to capture personal data during the booking process, and the associated meeting which took place on the 10th of November.
Briefly, it outlines that:
- personal data should be stored on an application rather than a booking
- applications will be split into service-specific tables in a way similar to [ADR 7](docs/adr/0007-storing-service-specific-properties.md)
- CAS3 will automatically create applications at the same time as bookings as a temporary measure until we have a better understanding of what the process of creating and managing an application will look like
As well …
=> ADR for service-specific applications

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonLogicService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonLogicServiceTest.kt
Use JSON Logic fields to determine first class citizens, store them in the AP Application table and then create/allocate an assessment.
=> 847 - Submit application endpoint

src/main/resources/static/api.yml
~~This is a first pass at what an ideal interface might look like between our CAS API and the facade to the new OASys ARN API which the integrations team are building for us (`approved-premises-and-oasys-dev.hmpps.service.justice.gov.uk`) on Capita's new OASys ORDS endpoints.~~
~~The same endpoints and response (without the `oaSysIds` element) are intended to be suitable for the CAS API to expose to the CAS1 UI app.~~
For example, the Approved Premises UI app might ask the CAS API for a list of issues contributing to risks of offending or harm: 
`GET /people/{crn}/oasys/risk-contributors:`
and receive:
```json
{
"assessmentId": 138985987,
"riskContributors": [
[
{
"label": "Accommodation issues contributing to risks of offending and harm",
"questionNumber": "3.9",
"answers": [
"Mr Smith …
```
=> Oasys endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/prisonsapi/CaseNotes.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseNoteFactory.kt
`originalNoteText` was leftover from when we were fetching case notes from Community API
=> Remove case notes property

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeserializationValidationService.kt
When creating or updating a Premises, if invalid data is supplied, an extra unwanted error is returned on the `status` property, even if it has a valid value.
Similarly, as part of the work on [adding bookings for Temporary Accommodation](https://trello.com/c/kEBk1zvf/540-spike-how-might-we-extend-the-existing-api-logic-for-bookings) a similar issue has been seen on the `serviceName` property when creating an invalid booking.
A `POST` request to `/premises` with the following body:
```json
{
"name": "Borgia House",
"addressLine1": "57 Northbrook Road",
"postcode": null,
"service": "temporary-accommodation",
"notes": "some notes about this property",
"localAuthorityAreaId": "d75ce5b8-fc07-494b-8950-a46a63ac377e",
"characteristicIds": [],
"status": "active"
}
```
returns the following …
=> (Fix) Allow DeserializationValidationService.validateObject to validate an enum as a string

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ConflictProblem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt, src/main/resources/db/migration/all/20221115123112__add_bed_id_to_bookings_table.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/DatesTest.kt
> See [ticket #467 on the CAS3 Trello board](https://trello.com/c/RqgsUkHV/467-a-user-can-create-a-new-allocated-booking-for-a-person).
This PR implements bookings for a bed in a way that is compatible with the premises-level bookings for the Approved Premises team.
Before creating the booking, it validates that:
- The bed exists on the premises
- The departure date is not before the start date
- A booking does not already exist for that bed during the given dates
A clashing booking results in a `409 Conflict` response from the server.
=> Implement bookings for Temporary Accommodation

.github/workflows/ci.yml, .github/workflows/generate-ui-types.yml
Only trigger the generate types workflow in `hmpps-approved-premises-ui` when a change to api.yml was merged
=> Only trigger UI type generation workflow if api.yml has changed

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
Retrieving bookings using the `GET /premises/{premisesId}/bookings` or `GET /premises/{premisesId}/bookings/{bookingId}` endpoints results in a problem response such as:
```json
{
"title": "Internal Server Error",
"status": 500,
"detail": "No enum constant uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.ServiceName.approved-premises"
}
```
The endpoints correctly return the booking/list of bookings.
- The property `BookingEntity.service` has been changed from an `@Enumerated ServiceName` to a `String`, as Spring does not automatically use `Converter`/`ConverterFactory` implementations to deserialize JPA entities from the database.
- The `BookingTransformer` now uses an `EnumConverterFactory` instance to get the correct enumerated value from the JPA entity's `String` value.
=> (Fix) Correctly deserialize service name for bookings from DB

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ConfirmationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ConfirmationTransformer.kt, src/main/resources/db/migration/all/20221123150057__add_booking_confirmation_table.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ConfirmationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket #472 on the CAS3 Trello board](https://trello.com/c/Le89Hfzk/472-a-user-can-confirm-a-provisional-booking).
This PR is the first piece of work to support the Temporary Accommodation booking flow. It allows for a provisional booking to be confirmed.
For the Temporary Accommodation service, a booking is provisional when it is first created. This is analogous to the `"awaiting-arrival"` status in Approved Premises bookings. Provisional bookings become confirmed once an HPT has approved the booking.
This PR adds:
- `"provisional"` and `"confirmed"` statuses as well as a `confirmation` property to the booking API schema
- A `POST /premises/{premisesId}/bookings/{bookingId}/confirmations` endpoint to confirm a booking
=> Add confirmations to bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
> See [ticket #536 on the CAS3 Trello board](https://trello.com/c/GC1EQ1p0/536-a-user-can-mark-a-confirmed-booking-as-active).
This PR is part of the work to support the Temporary Accommodation booking flow. It allows a booking on a Temporary Accommodation premises to record an arrival.
- The `NewArrival.keyWorkerStaffCode` property has been made optional. Validation has been added to ensure that an Approved Premises arrival still contains this value, and returns a `400 Bad Request` response if not.
- An arrival to a Temporary Accommodation premises will validate the actual arrival date and the expected departure date to make sure that (in case they are different to the booking) there are no conflicts with other bookings for the same bedspace.
=> Add Temporary Accommodation support to arrivals on a booking

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/MoveOnCategoryEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DepartureReasonTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/MoveOnCategoryTransformer.kt, src/main/resources/db/migration/all/20221128171437__add_service_scopes_to_departure_reasons.sql, src/main/resources/db/migration/all/20221128172629__add_service_scopes_to_move-on_categories.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/MoveOnCategoryEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See ticket [#537 on the CAS3 Trello board](https://trello.com/c/6ey0Kwp2/537-a-user-can-mark-an-occupied-bed-as-closed).
This PR is part of the work to support the Temporary Accommodation booking flow. It allows departure reasons and move-on categories to be service-specific.
- The `DepartureReason` and `MoveOnCategory` OpenAPI schemas have had a `serviceScope` property added, to be used in a similar way to `Characteristic.serviceScope`.
- A `service_scope` column has been added to the `departure_reasons` and `move_on_categories` tables. Existing rows in these tables have been assigned either a scope of `"approved-premises"` or `"*"` (the wildcard scope) depending on whether they are specific to AP or will also be used by TA. New rows have been assigned a scope of …
=> Add service scopes to departure reasons and move-on categories

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CaseNotesClient.kt, src/main/resources/application.yml, src/test/resources/application-test.yml
The real path actually has /case-notes at the start of it.  Coincidentally we were using this as a qualifier for Wiremock anyway so the change is a small one.
=> Fix Offender Case Notes Service path

.circleci/config.yml, helm_deploy/values-preprod.yaml
The new certification name will be provisioned in this other pull request https://github.com/ministryofjustice/cloud-platform-environments/pull/9339.
With a bit of digging most of these preprod hostnames were found https://github.com/ministryofjustice/cloud-platform-environments.
There are 2 outstanding values we need to put in place: 
```
SERVICES_AP-DELIUS-CONTEXT-API_BASE-URL: 
SERVICES_AP-OASYS-CONTEXT-API_BASE-URL: 
```
@edavey I wonder if you'd know the preprod hostname is for the Delius API?
@anthony-britton-moj [as the original author of the dev certificate](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-probation-integration-services-dev/05-certificates.yml) for the OASYS one, you might be …
=> Deploy to preprod

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DepartureTransformer.kt, src/main/resources/db/migration/all/20221129160348__make_departures.destination_provider_id_nullable.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
> See [ticket #537 on the CAS3 Trello board](https://trello.com/c/6ey0Kwp2/537-a-user-can-mark-an-occupied-bed-as-closed).
This PR is part of the work to support the Temporary Accommodation booking flow. It allows a booking on a Temporary Accommodation premises to record a departure.
- The `Departure` and `NewDeparture` schemas in the OpenAPI specification have been updated to allow `destinationProvider`/`destinationProviderId` to be optional.
- The `departures.destination_provider_id` column in the database has been set as nullable.
- The `BookingService` now performs additional validation:
- It ensures departure reasons/move-on categories are of the correct service scope (e.g. for a TA booking, it is either `"temporary-accommodation"` or the wildcard scope `"*"`). If …
=> Add Temporary Accommodation support to departures on a booking

src/main/resources/db/migration/all/20221202145718__update_pipe_jsonlogic_rule.sql
The original rule was invalid JSON
=> Update PIPE JsonLogic rule

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationRegionEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
> See [ticket #529 on the CAS3 Trello board](https://trello.com/c/Jnqzc0pE/529-users-can-assign-a-property-to-a-region).
Currently, when creating or updating a premises, a mock probation region is used that does not correspond to any real location. This PR allows for the probation region a premises is in to be specified when creating or updating it.
- A `GET /reference-data/probation-regions` endpoint has been implemented to provide a list of all available probation regions.
- The `NewPremises` and `UpdatePremises` schemas in the OpenAPI specification have been updated to require a UUID for the `probationRegionId` property.
- The `PremisesService` validates that the provided `probationRegionId` corresponds to an actual probation region in the database.
=> Use probation regions when creating or updating a premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/db/migration/all/20221205134051__split_applications_table.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AllocationQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ApplicationTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonSchemaServiceTest.kt
Split Applications into service specific tables, entities and responses.
Previously isWomensApplication and isPipeApplication existed on the applications table but these properties are not relevant to CAS3.  We have a need to add more CAS1 specific properties, namely selected offence and RoSH data so this is a prerequisite to that work.
=> 905 - Split out applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20221205160719__add_index_offence_fields_to_ap_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Adds convictionId, eventNumber and offenceId properties to the create application endpoint.
The FE can retrieve these from the get active offences endpoint then pass back the correct one when creating the application.
=> 905 - Provide index offence

helm_deploy/values-dev.yaml
They need access to the Swagger docs to build the integrations which will consume our Domain Events and update Delius.
=> Allow Unilink to access the dev env

src/main/resources/static/domain-events-api.yml
It's important that Domain Events provide a link to the UI of the Approved Premises service, to a resource which will allow a human being to explore the "application" for accommodation and its associated resources e.g.:
- the assessment of the application (including clarification notes)
- any bookings related to the application
For example, when a `booking.made` event is consumed by the Delius integration we expect a Delius "contact" to be created. This contact will be of the new (booking) type `EAPB` and will include the `applicationUrl` e.g.
`https://approved-premises/applications/484b8b5e-6c3b-4400-b200-425bbe410713`
Probation officers using Delius will be able to follow this link and view the (possibly multiple) bookings which have been made and explore the AP "application" in full …
=> Add applicationUrl property to Domain Events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/GroupedDocuments.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DocumentTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ConvictionLevelDocumentFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/GroupedDocumentsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenderLevelDocumentFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationDocumentsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DocumentTransformerTest.kt
Adds a `/applications/{applicationId}/documents` endpoint that returns meta data about the documents associated to:
- The Offender the Application is for
- The Conviction the Application is associated with
=> 897 - List Documents endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/resources/db/migration/all/20221207135709__add_original_departure_and_arrival_date_to_a_booking.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket #608 on the CAS3 Trello board](https://trello.com/c/C3QYguIW/608-a-user-can-mark-a-booking-as-extended).
This PR is part of the work to support the Temporary Accommodation booking flow. It allows a booking on a Temporary Accommodation premises to record an extension.
- Bookings have been updated to provide original arrival and departure dates, which are set when the booking is created and never changed. This is distinct from the current arrival and departure dates, which can be changed as a booking changes states. These original dates are required by CAS3 for MI reporting.
- Arrival and departure dates are overwritten for all state transitions that can change these values (i.e. arrivals, departures, and extensions). This behaviour is only applied to TA …
=> Add Temporary Accommodation support to extensions on a booking

src/main/resources/db/migration/local+dev/20221206114543__remove_mock_characteristics_for_temporary_accommodation.sql, src/main/resources/db/migration/local+dev/20221213124429__remove_mock_characteristics_for_temporary_accommodation.sql
The e2e tests for the Temporary Accommodation UI fail as some characteristics are missing:
It seemed like an old version of the API existed in the dev environment, as some Flyway migrations to add real Temporary Accommodation characteristics and to remove mock ones had been merged in some time ago. However, deploying the API to the dev environment results in the following failure when running Flyway migrations:
```
ERROR: update or delete on table "characteristics" violates foreign key constraint "premises_characteristics_characteristic_id_fkey" on table "premises_characteristics"
[12:35](https://mojdt.slack.com/archives/D04D2MMTT24/p1670934935786429)
key (id)=(9527...8bb0) is still referenced from table "premises_characteristics"
```
The Flyway migrations run successfully and the …
=> (Fix) Remove mock Temporary Accommodation characteristics

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/CancellationReasonTransformer.kt, src/main/resources/db/migration/all/20221209161455__add_service_scope_to_cancellation_reasons.sql, src/main/resources/db/migration/all/20221209162642__add_cancellation_reasons_for_temporary_accommodation.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket #471 on the CAS3 Trello board](https://trello.com/c/Rkqzx3HH/471-a-user-can-mark-a-booking-as-cancelled).
This PR is part of the work to support the Temporary Accommodation booking flow. It allows a booking on a Temporary Accommodation premises to record a cancellation.
- Cancellation reasons now have a service scope associated with them, which can be either `"approved-premises"`, `"temporary-accommodation"`, or the wildcard `"*"`.
- The `BookingService.createCancellation` method will validate that the supplied reason ID corresponds to a cancellation reason with the correct scope. If the scope is incorrect, the method will return a `"incorrectCancellationReasonServiceScope"` validation error.
- The `GET /reference-data/cancellation-reasons` endpoint now …
=> Add Temporary Accommodation support for cancellations on a booking

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
This endpoint follows the same pattern as the update endpoint for Applications:
- Must either be assigned to the assessment or a WORKFLOW_MANAGER in order to update it (this is subject to future changes pending outcome of auth conversations)
- The schema version of the assessment must be the latest
- The assessment must not have already been accepted or rejected
=> Implement PUT `/assessments/{assessmentId}` endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/static/api.yml
Break out Assessment into two subtypes so that the frontend can use the correct one since polymorphism on the `application` property isn't working with the OpenAPI->TS generator.
=> Refactor OpenAPI specification for Assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
This PR implements the POST `/assessments/{id}/acceptance` endpoint.
Assuming that:
- Schema validation passes
- The Assessment has not already been approved or rejected
Then the `document` value is persisted and the Assessment is marked as accepted.
=> 819 - Accept Assessment endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ArrivalEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ConfirmationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ExtensionEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ArrivalTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/CancellationTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ConfirmationTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DepartureTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ExtensionTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NonArrivalTransformer.kt, src/main/resources/db/migration/all/20221214123407__add_creation_time_to_booking_tables.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ArrivalEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ConfirmationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ExtensionEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NonArrivalEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket #622 on the CAS3 Trello board](https://trello.com/c/6aHYZoZT/622-record-when-bookings-change-states).
This PR is part of the work to support the Temporary Accommodation booking flow. It allows for the history of a booking as it changes states to be captured.
- The `BookingBody` schema and the booking state sub-schemas (`Arrival`, `Departure`, `Cancellation`, etc.) all have a `createdAt` property defined in the OpenAPI specification.
- The `bookings` table and associated state tables have a `created_at` column created and seeded through a Flyway migration.
- When creating a booking or a state entity, the `BookingService` uses the current system time as the `created_at` time.
=> Add creation time to bookings and state transitions

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/db/migration/all/20221214105317__assessment_rejected_reason.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
- Implement the POST `/assessments/{id}/rejection` endpoint
- Return `rejectionRationale` and `decision` on Assessment endpoints
=> 819 - Reject Assessment endpoint

helm_deploy/values-preprod.yaml
This setting causes the app to log the client_id, authorities, scopes and expiry when it retrieves a client_credentials JWT for service->service call authentication.  Turning this on in pre-prod to debug an issue with calling Offender Case Notes Service (we need to ensure we have the correct authorities.)  This does not log the JWT signature so is safe to enable.
=> Enable log-client-credentials-jwt-info on preprod

.gitignore, Dockerfile, build.gradle.kts, doc/how-to/run_seed_job_remotely.md, script/run_seed_job, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/AsyncConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/SeedController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/UnauthenticatedProblem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedLogger.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/resources/application.yml, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedTest.kt, src/test/resources/application-test.yml
This lays the foundations for the seeding work.
- Adds an endpoint POST /seed which accepts the type of seeding and a filename
- This endpoint returns 202 Accepted then starts the processing in a background thread
- We check that the entire file can be parsed and deserialized first (if not, collecting errors where possible)
- Then row by row, process each file
This doesn't actually do any processing with the Approved Premises CSV yet as this is more focussed around the reusable parts.
=> 903 - Seeding scaffolding

.gitignore, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LocalAuthorityAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationRegionEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/CsvBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CharacteristicService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CharacteristicEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedScaffoldingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedTestBase.kt, src/test/resources/application-test.yml
This can be triggered by placing a CSV file in the `/seed` directory (in dev etc.) or `./seed` when running locally with the following format:
```
id,name,addressLine1,postcode,totalBeds,notes,probationRegionId,localAuthorityAreaId,characteristicIds,status,apCode,qCode
...
```
The job is then started by sending a POST to `/seed` from within the container (or just from postman if running locally) with the following body (where our CSV file is named `ap-upload.csv`):
```
{
"seedType": "approved_premises",
"fileName": "ap-upload"
}
```
This will return a 202 Accepted to indicate the job has been started.  You can then monitor the progress of the job from the API logs.
An initial pass is made to ensure each row can be deserialized (e.g. are UUIDs well formed, do we have integers where we need …
=> 903 - Approved Premises seeding job

helm_deploy/values-test.yaml, src/main/resources/application.yml, src/main/resources/db/migration/test/R__1_create_users.sql, src/main/resources/db/migration/test/R__2_create_bookings.sql, src/main/resources/db/migration/test/R__3_create_applications.sql
This allows us to run [repeatable migrations](https://flywaydb.org/documentation/tutorials/repeatable) in the test environment, so we can be sure there's predictable data for user testing etc, and the environment doesn't get clogged up with test data. 
There's also a PR in the Wiremock repo https://github.com/ministryofjustice/hmpps-community-accommodation-wiremock/pull/7 that will allow us to generate these migrations in a predictable and consistent way.
=> Seed test environment with data

helm_deploy/values-dev.yaml
We've not included the requested IPv6 range:
```
ncc-tsc-team-10: "2a00:1d40:100:11a5::/126"
```
as the CloudPlatform doesn't support IPv6 IP filtering at present:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/ip-filtering.html#ip6-ipv6
=> Whitelist IP ranges of NCC pen. testers in dev env

.gitignore, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedUsersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/UserTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This can be triggered by placing a CSV file in the /seed directory (in dev etc.) or ./seed when running locally with the following format:
```
deliusUsername,roles,qualifications
SomeOne,"ASSESSOR,WORKFLOW_MANAGER","WOMENS,PIPE"
...
```
The job is then started by sending a POST to /seed from within the container (or just from postman if running locally) with the following body (where our CSV file is named user-upload.csv):
```
{
"seedType": "user",
"fileName": "user-upload"
}
```
This will return a 202 Accepted to indicate the job has been started. You can then monitor the progress of the job from the API logs.
An initial pass is made to ensure each row can be deserialized. If any rows fails this stage then no processing will happen and an error will be logged explaining the issue that …
=> 903 user role seeding

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BookingsReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/BookingsReportProperties.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt
> See [ticket #639 on the CAS3 Trello board](https://trello.com/c/z61TtnJY/639-reporting-for-bookings).
This PR enables users to create reports by providing data about bookings in a spreadsheet format.
- The `GET /reports/bookings` endpoint has been introduced. This endpoint has an optional `probationRegionId` query parameter which can be used for filtering bookings by probation region, or all bookings can be returned if this parameter is omitted. A successful request returns a response with `Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` (i.e. an XLSX file) and the generated spreadsheet in the body.
- The concept of a report generator has been created. The `ReportGenerator` base class can be inherited to provide specific report …
=> Provide user reports of all bookings/bookings for a region

helm_deploy/values-test.yaml
This points all our external APIs to the Wiremock instance at https://community-accommodation-wiremock.hmpps.service.justice.gov.uk/, configured at https://github.com/ministryofjustice/hmpps-community-accommodation-wiremock. This gives us more control over stubbing external APIs when carrying out user testing.
=> Use Wiremock for external APIs in test

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentClarificationNoteTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/db/migration/all/20230106113836__clarification_notes_now_have_a_query_and_a_response.sql, src/main/resources/db/migration/all/20230109090123__add_response_received_on_to_clarification_note.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentClarificationNoteEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
This adds some new columns to the Clarification Notes object, as well as allowing users to update a note with both a response, and when the response was received.
=> (873) Update clarification notes

src/main/resources/static/domain-events-api.yml
The Delius team would like the consuming integration to use the name of the practitioner who recorded the departure, on the Contact in Delius (Officer field).
This assumes that the key worker is the person recording the departure.
=> Add 'keyWorker' to 'person.departed' domain event

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/db/migration/all/20230110115806__add_contact_details_to_user.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RandomData.kt
This adds an endpoint to get the user details for a user with a specific ID. If ther details in Delius are different, we update the database to match these details and return the updated object.
=> (873) Add an endpoint to get user details

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20230104163132__add_pdu_column_to_premises.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket #570 on the CAS3 Trello board](https://trello.com/c/TON49LwD/570-users-can-assign-a-property-to-a-region-and-pdu).
This PR introduces PDUs to Temporary Accommodation premises. This has been done in a minimal and unopinionated way as a temporary measure to avoid conflicting with CAS1's planned changes to how geographic entities are modelled in the database, and will be revisited once those changes have been made.
This minimal PDU support is implemented by:
- Adding a `pdu` column to the `temporary_accommodation_premises` table. This column is just stored as text - while a more robust implementation would involve another table and a foreign key relationship, introducing such a table might complicate the previously mentioned model changes.
- Updating the …
=> Simple implementation of PDU for Temporary Accommodation premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
> See [ticket #651 on the CAS3 Trello board](https://trello.com/c/4Mv34gQd/651-reflect-bedspace-count-in-list-of-properties).
This PR updates the JPA-to-API mapping for a Temporary Accommodation premises to use the total number of bedspaces in all rooms in the premises to set `bedCount` rather than the `totalBeds` property on the JPA entity. This provides an always-accurate value for the premises as it exists in the database, rather than relying on a separately stored value which may diverge from the true number.
=> Provide calculated bedspace count for Temporary Accommodation premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
Community API omits the teams key when staff member is not in any teams (rather than returning an empty array).  This deserializes to null so teams needs to be nullable.
=> Staff Details Teams can be nullable

src/main/resources/static/domain-events-api.yml
This PR comprises a number of changes to domain events to record information needed when processing to generate metrics for the performance hub. See notes from [meeting of Dec 14th 2022](https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4258365759/Performance+Metrics+Meeting+on+Weds+Dec+14th+2022).
**NB**: This PR causes breaking changes to the integrations which have been written to consume these events and update Delius. An accompanying PR is required to adjust [those integrations](https://github.com/ministryofjustice/hmpps-probation-integration-services/blob/main/projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ApprovedPremisesService.kt).
Adds:
```
"mappaCategories": "M2",
"sentenceLengthInMonths": 57,
"offenceDescription": "Wounding or …
```
=> Add performance data to domain events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
Due to an issue in the test environment we have a need to see, temporarily, at which point assessments are being lost.
=> Temporary logging around retrieving allocated Assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationDocumentsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Change authorisation policy fo the list applications and get specific application endpoints.
This is now based on team caseload - if the CRN is managed by someone in the requesting user's team(s) then they are allowed to view the application.
Additionally: `WORKFLOW_MANAGER`, `ASSESSOR`, `MATCHER`, `MANAGER` holding users can see all applications except those prohibited to them via LAO.
=> 993 - Application view changes

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20230113145929__make_local_authority_area_id_nullable_in_premises.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesTest.kt
> See [ticket #654 on the CAS3 Trello board](https://trello.com/c/Yc06LzHr/654-local-authority-is-optional-when-creating-editing-a-property).
This PR modifies Temporary Accommodation Premises to allow the local authority area to be optional. This enables users to create or modify a premises even if they don't know which local authority is the correct one (such as if they are not familiar with the area and there is no obvious choice). The existing requirement that the local authority area is provided has been preserved for Approved Premises to avoid a breaking change.
=> Allow local authority area to be optional for Temporary Accommodation Premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt
When generating a bookings report, if a booking has a departure recorded, the `currentNightsStayed` column will still display the number of days between the arrival and the current date, leading to potential confusion.
Given a booking with an arrival date of 1/1/2022 and a departure date of 1/4/2022, a report generated on 12/1/2023 would produce a row with the following columns of interest:
| `currentNightsStayed` | `actualNightsStayed` |
| --: | --: |
| `376` | `90` |
The above booking should be represented in a report generated on 12/1/2023 as follows for the columns of interest:
| `currentNightsStayed` | `actualNightsStayed` |
| --: | --: |
| *(blank)* | `90` |
The `BookingsReportGenerator.convert` method has been updated to set `currentNightsStayed` to `null` if a departure exists on …
=> (Fix) Set 'current nights stayed' column in bookings reports to blank for a booking with a departure

.github/workflows/generate-ui-types.yml
At the moment, Github actions gives the error:
```
The identifier 'trigger-ui-workflow' may not be used more than once within the same scope.
```
=> Give unique names for the steps

doc/architecture/decisions/0010-use-repeatable-migrations-for-dev-and-test.md, src/main/resources/db/migration/local+dev/R__1_create_users.sql, src/main/resources/db/migration/local+dev/R__2_create_premises.sql, src/main/resources/db/migration/local+dev/R__3_create_characteristics.sql, src/main/resources/db/migration/local+dev/R__4_clear_bookings.sql
This ensures we return to a predictable state on each deploy. I’ve kept the old migrations so we don’t get any errors about missing migrations.
I’ve also added an ADR to document this decision, as well as the previous decision to use repeatable migrations in test.
=> Add repeatable migrations for dev

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
> See [ticket #643 on the CAS3 Trello board](https://trello.com/c/Dx2sBLCY/643-double-booking-only-when-theres-a-clash-with-another-cancelled-booking).
Currently, a booking for a Temporary Accommodation bedspace is not allowed to be made if another booking exists on that bedspace if the booking dates overlap. However, if the existing booking has been cancelled, then it should not prevent the new booking from being made, as the bedspace is now available.
This PR modifies the booking conflict logic so that cancelled bookings are not considered when determining if a conflict exists.
=> Allow a new booking for a Temporary Accommodation bedspace to overlap with a cancelled booking

src/main/resources/db/migration/local+dev/R__2_create_premises.sql
A request to `GET /premises/` returns an HTTP 500 response locally and on the dev server. This response is caused by an exception with the following message:
```
Parameter specified as non-null is null: method uk.gov.justice.digital.hmpps.approvedpremisesapi.api.model.TemporaryAccommodationPremises.<init>, parameter pdu
```
A request to `GET /premises` should successfully return a list of all premises.
Currently the repeatable migrations for dev environments introduced in #353 do not provide PDUs for Temporary Accommodation premises. This PR adds appropriate PDUs to the Temporary Accommodation premises created in the `R__2_create_premises.sql` migration to resolve the issue.
=> (Fix) Add PDUs to Temporary Accommodation premises in repeatable Flyway migration for dev

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/db/migration/all/20230116143807__add_deallocated_at_to_assessments.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReallocationAtomicTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
This PR implements the POST `/applications/{id}/allocations` endpoint spec.  This allows users with `WORKFLOW_MANAGER` to reallocate an assessment provided the user they are assigning to has the `ASSESSOR` role and where applicable the relevant qualifications.
=> 993 - Support reallocating Assessments

Dockerfile, doc/how-to/run_seed_job_remotely.md, src/main/resources/application.yml
Cannot mkdir on / since this would need to be a volume - so make a directory in /tmp instead.
=> Fixes for running seeding remotely

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
As dates are randomly chosen, occasionally the booking would be given a date before the non-arrival date used in the test, which would cause a 400 Bad Request response with the error message 'afterBookingArrivalDate'.
This test has been changed to use the arrival date of the booking as the date for the non-arrival.
=> Fix failing 'create non-arrival' test

src/main/resources/db/migration/local+dev/R__2_create_premises.sql, src/main/resources/db/migration/local+dev/R__4_clear_bookings.sql, src/main/resources/db/migration/test/R__1_create_users.sql, src/main/resources/db/migration/test/R__2_create_rooms.sql, src/main/resources/db/migration/test/R__3_create_bookings.sql, src/main/resources/db/migration/test/R__4_create_applications.sql
This is a rework of #366.
This PR achieves the same result, but empties out the `R__0_clear_bookings.sql` instead of renaming it (avoiding breaking the migrations) and uses `ON CONFLICT(id) DO NOTHING` for the booking seeding.
=> Additional seed data for Temporary Accommodation rooms/bookings in the test env

src/main/resources/db/migration/local+dev/R__1_create_dev_users.sql, src/main/resources/db/migration/local+dev/R__2_create_premises.sql, src/main/resources/db/migration/test/R__1_create_users.sql
We are now seeding users (and roles/qualifications) and premises using the: [SeedJob](https://github.com/ministryofjustice/approved-premises-api/blob/main/doc/how-to/run_seed_job_remotely.md) process.
So that seeding isn't lost on dev and test at every deploy we now stop truncating the `users` and `premises` tables on every migration run (every deployment).
=> Retain premises and users in dev and test environments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedUsersTest.kt
If there's an error during the `ensureCsvCanBeDeserialized()` test we continue to abort the entire seeding.
However, if there's an error processing an individual row (`job.processRow()`) we now catch the error and:
- log the full exception
- accumulate the exception message in a list which we log at the end of the seeding job
In this way we can attempt to seed 100 users, have 95 successful seedings and see a list of 5 problem rows to take away and remediate, e.g.
```
The following row-level errors were raised:
Error on row 1: Could not get user FREDBLOGGS
Error on row 21: Could not get user JOENINETY
Error on row 32: Could not get user CINDYSHERMAN
Error on row 76: Could not get user ANDYPANDY
Error on row 95: Could not get user OLIVEOIL
```
=> Log row level errors when seeding, and continue

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/db/migration/all/20230123135851__offline_applications.sql, src/main/resources/db/migration/all/20230123135852__link_booking_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OfflineApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/OfflineApplicationTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
**Introduce the concept of an Offline Application**
A new table `offline_applications` stores info on offline/pre-digital service applications.  There is currently no way of inserting data into this table, this will be a seeding task in a subsequent PR.
**Add a reference to Application or Offline Application from Booking**
Allow a Booking to link to an Application or Offline Application.  The reference is not currently populated but will be in a subsequent PR.
=> 1038 - Associate booking with Application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/db/migration/all/20230125094732__allow_risks_to_be_null.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
This allows us to set a flag to skip the creation of risks when creating an application. This will allow us to go live without the reliance on the OASys integration, which may not be ready for beta. If we do use this, we’ll need to backfill any applications without risks added, which may be a manual process.
=> Allow risks to be skipped with a flag set

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/StaffUserDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
When seeding users and roles we discovered that many of our Managers, Assessors and Workflow Managers do not have an email in their Delius `StaffMember` entity as represented via the `api/secure/staff/username/` endpoint.
This commit makes the email property optional.
We need to liaise with the F/E team to ensure that this doesn't introduce a breaking change where that `email` attribute is displayed to an Assessor who wishes to ask the Applicant a clarification question. See:
https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/500
=> Cope with missing email property from Community API StaffMember

doc/how-to/access_database_remotely.md, script/remote_shell
This adds a `remote_shell` command and some instructions on how to install and run jaqy to access the database.
=> Add instructions on accessing the remote database

helm_deploy/values-dev.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/application-local.yml, src/main/resources/application.yml, src/main/resources/db/migration/local+dev/R__1_create_dev_users.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
Currently the user `JimSnowLdap` does not exist in our local and dev environments until it is created by a call to `UserService.getUserForUsername`. This calls the Community API, which in the dev environment returns a response with a probation area code of `"GCS"`, which does not correspond to any probation region. This is causing the error `Unknown probation region code 'GCS' for user 'JIMSNOWLDAP'` to appear in the dev environment.
This also appears to be the case for users used for end-to-end tests, as well as personal accounts on the dev and test environments.
It seems that in production-like environments, the Community API will always return codes corresponding to real probation regions, and that this is just a consequence of using dummy data.
This PR adds two mechanisms to avoid …
=> Give users in local, dev, and test environments real probation regions

src/main/resources/db/migration/all/20230123154608__add_probation_region_to_users.sql
The `20230123154608__add_probation_region_to_users.sql` migration has been updated to ensure that any existing users have been assigned a default probation region (North West) before enforcing non-nullability on the `probation_region_id` column.
This should allow the migration to succeed in the preprod and test environments.
=> Fix migration to give existing users a default region

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
The list is sorted by name.
Our plan is that first phase of the Role Admin area will comprise a list
of users and their role. Adjustments to the role assignment will be managed
through the existing user seeding mechanism. See [`UsersSeedJob`](https://github.com/ministryofjustice/approved-premises-api/blob/expose-users-and-roles-to-role-admin/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt)
The facility to add and remove roles through the UI will follow.
In due course we'll need to paginate this list. For the initial release
we expect about 250 user with roles to be managed.
Perhaps we'll want some filtering, e.g.
- only show users with internally managed roles
- show users with a particular role
=> Expose users and roles to ROLE_ADMIN only

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
This fetches one of three statuses:
- `inProgress` - if the application is not submitted
- `submitted` - if the application is submitted and all clarificationNotes have responses
- `requestedFurtherInformation` - if the application’s latest assessment has any clarificationNotes without responses
As part of this, we also need to load in assessements for an application, so I've added a new variable to the Application entity, together with a helper to fetch the latest entity.
The transformer tests are a little more long winded than I'd like, but I was getting too bogged down with trying to DRY them up!
=> (1059) Add a status to applications

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/resources/db/migration/all/20230130160546__domain_events.sql, src/main/resources/static/domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApplicationSubmittedFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/CruFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/LduFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PersonReferenceFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ProbationAreaFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/RegionFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/StaffMemberFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/TeamFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/DomainEventTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
This PR adds the groundwork for Domain Events. 
A `DomainEventService` provides a mechanism for saving and retrieving the events.  They are stored in a single database table with the bulk of the event being kept in a JSON column to avoid having to create and maintain a table structure for each type of event.
Perhaps controversially: the data stored in the table is serialized from/deserializes to the same model as is returned by the endpoints to avoid the maintenance overhead of keeping an identical "domain" version of each event and transforming between them.
=> Domain events scaffolding

.circleci/config.yml
The bootstrap creates a CircleCI context that includes the hmpps prefix.
By using the old api name here we are effectively not providing a context so circleci uses the default environment variables, which are dev ones.
Therefore, prod containers try to deploy to the dev namespace.
You'll see this set correctly for [preprod here](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/.circleci/config.yml#L58) along with the other environments.
=> Prod deploys use the prepared CircleCI context

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonSchemaService.kt
When failing to validate a schema, log the JSON path and the validation message
=> Add logging to JsonSchemaService validation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
For https://trello.com/c/OFlUaOX5/1215-add-an-applications-view-for-a-workflow-manager-to-view-all-assessments we need to return an allocated user’s date, so I’ve updated the API spec and transformer to return a full reference to the user object.
=> Return full user detail in assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
We want to return the correct type of user depending on the service. The API is returning the expected user type already, so this is for documentation and ensuring the correct frontend types are generated.
=> Fix assessment discrimination

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/db/migration/local+dev/R__2_create_premises.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
> See [ticket #765 on the CAS3 Trello board](https://trello.com/c/xv01P30x/765-minimal-api-authorisation-work-for-regional-filtering).
Currently, the API does not provide a way to restrict users to only be able to access premises within their probation region. This is needed in order to onboard the Greater Manchester team so that they do not interact with East of England premises (and vice versa).
This PR introduces the ability for filtering premises by region in the `GET /premises` endpoint. This filtering is enabled by setting the value of the `X-User-Region` header to the ID of the probation region for the current user. The existing behaviour (i.e. no filtering) is preserved if this header is not supplied to avoid a breaking change.
Currently, the API trusts that the client (in this …
=> Filter premises by user region

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
When creating a Booking, where possible associate it with the latest submitted Application or Offline Application.
For AP Bookings, failure to do this will return a 400.  TA Bookings are still creatable without an Application.
=> Automatically associate bookings with an Application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
> See [ticket #770 on the CAS3 Trello board](https://trello.com/c/mDxlIttG/770-protect-against-users-circumventing-property-filtering).
This PR is the first part of the additional work to restrict users of the Temporary Accommodation service from accessing data belong to regions they are not in. It introduces the `UserAccessService` which can be used to determine whether the current user can access a particular region's data or all regions' data (which will be more important once the TA service distinguishes users by role).
The new `UserAccessService` is used to restrict requests to the `ReportsController`, such that:
- A Temporary Accommodation user can no longer request reports for a region they are not in if they were able to coerce the frontend UI to do so. A `403 Forbidden` response …
=> Restrict bookings reports based on user region

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
This adds a new `applications/{id}/assessment` endpoint to allow us to get an application's correct assessment. This will allow us to easily fetch the latest assessment for an application together with the application data, which we need for allocations.
=> (1216) Fetch assessment for application

src/main/resources/db/migration/all/20230214123554__correct_delius_code_for_greater_manchester_region.sql
Currently users in the Greater Manchester region cannot be onboarded onto the Temporary Accommodation service. This is because the Community API returns a probation area code of `N50` for these users, but in the database the `delius_code` for the Greater Manchester region is incorrectly recorded as `MCG`.
This PR adds a new Flyway migration to update the `delius_code` to the correct value.
=> (Fix) Use correct Delius code for Greater Manchester region

helm_deploy/hmpps-approved-premises-api/values.yaml
Deployments are often timing out because pods are being restarted before they can become ready.  This should hopefully give the pods enough time to startup.
=> Increase initial delay on liveness probe to 60s

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa.specification/UserSpecifications.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
This adds the missing filtering functionality to the `/users` endpoint, to allow us to filter by role and qualification. To allow for us to optionally append to the query depending on what arguments are provided, I've added a JPA `Specification`, which builds up a list of predicates based on the user input. It took a bit of wailing and gnashing of teeth, but it seems to work pretty well!
=> (1216) Allow users to be filtered by role and qualification

build.gradle.kts, docker-compose.test.yml, docker-compose.yml, helm_deploy/hmpps-approved-premises-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/domainevent/SnsEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt, src/test/resources/application-test.yml
This is the same work as in https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/421 with some tweaks to the config to hopefully resolve the binding issues that caused it to be rolled back.
Namely:
- remove dash from topic name, I'm not sure this should matter but the docs say lowercase only
- only mount secrets in dev (as this is the only place they currently exist)
=> 1135 - Publish Domain Events

.github/workflows/ci.yml
At the moment, PRs added to a merge group just keep waiting because the CI check is required, but the `merge_group` action doesn't trigger anything.
=> Trigger CI when adding to the merge group

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
When an assessment has been reallocated to a new user, the assessments are treated as readonly, so we should not return them in the list of assessments.
=> (1242) Only return un-reallocated assessments on list

src/main/resources/db/migration/all/20230216104604__move_back_to_blank_ap_applications_schema.sql
Since we will move the work done by the JSON logic expressions into the frontend in due time, we have decided to stop validating the JSON schema.  The fastest route to do this in the meantime is to use the empty schema (which all valid JSON validates against) again.
=> Revert to empty JSON schema for AP Applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/static/domain-events-api.yml
This is not present for all Offenders so null is a valid value
=> Make MAPPA nullable on Application Submitted Domain Events

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt, src/test/resources/application-test.yml
Correct detailUrl for Application Submitted domain events - was previously set to the frontend application URL rather than the event route on the API.
Log SNS receipt info when emitting events - this should help us with debugging etc.
=> Domain Events Fixes

Dockerfile, doc/how-to/run_migration_job_remotely.md, script/run_migration_job, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/MigrationJobController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationLogger.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/UpdateAllUsersFromCommunityApiJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MigrationJobScaffoldingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MigrationJobTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UpdateAllUsersFromCommunityApiMigrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/CommunityAPI.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This adds scaffolding for running ad-hoc data migation tasks that require kotlin code (e.g. where calls to upstream services need to be made.)
These can be called in a similar way to the seeding jobs - via a POST to `/migration-job` with the type of migration.  This does not require a JWT but can only be done locally.
Implemented is the first such task which updates all of the users in our `users` table from Community API.  The need for which is shown here: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/414#discussion_r1101781763
=> 1226 - Migration process to update users from Community API

helm_deploy/values-prod.yaml
The value we are choosing was supplied more recently than the value ending .dsd.io [1]. 
We don't think this is causing an issue yet but it may when the integrations service comes to be used.
[1] https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/8e4676c99386a425b35bea24166efa55de950693#diff-bb4e80ba0a6c43663498b44c19e42c074dcceac3d9564b49801202073b5c87ff
=> Update delius integrations service hostname

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ApplicationTeamCodeTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Allow users to view an Application if they are a member of a team that the CRN was managed by when the Application was created.
=> 1225 - Limit application access by caseload

Dockerfile, doc/how-to/delete_booking_remotely.md, script/delete_booking, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DeleteBookingController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/LoopbackUtils.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/MigrationJobController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/SeedController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DeleteBookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ConfirmationTestRepository.kt
This adds an endpoint at DELETE `/internal/booking/{booking id}` that can only be called from localhost.
This will delete the Booking and all dependent entities such as arrivals, nonarrivals, extensions etc.
=> 847 - Hard Delete Booking

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/LostBedsTransformer.kt, src/main/resources/db/migration/all/20230221114036__create_service-specific_tables_for_lost_beds.sql, src/main/resources/db/migration/all/20230221114122__migrate_existing_service-specific_lost_bed_data_to_service-specific_tables.sql, src/main/resources/db/migration/all/20230221114147__drop_service-specific_columns_from_base_lost_bed_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesLostBedsEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationLostBedEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/LostBedsTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
>  See [ticket #806 on the CAS3 Trello board](https://trello.com/c/RDiktZxl/806-introduce-service-specific-lost-bed-tables-entities).
This PR is part of the work to implement support for lost beds within the Temporary Accommodation service. It will enable service-specific behaviour such as validation for endpoints concerning lost beds.
- The `approved_premises_lost_beds` and `temporary_accommodation_lost_beds` tables have been introduced to provide service-specific data and the `lost_beds` table now contains common data shared between both services.
- The `LostBedsEntity` now has `ApprovedPremisesLostBedsEntity` and `TemporaryAccommodationLostBedEntity` as subclasses to do likewise within the API itself.
- The existing API logic has been updated to support these …
=> Create service-specific tables and JPA entities for lost beds

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/db/migration/all/20230216171125__staff_code_not_null.sql, src/main/resources/db/migration/local+dev/20230216171124__staff_code_for_non_existent_users.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UpdateAllUsersFromCommunityApiMigrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This should always be present a user, it was previously nullable to allow us to do a migration.  Now that's complete, we can set this to not nullable.
=> Make staffcode non nullable

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/LostBedReasonTransformer.kt, src/main/resources/db/migration/all/20230222140817__add_service_scope_to_lost_bed_reasons.sql, src/main/resources/db/migration/all/20230222140921__seed_temporary_accommodation_lost_bed_reasons.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LostBedReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
> See [ticket #809 on the CAS3 Trello board](https://trello.com/c/BckxYLXE/809-make-lost-bed-reasons-service-specific).
This PR is part of the work to implement support for lost beds within the Temporary Accommodation service. It introduces a service scope to lost bed reasons to allow each service to provide a different set of reasons for lost beds.
- Existing lost bed reasons have been given a service scope of `"approved-premises"`, except "Other", which has a scope of `"*"`
- The list of reasons for Temporary Accommodation has been seeded using a Flyway migration
- The `GET /reference-data/lost-bed-reasons` endpoint now accepts an `X-Service-Name` header, which allows for filtering of the returned list of reasons if provided
- The `PremisesService.createLostBeds` …
=> Introduce service scope for lost bed reasons

src/main/resources/db/migration/local+dev/20230216171124__staff_code_for_non_existent_users_fix.sql
The previous migration's WHERE clause was incorrect
=> Fix for dev migration to add staff code to non-existent users

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt
This was missing, so we need to add this, so we can fetch the correct non-Arrival reasons in the UI
=> (1290) Add a non arrival reason reference data endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/static/domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/StaffWithoutUsernameUserDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
Some Delius staff do not have an account to sign in with and therefore don't have a username/email.
=> Make username optional on Domain Events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NeedsDetailsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/OASysSectionsTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/NeedsDetailsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/OASysSectionsTransformerTest.kt
Don't offer Drug & Alcohol on the selection endpoint, always return them on the sections endpoint.
The selection endpoint is used to build the list of OASys sections that are auto-imported or optionally imported in the UI.  Removing these sections from the selection endpoint will result in them no longer appearing in any of the checkbox lists.
The section endpoint currently only returns the drug and alcohol sections if they are specifically requested, this changes the endpoint to always return the Drug and Alcohol sections.
=> Always return Drug and Alcohol OASys sections

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
> See [ticket #811 on the CAS3 Trello board](https://trello.com/c/n5PqaVQL/811-a-user-can-create-or-update-a-void-booking).
This PR is part of the work to implement support for lost beds within the Temporary Accommodation service. It allows users of the API to create and update Temporary Accommodation lost beds.
- The OpenAPI spec has been updated to provide `NewApprovedPremisesLostBed` and `NewTemporaryAccommodationLostBed` schemas to allow creating service-specific lost beds.
- The `PremisesService.createLostBeds` method has been updated to be able to validate and persist Temporary Accommodation lost beds.
- The OpenAPI spec has been updated to introduce a new `PUT /premises/{premisesId}/lost-beds/{lostBedId}` endpoint accepting an `UpdateApprovedPremisesLostBed` or …
=> Implement Temporary Accommodation support for creating and updating lost beds

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
This adds a `checkCaseload` option to the /people/search endpoint. If this is provided, then we also call the `getTeamsManagingCase` endpoint to check if the offender is part of the logged in user’s caseload. If they aren’t then we return a 403 response.
=> (1276) Optionally check caseload on user search

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
The upstream caseload endpoint requires staff code rather than username
=> Fix for optional Caseload check on People Search endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/db/migration/all/20230302151100__unique_constraint_for_delius_username.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserCaseSensitivityTest.kt
There should always be a 1:1 relationship between an entry in the "users" table and a Delius user.
=> Add unique constraint over delius username

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
This adds a /tasks endpoint to the API, which transforms any open Assessments into a more generic Tasks interface, which will eventually cover other types of "assignable" tasks, such as Placement Requests, Appeals etc.
=> (1314) Add a tasks endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CapacityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
> See [ticket #770 on the CAS3 Trello board](https://trello.com/c/mDxlIttG/770-protect-against-users-circumventing-property-filtering).
This PR is the second part of the additional work to restrict users of the Temporary Accommodation service from accessing data belong to regions they are not in. It adds new methods to the `UserAccessService` which can be used to determine whether the current user can perform a particular action (which will be more important once the TA service distinguishes users by role).
- Refactoring existing user access checks for Approved Premises to use the `UserAccessService`. The new methods have been written to be able to take into account both the current user and the service.
- Introducing new user access checks for endpoints that Approved …
=> Implement user access controls for premises endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/NotAllowedProblem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReallocationAtomicTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
This updates the reallocate endpoint to support multiple tasks. I’ve updated the body to accept a NewRellocation object with a Task Type and user ID. Rather than returning the Assessment object (which we don’t need), the endpoint now returns a Reallocation object with the Task Type and the user who the task has been reallocated to.
As we don’t currently support any task type other than assessements, we return a 405 method not allowed response. I’ve also added some tests for all the other types to serve as placeholders, which can be replaced as we add support for the other task types.
=> (1315) Allow a task to be allocated to a user

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedTemporaryAccommodationBedspaceTest.kt
This assertion was failing inconsistently due to changes in the ordering of characteristics. By sorting the lists prior to comparison we make the assertion "deterministic" or reliably repeatable.
=> Set order of characteristics for a 'deterministic' assertion

src/main/resources/static/api.yml
We now have permanent `propertyName` keys like:
- `acceptsHateCrimeOffenders`
- `isCatered`
This is in contrast to the existing `name` property which can be changed a needed e.g.
`Does this AP accept people who have been convicted of hate crimes?`
The representation of a characteristic via the API needs to include this new property so that the UI can:
- reliably display characteristics and
- request them in search parameters
=> Expose Characteristic.propertyName via API

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesSeedJob.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/PremisesTestRepository.kt
ApCodes are unique so we can use these to identify existing APs which will be updated as distinct from new APs which need to be created.
No longer having to manage a list of UUIDs reduces opportunities for errors.
=> Identify existing APs by ApCode rather than UUID in seeding

src/main/resources/static/api.yml
We’re not currently working with these, but they will be coming down the pipe shortly.
=> Add rfap to AP types

src/main/resources/static/api.yml
Adds OpenAPI specification for a POST /beds/search endpoint.
The request body format is split between CAS1 and CAS3 due to the different nature of the searches:
- CAS1 on Postcode District
- CAS3 on PDU
I had considered supporting both approaches regardless of service but since PDU only exists on `temporary_accommodation_premises` at the moment and I don't know if CAS3 has the lat/long for each Premises recorded anywhere it seems more sensible to just support what we need for now.
=> OpenAPI specification for Bed Search endpoint

src/main/resources/static/api.yml
This should be an integer, not an object
=> Fix `assessmentId` in the OpenAPI spec

src/main/resources/db/migration/all/20230317123100__use_bed_id_for_ap_lost_beds.sql
There is no `id` column on temporary_accommodation_lost_beds, should be `lost_bed_id`
=> Fix for Lost Beds migration.

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ValidationErrors.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ConflictProblem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/ValidatableActionResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/LostBedCancellationTestRepository.kt
> See [ticket #906 on the CAS3 Trello board](https://trello.com/c/PhHRtAyn/906-a-user-cannot-create-a-booking-or-another-void-if-an-existing-void-is-occupying-any-of-those-dates).
This PR extends the existing validation for Temporary Accommodation bookings that prevent double booking a room to lost beds. This allows for the following situations to be prevented:
- Double booking a lost bed
- Creating a lost bed to take place while a bed is occupied
- Creating a booking on a bed to take place while the bed is out of commission
- Changing the dates of a lost bed such that it overlaps with another lost bed or a booking
- Changing the dates of a booking (either through an arrival or an extension) such that it overlaps with a lost bed
=> Add checks for conflicting lost beds when creating or updating a lost bed or booking in Temporary Accommodation

doc/how-to/example_csvs/approved_premises_rooms_seeding_example.csv, doc/how-to/run_seed_job_remotely.md, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/RoomEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesRoomsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/resources/db/migration/all/20230321113733__add_code_to_rooms_with_unique_constraint.sql, src/main/resources/db/migration/all/20230321114516__add_code_to_beds_with_unique_constraint.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoomEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesRoomsTest.kt
This PR adds an `ApprovedPremisesRoomsSeedJob` which seeds rooms, their characteristics, and beds via the seeding script run on remote pod (or local environment) as:
```sh
./script/run_seed_job approved_premises_rooms rooms_with_characteristics
```
The CSV provided must have the following columns:
- `apCode`
- `bedCode`
- `roomNumber`
- `bedCount`
- `isSingle`
- `isGroundFloor`
- `isFullyFm`
- `hasCrib7Bedding`
- `hasSmokeDetector`
- `isTopFloorVulnerable`
- `isGroundFloorNrOffice`
- `hasNearbySprinkler`
- `isArsonSuitable`
- `isArsonDesignated`
- `hasArsonInsuranceConditions`
- `isSuitedForSexOffenders`
- `hasEnSuite`
- `isWheelchairAccessible`
- `hasWideDoor`
- `hasStepFreeAccess`
- `hasFixedMobilityAids`
- `hasTurningSpace`
- `hasCallForAssistance`
- `isWheelchairDesignated`
- …
=> 1288: seed AP rooms and beds

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReallocationAtomicTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This tweaks the reallocation endpoint to include the task type in the URL, as well as adding support for Placement Requests to be reallocated, as well as some quality of life improvements.
=> (1382) Allow placement requests to be reallocated

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This represents reality, and will fix an issue we have with our typing. If CAS3 choose to use tasks and allocations further down the line, we can use a discriminator.
=> Reallocation returns an ApprovedPremisesUser

src/main/resources/static/api.yml
> See [ticket #971 on the CAS3 Trello board](https://trello.com/c/QeqfZz0s/971-new-api-endpoint-to-get-all-bookings-filtered-by-status).
This PR adds the `GET /bookings/search` endpoint to the OpenAPI specification to enable frontend development of the "find a booking" feature to happen in parallel with the implementation of the API work.
=> Add booking search endpoint to OpenAPI spec

docker-compose.arm64.yml, docker-compose.test.arm64.yml, script/development_database, script/test_database, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DbExtension.kt
This PR aims to reduce the time taken to run unit and integration tests.
It introduces a JPA extension (`DbExtension`) that performs the following optimisations:
- Run Flyway migrations once at the start of the test run
- Store data seeded into the database at the start of the test run
- Truncate all tables and reinsert seeded data before each test to ensure the database is in a known state
It also improves the performance of PostGIS on ARM64 machines (such as newer Macs) by providing Docker Compose configurations using a community PostGIS image that run natively, rather than emulating AMD64, bringing the time taken to run the tests in line with the CI pipeline. The `test_database` and `development_database` scripts will automatically use these configurations on an ARM64 environment.
=> Use DbExtension to manage database for tests to improve performance

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/resources/db/migration/all/20230331103832__add_assessment_id_to_placement_request.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
- Record which assessment was used to create a Placement Request
- Return the `applicationId` and `assessmentId` with Placement Request response bodies
=> Add applicationId and assessmentId to Placement Request responses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
Before this was fetching assessments regardless of if they’d been submitted or not, as well as only fetching placement requests that had been allocated to the logged in user, which is not what we want.
This adds a `getAllReallocatable` service method to the Assessment service, which only fetches unsubmitted and unreallocated assessments and a `getAllReallocatable` service method to the PlacementRequest service, which only fetches unreallocated Placement Requests without an associated booking.
=> Fix tasksGet endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/resources/db/migration/all/20230411165209__add_release_type_to_application.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt
We need to return the release type when listing placement requests. This is something we already send when an application is submitted, but this is only used for the Domain Event. We then need to add a new database column, so we can persist it in the database too, and return it when listing / showing placement requests.
=> (1444) Record and return release type

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BookingSearchController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BookingSearchRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingSearchResultTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/resources/db/migration/all/20230411162335__add_indices_for_booking_search.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingSearchResultFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingSearchServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingSearchTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
> See [ticket #971 on the CAS3 Trello board](https://trello.com/c/QeqfZz0s/971-new-api-endpoint-to-get-all-bookings-filtered-by-status).
This PR implements the `GET /bookings/search` endpoint introduced by the OpenAPI specification changes from #533. This enables the delivery of the "find a booking" feature in the Temporary Accommodation service.
- The `X-Service-Name` header in the `GET /bookings/search` endpoint has been added as a required header. This is a formality from the frontend client's point of view as it's already provided for all API requests by default, but allows the API to filter bookings by service type, avoiding the possibility of reporting bookings for the wrong service.
- The `BookingSearchRepository` class has been introduced to perform the actual …
=> Implement 'booking search' endpoint

src/main/resources/application-local.yml
This should have been added when the `all-except-integation` and `integration` migration sets were split out but I missed it!
=> Add `all-except-integration` migration set to local profile

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
The original logic (written in Kotlin) used `.firstOrNull()` to get a single booking or lost bed that conflicts (if any existed). The logic was later converted into JPQL queries which returned a nullable single result, which works as long as the query returns 0 or 1 results, but more than one results in a NonUniqueResultException. Unfortunately, JPQL doesn't have any `LIMIT 1`/`FETCH FIRST ROW ONLY` construct, so the repository methods that execute the JPQL queries have been updated to return a list. The service methods then call `.firstOrNull()` on the list returned by the repository to achieve the same result as the original logic.
=> Fix NonUniqueResultException when checking for conflicts with bookings/lost beds

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/TestPropertiesInitializer.kt
When finding an available port, start a Wiremock server at that point to reserve the port and handle the case where two processes may be doing this at the same time by retrying up to 10 times
=> Fix for race condition on Wiremock port when running tests in parallel

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeserializationValidationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProblemResponsesTest.kt
As Instants are deserialized from ISO-8601 with Offset strings they need special handling in the problem response code which was missing as when it was written we were only using OffsetDateTime.
=> Fix for `expectedObject` being returned for valid Instants when another validation error is present on the request

applicationinsights.nonprod.json
Ideally we will collect and ship to AppInsights:
- Max Heap
- Heap Committed
- Heap Used
- GCs
This property causes AppInsights to log available JMX metrics so we can progress this.
=> Set selfDiagnosis level to DEBUG on AppInsights in dev to ascertain available JMX metrics

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This solves an issue where several concurrent requests to submit an Application can all be processed if they pass the check to prevent duplicate submission before the first request completes.
=> Fix for race condition when submitting an Application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
Before, when a placement request was reallocated, the requirements were not copied over. To make this work properly, we need to load the relation by calling `toList` on each collection. We can’t eagerly load the relation as we get a `MultipleBagsException`. There are all manner of complex workarounds, but this seems to do the trick and only results in two additional queries, so not worth the additional stress and complexity.
=> Ensure requirements are copied when reallocated

src/main/resources/db/migration/local+dev/R__2_create_premises.sql, src/main/resources/db/migration/local+dev/R__5_clear_applications.sql
This ensures a clean database when we deploy, and stops the DB getting clogged with test data. A drawback is that we don’t have realistic premises data in dev/test, but we don’t have seeded data in test anyway, so this is not a concern.
=> Clear applications and premises in dev on deploy

src/main/resources/static/api.yml
This is a minimum set of type changes to enable forwards-compatibility work in the UI - setting up the UI so that when turnaround-related changes go into the API, there will be no user-visible change until the feature is enable.
Full discussion here - https://mojdt.slack.com/archives/C03K0HB0LBE/p1681824749993519
=> OpenAPI changes for turnarounds feature

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationDeliveryUnitEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
> See [ticket #1015 on the CAS3 Trello board](https://trello.com/c/5Jhi2OZF/1015-re-associate-existing-premises-to-the-new-pdu-records).
This PR is the second part of the work to migrate Temporary Accommodation premises away from using opaque strings for probation delivery units (PDUs). It follows on from #550, which introduced a reference data endpoint for PDUs to the API and provided the infrastructure to perform this migration.
This PR updates the `POST /premises` and `PUT /premises/{premisesId}` endpoints to allow an ID representing a PDU in the database to be provided.
To maintain backwards compatibility while transitioning to modelling premises PDUs in a structured way, when creating or updating a premises, the `PremisesService` now accepts an `Either<String, UUID>` that represents …
=> Implement support for either PDU name or ID when creating or updating a Temporary Accommodation premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NewPlacementRequestBookingConfirmationTransformer.kt, src/main/resources/static/api.yml
This simplifies the response made when making a booking request to return just the information we need, rather than the entire booking object.
=> Return confirmation object after making a booking

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/ValidatableActionResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
This fixes the issue where a failure to create a Placement Request after an `application.assessed` Domain Event has been emitted causes the Domain Event to be removed from the database when the transaction rolls back.
=> Fix for Placement Request failure sequencing

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/JsonSchemaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/db/migration/all/20230417115757__add_arrival_date_to_ap_applications.sql, src/main/resources/db/migration/all/20230418103022__add_ta_application_schema.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationTeamCodeEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentClarificationNoteEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationJsonSchemaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/JsonSchemaTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
The `GET /applications` endpoint in dev has been taking a long time to respond and often hitting out of memory exceptions.  This is because:
- the `data` and `document` fields on Applications are huge
- we don't have pagination on this endpoint
- we do upstream requests to Community API for offender info to construct the `person` part of the response - when these are a cache miss this takes a toll
- we do upstream requests to Community API for each user-offender pair to establish whether they're a limited access offender and if the user can view their records if so
To try and alleviate:
- changed `PUT /applications/{id}` to allow sending the first class properties for AP Applications
- made release date a first class property (this is the only piece of data needed for the table in the …
=> 1451 - Applications Summary

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/db/migration/all/20230424115206__add_is_inapplicable_to_approved_premises_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
This adds a new `isInapplicable` property that can be sent when an application is updated. If it is set to true, then the status returned is `inapplicable` and the application is filtered out when requesting all applications.
=> (1472) Set an application as inapplicable

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
We’re passing the arrival dates from the frontend as dates, not datetimes, so we need to update the service to accept dates. The underlying data model stores the `arrivalDate` as a datetime, but I think it’s OK to keep them like this to give us flexibility.
=> (Fix) Update and submit applications accepts date

docker-compose.test.yml, docker-compose.yml
- The API appears to still work when we create a CAS1 application we can see redis keys added for the offenderDetailsCache
- Our environments are currently running version 4.x.x
- We've been asked to upgrade due to EOL
- I can't find out why we are using bitnami rather than the official redis image, to avoid potential problems with the upgrade I'm going to keep the surface area of problems smaller by staying with the same maintainer - one for later
- apparently redis supports backwards compatibility even between major changes[1] so we should be able to attempt the otherwise big jump in one go
[1] https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/upgrade.html#upgrade-paths
=> Upgrade to Redis 7.0.11 in dev

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
> See [ticket #1015 on the CAS3 Trello board](https://trello.com/c/5Jhi2OZF/1015-re-associate-existing-premises-to-the-new-pdu-records).
This PR is the fourth and final part of the work to migrate Temporary Accommodation premises away from using opaque strings for probation delivery units (PDUs). It follows on from #550, which introduced a reference data endpoint for PDUs to the API and provided the infrastructure to perform this migration; #577, which allowed clients of the API to use PDU IDs when creating or updating premises; and #589, which performed the migration on the database and refactored the API to support that change.
This PR changes the `TemporaryAccommodationPremises` schema in the API to provide the `probationDeliveryUnit` field. This field is an object with the schema …
=> Return PDU information in endpoints returning a Temporary Accommodation premises

src/main/resources/static/api.yml
https://trello.com/c/iWShWKBw/1016-premises-can-record-the-turnaround-day-count
This PR include changes to add the `turnaroundWorkingDayCount` field to the `TemporaryAccommodationPremises` schema in the openApi spec
=> Add turnaroundWorkingDayCount to TemporaryAccommodationPremises schema

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/BookingsReportProperties.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt
https://trello.com/c/p1Jey0Qq/1059-change-booking-report-endpoint-to-require-a-month-and-year
=> 1059 - Support specifying year and month for Bookings report

src/main/resources/db/migration/local+dev/R__6_create_rooms_and_beds.sql
It would be useful to have these seeded onto the dev environment so we have a sample set of data to use when testing features or demonstrating.
Following the precedant for seeding these for the test environment https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/src/main/resources/db/migration/test/R__2_create_rooms.sql
I'm not 100% sure why these don't already exist. It might be because we had e2e tests running on the dev environment which were creating realistic looking data. Since the recent move back to truncating the Premises table on deploy we only have the old premises seeds which are no longer enough?
Next steps are to seed bookings for these beds.
=> Seed CAS3 rooms and beds for local and dev

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/TemporaryAccommodationPremisesSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/main/resources/db/migration/all/20230426110622__add_turnaround_working_day_count_to_temporary_accommodation.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
https://trello.com/c/iWShWKBw/1016-premises-can-record-the-turnaround-day-count
This PR builds on https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/597 and includes changes to:
- Add `turnaround_working_day_count` field to `temporary_accommodation_premises` table
- Expose/handle the new field when using CRUD operations on TemporaryAccommodationPremises entities
=> Add turnaroundWorkingDayCount to TemporaryAccommodationPremises

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/GovUKBankHolidaysApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/bankholidaysapi/UKBankHolidays.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WorkingDayCountService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WorkingDayCountServiceTest.kt
https://trello.com/c/LNcyCgA9/1057-set-up-an-integration-to-govuk-bank-holidays
This PR include changes to add:
-   An integration for gov uk bank holidays endpoint
-  A working day count service to return working day count between two dates (both inclusive)
=> Set up an integration to gov uk bank holidays

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WorkingDayCountService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TurnaroundTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TurnaroundEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/GovUKBankHolidaysAPI.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/TurnaroundTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WorkingDayCountServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt, src/test/resources/application-test.yml
> See ticket #1027 on the CAS3 Trello board](https://trello.com/c/k0gQjnra/1027-new-bookings-automatically-create-a-new-turnaround-record).
This PR is the second part of the work to introduce and automatically create turnarounds for bookings. It follows on from #607, which created the `turnarounds` table in the database and introduced the associated `TurnaroundEntity`.
This PR contains the following changes:
- A turnaround is automatically created for a booking when the booking itself is created. The working day count is set to the value as specified on the premises that the booking is within.
- The Redis configuration has been updated to support the GOV.UK Bank Holidays API, which was introduced as a dependency in #606, and configured with a cache expiry of 1 day.
- The booking conflict …
=> Automatically create a turnaround when creating a new Temporary Accommodation booking

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TurnaroundTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
> See [ticket #1025 on the CAS3 Trello board](https://trello.com/c/ERqViWY2/1025-new-endpoint-for-editing-a-booking-turnaround).
This PR introduces the `POST /premises/{premisesId}/bookings/{bookingId}/turnarounds` endpoint, which can be used to update the turnaround period for the specified booking.
This is implemented by creating a new `TurnaroundEntity` and adding it to the `BookingEntity.turnarounds` list.
The endpoint validates that:
- The `workingDays` value is a positive integer.
- The updated turnaround time does not conflict with another booking or a lost bed on the bed that the booking is for.
=> Add 'create turnaround' endpoint

src/main/resources/db/migration/local+dev/R__3_create_characteristics.sql
The new seeds in #616 broke the build as there were existing characteristics with the same names. As CAS3 don’t use these in the seeds, and premises get truncated on every deploy, I think this is safe to do.
=> Truncate characteristics before create

Dockerfile
This new image[1] has no critical or high vulnerabilities whereas the one we were on[2] has 6 critical and 8 high.
When looking at the Kotlin template that we were originally based off we can see that it has made the change from openjdk to eclipse-temurin on the basis that "Kotlin doesn't require JDK to build" [3]. We stop short of jumping to Java 18 as that pull request does to try and make the smallest step.
[1] https://hub.docker.com/layers/library/eclipse-temurin/17-jre-jammy/images/sha256-ddf36656dc8920621fddf4928bdcb4b98c0d0e7bc9672f0cea8115c10ad5cbc6?context=explore
[2] https://hub.docker.com/layers/library/openjdk/17-slim/images/sha256-779635c0c3d23cc8dbab2d8c1ee4cf2a9202e198dfc8f4c0b279824d9b8e0f22?context=explore
[3] https://github.com/ministryofjustice/hmpps-template-kotlin/comm …
=> Change base image to no longer require JDK

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
> See [ticket #1056 on the CAS3 Trello board](https://trello.com/c/QRj1kCPr/1056-find-a-bedspace-journey-should-take-turnarounds-into-account-before-returning-them-as-available-options).
This PR updates the bed search logic to filter out beds with a booking that will be in a turnaround state at some point during the desired date range.
Due to the dependency on external services for calculating the duration of a turnaround, the existing SQL query has not been modified, and the filtering logic has been implemented at the service level. To do this, the following simplifying assumptions have been made:
- A booking that overlaps at all with the desired range of dates is already filtered out by the existing SQL query.
- Only the booking with the closest departure date for each candidate bed can …
=> Update bed search endpoint to filter out beds with an active turnaround

src/main/resources/static/api.yml
This was doubled up. I think `isRecoveryFocused` is the correct spelling but as the misspelled one is in the database, I think we should stick with that one for now (as it’s only used as a key)
=> Remove erroneously added PlacementCriteria

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/BookingsReportProperties.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt
https://trello.com/c/p1Jey0Qq/1059-change-booking-report-endpoint-to-require-a-month-and-year
This is a follow up to be merged once the frontend work to use the new year/month parameters has been released.
=> Make month/year parameters required for Booking reports

Dockerfile, doc/how-to/clear_a_cache_remotely.md, script/clear_cache, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/CacheController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CacheService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CacheClearTest.kt
This adds a `DELETE /cache/{cache name}/clear` endpoint that can only be accessed locally which clears the named cache.
=> 1037 - Cache clear mechanism

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
Implementation of this Trello card: https://trello.com/c/ldChlHiW/1515-change-assessments-to-only-return-necessary-information-to-prevent-oom-issues
**This is a breaking change**
Changes the `GET /assessments` end-point to return summary information for each assessment as described in the card.
Maps each row of a SQL query to a 'domain' object (dto?) using `@Query`, `@NamedNativeQuery` and `@SqlResultSetMapping` annotations in the `AssessmentRepository` interface.
In outline the implementation follows the approach used to modify the `GET /applications` end-point to return application summaries.
=> #1515 :zap: Change/Assessments to return necessary information only to prevent OOM problems.

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
This replaces the `active` status with an `in_progress` and `not_started` status based on if the assessment is started.
=> Add in-progress and not-started statuses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20230517152824__add_offence_conviction_risk_information_to_temporary_accommodation_applications_table.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
> See [ticket #1104 on the CAS3 Trello board](https://trello.com/c/nonHg12u/1104-a-user-can-create-a-temporary-accommodation-application).
This PR allows clients to create an application for the Temporary Accommodation service. The process is similar to creating an Approved Premises application, but no checks are made using the `apDeliusContextApiClient.getTeamsManagingCase` function. Temporary Accommodation will be using probation regions to determine access to applications at this stage.
=> Add support for creating Temporary Accommodation applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BedSummaryTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BedSummaryFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BedSummaryTransformerTest.kt
This add a `/premises/$premises.id/beds` endpoint to return a summary of all the beds in a premises. I borrow heavily from @bell-pa's work on Assessment summaries to carry out a JPQL query that returns booleans for if a room is booked or out of service, and then transform that into a status response.
=> (1536) Add an endpoint to list a summary of all beds in a premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
> See [ticket #1120 on the CAS3 Trello board](https://trello.com/c/5FEf051U/1120-include-risk-information-in-the-api-responses-for-application-endpoints).
The frontend logic that was copied across from AP includes the RoSH/MAPPA risks widget. This information is stored in the database for a Temporary Accommodation application but is not returned by the API.
This should be returned for now as although we don’t know if we need it in the future, it’s fairly trivial to implement, compared to the effort involved in removing it from the frontend.
=> Include risk data in API responses returning a Temporary Accommodation application

src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
These are stored in the database as `isPIPE` and `isESAP`, so they need to match.
=> Change capitalisation of Pipe and Esap criteria

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BedDetailTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BedSummaryFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedDetailQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CharacteristicQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BedDetailTransformerTest.kt
This builds on #648 to add an endpoint to show all the details of a given bed, together with the characteristics that are tied to that bed's room. This will allow us to build out the bed view as shown in https://approved-premises-prototype-main.apps.live.cloud-platform.service.justice.gov.uk/manage/bed-information
=> (1536) Add endpoint to show bed details

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/PopulateNomsNumbersOnApplicationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/PopulateNomsNumbersOnBookingsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/resources/db/migration/all/20230523183735__add_noms_number_applications.sql, src/main/resources/db/migration/all/20230524084116__add_noms_number_bookings.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PopulateNomsNumbersOnApplicationsMigrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PopulateNomsNumbersOnBookingsMigrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
So that we can preemptively cache Prison API Inmate Details responses we need to know the Noms Number of any Offenders we want to do this for.  By storing the Noms Number on Applications/Bookings alongside the CRN we can avoid having to call Community API every time (or getting the full cached response from Redis) to get the Noms Number - this will help us reduce the amount of data transfer needed for preemptive caching.
=> 1446 - Store noms number on Bookings & Applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/SeedServiceTest.kt
When running tests & locally through IntelliJ seed files can be loaded because they physically exist on the Filesystem.  When running from a JAR they are embedded within the JAR so first need to be copied to a real file before the rest of the seeding process can read them.
=> Fix for auto seeding when running from JAR

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt
The format we were outputting originally (only a password) is valid but JedisURIHelper that's used by RedLock assumes username and password always appear together
=> Add user/pass delimiter to rediss urls

build.gradle.kts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NotifyGuestListUserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/application.yml, src/main/resources/db/migration/all/20230512113922__add_notify_guest_list.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/EmailNotificationServiceTest.kt, src/test/resources/application-test.yml
This adds a Gov Notify integration and uses it to send an email when an Assessment for an Application is allocated or reallocated.
The `notify.mode` property has 3 options:
- DISABLED: no interaction with the Notify service actually takes place
- TEST_AND_GUEST_LIST: use a Notify Guest List key for certain users, use a different key for other users
- ENABLED: use a single Notify key for all users
There are 3 types of Notify key:
- Test: Doesn't actually send emails but the API responds as though it has
- Guest List: Does send emails to verified email addresses but responds with an error for other email addresses
- Live: Sends emails to any email address
In dev we can combine the guest list and test modes by having a list on our side (which is the new table `notify_guest_list_users`) which …
=> 1443 - Gov Notify integration

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProblemResponsesTest.kt
Return a problem response with the first issue encountered in the `detail` property
=> Add exception handling for query parameters

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
This sets the connection and read timeouts for the Gov UK (Bank Holidays) client to 10 seconds.
Have not touched the other clients yet as we probably need to figure out what sensible values would be there.
=> Set connect and read timeout to 10 seconds for Gov UK WebClient

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
PR #656 updates the version of uk.gov.justice.hmpps.gradle-spring-boot to 4.8.7, which includes new rules for ktlint. Most of the breaking changes have already been resolved by #662 and #664, however #620 and #633 have introduced some additional changes which don't currently fail ktlint but violate the incoming rules.
=> Format project with incoming ktlint rules

.circleci/config.yml, build.gradle.kts, doc/how-to/check-vulnerabilities.md, script/trivy_scan
> See [ticket #1157 on the CAS3 Trello board](https://trello.com/c/0IlKERvZ/1157-patch-4-critical-vulnerabilities-identified-by-trivy).
This PR updates the following plugins to ensure that the API is using fixed versions of the Spring dependencies where possible:
- `uk.gov.justice.hmpps.gradle-spring-boot:4.8.7` pins Spring to 2.7.12 and updates `.trivyignore` to resolve vulnerabilities that cannot be patched without a major version change
- `org.jetbrains.kotlin.plugin.spring:1.8.21`
- `org.jetbrains.kotlin.plugin.jpa:1.8.21`
It also provides fixes/improvements to the Trivy integration with the project:
- The Trivy scan in the `security` CircleCI workflow has been fixed to respect the contents of the `.trivyignore` file
- A new `security-branch`  workflow has been introduced that can be …
=> Resolve vulnerabilities reported by Trivy as High or Critical

script/clear_cache
Clearing a cache is done by calling `DELETE /cache/{cacheName}` from within the container running the API. However, the `clear_cache` script incorrectly sends the request to `DELETE /cache/{cacheName}/clear`, which causes the following misleading response:
```
{
"title":"Unauthenticated",
"status":401,
"detail":"A valid HMPPS Auth JWT must be supplied via bearer authentication to access this endpoint"
}
```
=> Use correct URL for `script/clear_cache`

.circleci/config.yml, gradle.properties
> See [ticket #1160 on the CAS3 Trello board](https://trello.com/c/C1mkETas/1160-fix-gradle-owasp-job-so-it-scans-for-security-vulnerabilities-in-the-api).
Calling `./gradlew dependencyCheckUpdate` in the CircleCI `security` workflow  fails with the following message:
```
Initial heap size set to a larger value than the maximum heap size
```
Reducing the initial heap size fixes this error, but retains the configured maximum as introduced in https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/386, which should prevent the recurrence of the OutOfMemoryError that was resolved by that change.
=> Fix 'unable to start the daemon process' in 'Update OWASP Dependency-Check Database' CircleCI job

.circleci/config.yml
> See [ticket #1157 on the CAS3 Trello board](https://trello.com/c/0IlKERvZ/1157-patch-4-critical-vulnerabilities-identified-by-trivy).
As part of #656, a change was made to the `security` CircleCI workflow to generate the `.trivyignore` file for the `trivy_latest_scan` job. However, this file was not being used, unlike in the `trivy_pipeline_scan` job in the `security-branch` workflow.
It can be seen by comparing the steps executed by [`trivy_latest_scan`](https://github.com/ministryofjustice/hmpps-circleci-orb/blob/main/src/jobs/trivy_latest_scan.yml#L34-L83) and by [`trivy_pipeline_scan`](https://github.com/ministryofjustice/hmpps-circleci-orb/blob/main/src/jobs/trivy_pipeline_scan.yml#L24-L53) that the latter has a step called …
=> Include generated .trivyignore file in `trivy_latest_scan` CircleCI job

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PreemptiveCacheTest.kt
For non-2xx responses cache for 30 seconds, 5 minutes, 10 minutes, 30 minutes (then 30 minutes for every failed attempt thereafter) and start shipping exception to Sentry after 4 attempts.
=> Change handling of errors for Preemptive caching

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/JsonSchemaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/EntityUtils.kt, src/main/resources/db/migration/all/20230530130559__create_placement_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesPlacementApplicationJsonSchemaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/JsonSchemaTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
This adds a new Placement Application model, which acts like a mini-application with the same kind of data and document fields. This can then be assigned to an Assessor, who will be able to approve/reject the application without having to have a seperate Assessment object.
=> (172) Add CRUD endpoints to placement requests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesOfflineApplicationsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/db/migration/all/20230601094346__remove_submitted_date_from_offline_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OfflineApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesOfflineApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- Remove `submittedAt` from OfflineApplications as we won't actually have this data for legacy applications
- Add a Seed Job that creates an Offline Application for each CRN in a CSV
=> 66 - Seed offline applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PlacementApplicationUtils.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This allows Placement Applications to show up as tasks and be reallocated, in a similar way to assessments and placement requests. These were originally going to be called `PlacementRequestReview`s, but the thinking has evolved, so I've renamed them to `PlacementApplications`
=> (173) Show Placement Applications as tasks

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesRoomsSeedJob.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesRoomsTest.kt
Rather than using the bedCode from the upload for the name use `{Room Number} - {Bed Number}`
Also allow updating Bed Names when reprocessing an existing Bed
=> Change AP Bed seeding process to derive Bed Name from room & bed numbers

.circleci/config.yml
This is not needed as it runs as part of the build
=> Remove lint step

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementDateEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/resources/db/migration/all/20230602111949__add_first_class_fields_to_placement_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementDateEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
This adds some first-class entities to placement applications, so they are easier to fetch when listing / viewing / using to create a placement request. The first is a placement type, and the second is a many to one relation of PlacementDates. This will give us the flexibility for PPs to request mutliple placements as shown in the Figma design here:
=> (174) Add first class entities to placement applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/JsonSchemaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/db/migration/all/20230525120902__cas_2_applications.sql, src/main/resources/db/migration/all/20230602092725__add_cas_2_application_schema.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationJsonSchemaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ApplicationTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/JsonSchemaTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonSchemaServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
[Trello card](https://trello.com/c/gYeRYOSP/214-save-an-application)
As part of our work on CAS-2, we need to be able to create and retrieve blank applications in a CAS-2 specific manner.
We are mostly following the [pattern already set out by CAS-3](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/641). When POSTing to `/applications` we check the `ServiceName` and diverge to saving our own application. When GETing applications we check the service name in the `ApplicationService`.
* naming: the CAS-2 repo is currently called `supported-accommodation` but this name has now been rejected - it looks like we will be using CAS-2 as a primary name for users, with a second name TBA. After chatting with other devs it seems like there is a future plan to bring everything …
=> POST and GET CAS-2 applications

src/main/resources/db/migration/all/20230605134546__remove_other_lost_bed_reason_for_approved_premises.sql
This is still in use for TA, so we’ll just update the scope
=> Remove other lost bed reason for AP

helm_deploy/values-dev.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/db/seed/dev+test/user.csv
> See [ticket #1135 on the CAS3 Trello board](https://trello.com/c/HUFggb7I/1135-add-new-cas3-roles-to-dev-and-test).
This PR is the second part of the work to introduce user roles to the Temporary Accommodation service. It adds the CAS3_ASSESSOR and CAS3_REFERRER roles and assigns these roles to the `temporary-accommodation-*` users in the dev and test environments.
This PR does not expose these new roles in API responses as this will be implemented in [ticket #1136](https://trello.com/c/DxTBacWv/1136-extend-profile-endpoint-to-return-the-cas3-user-roles).
=> Create CAS3_ASSESSOR and CAS3_REFERRER roles and assign to dev/test users

src/main/resources/db/migration/all/20230605160742__use_correct_type_for_cas_2_application_json_schema.sql
Fixes an accidental omission from PR #670 in which we failed to set the type of the json schema we created for CAS2 applications. This was causing POST requests for CAS2 applications to fail.
=> Set CAS2 application type in json schemas table

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
This updates the Tasks to return different values depending on the task type. It also updates the `/tasks` endpoint to return tasks that are allocated to the logged-in user. At the moment, this only works for matchers, but we can easily  extend this to return assessments, and any other type of tasks we choose to add in the future.
The existing `/tasks` endpoint has been moved to `/tasks/reallocatable`, which fetches all reallocatable tasks for a workflow manager. We'll need to update the UI to call this endpoint when this work is in.
=> (174) Allow a matcher to see in review placement applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
Tasks have a broad ‘Status’ of `not_started`, `in_progress` or `complete`, but we need a more fine grained status for the PlacementRequestTask.
=> Add PlacementRequestStatus to Tasks

.circleci/config.yml
We’re still getting intermittent failures with the message:
```
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```
Even though we’ve reduced the memory usage, there’s still no room for the other processes in the container sometimes, and this causes the containers to run out of memory. This reduces the amount of RAM each Gradle process can use, as well as upping the number of containers to try and make up for the slower tests.
=> Attempt to fix CI memory errors

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
> See [ticket #1136 on the CAS3 Trello board](https://trello.com/c/DxTBacWv/1136-extend-profile-endpoint-to-return-the-cas3-user-roles).
This PR is the third part of the work to introduce user roles to the Temporary Accommodation service. It allows endpoints that return a `TemporaryAccommodationUser` (such as `GET /users/{id}` or `/profile`) to return roles specific to the Temporary Accommodation service.
To do this, the `UserRole` enum has been split into service-specific enums, `ApprovedPremisesUserRole` and `TemporaryAccommodationUserRole`, and the `User.roles` property has been moved into the service-specific schemas.
As a consequence, the `roles` query parameter on the `GET /users` endpoint can now only accept `ApprovedPremisesUserRole`s. However, as the Temporary Accommodation …
=> Return CAS3 user roles in API responses returning `TemporaryAccommodationUser`s

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/db/migration/all/20230608133712__add_cancellation_type_for_appealed.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
- Create a new Cancellation Reason "Booking successfully appealed"
- When this is used to cancel an AP Booking which is linked to a Placement Request, create a new Placement Request with the same criteria
=> 213 - Return Bookings cancelled due to an appeal to matching

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
**Add variables to existing templates:**
- crn for all templates
- startDate/endDate for Booking Made template
**Add redundant CAS1-only checks around sending emails because copy is AP specific.**
Most of these are at call-sites that can only currently be hit for AP Applications but this will add another layer of protection against future changes to allow CAS2/3 to use these inadvertedly sending AP-specific emails to CAS2/3 users.
**Enable Notify in dev**
Using the `TEST_AND_GUEST_LIST` will send real emails to people on the Notify Guest List (and in the `notify_guest_list_users` table our side) otherwise it will not send.
=> Notify content changes

src/main/resources/db/migration/all/20230614133851__remove_cancellation_reason.sql
This is no longer needed. For safety’s sake, we’ll set this to inactive
=> Set Withdrawn by Approved Premises to inactive

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
In-progress placmement applications were showing as tasks, which broke when we were trying to transform them. This updates the service to ensure all the reallocatable tasks are submitted.
=> (Fix) Don’t show in-progress applications as tasks

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAProbationRegion.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
> See [ticket #1106 on the CAS3 Trello board](https://trello.com/c/rQD1dKfI/1106-a-user-cannot-create-edit-submit-a-temporary-accommodation-application-for-a-crn-that-is-not-in-the-users-region).
This PR is the fourth part of the work to introduce user roles to the Temporary Accommodation service. It implements restrictions for viewing and manipulating applications based on the user's role and probation region.
Specifically, it introduces the following restrictions:
- A request to the `POST /applications` endpoint to create a new Temporary Accommodation application can only be performed by a user with the `CAS3_REFERRER` role.
- A request to the `GET /applications` endpoint to list Temporary Accommodation applications will:
- For a user with the `CAS3_ASSESSOR` role, list all submitted …
=> Restrict access to Temporary Accommodation applications by region/role

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
These should go to the person from whom the Assessment was deallocated, not the new assignee
=> Correct recipient of deallocated emails

src/main/resources/db/seed/dev+test/user.csv
Without the `CAS3_REFERRER` role, the E2E tests for creating an application will fail due to the `403 Forbidden` response.
=> Fix missing role on 'temporary-accommodation-e2e-tester' user

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/LostBedsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/LostBedsTransformerTest.kt
This adds a couple of extra attributes to the API response for lost beds.
=> Add bed and room name to lost bed response

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
AP beds can now be overbooked for manual Bookings - this was missed for arrivals though
=> Allow AP over-bookings when marking an Arrival

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/CancellationTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CancellationQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
This allows us to fetch any previous cancellations for a placement request's application, so matchers can be made aware of any previous cancellations that have happened, together with the reasoning.
=> (214) Return cancellations when requesting a placement request

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/InmateDetailsCacheRefreshWorker.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/OffenderDetailsCacheRefreshWorker.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/PreemptiveCacheRefresher.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/cache/preemptive/InmateDetailsCacheRefreshWorkerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/cache/preemptive/OffenderDetailsCacheRefreshWorkerTest.kt, src/test/resources/application-test.yml
If work is finished earlier than the 2 minutes then sleep until it is over.  This should bring down the noise level in the logs as the lock is currently bouncing between instances constantly and printing the Got Lock/Released Lock messages every time.
=> Use entire 2 minutes during Preemptive Cache Refresh

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedMoveEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/db/migration/all/20230619112523__add_bed_moves_table.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MoveBookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This adds an endpoint to move a booking from one bed to another, together with any notes. On submit, the booking's bed is changed, as well as creating a new `BedMoveEntity` to record the change. We don't do anything with this entity yet, but we may do in future.
=> (3) API endpoint to move beds

doc/architecture/decisions/0013-transition-internal-service-naming-towards-casx.md
As promised during a CAS API check-in this change documents the decision to move towards the naming convention of CASX within the codebase.
Rather than Approved Premises and Temporary Accommodation, we change course towards CAS1, CAS2 and CAS3 for internal identification.
=> ADR for internal service naming in favour of `CASX`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Return a 500 with detail of `No nomsNumber present for CRN` or `No OASys present for CRN` to be consistent with other endpoints to allow frontend to handle more elegantly
=> Return 500s when no NOMS Number or OASys present during Application creation

src/main/resources/db/seed/local+dev+test/user.csv
We seed roles for our local development user, to allow us to use the CAS3 Apply feature end-to-end during local development
=> Add roles for JimSnowLdap

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/prisonsapi/Alert.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AlertFactory.kt
This fixes a deserialization error caused by us incorrectly typing comment as not-null
=> Acct Alert comments can be null

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APOASysContext.kt
The eventual upstream (OASys) can be slow to respond, to reduce the risk of bumping into the 10s timeout between our frontend and API we can fetch the sections concurrently.  We're using coroutines dispatched to a blocking IO thread pool to do this to avoid refactoring the entire client layer to be async.
=> 256 - Make oays requests concurrently

helm_deploy/values-test.yaml
We want to run some load testing from our local machines towards the test environment.
This value can be found centrally here [1] and in this dxw config repo[2] (for dxw folks)
Looks like this is the only change we need based on the previous change to add pen tester ips[3].
[1] https://github.com/ministryofjustice/hmpps-env-configs/blob/4df76ba6d34e4a4994a39003ae4729924b92201c/delius-core-dev/sub-projects/delius-core.tfvars#L92
[2] https://github.com/dxw/govpress-platform/blob/f2175912c3b6086cb8f3df901617899ec0af05f0/terraform/infrastructures/chef-server-staging/locals.tf#L35
[3] https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/26e5d31cf2dbc4d91d191797839f21529fb8c217
=> Add dxw vpn to Test env allow list

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
It is possible for HMPPS Auth to issue a JWT with only a single authority claim. When this happens, this single claim is encoded as a string rather than array of strings with a single element. When the API tries to extract the authorities in the JWT, the attempt to cast the string to a `Collection<String>` fails and a `ClassCastException` occurs.
This PR introduces explicit handling for the case of a single authority claim. Additionally, unexpected data will result in a an empty list of authority claims, meaning that a JWT that is malformed in this way will result in a more appropriate 401/403 response instead of a 500.
=> Prevent `ClassCastException` for JWT with only a single authority claim

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
HMPPS Auth, in some situations, generates a JWT where the authority claims are represented as a comma-separated string, despite [the README implying that this should be an array of strings](https://github.com/ministryofjustice/hmpps-auth/tree/b3fd501ab7ef1c0b0dbbc51a65a5895b81361ce0#get-a-jwt-token). This causes a JWT with the `ROLE_PROBATION` authority to be incorrectly considered invalid if it appears in such a list. For example, generating a JWT in the test environment yields the following payload:
```
{
"jti": "94851966-5c4a-4e6b-b094-ca409bff9010",
"sub": "TEMPORARY-ACCOMMODATION-E2E-TESTER",
"authorities": "ROLE_WORKLOAD_MEASUREMENT,ROLE_PROBATION",
"name": "Temporary Accommodation E2E Tester",
"auth_source": "delius",
"user_id": "2500430111",
"passed_mfa": false,
"exp": 1687573444 …
```
=> Handle multiple authority claims in the JWT being provided as a comma-separated string

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt
> See [ticket #1124 on the CAS3 Trello board](https://trello.com/c/zln7bteP/1124-amend-the-calculation-of-total-booked-days-in-occupancy-report).
The bed utilisation report has been identified as having an incorrect calculation for the number of booked days (and therefore the occupancy rate). Currently, the total number of booked days is calculated as the sum of booked days for closed, active, confirmed, and provisional bookings, as well as the number of effective turnaround days (i.e. not including weekends or bank holidays) and void days. This leads to a misleadingly high occupancy rate.
This PR alters the calculation to just the sum of booked days for closed and active bookings. This has been confirmed to be the expected calculation by users of the report and leads to a more accurate …
=> Update total booked days/occupancy rate calculation on bed utilisation report

build.gradle.kts, doc/how-to/run_performance_tests.md, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/ApplyJourneyStressSimulation.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Auth.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Environment.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Json.kt
> See [ticket #1244 on the CAS3 Trello board](https://trello.com/c/RVHj2JFc/1244-can-we-spare-1-day-to-set-up-some-load-testing-on-apply-to-de-risk-go-live-for-both-us-and-cas1).
This PR provides a prototype for using Gatling as a tool to run performance tests against the API.
This will help us to identify parts of our application that regress in performance or are vulnerable to high load, which will give us confidence that it will be able to handle the increased traffic from onboarding new groups of users.
Specifically, this PR runs a simulation of the Apply journey in Temporary Accommodation. Each simulated user will perform the following steps:
1. Create a new application.
2. Update the application a random number of times.
3. Submit the application.
Between each step is a pause to …
=> Introduce Gatling performance tests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/ThrowableUtils.kt
Whilst the full exceptions are logged too it's not practical to go through hundreds of entries in AppInsights.  The particular example here is seeding users - the exception message doesn't identify why we failed to retrieve a user but the root exception does (e.g. a 404 vs a failure to map probation region).
=> Update seeding process to output root exception message too where available

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReallocationAtomicTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
Reallocating a task according to the application ID caused some issues, because applications can have multiple “active” placement applications, so this was raising an error. Rather than have a special case for placement applications, it makes sense to have all tasks act on their own IDs, rather than relying on the applicationID being present. This also involves so changes to the URLs that the UI causes, so this is a breaking UI change, but I'll be working on this in parallel.
=> (268) Fix placement application bug

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ArrivalEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ArrivalTransformer.kt, src/main/resources/db/migration/all/20230628104650__add_arrival_date_time_to_arrivals.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ArrivalEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
This adds the functionality to add an Arrival Time in  DateTime format for CAS1 premises. There's been a bit of jiggery pokery to ensure compatibility with CAS3, but hopefully this is all sensible enough.
=> (271) Add arrival time

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/CalendarRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/LostBedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CalendarRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt
After introucing lost bed cancellation in the frontend, I noticed that cancelled lost beds were still showing in some places. This filters cancelled lost beds in the lost bed listing, as well as altering the status of beds with cancelled bookings / lost beds in the bed listing, and removing cancelled lost beds / bookings in the calendar view.
=> Hide cancelled lost beds and bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/MDCHandlerInterceptor.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/HttpAuthService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This adds the following to the MDC for a given request:
- `request.id`: a random per-request UUID that can be used to group all log messages for a given request.
- `request.uri`: the requested URI, e.g. `/premises/a93602aa-4787-4aa4-a488-a22ba01149fb`.
- `request.method`: the request method, e.g. `GET`.
- `request.pathPattern`: the path pattern that best matches the requested URI in the format that developers talk about it, e.g. `/premises/{premisesId}`.
- `request.params`: all path parameters and query parameters are added as subkeys. For example, the above value of `request.uri` would have a corresponding `request.params.premisesId` MDC key with a value of `a93602aa-4787-4aa4-a488-a22ba01149fb`.
- `request.serviceName`: the service the request is for, derived from the `X-Service-Name` …
=> Add request information to MDC

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
This will allow us to link tho the application and/or assessment when viewing applications. These are optional fields because CAS3 don't currently have the concept of applications and assessments, and ad-hoc bookings in CAS1 will not have associated applications/assessments too.
=> Add application ID and assessment ID to bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PersonUtils.kt, src/main/resources/db/migration/all/20230629140901__make_noms_number_nullable.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
This allows us to start / continue with an application if there are no NOMIS details or Oasys entries. We'll need to do some work on the frontend to handle these eventualities and catch Oasys and NOMIS case notes / adjudication 404s, but this work is proceeding.
=> Handle missing NOMIS and OASys data

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/prisonsapi/AdjudicationsPage.kt
We can’t guarantee that these will come back from the API, and we’ve seen nullability errors when making API requests for adjudications. Given we only need `offenceDescription`, it’s safe to make these nullable.
=> Make `oicChargeId` and `offenceCode` nullable

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CaseNotesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAcctAlertsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAdjudicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
This removes the places where we raise a 500 error when a NOMS number is missing. 
- In the case of the person search, we continue as normal (the transformer handles null inmate details)
- In the case of the case notes etc, we return a 404 (this is handled in the frontend)
- In the case of bookings, we return null for inmate details
=> Handle missing NOMS numbers in more places

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/CalendarRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CalendarRepositoryTest.kt
Currently, if a booking is recorded as non-arrived, then it still shows in the calendar and blocks the bed for future bookings. This should fix the underlying issue.
=> Handle non-arrivals

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
The /extensions endpoint currently returns a 409 when there are conflicts with an AP Booking / Lost Bed. As in other endpoints, we accept overbookings, as this is how APs are used to working.
I’ve also removed some duplicated checks in the controller for TA premises, as these are already taken care of in the service method.
=> Allow overbookings for Approved Premises when extending

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/GroupedDocuments.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DocumentTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DocumentFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DocumentTransformerTest.kt
A small amount of documents don’t seem to have IDs, as we treat them as non nullable, when we get them back from the API, an error is thrown. We need to IDs to be able to download the documents, so it’s not as simple as making the ID nullable. 
To get around this for now, we’ll filter out any documents that have no ID, so they don’t get returned. This will unblock the immediate issue that some applicants have. If it transpires that users are expecting those documents without IDs to be visible, we’ll revisit.
=> Filter out Documents without IDs

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
We can’t always guarantee a NOMS number will be present, so we need to handle when a NOMS is null, rather than throwing a null error.
=> Handle missing NOMS number in domain events

src/main/resources/db/seed/dev+test/user.csv
We’ve found that this mechanism of seeding isn’t working. Each time the API deploys to dev the CAS3 roles are not set.
When we seed them manually they are set.
When we destroy a single pod they are set.
We think that the fact that a deployment launches multiple pods at once that a race condition means that users lost their roles. This is unconfirmed but we think the right way to fix this is to use Redlock to prevent the race.
For now we need user roles to be stable. We can’t reasonably reseed after every API deploy so we’re going to remove this and trust in manual seeding.
=> Remove cas3 user role seeding in dev and test

src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
We would like to be able to update a CAS2 application. This PR makes the updates to `api.yml` to make that possible - future [work to handle them in this PR](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/800)
1. Adding an enum for `UpdateApplication` `type` field. I wasn't sure if this should be a type that the `Application` model can also use, but that would also need to include an `offline` type, which I don't think we handle on the update method?
2. Adding a class for `UpdateCas2Application` so that in the future we can distinguish it from the other
types of applications in the `applicationsApplicationIdPut` method in
ApplicationsController.
=> CAS2 update application types

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AllocationQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
The current allocations engine allocates assessments to users who have the lowest number of allocated, but incomplete assessments. This ends up penalising assessors who complete a large number of assessments quickly, meaning they keep getting assessments pile up.
This alters the query to take into account recent applications that have been assessed, so, for example, if two assessors have no pending assessments, but one assessor has recently completed an assessment, it will prioritise the one with no completed assessments in their workload.
=> Take current workload into account when allocating

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
The service is attempting to preemptively refresh NULL as a nomsNumber which is causing a kotlin not null exception to be thrown and prevent the refresher from progressing past the NULL value
=> Exclude NULL nomsNumber from preemptive cache refresh

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
This adds an endpoint for CRU managers to view all Placement Requests. We will want to add pagination, filtering etc, but this gets us part of the way
=> Add a CRU Dashboard Endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TurnaroundTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
> See [ticket #1242 on the CAS3 Trello board](https://trello.com/c/OzEFpo2w/1242-only-cas3assessor-can-crud-any-manage-endpoint).
This PR introduces the requirement that within the Temporary Accommodation service, a user must have the `CAS3_ASSESSOR` role to access endpoints involved in the Manage journey. This includes endpoints to view or manage:
- Premises
- Rooms
- Bookings
- Lost beds
This restriction also applies to the endpoints responsible for generating reports.
> **Note**
> This shouldn't be merged until we have a complete list of users who need the `CAS3_ASSESSOR` role.
>
> We will need to provide this role to existing users to avoid incorrectly forbidding them from accessing endpoints they should be able to.
=> Restrict Manage endpoints to users with `CAS3_ASSESSOR` role in Temporary Accommodation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DeleteBookingTest.kt
When we tried to use this script on prod we get the following error[1]:
```
ERROR: update or delete on table "bookings" violates foreign key constraint "turnarounds_booking_id_fkey" on table "turnarounds"
Detail: Key (id)=(76abf8b6-2fff-40f0-aea1-c54f4d30ff5d) is still referenced from table "turnarounds".
```
This could be because turnarounds was added after this script was introduced.
This change attempts to also clear any associated turnaround records as part of the deletion.
[1] https://ministryofjustice.sentry.io/issues/4321107098/?alert_rule_id=12408391&alert_type=issue&project=4503931792392192&referrer=slack
=> Delete booking script removes any turnaround records

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NewPlacementRequestBookingConfirmationTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This updates the `placement-requests/$id/bookings` endpoint to accept either a bedId or premisesId. As we can’t easily do an either/or null in the OpenAPI spec, we check for the presence of either bedId or premisesId, and raise an error if neither is present.
Bed IDs are already optional, so this shouldn’t cause any breakages elsewhere. I’ve had a quick look around and everything seems to work as expected when a Bed ID is missing.
=> (323) Allow a Booking to be created without a bedID

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
We return a generic 500 with "There was an unexpected problem" as the response but are currently discarding the actual exception - this logs the exception server side too.
=> Log unmapped exceptions in ExceptionHandling

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
All workflow managers can create bookings regardless of if a placement
request is allocated to them.
=> Allow workflow managers to create bookings from any placement request

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/resources/db/migration/all/20230725101601__add_is_parole_to_placement_requests.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt
This will usually be `false`, but in the case of when a Request is created from a PlacementApplication that has a type of `RELEASE_FOLLOWING_DECISION`, we need to set `isParole` to true, so the assessors know that the startDate is malleable and can be within six weeks of the stated date.
=> Add an isParole column to PlacementRequests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt
This ensures a placement request with a cancelled booking can be rebooked.
=> Show placement requests with cancelled booking as notMatched

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
Create CAS3 Application even if a pop doesn’t have a NomsNumber
During the CAS1 release of Apply they found that there were many people who didn’t have this field. We are now following CAS1 in making this optional for an application.
https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/6fd33c4b3d6b822d73d8455ef418f38957a95094
=> 1310 - Missing Noms Number doesn't prevent new CAS3 applications from being created

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
Optional body was failing validation.  Splitting out into two endpoints until the reason is added in the frontend.
=> Fix for Application Withdrawal issue

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysSectionsTest.kt
The frontend is still calling this endpoint if the selections endpoint returns a 404 so needs to behave in the same way.
=> Return 404 instead of 500 when upstream to OASys for sections endpoint times out

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
We would like to have a dashboard for CAS2 users that shows their 'in progress' applications.
We previously had the functionality to get all CAS2 applications, but we had not been filtering by the User ID. This PR adds that filter to the existing query, and the `status` field to the `Cas2ApplicationSummary` model. 
We currently only have `inProgress` applications, but will shortly be adding a submitted status.
=> Return CAS2 applications for user

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20230731121845__add_other_withdrawl_reason_to_applications.sql, src/main/resources/static/api.yml, src/main/resources/static/domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
When withdrawing an application, the user has to state the "other" reason if they select "other". This adds an `otherReason` field to the endpoint, and persists this in the database and the domain event. This also deprecates the `withdrawl/reason` endpoint, as we're working on the frontend implementation now. As such this shouldn't be deployed to prod until the frontend work is complete.
=> (359) Add other reason to application withdrawl

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/CalendarRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CalendarRepositoryTest.kt
We’ve noticed an issue where if a booking/lost bed finishes on the first day of the search period, it won’t show up. I’ve looked into this, and it seems that the Postgres `OVERLAPS` functionality is not inclusive. After a bit of Googling, it seems that using `tsrange` and the `&&` overlaps operator seems to do the trick.
I’ve also added a test to demonstrate and fix the regression.
=> (371) Fix issue with lost bed dates in the calendar not always displaying correctly

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/resources/db/migration/all/20230728154909__add_completed_at_column_to_temporary_accommodation_assessments_table.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationAssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
> See [ticket #1308 on the CAS3 Trello board](https://trello.com/c/X2ymPmWq/1308-application-state-can-be-updated-by-the-frontend).
This PR introduces a set of statuses specific to Temporary Accommodation assessments. This was mentioned but not implemented in #841 to keep the scope of that PR small; the described change is here.
Specifically, in Temporary Accommodation, the following states are required:
=> Implement service-specific statuses for assessments

src/main/resources/db/migration/all/20230807115837__rename_close_proximity_premises_characteristic_to_clarify_meaning.sql
> See [ticket #1428 on the CAS3 Trello board](https://trello.com/c/5xkl5JFp/1428-update-close-proximity-property-attribute).
The characteristic has been renamed to 'Close proximity to another CAS3 property' so that it's more obvious what it's referring to.
=> Rename 'Close proximity' premises characteristic to clarify meaning

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
This updates the placement requests dashboard to be able to filter by its status, rather than the parole status.
=> (373) Filter placement requests by status

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt
This allows us to get the premises name for a placement requests’s booking when listing the placement requests.
=> (373) Return booking summary in placement request list

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReallocationAtomicTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
> See [ticket #1308 on the CAS3 Trello board](https://trello.com/c/X2ymPmWq/1308-application-state-can-be-updated-by-the-frontend).
This PR modifies existing endpoints and introduces new endpoints to allow changing the state of a Temporary Accommodation assessment.
Specifically, the list of states a Temporary Accommodation assessment can be in and the corresponding API endpoint are as follows:
- `unallocated`: This is the default state when the assessment is created, but can be reached using the `DELETE /tasks/assessment/{assessmentId}/allocations` endpoint if a user needs to unallocate an assessment from themself.
- `rejected`: The `POST /assessments/{assessmentId}/rejection` endpoint is used to reject an application.
- `closed`: The `POST /assessments/{assessmentId}/closure` endpoint is …
=> Implement API endpoints to change the state of a Temporary Accommodation assessment

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
Change Placement Request dashboard endpoint to return all Placement Requests instead of defaulting to filtering on not matched when status not provided.
Add crn, tier, arrivalDateStart, arrivalDateEnd optional filters.
=> 373 - Placement requests search

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt
This allows the API to order placement requests by their assocated application's created_at date. We have to do a join and an alias for this to work as we're querying across tables.
=> Allow ordering by application date

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
> See [ticket #1381 on the CAS3 Trello board](https://trello.com/c/K6AjM2OT/1381-a-user-can-also-link-to-a-referral-as-part-of-creating-a-provisional-booking).
This PR introduces the ability to link bookings to applications within the Temporary Accommodation service. This is done by passing in an `assessmentId` parameter when sending a request to the `POST /premises/{premisesId}/bookings` endpoint.
This new field is optional, so the existing behaviour is preserved if this ID is not provided.
=> Link bookings to applications in Temporary Accommodation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentReferralHistoryNoteTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/db/migration/all/20230807153538__add_referral_history_notes_tables.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesAssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentReferralHistoryUserNoteEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationAssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/AssessmentReferralHistoryUserNoteTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
> See [ticket #1321 on the CAS3 Trello board.](https://trello.com/c/iIjSVHfm/1321-human-notes-can-be-added-to-applications)
CAS1 originally had the idea of building a generic notes system that allowed for both human-written and system-generated notes to be associated with applications. This PR implements the human side of this system for use in both CAS1 and CAS3.
These notes will be collated together to show the history of a referral; as demonstrated below:
The base-level note functionality, and the human side, is implemented here. [The system notes half of this functionality will be added in #1351.](https://trello.com/c/FTcVxbYl/1351-when-a-status-is-changed-a-system-note-is-created)
=> 1321 - Add human notes to applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/FetchOffenderNamesForApplicationsFromCommunityApiJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/UpdateAllUsersFromCommunityApiJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/resources/db/migration/all/20230809113516__add_name_to_ap_applications.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/FetchOffenderNamesForApplicationsFromCommunityApiJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This PR adds a name field to Approved Premises Applications and begins populating it for newly created Applications.
For existing Applications we also introduce a Migration Job which we can trigger which will backfill the names for existing Applications.  Once this has been run we can make the column not-null in a subsequent release (assuming we are able to succesfully backfill every Application with a name)
=> 373 - Add name to ap applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
> See [ticket #1425 on the CAS3 Trello board](https://trello.com/c/swZZtC2L/1425-frontend-can-query-for-referrals-by-crn).
This PR introduces the `crn` query parameter for the `GET /assessments` endpoint, which allows users of the API to query for Temporary Accommodation assessments for a specific person.
This parameter has not been implemented for the other CAS services, so using it will have no effect unless the `X-Service-Name` header is set to `temporary-accommodation`.
=> Allow filtering of Temporary Accommodation assessments by CRN

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/AuthorisableActionResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PersonUtils.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
> See [ticket #1452 on the CAS3 Trello board](https://trello.com/c/3Px0wqKJ/1452-filter-out-referrals-from-the-receive-table-when-the-current-user-doesnt-have-access-to-the-crn-lao).
This PR modifies the response from the `GET /assessments` endpoint to remove assessments for people who are identified as LAO when the user does not have LAO access.
Currently, if any assessment could be returned that requires LAO access, the API returns a 403 Forbidden response. In Temporary Accommodation, this has the effect that the user is signed out of the service. In this situation, no user can assess applications until someone with LAO access has processed the assessment. By filtering these assessments out instead, it allows users to continue with their work without leaking information that they are …
=> Remove assessments for LAO from response for `GET /assessments` endpoint when user does not have LAO access

helm_deploy/values-prod.yaml
When bookings are made by CRU managers, we want to be able to ensure this is reflected in Delius too, so we want to create a domain event.
=> Enable domain events for manual bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/MigrationJobController.kt
We should be running long-running jobs async, as running the `fetch_offender_names_for_applications` job in prod with lots of data is timing out.
=> Run migration jobs async

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt
We’re having an issue with some responses still not working, even though the upstream API returns successfully. This should help us diagnose what’s going on.
=> Throw original exception if the response is 2xx

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/resources/application.yml
We are getting some absolutely huge responses (400k+) from Community API for some CRNs which is blowing out the default in-memory size that Spring expects (262144 bytes). This adds a config value to increase this limit to try and combat this. Going forward, we’ll want to optimise the response and there is an ongoing discussion with the integrations team about this, but upping the memory limit should hopefully fix the immediate problem.
=> Increase memory size for Community API responses

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
We originally tried to enable this in prod by removing the env var entirely, but this doesn’t seem to have had the intended effect, so I’m setting the value to `false` implicitly to see if that works.
=> Make MANUAL_BOOKINGS_DOMAIN_EVENTS_DISABLED false

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
We don’t need to do this anymore, as anyone can mark a placement request as unable to match.
=> Remove allocation check when making bookingNotMade

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/FetchOffenderNamesForApplicationsFromCommunityApiJob.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/FetchOffenderNamesForApplicationsFromCommunityApiJobTest.kt
This seems to work in every environment except from prod. My assumption is that it’s because there’s more data in prod, and some applications have already been updated with names, so something’s getting out of whack. 
With this in mind I’ve updated the task to only fetch applications with Null names. While testing, this seemed to effect pagination too, so I’ve updated the pagination query to return a `Slice` (https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Slice.html) which only knows if there is a nextPage. 
After much wailing and gnashing of teeth, we realised that we only need to get the first page of results each time, as when we update the results, this does not update the  counter, leading every other page to get skipped.
=> Attempt to fix offender name update task

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
> See [ticket #1449 on the CAS3 Trello board](https://trello.com/c/WKfi06nk/1449-proper-fix-in-the-api-for-non-author-access-to-applicationsassessments).
We discovered a bug where Temporary Accommodation assessments that were not created by the current user were not able to be accessed, giving a 403 Forbidden response in the API. This was fixed in #877, but the fix was implemented very quickly due to time constraints. As a result, it's currently possible for a user with the `CAS1_WORKFLOW_MANAGER` role to access Temporary Accommodation assessments, and likewise with the `CAS3_ASSESSOR` role and Approved Premises assessments.
This PR updates the authorisation logic such that:
- For Approved Premises, the user can access the assessment if they have the `CAS1_WORKFLOW_MANAGER` role *or* if …
=> Authorise user access to assessments in a service-aware way

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentReferralHistoryNoteTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
Following on from a conversation with Bryan regarding how human notes (`ReferralHistoryUserNote`s) currently hold information about the user who has written them, we discovered that the intended methodology for acquiring and showing the name of the submitting user was done in a roundabout way:
- `AssessmentReferralHistoryUserNoteEntity` contains the full `UserEntity` object, called `createdByUser`.
- When transformed from JPA to API, the resulting `ReferralHistoryUserNote` only contained a `UUID` object called `createdByStaffMemberId` - this matches the approach taken for the work on Clarification Notes.
- Therefore, when attempting to display notes, the UI would need to assemble a list of staff member IDs, then make a call to `/profile/${id}` for each id, returning a …
=> Update OpenApi spec to allow human notes to pull user information from the API

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/PersonInfoResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PersonUtils.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
Reverts ministryofjustice/hmpps-approved-premises-api#911
We're now reproposing [the API LAO changes originally set out here](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/804). 
We had to revert them from dev where we were conducting some manual tests:
- We needed to make CAS3 frontend changes (which also applies to CAS2 who have been looped in) which without blocked the deployment pipeline
- CAS1 found some odd behaviour during the test (which may require an additional change to this PR)
Before we go again we should check that each frontend has updated it's types and CAS1 is happy they've fixed any problems.
=> Revert "Revert "Merge pull request #804 from ministryofjustice/309-replace-pe…"

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/PersonInfoResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
> See [ticket #1433 on the CAS3 Trello board](https://trello.com/c/vZ1cG8c0/1433-the-api-should-not-remove-a-booking-from-the-list-if-we-have-any-problem-fetching-data-spike).
This PR allows bookings to be returned by the `GET /premises/{premisesId}/bookings` and `GET /premises/{premisesId}/bookings/{bookingId}` endpoints when information about the person for whom the booking has been made is unavailable. It introduces a new `UnknownPerson` schema in the API specification, which allows consumers of the API to distinguish between a situation where the information is being intentionally withheld (represented by `RestrictedPerson`) and where the information is not currently available for some other reason (represented by `UnknownPerson`).
This PR depends on #804, and has the branch …
=> Present bookings when person information is unavailable

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingSearchResultTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingSearchTransformerTest.kt
> [see #1503 on the CAS3 Trello board.](https://trello.com/c/fWgW7BRK/1503-person-name-on-bookingsearchresultpersonsummary-should-be-optional)
[`BookingSearchResultPersonSummary.name` was previously a required field in the OpenApi specification.](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/2abdd8ab637020ea0c0620701c3e806a8fbb1a4b/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingSearchResultTransformer.kt#L23)
We now require this field to allow `null` values in the case of LAO individuals, as their names should not be revealed to the current logged-in user.
=> Relegate `BookingSearchResultPersonSummary.name` to be an optional field for allowing nulls for LAO

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentReferralHistoryNoteTransformer.kt, src/main/resources/db/migration/all/20230822104736__create_table_for_assessment_system_notes.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentReferralHistorySystemNoteEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/AssessmentReferralHistorySystemNoteTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentReferralHistoryNoteTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/ReferralHistoryNoteHelper.kt
> See [ticket #1531 on the CAS3 Trello board](https://trello.com/c/FTcVxbYl/1351-when-a-status-is-changed-a-system-note-is-created).
This PR introduces a new type of `ReferralHistoryNote` to capture and represent when various actions are performed on an assessment in the Temporary Accommodation service - `ReferralHistorySystemNote`.
A `ReferralHistorySystemNote` looks like the following:
```
{
"id": "00000000-0000-0000-0000-000000000000",
"createdAt": "2023-01-01T12:34:56.789Z",
"message": "",
"createdByUserName": "SOMEUSER",
"type": "system",
"category": "in_review"
}
```
A system note is created in the following situations:
- When an application is submitted. This is when the assessment is created and the note will have a category of `"submitted"`.
- When an assessment is allocated or …
=> Create system note when a Temporary Accommodation assessment changes state

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUsageReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BedUsageReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BedUtilisationReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/util/ReportingUtils.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUsageReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/util/ReportingUtilsTest.kt
> [see #1508 on the CAS3 Trello board.](https://trello.com/c/Vr2C038X/1508-update-reports-to-include-unique-property-and-bedspace-identifiers)
This PR implements a change to the report-generation for bed usage and bed utilisation. Previously property and bedspace references were set in the `name` field and cannot be edited by the user.
The scope of this PR, rather than open editing of this field to the user, is to add two new fields - `uniquePropertyRef` and `uniqueBedspaceRef`. These fields hash the UUIDs given in the `propertyRef` and `bedspaceRef` fields respectively to a base-58 version (alphanumeric minus 0, O, I, and l), resulting in a maximum of 11 easily-readable characters. Hashes persist for the same `propertyRef` and `bedspaceRef` for ease-of-use in the real world.
Editing of …
=> Update properties to add unique property and bedspace identifiers

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/OASysSectionsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRiskToSelfTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APOASysContext.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/OASysSectionsTransformerTest.kt
CAS2 would like to request only the Risk to Self section of an OASys.  (https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/176 ) 
Currently there is the `oasys/sections` endpoint which enforces returning several sections (e.g. ROSH, Risk to Self, Risk Management Plan) and optionally returns some other sections. It also does not return one of the questions we need in Risk to Self ('historical risk of self-harm')
This PR suggests an `oasys/risk-to-self` endpoint which only returns the Risk to Self section. I'd be interested in any feedback on this approach. We will shortly need to request just the ROSH section, so I thought about having a param sent through to determine what section is returned, but having it as it's own endpoint seemed easier to understand.
=> Return Risk To Self section of OASys report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApplicationReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/ApplicationReportProperties.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequirementsEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/ApplicationReportGeneratorTest.kt
This allows us to get a report about applications that have been submitted in a particular month. Not all the data we've been asked for is easy to get at the moment, so some of the fields are currently null.
=> (143) Add /reports/applications reports endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/resources/application.yml
We’re having some issues with certain case note responses timing out. I’ve added a special timeout value for case notes so we can hopefully fix this. Long term fix is to get a custom API endpoint for this kind of info, but this should fix things in the short-term.
=> Increase Case Notes timeout to 30 seconds

.circleci/config.yml
Following on from https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1078, we also pin of the version NPM we use in the e2e tests too as NPM 10 isn't compatible with the current version of Node
=> Pin e2e node version to 9.8.1

src/main/resources/db/migration/local+dev+test/R__1_create_dev_users.sql
This has been updated manually on the dev and test environments but should these migrations run again then we want the regions to continue to be the same.
In the frontend we are running e2e tests that require a referrer to submit a referral, the assessor then signs in and can see that referral. The way CAS3 manages content via region (rather than nationally with CAS1) makes this important.
=> Seed CAS3 CI test users with the same region

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/main/resources/static/api.yml
If an application has a non statutory sentence type, then currently, we cannot submit an application, as there is not necessarity a relevant release type for this type of sentence. This is a very unusual circumstance, as non-statutory sentence types would not ordinarily be eligible for AP, but this happens often enough for us to have to handle it.
After some discussion, we decided to add a `notApplicable` option, rather than making it non-nullable, which would have ramifications elsewhere.
=> (397) Add a `notApplicable` releaseType option

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/NotFoundProblem.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
As we’re reusing `getUserForUsername` when using the `users/delius` endpoint, this adds a `throwProblemOn404` option to the service methof, which defaults to `false`. 
If it’s set to `true` and the response from Delius is a 404, we throw a `NotFoundProblem`, which bubbles up to the controller as a 404. 
I’ve also tweaked the `NotFoundProblem` to accept an optional `identifier`, which allows us to customise the JSON body of the 404 response if we need to.
=> (Fix) Return a 404 when a user cannot be found

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/db/migration/all/20230830105713__add_summary_data_json_column_to_temporary_accommodation_assessments.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationAssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
> See [ticket #1504 on the CAS3 Trello board](https://trello.com/c/Sb4KYeHX/1504-referral-data-can-be-presented-without-knowledge-of-how-to-navigate-the-question-answer-data-blob).
This PR introduces the `summaryData` field on a Temporary Accommodation assessment. This is a user-defined bag of data intended to allow the assessment summary page in the UI to present basic information from the application in a version-agnostic way. For example, whether the offender can share accommodation with others could be represented as `summaryData.canShare`, allowing the application schema to be modified independently, such as by reordering the application questions.
As the assessment is created when the application is submitted, this information is required as part of the …
=> Provide summary data to Temporary Accommodation assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
This adds the ability for workflow managers to access reports. To make the tests a bit more complete, I've added a `ParameterizedTest` to test `userCanViewReport` with all available roles
=> Allow Workflow Managers to access reports

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
This builds on https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/945 to give admins access to reporting as well
=> Allow CAS1_ADMINs to access reports

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
> See [ticket #1509 on the CAS3 Trello board](https://trello.com/c/WFeqioTH/1509-dont-include-cancellations-in-overlapping-residents).
This PR modifies the bed search logic for Temporary Accommodation to exclude bookings with one or more cancellations. As these have been cancelled, presenting these bookings to the user has the potential to cause confusion and additional work to determine which (if any) of the bookings are actually relevant.
=> Exclude cancelled bookings from being considered as overlaps in Temporary Accommodation bed search

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/ApplicationReportGeneratorTest.kt
When making its way into production, we found that the Application reports were running out of memory. This is something we’ve seen before when listing all the applications, becuase the default query loads all the application data json into memory, which overloads the service. This creates a new repository (for tidiness, as the ApplicationEntity was getting a bit big) to generate a custom report row, containing all the things we need from the database to generate a report. This should hopefully cut down on memory usage so we can actually generate reports in prod.
I’ve had to update the unit tests to cast the applications to a `ApplicationEntityReportRow`, which is a bit long-winded, but works. I’ve also updated the integration tests to be a bit more robust.
=> (Fix) Create custom SQL for the Application Reports

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApplicationReportRow.kt
This field is not always present, so should be nullable
=> (Fix) Make offenceId nullable

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/OASysSectionsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRiskToSelfTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRoshTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APOASysContext.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/OASysSectionsTransformerTest.kt
Following [CAS2’s implementation of an `oasys/risk-to-self` risk to self specific endpoint ](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/920)(as an alternative to the generic OASys endpoint which returns all sections), this PR does the same for risk of serious harm (RoSH), creating an `oasys/rosh` endpoint.
=> Return RoSH section of an OASys report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentStateTest.kt
> See [ticket #1532 on the CAS3 Trello board](https://trello.com/c/BPzOc5fV/1532-referral-status-not-updating-properly).
When trying to mark an assessment that is 'ready to place' as being 'in review' again, the API would not correctly update the state, causing the assessment to still be shown as 'in review'.
This was caused by the `AssessmentService.reallocateTemporaryAccommodationAssessment` method not resetting the decision on the assessment to `null`. Making this change results in the expected behaviour.
The `AssessmentStateTest` class contains a test method that verifies all of the expected state transitions work as intended.
=> Fix assessment state transition from 'ready to place' back to 'in review'

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
This adds a page argument to the users endpoint, which allows us to paginate and sort the response, if the `page` argument is added. I’ve also added some util functions that should make dealing with pagination a bit easier / more DRY in future. These functions are now being used in the `getAllActive` function in the PlacementRequestService too.
=> (430) Add pagination to user list

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
The sorting wasn’t working correcly, because in some cases, the enums weren’t matching the actual field names. Using `x-enum-varnames` fixes this for every field except `application_date` where I’ve had to use a conditional to specify the sort field manually. I’ve also updated the tests to test the sorting, and also DRYed up some of the setup on the other dashboard tests
=> (426) Fix sorting on Placement Request Dashboard

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
The Applications report is currently returning ALL applications, which is obviously not what we want. I’ve added a query to filter for only AP applications, as well as updated the integration test to confirm that CAS3 applications get filtered out.
=> Ensure that only CAS1 Applications are returned in the application report

.circleci/config.yml
1.34.1 is not compatible with the latest version of NPM CLI (> 10) so we need to update the docker image
=> Update Playwright Docker image

doc/architecture/decisions/0015-cas3-street-numbers-needed-for-domain-events.md
We need to make a decision as to what CAS3 should do regarding the two domain events.
As a way to document and share the context this ADR can sit as draft until/if it's acceptable with the wider team.
[Slack conversation where this ADR was shared and discussed](https://mojdt.slack.com/archives/C03KVQUFSER/p1693926525340799). This approach should work. The ndelius/integrations team will need to break up the addressline1 if it exceeds 35 characters.
=> ADR for CAS3 property addresses for domain events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/ApplicationReportGeneratorTest.kt
At the moment, the premises type is returning an integer, which is what gets stored in the databse, for example, if the premises type is `normal`, we get `0`, premises type is `pipe` we get `1` and so on. This updates the query to return the `ap_type` as `premisesTypeIndex`. We can then change the `getPremisesType` interface method to get the index (if it exists) and use `ApType.entries` to get the enum value by the index. I suspect this is how it’s done with normal JPA classes, but with query interfaces, it seems we need to jump through this additional hoop!
=> Get premises type correctly in Application reports

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
We are doing some work [on pulling in ROSH risks ](https://trello.com/c/dl2n6Ny1/343-rosh-rosh-risk-summary-from-oasys) which highlighted that we are getting the person's risk when a CAS2 Application is first created. We don't need to do this for CAS2 so I'm taking that field out. Same for an `arrivalDate` as I don't believe we currently use that.
This should also simplify work coming up on [CAS2 inheritance](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/960)
=> remove `riskRatings` and `arrivalDate` from CAS2 Application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
When setting the exclusion roles, it looked like they weren’t being set. These were being set in the database correctly, but the transformer was not handling them correctly, meaning the users didn’t think they were being set. I’ve updated the tests to be more robust, as well as updating the `transformApprovedPremisesRoleToApi` function to handle all roles.
=> (Fix) Ensure all user roles are returned

doc/how-to/preprod-database-refresh.md, helm_deploy/hmpps-approved-premises-api/templates/cronjob-prod-to-preprod-refresh.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml
~~**Not to be merged until https://github.com/ministryofjustice/cloud-platform-environments/pull/16411 is in**~~
This cribs from work the interventions team have done to set a cron job to run every Sunday to copy prod data to preprod:
https://github.com/ministryofjustice/hmpps-interventions-service/blob/main/helm_deploy/hmpps-interventions-service/templates/cronjob-prod-to-preprod-refresh.yaml
This will allow us to make preprod a more realistic environment, allowing UAT and debugging easier to carry out.
=> Add a cron job to copy prod data to preprod

.circleci/config.yml
This is a bit of a blunt instrument, but the CI times seem to be creeping up, so let’s throw another container at it.
=> Increase parallelism on CI tests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
This updates the `findAllByReallocatedAtNullAndBooking_IdNullAndIsWithdrawnFalse` to join the booking_not_mades table to ensure that placement requests disappear from the Tasks endpoint when they are marked as unable to match.
=> (450) Unmatchable Placement Requests don’t show as tasks

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AllocationQueryTest.kt
Now we can 'soft-delete' users, we need to make sure nothing is allocated to them, otherwise tasks will fall down a black hole!
=> Only fetch active users when auto-allocating

doc/how-to/access_database_remotely.md, script/remote_db
I got fed up of having to check the docs each time to remember how to do this, so I’ve added an easier method. I’ve updated the docs to detail both methods, as sometimes you’ll need access to the bash shell as well as Jaqy.
=> Add a remote_db script

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
This will allow us to show the decision that an assessment was made when viewing an application.
=> Add an assessment decision date to an application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequirementsEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequirementsEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
There are sometimes cases when an application can have multiple assessments, so we need to ensure we only get one placement requirement object. Ordering by created at and using `findTopBy` seems to do the trick.
=> (455) Fetch latest placement requirements

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
I was wracking my brains about why there were so many placement requests that appeared to be out of date in the task list. While all the other task queries are JPA derived queries (i.e `findBy..`), the Placement Request query is a custom one, and we left out the `reallocated_at IS NULL` conditional. This should fix it and mean there are much fewer tasks in the list now.
=> Hide reallocated placmement request in task list

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/RoomEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RoomServiceTest.kt
> See tickets [#1518](https://trello.com/c/9j9u5rA6/1518-bedspace-references-are-editable) and [#1519](https://trello.com/c/vsOnvtbC/1519-property-references-are-editable) on the CAS3 Trello board.
This PR updates the behaviour of the `PUT /premises/{premisesId}` and `PUT /premises{premisesId}/rooms/{roomId}` endpoints to allow the name of a premises or room respectively to be updated.
The `UpdatePremises` schema for the `PUT /premises/{premisesId}` endpoint now looks like:
```jsonc
{
"addressLine1": "1 The Street",
"addressLine2": "",
"town": "Faketon",
"postcode": "AA1 1AA",
"notes": "Some text",
"localAuthorityAreaId": "00000000-0000-0000-0000-000000000000",
"probationRegionId": "00000000-0000-0000-0000-000000000000",
"characteristicIds": [
"00000000-0000-0000-0000-000000000000",
// …
```
=> Allow names of premises and rooms to be updated in Temporary Accommodation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
Currently there is no way to retrieve the index offence for a referral in the Temporary Accommodation service. When creating an application, the offence ID is required and stored in the database already. By including the offence ID in the `TemporaryAccommodationApplication` schema, it becomes accessible when users of the API send a request for an application or for an assessment (which include its application), allowing the presentation of the index offence.
=> Add offence ID to Temporary Accommodation applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/CommunityAPI.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/PrisonAPI.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
> See [ticket #1569 on the CAS3 Trello board](https://trello.com/c/mrl4OEIg/1569-a-user-cant-see-a-booking-if-nomis-returns-500-for-that-nomsnumber).
A CAS3 user reported being unable to make a booking on a property. An investigation determined that [this Sentry event](https://ministryofjustice.sentry.io/issues/4479799213/?environment=prod&project=4503931792392192&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) corresponds to the user's request and from [AppInsights](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22a5ddf257-3b21-4ba9-a28c-ab30f751b383%22%2C%22ResourceGroup%22%3A%22nomisapi-prod-rg%22%2C%22Name%22%3A%22nomisapi-prod%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fa5dd …
=> Avoid throwing an exception when inmate details are unavailable from the Prison API

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/resources/db/migration/all/20230921153329__make_placement_request_allocated_to_user_id_nullable.sql, src/main/resources/static/api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
We’re getting an unusual number of allocations failing when submitting applications etc. While we attempt to work out what’s going on, we’ll log errors and make the allocated to user null. We’ll also log the failure to allocate together with the number of attempts, which will give us more of an idea why these errors are happening.
As part of this we’ve had to make the allocated to user nullable in a few places.
=> Don’t fail when unable to allocate a user

src/main/resources/db/migration/all/20230915300000__update_greater_manchester_probation_region_mapping.sql
There was work 3 months ago to introduce a mapping layer ontop of probation regions called `probation_area_probation_region_mappings`.[1]
Our latest attempt to seed an HPT user failed with this error related to incorrect probation region for N50[2]. This is odd because we’ve seeded users with N50 before and they’re using the service. I think the problem is coming from the changes made to how we check the probation region here[5].
This appears to have copied over the wrong Delius region code for Greater Manchester[3]. Instead of MCG it should be N50. I suspect the latest work missed the migration we made to correct this code[4] and took the values from a seed file rather than from the real values.
[1] https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/a1551b3d4daa9f749c …
=> Correct regional mapping code for Greater Manchester

doc/architecture/decisions/0017-handle-nomis-users-without-inheritance-in-cas2.md, doc/architecture/decisions/0018-introduce-cas2-api-namespace.md
I've discussed this with @Harriethw and @adamhughes86 already and we think this is a good way forward.
We're now keen to hear from @pezholio , @danlivings-dxw, @tahb, @gareth-hallberg, @nsmj63-dxw 
I've also drafted a further ADR ("16: Introduce CAS2 API namespace") in which we make the case for introducing a `/cas2/` namespace to the API and introducing CAS2-specific controllers. We think this would be a preliminary step, before doing any of the work outlined here to handle Nomis users. i.e.:
1. refactor existing behaviour to `/cas2/` API namespace and CAS2 controllers
2. handle Nomis users / CAS2 Applications as outlined here
=> ADR: Handle Nomis users without inheritance in CAS2

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20230927134507__add_target_location_to_approved_premises_application.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This field is already passed when submitting an application, but only gets used in domain events. This adds a new targetLocation field to the application location, so we can use it in reporting. We will need to look at backfilling the applications that do not have this data, possibly using the domain events.
=> (460) Persist targetLocation in applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserAllocationsEngine.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserAllocationsEngineTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
The Allocations engine has been giving us a lot of grief recently. I attempted a fix in a previous PR, but I’ve since discovered that it didn’t _quite_ match up with what was expected. To try and make this a bit more configurable, and to remove some of the complex logic, I’ve added a `UserAllocationsEngine` class, which has a `getUserPool` function that uses the `CriteriaBuilder` to get a list of qualified users IDs, we then pass those IDs to get the user with the smallest workload, depending on the type of task.
It’s still a little cumbersome, but I’ve attempted to make it a little easier to grok with comments etc.
=> Add an AllocationsEngine class

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
https://trello.com/c/CyPr93lv
We had a support request for a user whom had been unable to access the service because they were appearing as "West Midlands" rather than "Kent, Surrey & Sussex".
After confirming the regional data is now set correctly after a presumed update, our users table still had the WM region associated with it.
We extend the existing update mechanism to now also update the user's region. As this is part of a scheduled job my hope is that this change will automatically keep up to date with ndelius as the canonical store for regional ids.
- add a helper method for finding the users region so we can reuse it in create and update logic
=> Fix user region not refreshing to the latest Delius value

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/AdjudicationsApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApOASysContextApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CaseNotesClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/GovUKBankHolidaysApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/HMPPSTierApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/WebClientCache.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PreemptiveCacheTest.kt
> See ticket [#1570 on the CAS3 Trello board](https://trello.com/c/KU3pJJox/1570-redis-cache-keys-are-required-for-rendering-the-assessment-page).
This PR performs a refactoring of `BaseHMPPSClient` and related classes to separate caching and outbound HTTP requests.
This was originally done as preparatory work to resolve the bug described in the Trello ticket above (ultimately from [this Sentry issue](https://ministryofjustice.sentry.io/issues/4479884804/)), however, it appears that this problem has already been resolved by some other work. An integration test verifying the fix has been added to this PR to prevent an accidental regression.
This PR refactors the specifics of interacting with the cache out of `BaseHMPPSClient.doRequest` into several methods on a new `WebClientCache` class: …
=> Separate caching and downstream API request logic

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
This updates our `TaskTransformer` to use `addWorkingdays` instead of the blunt instrument `plusDays`.
It also (and potentially more controversially) changes the WorkingDayCountService to use a static file. We’re hitting the GOV.UK bank holidays API a lot to make these requests (even though they’re cached in Redis). In a seperate PR, we’ll add a Github action (similar to https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1050) to check the file for changes, and open a PR to replace the file if it has.
=> (425) Use working days for task due days

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseDetailFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, wiremock/mappings/ApDeliusContext_GetCaseDetail.json
As part of our reporting needs, we need to get the reporting team for a CRN (e.g. the Case Manager). Before, we were just fetching the first team of the logged in user, but it turns out this isn't what we need.
As part of the ambition to move away from Community API, the integrations team have built us a shiny new endpoint to give us all the information we need about a case, including the managing team.
This PR adds the client integration for this endpoint, and uses it when submitting an application and storing the domain event info.
Going forward, we'll want to replace all our calls to getting offender details with this new endpoint (as well as some bulk fetch endpoints, which have also been built), but let's start with this first.
=> (480) Get managing team for CRN

.github/workflows/generate-cas2-ui-types.yml, .github/workflows/generate-ui-types.yml
We now need to watch the build YML files for changes, not the source ones. I’ve also added a seperate CAS2 workflow to watch the CAS2 YAML file.
=> Update type generation workflows

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseDetailFactory.kt, wiremock/mappings/ApDeliusContext_GetCaseDetail.json
The datetimes include offsets, so can’t be parsed to a LocalDateTime.
=> Update Mappa lastUpdated to ZonedDateTime

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
If a Booking is cancelled, it won’t have an associated bed.
=> Make Bed info nullable

build.gradle.kts, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/domainevent/SnsEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt, src/main/resources/application-local.yml, src/main/resources/application.yml, src/main/resources/db/migration/all/20231009162205__add_support_for_cas3_to_domain_events_table.sql, src/main/resources/static/cas3-domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3DomainEventFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/PersonReferenceFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/PremisesFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventBuilderTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventServiceTest.kt, src/test/resources/application-test.yml
> See ticket [#1623 on the CAS3 Trello board](https://trello.com/c/JAHewQrO/1623-we-can-send-domain-events-without-requiring-an-application-id).
Following [this discussion](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1004#discussion_r1348479356) on #1004 where a need for a meaningful record identifier when the application ID is unavailable was raised, and [this Slack discussion with the probation integrations team](https://mojdt.slack.com/archives/C03KVQUFSER/p1696846088073159), we've reached an agreement to modify the structure of the domain events that we send, such that the `additionalInformation` section of the event can accept an optional `applicationId` and/or an optional `bookingId`.
While this change on its own is rather small, the above PR (#1004) at the …
=> Add support for CAS3 domain events

src/main/resources/application.yml
This needs to match the
`SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_*` environment variables defined in the helm template `values.yaml` e.g.
`SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOMIS-USER-ROLES-API_CLIENT-ID`
The error this should fix is:
```
Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: 
Factory method 'clientRegistrationRepository'threw exception; nested exception is java.lang.IllegalStateException:
Provider ID must be specified for client registration 'nomis-user-roles-api
```
=> Fix: adjust oauth client registration key to match spring env var

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/resources/application.yml, src/test/resources/application-test.yml
There were 2 further problems with our config which are addressed here, to give us the follow configs:
The OAuth client used to authenticate the system-to-system connection between the CAS and the new Nomis-User-Roles client must be configured with a key in `security.oauth2.client.registration` in `application.yml` which matches the environment variable defined in `helm_deploy/values.yaml` in the form `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_*`, in this case:
- `nomis-user-roles-api` in `application.yml` and
- `SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOMIS-USER-ROLES-API_CLIENT-{ID,SECRET}` in `values.yaml`
Additionally, we need to tell our API client which OAuth client to use. This is done in `WebClientConfiguration.kt` using the value set in `security.oauth2.client.registration` …
=> Fix (pt 2) OAuth client registration and BASE URL config for Nomis-User-Roles API client

docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/PersonSummaryInfoResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/UserAccess.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseAccessFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt, wiremock/__files/caseSummary, wiremock/__files/userAccess, wiremock/mappings/ApDeliusContext_GetCaseSummaries.json, wiremock/mappings/ApDeliusContext_GetUserAccess.json
The integrations team have built us two endpoints to fetch information for multiple CRNs in one API call. One fetches the basic information about the case, and the other checks if the logged in user has permissions to view those cases. This should significantly speed up requests when we have to fetch multiple cases on one endpoint (for example when listing multiple entities). By way of a trial, I've added all the necessary wiring to call these new endpoints on the Premises summary endpoint. If we're happy, it should be fairly trivial to roll the endpoint out on other listings pages.
=> (454) Bulk fetch CRNs on Premises Summary request

helm_deploy/values-dev.yaml
from https://nomis-user-dev.aks-dev-1.studio-hosting.service.justice.gov.uk to https://nomis-user-roles-api-dev.prison.service.justice.gov.uk
=> HAAR-1778: update nomis-user-roles-api dev url

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventBuilder.kt, src/main/resources/application.yml, src/main/resources/static/cas3-domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3PersonArrivedEventDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3PersonDepartedEventDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventBuilderTest.kt, src/test/resources/application-test.yml
> See [ticket #1639 on the CAS3 Trello board](https://trello.com/c/sPimu5Mx/1639-add-urls-to-the-person-arrived-and-departed-domain-event-endpoints).
Following a discussion with the integrations team, we've come to the agreement to provide URLs to the relevant booking and application (if available) associated with the event. This PR introduces `applicationUrl` and `bookingUrl` as properties on the two existing CAS3 domain events, as well as the infrastructure to generate appropriate URLs for future event types.
=> Add application URL and booking URL to CAS3 domain events

src/main/resources/db/migration/all/20231019112844__retire_error_in_booking_reason.sql
This is a duplicate, so we should retire it.
=> (485) Retire “Error in Booking” reason

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/DailyMetricsReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ReferralsMetricsReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApprovedPremisesApplicationMetricsSummaryDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ReferralsDataDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DailyMetricsReportTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferralsReportTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/DailyMetricsReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/ReferralsMetricsReportGeneratorTest.kt
The Daily Metrics and Referrals reports wer erroring as we were loading all the application JSON in memory. This tweaks the queries we use to only return what we need, cast it as a DTO in the service, and then pass the list of DTOs to the Generators.
=> Fix memory errors on Daily Metrics and Referrals report

src/main/resources/application.yml
Attempted fix for https://ministryofjustice.sentry.io/issues/4401628845/?project=4503931792392192&query=is%3Aunresolved+N013922&referrer=issue-stream&statsPeriod=90d&stream_index=0 
We initially tried to increase max-in-memory-size, but this setting overrides that
=> Increase max-response-in-memory-size-bytes

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
Following on from #1066 - the config we set was only used in the Community API previously, so we'll use this setting for Prisons API too.
=> Add maxResponseInMemorySize config to PrisonsAPI

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApplicationReportRow.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
This is needed for performance reporting. The original plan was to have a breakddown by release type and sentence type, but we’ve agreed that adding this to the application report was sufficient.
=> (413) Add sentence type to Application Report

.circleci/config.yml, build.gradle.kts
This uses `gradle assemble` on the main and test code to ensure all code is built at the build stage (previously, all containers were building the test code at the test stage). I've also split the unit and integrations tests up into seperate jobs, so they can run in parallel.
=> Speed up CI

src/main/resources/application-local.yml
In the Cloud Platform deployed environments these flags are set with environment variables set in the Helm 'values.yaml' e.g.
```
DOMAIN-EVENTS_CAS2_EMIT-ENABLED: true
```
=> Add missing CAS2 domain event feature flag for local env

build.gradle.kts
Addresses https://nvd.nist.gov/vuln/detail/CVE-2023-2976
This is used by kotlinx/dataframe, but is not included directly.
=> Bump Guava version

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt
The integrations team have identified that multiple event types have incorrect URLs in the development environment in the form:
```
${url-templates.api.cas3.referral-submitted-event-detail
```
This is caused by a missing closing brace in the `@Value` annotations used to autowire the URL template configuration values into the CAS3 `DomainEventService`.
=> Fix malformed URL templates for CAS3 domain events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
Now assessments can be withdrawn, we need to hide them on the assessments and application listing pages.
=> (APS-14) Hide withdrawn assessments

helm_deploy/values-prod.yaml
Double the memory limits  and double the maximum java heap allowancee in an effort to prevent out of memory exceptions being fired[1].
The CAS3 frontend[2] and CAS1 frontend[3] are exp seemingly random request timeouts after 30s.
There was another recent effort to increase memory size of spring[4] but without detail of what this was attempting to fix, it’s hard to know if this was a related attempt.
[1] https://ministryofjustice.sentry.io/issues/4087001141/?environment=prod&project=4503931792392192&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
[2] https://ministryofjustice.sentry.io/issues/4383361316/events/?environment=prod&project=4504129156218880&referrer=issue-stream&statsPeriod=90d&stream_index=0
[3] …
=> Double memory allocation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ExternalUserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ExternalUserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/HttpAuthService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/cas2/PersonUtils.kt, src/main/resources/db/migration/all/20231017175537__create_table_for_external_users.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ExternalUserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ExternalUserTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/OffenderServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/JwtAuthHelper.kt
External users from NACRO will be logging into CAS to perform specific operations on *submitted* CAS2 applications only.
The users are managed on HMPPS auth and will have the role `CAS2_ASSESSOR` (the JWT 'authority' `ROLE_CAS2_ASSESSOR`). The `auth_source` of their claim will be `auth`. 
See AP-Tools [PR 48](https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/48) for a CAS2_ASSESSOR user for use in local development.
In this PR we:
- allow an external user to authenticate and create a representation for each one in a new `external_users` table
- allow holders of the `CAS2_ASSESSOR` role to `GET` a list of submitted applications or an individual submitted application.
Note that for "submitted" we test for the presence of a  
value in the `Cas2Application.submittedAt` …
=> (518) External NACRO assessor logs in to view submitted CAS2 applications

src/main/resources/db/migration/all/20231019120235__backfill_new_eligibility_reason_field_on_cas3_referrals.sql
We’ll need this historic data for referrals created so far in production.
=> Backfill cas3 referrals so they have eligibility reasons

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt
In this PR I make a case for introducing a new REST resource to represent applications 
which have been submitted.
The other CAS services introduce a new DB entity (`Assessment`), but I think this is
overkill for our needs. We can achieve the "separation of concerns" which we need
by introducing a new API model (REST representation) to present the existing application
record in the post-submission world.
When the UI asks that API for a list of applications, what is the appropriate
range of filtering which should be implicitly applied by the API?
`GET /applications`
- APPLICANT: all applications which I've created (filter on associated user)
- ASSESSOR: all application which have been submitted (filter on submittedAt
presence)
- ADMIN: all applications (no filter)
`GET …
=> Implement submissions endpoint for assessors

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesOfflineApplicationsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/application.yml, src/main/resources/db/migration/all/20231026150308__add_event_number_to_offline_applications.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OfflineApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This tweaks `createApprovedPremisesAdHocBooking` to ensure that the index offence is provided alongside an adhoc booking (which is required when emitting domain events).
=> (APS 13) Emit domain events for all manual bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BookingsReportRow.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt
> See [ticket #1516 on the CAS3 Trello board](https://trello.com/c/fixhLvcQ/1516-include-new-referral-columns-in-the-mi-report-download).
There are several columns that are now required for MI reporting for bookings that have applications. For bookings not associated with an application these must be empty, but otherwise should be included in the booking report.
=> Include referral columns in booking report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
We have some nullability issues (see https://ministryofjustice.sentry.io/issues/4590242455/?project=4503931667742720&project=4503931792392192&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0) when running the e2e tests, so adding some logging to see what’s going on.
=> Add debug info for manual bookings

src/main/resources/db/migration/all/20231026150308__add_event_number_to_offline_applications.sql
When we reverted the changes in #1094, we removed the migrations, which has broken the deploy.
=> Restore removed migration

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
**This should be merged with the corresponding change at the UI https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/273**
CAS2 Applications are now submitted using a POST to the submissions endpoint:
`POST /cas2/submissions` with
`{ translatedDocument: JSON, applicationId: UUID}`
rather than
`POST /cas2/applications/{applicationId}/submission` with
`{ translatedDocument: JSON, type: 'CAS2'}`
Representing a submitted application as a "submission" resource with a type of `CAS2SubmittedApplication`
allows us to avoid adding to complexity to the `ApplicationsController`.
Note also that:
- the `applicationId` is now received as the `applicationId`
form data param rather than being in the path.
- the `type` param is no longer part of the interface, as this was not …
=> Move CAS2 application submission endpoint to /cas2/submissions

build.gradle.kts, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesOfflineApplicationsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/resources/application.yml, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OfflineApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This is a redo of https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1084 - we needed to revert it as it went into production before we were ready for it.
=> (APS-13) Emit domain events for all manual bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationTimelineNoteEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationTimelineNoteService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineNoteTransformer.kt, src/main/resources/db/migration/all/20231102094837__create_application_timeline_notes.sql, src/main/resources/static/_shared.yml, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationTimelineNoteEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
1. New endpoint /applications/{applicationId}/notes. 
2. Database migration.
3. New ApplicationTimelineNoteEntity and ApplicationTimelineNoteRepository and ApplicationTimelineNoteService.
4. Tests for creating notes.
5. Tweaked Timeline endpoint return to include these notes as a new TimlineEventType.
6. Tests that show the timeline endpoint can return these notes in payload.
=> Aps23 users must be able to add manual notes into the timeline view

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
The work we did in #1096 means that some bookings now have offline applications. When they're changed or cancelled, we want to use domain events too. At the moment, the code makes the assumption that the bookings will have applications, which isn't the case for bookings with offline applications, so we're getting nullability errors. This should fix this issue.
=> (APS-42) Allow bookings with offline applications to be amended or cancelled

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/PlacementMetricsReportGenerator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/PlacementMetricsReportGeneratorTest.kt
The Placement Metrics report is failing because some of the timeliness values are null. Instead of using a bang to make them not null, let’s filter out the null entries.
=> Filter out null timeliness entries

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt, src/main/resources/static/_shared.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReferenceDataTest.kt
This endpoint will allow the UI to build a form for an assessor to provide a status update.
The status options are currently defined inline in `model/reference/Cas2ApplicationStatusSeeding.kt`
but we'll introduce database seeding to manage them.
=> Add CAS2 application status reference data

src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/ApplyJourneyStressSimulation.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/BookingsReportGenerationTimeSimulation.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Applications.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Bookings.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Premises.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/ReferenceData.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Users.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Auth.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Json.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Session.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BookingsReportData.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BookingsReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseDetailFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenderDetailsSummaryFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RandomData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/ReportsTestHelper.kt
> See [ticket #1535 on the CAS3 Trello board](https://trello.com/c/b8NYSvNw/1535-report-mi-spreadsheet-includes-personal-data).
This PR introduces columns containing personal data to the bookings report. These columns are:
- `personName`
- `pncNumber`
- `gender`
- `ethnicity`
- `dateOfBirth`
Of these columns, four are populated as expected - `pncNumber` is currently not available and is always presented as a blank cell. This is because we do not store personal information within our service and have to obtain it elsewhere. Although we cache results from the Community API, the number of results expected in a typical spreadsheet is between 200 and 400 rows, and performing a request to the cache for each CRN incurs an unacceptable performance degradation (see below). The alternative solution …
=> Include personal data for bookings report

src/main/resources/application.yml
We noticed a bunch of errors during a 3 minute window where database connections couldn't be created. [Slack alerts](https://mojdt.slack.com/archives/C044ZUGJRC7/p1699463989529889). [Slack conversation](https://mojdt.slack.com/archives/C03K0HB0LBE/p1699464447663939).
On investigating App Insights we see the following:
Blue = max available connections
Purple = sum of active connections
Ping = connections pending
Green = connections timed out
This tells me that something hogged all 40 connections and explains why we see failures to acquire new connections shortly after. We should investigate separately what logic required such a dramatic increase. I suspect it's the booking/search being unpaginated. For now though, we can increase our max database connections to be more resilient.
There are …
=> Increase maximum database connections to 20 per replica

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
When working on the frontend, we identified a couple of issues with the placement application withdrawl logic, and we also needed to ensure that applications that already had associated bookings could not be withdrawn.
=> (APS-14) Tighten up placement application withdrawl logic

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/ApplicationStatusMigrationJob.kt
Even though we're paginating, it's all happening in one transaction, so the garbage collector isn't clearing up any memory until the transaction is complete. I *think* running `applicationRepository.flush()` at the end of each page should sort it.
=> Flush changes in migration

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/ApplicationStatusMigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SetApplicationStatusMigrationTest.kt
This calls `saveAndFlush` when updating the DB entries to save the applications immediately, as well as passing the entityManager to the Job so we can clear the transaction cache after each page.
=> Call saveAndFlush and use entityManager

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/ApplicationStatusMigrationJob.kt
When looking at https://www.baeldung.com/spring-data-jpa-iterate-large-result-sets#streaming-from-the-database, I missed that the `try` block used the output of `findAllForService` within an argument for the data to stream correctly. This way to do this in Kotlin is with a `.use` block, so I’ve updated the code to do this.
=> Use streaming correctly when using large dataset

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/ApplicationStatusMigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
We’re still having problems in preprod when updating statuses and pages getting  skipped. To get around this, I’ve changed the query to only fetch  applications without a status. This borrows from an approach we used in https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/906 when we were updating offender names, which seemed to work. 
Only fetching applications without a status also means we can run the task multiple times and only fetch/update a subset of applications too.
=> Only update applications without statuses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/StatusUpdateEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ExternalUserTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/StatusUpdateTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmittedApplicationTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2StatusUpdateEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas2StatusUpdateTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ExternalUserTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/StatusUpdateTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmittedApplicationTransformerTest.kt
Our representation of a `SubmittedApplication` now includes a list of `StatusUpdate`s
Note that:
- `updatedAt` is the creation timestamp of the status update
- `updatedBy` is a new representation of an `ExternalUser`
- status updates are ordered by date descending i.e. most recent first
=> Expose representations of CAS2 status updates within SubmittedApplication

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
When returning placement applications for an application, we don’t want to show withdrawn ones. I've added a test to confirm this, as well as extending the tests to test all non-withdrawn placement applications get returned.
=> Hide withdrawn placement applications

src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/ApplyJourneyStressSimulation.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/BookingsReportGenerationTimeSimulation.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Applications.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Bookings.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Premises.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/ReferenceData.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Users.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Auth.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Json.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/util/Session.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BookingsReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BookingsReportRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RandomData.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/ReportsTestHelper.kt
This PR replaces the Hibernate-managed JPQL query for `BookingRepository.findAllByOverlappingDate` with a handwritten native SQL query called from `BookingsReportRepository.findAllByOverlappingDate`.
This native SQL query returns just the set of data that is needed to populate the booking report and avoids the N+1 query problem caused by lazily loading dependent entities on the booking.
The performance test used to assess the performance of this change was performed using the same code and methodology as for #1100.
The original control test from `main` as of #1100, using JPQL and allowing Hibernate to generate multiple queries:
The results of the test as a result of using a handwritten native query:
The findings, summarised in a table:
| Test | Success rate | Minimum time (s)[1] | Maximum …
=> Use native query to retrieve data for bookings report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/ApplicationStatusMigrationJob.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SetApplicationStatusMigrationTest.kt
Currently, when running `save` against the application, we save the entire object, which may cause issues in production when real users are using the system. This detaches the entity to remove it from the [JPA entity lifecycle](https://dzone.com/articles/jpa-entity-lifecycle) and then runs a custom update to only update the status field.
=> (APS 45) Update migration to only update status

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/ApplicationStatusMigrationJob.kt
I don’t know why this worked in test, but I think we need to detach the application after we’ve done everything we need to do with the application.
https://ministryofjustice.sentry.io/issues/4633236006/?referrer=slack&notification_uuid=1f80056b-a46b-4f9a-902b-7be138a494d9&alert_rule_id=13862421&alert_type=issue
=> Detach application after fetching assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
When I did the frontend, I assumed we'd named the sortBy field to be the same as the other endpoints (I missed this in the review!). Rather than changing the implementation in the frontend, I've changed it here for consistency's sake.
=> Rename applicationSortField to sortBy

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
The way I’d written the query wasn’t quite working as we expected, and we were also pulling through unsubmitted applications, which caused errors in the frontend.
=> Fix placement application query

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmittedApplicationTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmittedApplicationTransformerTest.kt
We do not need this field, as it relates to the `ApplicationStatus` types which are not revelant to our submissions, and do not want them confused with our `StatusUpdates` which are added by assessors to a submitted application.
=> Remove `status` on CAS2 SubmittedApplications

helm_deploy/values-preprod.yaml, helm_deploy/values-test.yaml
> See [ticket #1700 on the CAS3 Trello board](https://trello.com/c/lBb6hRsw/1700-enable-all-domain-events-in-preprod-to-enable-further-testing-by-the-delius-team).
This PR enables the six current CAS3 domain events in the `test` and `preprod` environments. This is needed to enable the Delius integrations team to carry out testing.
=> Enable CAS3 domain events in `test` and `preprod` environments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
For some reason, this is skewing the count returned in the search results. We don't need this join anyway, so we should remove it.
=> Remove join from count query

detekt.yml
[This came up during a recent PR review](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1105#discussion_r1387866695).
This keeps the rules inline with how we’ve been importing on the project so far. With this change we don’t review whether this is the right/wrong choice, we just aim to consistently apply the previous rule.
Detekt defaults this to be excluded[1] so we remove the exclusion.
[1] https://detekt.dev/docs/rules/style/#wildcardimport
With the exception removed we can see detekt correctly starts to fail:
=> Detekt monitors for wildcard java util imports

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt
At present we rely on an explicit `ensureExternalUserPersisted()` function within controller actions to ensure that the logged in assessor is recorded in our `external_users` table.
It would be good to develop this, perhaps:
- making it the responsibility of `HttpAuthService.getCas2AuthenticatedPrincipalOrThrow()`, or
- do something more elaborate using Spring's `UserContext` see [NomisUserRoles](https://github.com/ministryofjustice/nomis-user-roles-api/blob/main/src/main/kotlin/uk/gov/justice/digital/hmpps/nomisuserrolesapi/utils/UserContext.kt#L6) and [Baeldung: Get User in Spring Security](https://www.baeldung.com/get-user-in-spring-security)
=> (649) Fix: ensure new assessor is persisted on GET to individual SubmittedApplication

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This adds a `isCancelled` helper to a booking to check if a booking is cancelled, we can then use it to add to the
`createApprovedPremisesBookingFromPlacementRequest` validations to allow placement requests with cancelled bookings to have a new booking applied to them.
I’ve also DRYed up the expectations in the unit tests a little bit. There’s still a bit too much repetition in the setup stage than I’d like, but it’s a bit better than it was.
=> (APS-41) Placement with a cancelled booking can be rebooked

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ManageUsersApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ExternalUserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/manageusers/ExternalUserDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ExternalUserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ExternalUserTransformer.kt, src/main/resources/application.yml, src/main/resources/db/migration/all/20231120153953__add_name_and_email_to_external_users.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ExternalUserDetailsFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ExternalUserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/ManageUsersAPI.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ExternalUserServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ExternalUserTransformerTest.kt, src/test/resources/application-test.yml
See [Trello 633](https://trello.com/c/ojaf1IBa/633-add-name-and-email-address-to-external-users)
Note that to run locally [AP-Tools now provides HMPPS Manage-Users API on port 9560](https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/52)
The representation of an `ExternalUser` which is used in `Cas2StatusUpdate.updatedBy` needs to have more information than we were initially extracting from the logged in user's JWT.
Our `ExternalUserService` now connects to the HMPPS-Manage-Users' `/externalusers/{username}` endpoint and we add `name` and `email` properties to:
- the record which we persist in the `external_users table` and also to 
- the JSON representation which we provide to the UI.
=> 633 Add name and email address to `ExternalUser`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesSummaryTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PremisesSummaryTransformerTest.kt
Refer [1702](https://trello.com/c/CxWyysoq/1702-premises-list-includes-local-authority-for-gm) for more information.
This change is to return optional 'localAuthorityAreaName' in API 'premises/summary' endpoint for temporary accommodation premises only.
confirm:
advance?
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-temporary-accommod …
=> [1702]- Premises summary include local authority name for CAS3 temporary accommodation premises

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ProbationOffenderSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/PeopleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ProbationOffenderSearchResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/probationoffendersearchapi/ProbationOffenderDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/probationoffendersearchapi/ProbationOffenderSearchNomsRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/main/resources/application.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationOffenderDetailFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/ProbationOffenderSearchAPI.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/OffenderServiceTest.kt, src/test/resources/application-test.yml
This depends on the AP Tools PR being merged: https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/51 
If you'd like to call the added controller function from the UI there is this WIP PR: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/310
We need to allow a CAS2 user to search for an offender by prison number (nomsNumber), from an API that returns a CRN in order to make subsequent requests for OASyS data. This PR makes a request to [the `probation-offender-search` API](https://github.com/ministryofjustice/probation-offender-search). The shape of the [data returned should match what's returned from the probation API](http://localhost:8084/swagger-ui/index.html#/offender-search/search_1), which is a list of OffenderDetails.
See their …
=> Search for person by NOMIS ID for CAS2

src/main/resources/application.yml
It's not clear why Spring is throwing this error:
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException:
Error creating bean with name 'caseNotesWebClient' defined in class path resource
[uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.class]:
Unsatisfied dependency expressed through method 'caseNotesWebClient' parameter 0;
nested exception is org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'clientRegistrationRepository' defined in class path resource
[org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2ClientRegistrationRepositoryConfiguration.class]:
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: …
```
=> Restore OAuth config for Nomis-User-Roles API client

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationOffenderDetailFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
We need to display a person's PNC number to our CAS2 users.
We can get this when we search for an offender when we call `searchOffenderByNomsNumber` on the ProbationOffenderSearch. https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/61284aa89c71b09a6d095ebc6fe8b491c26dc3b3/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt#L39 
This PR adds the number as an optional field to the `FullPerson` model and the `PersonTransformer`.
=> Add PNC number to FullPerson

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/UpdateSentenceTypeAndSituationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MigrationJobScaffoldingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UpdateAllUsersFromCommunityApiMigrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UpdateSentenceTypeAndSituationJobTest.kt
This adds a new data migration job to backfill the sentence type and situation. To keep things contained I’ve created a new repository and put the helper classes in the job itself.
As we’re only fetching a small subset of data, we _should_ be able to get away without having to paginate through the results, but the proof of the pudding will be in the eating when we run it in preprod!
=> (APS 72) Add a job to update the sentence type/situation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/probationoffendersearchapi/ContactDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/probationoffendersearchapi/IDs.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/probationoffendersearchapi/OffenderAlias.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/probationoffendersearchapi/ProbationOffenderDetail.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationOffenderDetailFactory.kt
Searches by NOMIS ID are failing in preprod, because the ContactDetails type on the ProbationOffenderSearch's OffenderDetail is expecting a list of strings when it should be a PhoneNumber type.
This change should fix this error in Sentry:
https://ministryofjustice.sentry.io/issues/4684242081/events/oldest/?project=4503931792392192&referrer=oldest-event
https://mojdt.slack.com/archives/CR5ESQ8T1/p1701357376640669?thread_ts=1701357217.778399&cid=CR5ESQ8T1
=> Fix for CAS2's search by NOMIS ID feature 

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ArrivalEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventBuilderTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingSummaryTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
Refer [1635](https://trello.com/c/D6yRwBAV/1635-users-can-change-a-bookings-arrival-date) for more information.
This PR contains changes to allow arrival date changes for CAS3 premises booking only. We leverage on existing API `/premises/{premisesId}/bookings/{bookingId}/arrivals` to achieve updating the arrival date for CAS3 booking.
So we changed the booking entity to refer list of arrivals instead of single arrival entity and the latest arrival record can be retrieved as well. The CAS1,CAS2 booking will have only 1 arrival entity, but CAS3 will have multiple arrival entity
Note: Existing CAS1,CAS2 booking continue to follow existing process of creating single arrival only.
ready to be released at any point. …
=> [1635]- CAS3 booking arrival date change

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderDetailsDataSource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/CommunityApiOffenderDetailsDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/ConfiguredOffenderDetailsDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/OffenderServiceTest.kt, src/test/resources/application-test.yml
> See [APS-67 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-67).
This PR introduces a facade for retrieving offender details, allowing us to abstract to some degree over the source of this information, simplifying the planned transition away from the Community API in favour of the AP Delius Context API.
This facade is implemented such that it can be configured through the Spring property `data-sources.offender-details` or the environment variable `DATA-SOURCES_OFFENDER-DETAILS`, which accepts values of either `community_api` or `ap_delius_context_api`. This allows for control over when and in what environments the transition to the AP Delius Context API occurs, and allows us to rollback the transition without reverting significant code changes should …
=> [APS-67] Introduce facade for offender details

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/BookingSummaryForAvailability.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingSummaryForAvailabilityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
When checking out [some of the endpoints that had N+1 queries via Application Insights](https://portal.azure.com/#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-prod-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA1WOSw7CMAxE95zCYlOKVAEH6Io9Cy5QhWYEkZraJE6hiMOTgvjtrHnzRrYQ9BZ96xBnd7qcEEBtx8k2e%252B6wMx5U11QYkcADbCUB3kXEyogr6KPoKM%252FiXDjqMSCeu3mGuGqeJ2U1XWNTMOq4r9%252FH0in8llOvuRqT9ya4G8gMx293kfPFv1%252BupuzjliUdRmLBizbTz3lPWWizntDvHlnE9gGhmpMD9QAAAA%253D%253D/timespan/P1D) I noticed that the `premisesPremisesIdSummaryGet` endpoint was making a lot of queries …
=> Fix N+1 queries when fetching premises availability

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserAllocationsEngine.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserAllocationsEngineTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
When returning the eligible users for a Task, we’ve had issues where ineligible users are being returned. Tracking this down, it seems to be a problem where the `hasQualificationsAndRoles` specification is returning users that have any qualification in the provided list of required  qualifications, not all of the roles.
This is a situation we’ve already covered when automatically allocating users to a task, so I’ve updated the UserAllocationsEngine (which handles automatic allocations) to accept an `excludeAutoAllocations` flag. This allows us to return all qualfied users in our pool of potential users (currentlt the AllocationsEngine excludes users who have roles that prevent them from being automatically allocated a task)
I’ve also made some tweaks to the Tasks tests to make sure the …
=> (Fix) Use allocations engine to fetch users for a Task

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RegistrationClientResponseFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
Refer [1726](https://trello.com/c/mSSzt3eH/1726-guard-against-risk-registrations-that-dont-have-risk-categories) for more information.
This PR is to return `RiskStatus.Error` when missing mandatory element `registration.registerCategory`, `registration.registerLevel` from MAPP Risk details from Delius endpoint `/secure/offenders/crn/$crn/registrations?activeOnly=true`
confirm:
advance?
[Find the …
=> [bugFix-1720]-Return error when mandatory mappa registration details missing in Risk details from Delius

src/main/resources/db/migration/dev+test/R__5_create_bookings_for_cas3_kss.sql
This PR is to change the CAS3 e2e test booking to use Non-LAO CRN to make the booking pagination to work in E2E.
=> Change cas3 e2e test booking to use non-lao crn

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
We are seeing a `DataBufferLimitException` thrown when searching for the NOMIS ID that we use in our e2es on the dev environment, we think because the domain events in cas1/3 have a created a long list of addresses for this person on the nDelius API. [1]
This commit configures the memory limit for the relevant client, as we've done elsewhere [2] to see if that unblocks us while we wait for a more long term solution.
[1]https://mojdt.slack.com/archives/C03K0HB0LBE/p1702296717838819?thread_ts=1702291579.139989&cid=C03K0HB0LBE 
[2] https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1120
=> Increase memory limit responses for probation offender search

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderRisksDataSource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/CommunityApiOffenderRisksDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/ConfiguredOffenderRisksDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt, src/test/resources/application-test.yml
> See [APS-67 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-67).
This PR introduces a facade for retrieving offender risks, allowing us to abstract to some degree over the source of this information, simplifying the planned transition away from the Community API in favour of the AP Delius Context API.
This facade is implemented such that it can be configured through the Spring property `data-sources.offender-risks` or the environment variable `DATA-SOURCES_OFFENDER-RISKS`, which accepts values of either `community_api` or `ap_delius_context_api`. This allows for control over when and in what environments the transition to the AP Delius Context API occurs, and allows us to rollback the transition without reverting significant code changes should problems …
=> [APS-67] Introduce facade for offender risks

helm_deploy/values-dev.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/SeedConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/resources/db/migration/dev+test/R__6_clear_cas2_applications.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas2AutoScriptTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/SeedServiceTest.kt
This is a reprise of https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1207 which was reverted due to a problem loading fixture files from the "resources" bundle.
In this version of the PR the loading of files is:
- done using a "resource loader"
- wrapped in a "try" block to avoid causing a error which blocks deployment
See https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/bde98f81a698c61a979a498f4831f569759bf5d1/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt#L133-L144
=> 593 pt 2 CAS2 "auto-script" seeding for dev test

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
We’re having some pretty major performance issues on the bookings/search endpoint. CAS1 have had similar issues before and it’s been because JPA can’t work out how to do a COUNT query so ends up loading all the records into memory before doing pagination. Hopefully adding a countQuery will help here
=> Add `countQuery` to Bookings Search

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
Reverts ministryofjustice/hmpps-approved-premises-api#1232
This shouldn't be causing a problem but we've reverted the booking pagination and we still have an issue.
We need to work on this query now and there's a tiny chance that this change might be causing a problem so we'd like to eliminate it from our investigation.
We should consider re-adding this back in as additional safety once we're done or in the following work.
=> Revert "Add `countQuery` to Bookings Search"

helm_deploy/values-dev.yaml
We believe the CAS3 E2E tests are now creating so many domain events the dev user has a huge and problematic amount of NDelius data - 935.
[Slack thread here of where we found this.](https://mojdt.slack.com/archives/C03K0HB0LBE/p1702291579139989)
The long term fix is to change our e2e tests so that we create a new offender each time as CAS1 do[1]. Until we can do that, we should disable these events in dev (they are still on in preprod) and accept the lower parity.
We should re-enable these as soon as possible to make the environments behave in a similar way.
[1] https://github.com/ministryofjustice/hmpps-probation-integration-e2e-tests/blob/main/tests/approved-premises-and-delius/submit-application.spec.ts
=> Disable CAS3 domain events in dev where they create ndelius addresses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/resources/db/migration/all/20231212162909__add_incidies_for_booking_search.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
- Exists should stop counting when it matches the condition. Using ‘Select 1’ instead of ‘count 1’ should return the first record in a simpler way
- Add a database index for each subquery, it didn't seem like we had these indexes:
This isn't going to get us out of the N+5 problem we have but it might buy us some time.
=> Booking search query optimisations

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ExternalUserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CapacityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/RoomTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/ConfiguredOffenderRisksDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
Before this commit, the bed count shown when listing premises did not match the number of beds configured in the system. This was because the count was being populated from premises.total_beds, which was not neccessarily being kept in sync with the number of beds registered in the system (e.g. when a new bed was added via the API, the count was not being modified).
This commit removes all code relying on the premises.total_bed column and instead always calculates the bed count on-the-fly.
When performing find operations in the PremisesRepository, a sub-query is used to determine the bed count. Whilst this does not create a particularly performant execution plan (a subplan us executed for each row), this was deemed acceptable given that the size of the premises table is small, and if …
=> aps-48 stop using static total_beds column and calculate on-the-fly

src/main/resources/db/migration/local+dev+test/R__1_create_dev_users.sql
We've asked for the user CAS-LOAD-TESTER to be created for us. The intention of this user is that any CAS service can use it with Gatling to do load testing on our dev environment.
Roles should continue to be tested in the rest of the test suite with the existing users that are currently provisioned. This new user will be the only one that's role agnostic so they can more efficiently exercise all endpoints.
We do a refactoring of the user and role seeding so we have a single definition of all roles. We continue to use JIMSNOWLDAP for this.
We then do a bit more work in these dev migrations to go and select them and copy them across. For dev this feels like a reasonable compromise so we can more clearly see who has which role and create new users quickly.
Two examples of roles after this …
=> Seed all roles for a new load test user

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2ApplicationsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmittedApplicationTransformer.kt, src/main/resources/db/migration/all/20231213095259__add_person_to_cas_2_application.sql, src/main/resources/static/_shared.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmittedApplicationTransformerTest.kt
Currently, we store the CRN of a person on an application, and then use that CRN to make an API call to retrieve the rest of the person's data whenever we return an application or application summary.
Instead, we would like to store a "snapshot" of the information about the Person on an CAS2 application, at the moment when the application is created.
We would like to save these fields on an Application Entity, which will be used to build the `person` field on an `Application` that is returned to the frontend. 
```      
nomsNumber
pncNumber 
name 
dateOfBirth 
nationality 
sex 
prisonName 
personStatus 
isRestricted 
```
To do this we need to:
1. Change the `Cas2ApplicationEntity` 
We plan to change the underlying entity to hold these new fields. 
1. Run a migration to add these new …
=> Save a Person on a CAS2 Application

helm_deploy/values-test.yaml
This was prevously added to the other environments, but not test https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1167/files
And I think it's causing this exception https://sentry.io/organizations/ministryofjustice/issues/4673356945/?environment=test&project=4503931792392192&query=&referrer=project-issue-stream
=> Add Manage Users API url to test environment

src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/steps/Bookings.kt
Depending on the user being used, they will have access to different CRNs in different environments.
Jimsnowldap can see X320741 locally.
However we want to use a dedicated load test on a real environment. This means our user won’t have access to both crn so we need to make this configurable to avoid 403s during the booking create process.
We've provisioned this variable before, over here https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1250
=> Creating CAS3 bookings within load tests no longer 403s

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
We need to show the PNC number of a person on an application. This adds it to the Person Transformer method that is used in the Application Transformer `transformJpaToApi` so that when we get an Application this will be returned.
=> add pncNumber to Person returned on application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
We need to display the user's email address and name on Applications, so we are now returning the full user rather than just the id.
=> Return full User on CAS2 Application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApplicationReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
This returns a list of all unique applications made. If an application has an associated booking (i.e. it’s been made through the standard Apply - Assess - Placement flow), then we include information about the associated booking too. This is in addition to the main Applications report, which we’re keeping around for now as it contains more information. Once the Placement Requests report is done, we’ll remove the old-style Applications report.
=> (APS-66) Add new referrals report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/JwtAuthHelper.kt
We have the need on CAS2 for an admin account who can view any submitted application This is likely to be an internal user, so I am assuming they will be using a NOMIS account to login.
=> Allow a CAS2 Admin to view submitted applications

src/main/resources/db/migration/all/20231215134241__backfill_placement_date_to_request_fk.sql
The placement_application_dates.placement_request_id backfill script should of excluded placement_requests that have been realloacted. Otherwise it can fail (and has) as the subquery matches on more than one row
=> Fix placement_application_dates backfill migration

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
When viewing placement applications for an application, we should only show ones that haven’t been reallocated. I’ve updated the query, as well as updated the test to confirm that reallocated placement applications don’t show.
=> Don’t show reallocated placement applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/Cas2ExampleMetricsRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ReportsService.kt, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
In this PR we expose a CAS2 endpoint for downloading a spreadsheet "report" containing metrics.
Our initial endpoint is a example report to demonstrate the user-journey and verify that the correct authorisation controls are in place:
`cas2/reports/example-report`
This download is only available to users with the `CAS2_MI` role.
See related PRs:
- AP Tools [PR 55](https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/55) - adds a Nomis user with the `CAS_MI` role to the local development environment
- CAS2 UI [PR 376](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/376) - adds user-interface to GET the example report
=> CAS2 Reports: MI User downloads an example report

helm_deploy/values-test.yaml
This commit fixes the names of the env vars in test, matching the changes made on 317760c25d72008b9a300f31dca47a5cc4553858 for other envs
=> Fix test env var for async save enabled

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventWorker.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventWorkerTest.kt
Making `domainTopic` `final` means we try to fetch the domainTopic on boot. If it doesn't exist (as in our test environment), the application crashes.
=> Don’t specify Worker type in constructor

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/resources/application.yml
The CAS2 domain event OpenApi spec was not being served up via the SwaggerUI interface.
=> Serve CAS2 domain event spec via Swagger UI

src/main/resources/application-local.yml, src/main/resources/db/seed/local+dev+test/cas2_application_data/data_A1234AI.json, src/main/resources/db/seed/local+dev+test/cas2_application_data/document_A1234AI.json
This PR:
- updates the application `data` and `document` fixtures to reflect the current questions and answers used
- enables the "auto-script" seeding in the local development env (I'm not sure why this was not enabled before!)
=> Update CAS2 'Auto-script' seeding fixtures

build.gradle.kts
By default the gradle gatling plugin will automatically chose with version of gatling to use. Gatling >= 3.10 is incompatible with the version of Jackson used by Spring Webflux. This causes a ClassNotFoundException when running load tests.
The workaround applied on this commit is to pin the version of gatling used by the plugin to a version < 3.10.
We can consider unpinning the version once we have upgraded to a later version of webflux (and even, this is assuming at some point spring boot 3 will use jackson >= 2.16.0, see notes below)
Specific details on the incompatibility:
* Gatling >= 3.10 uses jackson 2.16.0
* Earlier versions of Gatling use jackson 2.15.0
* It appears that Gatling is using jackson 2.16.0 in such a way that will fail if 2.15.0 is used at runtime
* We currently use …
=> pin gatling to a specific version

doc/how-to/run_performance_tests.md, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/ApplyJourneyStressSimulation.kt, src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/BookingsTimeSimulation.kt
Added an additional journey into the BookingsReportGenerationTimeSimulation to measure performance of the booking search API
=> Add performance test for booking search API

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
`TaskWrapper` now returns a `UserWithWorkload` array, but the spec wasn’t updated. For some reason we weren’t getting compilation errors!
=> (Fix) Update tasks endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/TypedTask.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This adds sorting and native SQL pagination to the `/tasks/reallocatable` endpoint. This is a bit tricky as we have to fetch three different entity types. Before we've been a bit manual with our approach, but this makes pagination and sorting tricky because we have to load all the entities into memory to do the sort. This will only get harder once the service gets opened to more regions, and the Tasks page is already incredibly slow.
I've got around this by having a `UNION` query that fetches the bare minimum of fields from all the taskable tables, then fetching the entities by their ID in three separate queries. We then have to re-sort the fields after fetching to ensure the sort order is preserved.
=> (APS 153) Add sorting to the reallocatable tasks endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesSummaryTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PremisesSummaryTransformerTest.kt
When we start rolling out to multiple regions, we’re going to want to group/filter by region, so this will make it easier.
=> (APS-175) Return region name with premises summaries

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
When looking at not matched placement requests, it's showing withdrawn placement requests too, which is not what we want at all. When `notMatched` is provided we need to filter out placement requests that are withdrawn.
=> Hide withdrawn placement requests for `notMatched`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
This is to be consistent with other CAS1 endpoints. `SortOrder` is also used in the `/bookings/search` endpoint, which is used by CAS3, but I’ve kept this in so we don’t have to make UI changes to CAS3
=> Replace `sortBy` and `sortField` in /assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/UserWorkload.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
Now we're surfacing workload data, it occurred to me that we're only surfacing assessments, not the other types of task. This PR refactors the workload fetching service method to fetch all workloads in one query and fetches all other task types, summing them at the end.
=> (Chore) Get all task counts

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/InmateStatusOnSubmissionMigrationJob.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MigrateInmateStatusOnSubmissionTest.kt
Previously the migration job assumed that all applications had a NOMs number set, which is not neccessarily the case. For these applications the backfill logic has been changed to always set the status on submission to IN
=> Inmate Status on Submission Migration Job Fix

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
Before, changed bookings were being translated to `approvedPremisesBookingCancelled`. This isn’t what we wanted, so this PR changes the transformer to return the correct type. To improve the coverage, I’ve also added a test to test the transformations from domain event to timeline event are correct.
=> (APS-174) Fix timeline transformer

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderDetailsDataSource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/OffenderDetailSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/OffenderDetailsUtils.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/ApDeliusContextApiOffenderDetailsDataSourceTest.kt
> See [APS-67 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-67).
This PR provides the ability to use the AP Delius Context API as a data source for offender details. This is achieved by implementing the `ApDeliusContextApiOffenderDetailsDataSource` class.
The `ApDeliusContextApiOffenderDetailsDataSource` class performs transformations of the data in order to match the same data structure used by the Community API for backwards compatibility. These are enabled by various utility methods in the `OffenderDetailsUtils.kt` and `BaseHMPPSClient.kt` files.
This PR does not change the data source for offender details as this is down to the individual configuration for each environment.
=> [APS-67] Implement AP Delius Context API offender details data source

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/resources/static/domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApplicationAssessedFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DailyMetricsReportTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/DailyMetricsReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventWorkerTest.kt
I missed that when reviewing. As this is information about the event itself, it should sit in the `eventDetails` object.
=> Move `arrivalDate` to `eventDetails` part of `ApplicationAssessedEnvelope`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Ocassionally roles are duplicated when listing users - here we unique by the role’s name when listing. There’s an open question about whether this can be avoided (partially addressed by https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1296) but this solves the initial issue.
=> Depduplicate roles when listing users

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
When showing users, we're allowing inactive users to be allocated, which is causing issues. This updates the endpoint so we ignore inactive users.
=> Filter out inactive users when showing a task

script/test_database, script/utils/launch-docker.sh, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
As part of the work to update the assessment endpoint to use ‘in database’ paging, we need to move the logic that filters on status into the database queries.
As a pre-requisite to this work this commit ensures there is an integration test for each possible CAS1/CAS3 status, and tests to ensure multiple statuses can be used for filtering
This commit also adds a script to ensure docker is running locally before starting starting the test database
=> Adding tests for all possible assessment statuses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
This logic will be going away soon, but dev and preprod are broken at the mo, so let’s get this in
=> Don’t attempt pagination on an empty resultset

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderRisksDataSource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/InmateStatusOnSubmissionMigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/StaffMemberService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt
We’ve been having an issue when a user hits the `userAccess` endpoint, but gets an error. `canAccessOffender` should be catching when the endpoint returns a 403, but the conditional is not working as expected.
After some research, I’ve discovered that `HttpStatus` is an enum, so `==` is using reference equality, not value equality. However, using `equals` uses the value, so will match predictably [1]
[1]: https://stackoverflow.com/questions/45975550/using-equal-sign-for-httpstatus-bad-request-not-working
=> (Fix) Use `equals` to match `HttpStatus`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
In #1324 we introduced `equals` when matching `HttpStatus`. However, we missed this in the `OffenderService` class, which is the one we're currently experiencing bugs. I had changed this to match on the value, which should work, but we're still experiencing problems. I've not got much confidence this will fix the issue, but this will at least give us consistency.
=> Use `equals` to match `HttpStatus` in OffenderService

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/TimeExtensions.kt
Before this change @SqlResultSetMapping was used to map results from several native queries in the AssessmentRepository into instances of DomainAssessmentSummary, via a @NamedNativeQuery definition
Whilst use of ResultSetMapping helps overcome issues mapping some SQL types into their equivalent kotlin-native types (1), the convention in all other repositories is to use Spring Data’s interface-based projection and work around the aforementioned mapping issues by mapping UUIDs to text in the SQL, or mapping timestamptz to Timestamp instead of OffsetDateTime.
Furthermore, Spring Data’s automated paging functionality does not fully work when using @NamedNativeQuery. On startup you see warning logs as follows:
“Finder [insert method name] is backed by a NamedQuery but contains a Pageable …
=> Remove ResultSetMapping for Assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2UnsubmittedApplicationsReport.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2/UnsubmittedApplicationsReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ReportsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
This PR follows on from https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1315 which should be merged first.
The new `unsubmitted-applications` report included here comprises the following fields:
```
applicationId: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
personCrn: "X320741"
personNoms: "A1234AI"
startedAt: "2024-01-09T09:17:55"
startedBy "POM_USER"
```
This category of application (unsubmitted) will include:
- abandoned applications where the POM or person has decided
not to proceed
- abandoned applications where a different application for
this person has been submitted
- recently created in-progress applications which have not
yet been submitted
The analysts using this data can perform further analysis,
linking with data from the "Submitted applications" report
as …
=> (766) Stream CAS2 'unsubmitted-applications' report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRiskToSelfTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRoshTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonOASysRiskToSelfTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonOASysRoshTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonRisksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/JwtAuthHelper.kt
Previously on CAS2 we were granting access to all users with ROLE_PRISON, a role
granted automatically to all nomis authorised users. This is too broad a
restriction, because it means any users logging in via nomis will be
able to search for prisoners and make applications.
As our referrer users for private beta will be POMs, we should restrict
to the POM role for now. This can be assigned to devs to test in
different environments. 
There is some question around whether our users 
in production will definitely have this role, but we've been told that this should
be the role applied to all POMs. We can mitigate this risk by testing with a trusted
user shortly before going live.
Contract managers will be given the role CAS2_ADMIN so they can see
submitted applications, but they shouldn't …
=> Restrict CAS2 referrer users to ROLE_POM

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationStatusUpdatesReport.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2SubmittedApplicationReport.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2UnsubmittedApplicationsReport.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
This PR should be merged after:
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1315
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1322
To avoid any potential performance (slow query or memory) issues in the future, we limit the size of these reports to the most recent 12 months.
These reports do not, in any case, do anything complex or expensive.
=> (775) CAS2: Limit MI reports to last 12 months

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/TimeExtensions.kt
There is a need to be able to remove the ‘nano-specific’ part of milliseconds in tests because this nano precision is lost when persisted to postgres, leading to dates not matching a copy of the same date retained in memory that still has nano-specific values.
The previous implementation of the method could lead to invalid nano values. This has been solved by instead using in-built TimeUnit conversion to deal with rounding.
=> Fix time conversion test instability

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
The ‘arrived-departed-domain-events-disabled’ configuration is used to determine if domain events should be emitted for arrival, non-arrivel and departure booking events.
Even if we don’t want to emit domain events to SNS, it’s still useful to persist them to the domain_events table as this information can be used for reporting purposes.
This change ensures that when arrived-departed-domain-events-disabled’ is true, we still persist the events
=> Persist booking domain events when emit disabled

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt
This allows `/premises/summary` to filter by a probation region
=> (APS-82) Optionally filter premises by probation region

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/StatusUpdateService.kt, src/main/resources/db/migration/dev+test/R__7_clear_cas2_domain_events.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas2AutoScriptTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/DomainEventServiceTest.kt
This PR extends the existing "auto-script" seeding of CAS2 applications to include CAS2 domain events:
- `application.submitted`
- `application.status-updated`
This will make it easier to test management information reporting which relies on these domain events.
=> Seed CAS2 domain events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas2AutoScriptTest.kt
These properties are set on submission of the application in
`ApplicationService.submitApplication()`:
"promoted" up out of the application.data JSON blob:
- `preferredAreas`
- `hdcEligibilityDate`
- `conditionalReleaseDate`
and also `referringPrisonCode` which is looked up from the
Prison API.
Another property (`telephoneNumber`) will be added soon.
These first-class properties are used in the 'metadata'
which is shown in the "application summary" which
accompanies a submitted application. They are also included
in the submitted.application domain event and through this,
the "Submitted applications" management information report.
=> 778 CAS2: improve seeding to include first class fields on submitted applications

src/main/resources/db/migration/all/20240117101007__add_missing_indexes.sql
These were not created before, so is slowing the application down.
=> Add missing foreign keys and indexes

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderRisksDataSource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseDetailFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/ApDeliusContextApiOffenderRisksDataSourceTest.kt
> See [APS-67 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-67).
This PR provides the ability to use the AP Delius Context API as a data source for offender risks. This is achieved by implementing the `ApDeliusContextApiOffenderRisksDataSource` class.
This PR does not change the data source for offender risks as this is down to the individual configuration for each environment.
**NB**: The behaviour for retrieving the MAPPA details has changed - the current behaviour in the Community API implementation is derived from be95ffa, which ensures a registration exists that corresponds to the MAPPA details and returns an error if not. However, the structure of registrations from the AP Delius Context API is different, and does not include the necessary information …
=> [APS-67] Implement AP Delius Context API offender risks data source

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
We don’t believe these are being consumed yet and that this work is in progress after specs have been exchanged[1].
We leave the test environment as having these domain events off as I think the dev and test environments probably send events to the same queue and may cause odd behaviour (such as duplicate contacts) in downstream systems like nDelius?
[1] https://mojdt.slack.com/archives/C05GEPLBRN3/p1705400557152239
=> Emit CAS2 domain events in prod

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/StatusUpdateService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/DomainEventTestRepository.kt, src/test/resources/application-test.yml
The CAS2 `StatusUpdateService` was using the `url-templates.frontend.application` (Approved Premises/CAS1) setting rather than CAS2's `url-templates.frontend.cas2.application`.
In this PR we:
- set the test config to a clear literal value (`http://cas2.frontend/applications/#id`)
- extend our integration tests to verify that the expected value has been used in the creation of both `application.submitted` and `application.status-updated` events
=> Fix frontend CAS2 `applicationUrl` in application.status-updated domain event

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/convert/UrlTemplateConverter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEventSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineNoteTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentClarificationNoteTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UrlTemplate.kt, src/main/resources/application.yml, src/main/resources/db/migration/all/20240117111637__add_assessment_id_to_domain_event.sql, src/main/resources/db/migration/all/20240117142156__backfill_domain_event_assessment_id.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt, src/test/resources/application-test.yml
To support this change we need to add an assessment_id column to domain_events, and backfill it for existing entries
=> APS-193 add urls to timeline reponses

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmittedApplicationTransformer.kt, src/main/resources/db/migration/all/20240118100212__add_telephone_number_to_cas2_applications.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmittedApplicationTransformerTest.kt
We would like to save the referrer's telephone number as a "first class"
field when a CAS2 Application is submitted, and surface it when a submitted application is viewed. 
This will allow us to surface it on submitted applications to Assessors, without having to dig
into the document JSON blob.
=> Add telephone number as "first class" field to CAS2 Applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/OffenderDetailsUtils.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/CalendarServiceTest.kt
This is confusing to users, so we need to be consistent.
=> (APS-206) Remove middle names from tasks endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
We originally locked this down to only admins and workflow managers, but there is no need to do this, and users are getting kicked out. I’ve also changed the endpoint to return a 501 if the service is not CAS1, which seems more appropriate.
=> (Fix) Open timeline endpoint up to all roles

src/main/resources/db/migration/all/20240118152118__add_missing_application_indexes.sql
This adds some missing indexes that relate to an application, which should hopefully speed the application up. There's still a few more in other places, but these seem to cover a good chunk of the whole application.
=> Add missing application indexes

src/main/resources/db/migration/dev+test/R__7_clear_cas2_domain_events.sql
This "repeatable" migration was not running as expected on each deployment to dev and to test.
This is because it was missing the magic "timestamp" placeholder which is used to make migrations repeat.
See https://flywaydb.org/blog/flyway-timestampsandrepeatables
This came to our attention because the domain events table on 'dev' contained old `cas2.application.submitted` events which were missing certain attributes which are required by our CAS 'Submitted applications' MI report.
=> Fix: CAS2: add magic flyway timestamp to make migration 'repeatable'

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/resources/db/migration/all/20231211082335__add_indices_for_cas3_assessment_search.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
Refere [1722](https://trello.com/c/TTDY9BDm/1722-improve-performance-of-loading-referrals-during-the-receive-journey) for more information.
This PR to overcome performance problem in searching CAS3 assessment. 
**Current**:  the search is happening by selecting all assessment and then filter by assessment status.
**Change**:  This PR is to add the additional WHERE clause to an in existing query using 'status'(assement-status). Additionally merging existing 2 CAS3 assessment search query into single query.
Added indexes to applications(crn), temporary_accommodation_applications(probation_region_id) to improve assessment search query performance.
The status where clause is derived by following the existing logic as below
```
**Status**                                    **DB Query** …
```
=> [Feature/1722] - Change CAS3 assessment search by using status directly in DB query

.circleci/config.yml
Currently we’re seeing failed runs[2] with:
```
> hmpps-community-accommodation-tier-2-e2e@1.0.0 test
> npx playwright test --project=setupDev --project=dev
Running 4 tests using 1 worker
×
1) [setupDev] › auth.setup.ts:5:6 › authenticate ─────────────────────────────────────────────────
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1091/chrome-linux/chrome
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.40.0. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.39.0-focal               ║
║ - required: mcr.microsoft.com/playwright:v1.40.0-focal               ║
║ …
```
=> Fix CAS2 e2e by matching versions

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationTimelineNoteEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationTimelineNoteService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineNoteTransformer.kt, src/main/resources/db/migration/all/20240122082355__change_created_by_to_created_by_user_id.sql, src/main/resources/static/_shared.yml, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationTimelineNoteEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
This updates the timeline notes and timeline events to return an entire user object, rather than the user ID. There's also a couple of refactors/tweaks I discovered on the way.
=> Return entire user object when returning timeline notes

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesSummaryTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PremisesSummaryTransformerTest.kt
This adds AP areas to premises summaries, and allows them to be filtered by the area. We've realised that this is a more appropriate thing to filter / group by, but have kept the legacy behaviour in too for compatibility reasons.
=> (APS-214) Add AP Areas to premises summaries and allow filtering

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAProbationRegion.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApArea.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-196
Add optional AP Area ID filtering to /tasks and /tasks/{taskType}
/tasks/reallocatable will be updated in a subsequent PR
=> APS-196 add optional AP Area ID filtering to tasks endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This commits simplifies the reallocation code In preparation for adding filtering on AP Area ID.
The 3 ‘allocation queries’ for placement requests, placement applications and assessments have been flattened into a single query per entity type.
This commit has no functional change, just refactoring
=> Simplified Reallocated Task Logic

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20240123091639__change_application_probation_id_to_ap_area_id.sql, src/main/resources/db/migration/all/20240123104559__migrate_application_probation_ids_to_ap_area_ids.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This updates the `ApprovedPremisesApplicationEntity` to take an `apArea`, rather than a `probationRegion`. This has resulted in some changes to the queries when filtering tasks, as well as changes to the submission endpoint.
I've kept the legacy `probation_region_id` in the database for now (there's a migration to backfill any applications that already have probation regions), but once all applications have AP Areas by way of a backfill, we can remove this column.
=> (APS-214) Change Probation Region ID to AP Area ID

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
This supersedes Gareth's PR here -> https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1353 as we're now using AP Area ID instead of Probation Region ID, and it was easier to cherry pick changes into a new branch
=> /placement-requests/dashboard now allows filtering on ap area id

src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml
This is required to set the correct referral type values in Delius. Once this is in, we can update the frontend to allow the relevant types to be set.
=> (APS-165) Add new licence release type options

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/ApAreaMigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApAreaMigrationTest.kt
This adds a migration job to add an AP area to all Approved Premises applications. In most circumstances, these will be the AP Area of the submitting user, but there are a small subset of applications, where the user and area do not match up. After a review with Sararh, we’ve got a list of these handful of applications, and have the IDs of all the applications and associated AP Area.
Once these are run, we can then update the remaining applications with the AP area of the submitting user.
=> (APS-219) Add migration job to add AP Areas to applications

src/main/resources/db/migration/all/20240123121855__delete_cas_2_applications_used_for_production_test_run.sql
We had planned to use realistic referral data and leave these referrals in the service. In practice there were a couple of problems with this which mean we want to remove these:
1. Authorship was from the team
2. These referrals might not receive update from Nacro
3. The referral might be double counted somewhere downstream in reporting
We could delete this manually on the prod command line but want to get this more sensitive change in as code where it can be reviewed.
The application IDs are taken from prod:
Are there any associations I've missed?
[Testing recording in Slack](https://mojdt.slack.com/archives/C05GEPLBRN3/p1706026107319099?thread_ts=1706026069.051109&cid=C05GEPLBRN3).
=> Delete two production CAS2 applications used for testing

.circleci/config.yml
Previously this was an informational step to alert the person releasing that their might be an issue.
We are now in the position where CAS1&3 are in public beta and CAS2 is about to go into private beta. The risk of deploying a breaking API change has increased to a point where we should now make this a required step when deploying to preprod and prod.
Instead we now run the risk of flakey e2e tests from any of the projects from failing with false positives and blocking an API deploy.
=> API prod deploys require all frontend e2e to pass

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
Refer ticket [cas-182](https://dsdmoj.atlassian.net/browse/CAS-182) for more information
This PR is to change the CAS3 booking search query to use `status` column in `bookings` table instead of inferring the status from multiple table.
Note: The `status` column is populate for cas3 booking journey with different dates.
confirm:
advance?
[Find the build-and-deploy job in …
=> [CAS-182]-CAS3 booking search query to use 'status' column in the query

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntityReportRow.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/PlacementApplicationTestRepository.kt
https://dsdmoj.atlassian.net/browse/APS-222
Previously the placement application report query would filter on approved_premises_applications submitted on the given month/day. This is incorrect, it should of filtered on placement_applications submitted on the given month/day.
=> Placement Application Report Date Filter Fix

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2SubmittedApplicationReport.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
[Trello 781](https://trello.com/c/9XR5doJr/781-change-submittedon-to-submittedat-in-submitted-applications-mi-report)
In the CAS2 "Submitted applications" MI report we've decided that we need the timestamp of submission rather than just the date.
See https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/457 for the accompanying tweak to the report 'details' provided in the UI.
=> (781) CAS2: Present submittedAt as timestamp rather than date in 'Submitted applications' report

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml
This will allow us to confirm the new endpoints work as expected before retiring the Community API endpoints for getting offender details
=> Enable `ap_delius_context_api` in Dev and Preprod

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1WithdrawableDateRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/Cas1WithdrawableDateTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementDateEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/Cas1WithdrawableDateTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-245
The /application/{application-id}/withdrawable endpoint can be used to provide a list of entities that can be withdrawn. These will be one of the following three types:
* Placement Request
* Placement Application
* Booking
There are also circumstances under which the Application itself can be withdrawn which should be considered before calling this endpoint (in those cases the endpoint would logically return an empty list).
As part of this change the placement application logic has also been simplified to only allow a placement application to be withdrawn if no decision has been made against it (previously it would allow ‘accepted’ applications if the associated placement requests had no bookings). Accordingly, we’ve removed the logic …
=> Add Application Withdrawable Endpoint

helm_deploy/values-prod.yaml
These URLS are used to generate domain events and emails. This commit changes to use our correct production URL, which is changed from previous naming pattern.
=> correct CAS2 URL in production

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt
> See [APS-192 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-192).
This PR introduces a human-readable description for each domain event presented in the application timeline (`GET /applications/{applicationId}/timeline`).
This description is generated by the `DomainEventDescriber` class. Currently, this only supports CAS1 events.
=> [APS-192] Add descriptions to timeline for domain events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BookingsReportRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
Refer [CAS-191](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-191) for more information.
This PR is to fix a bug in CAS3-booking report where booking appears in the report more than once due to multiple updates in departure date, Hence getting the latest departure date should gives correct information in the report.
Same applies to arrival date as well. Both are fixed in this PR.
Need to monitor the performance of this report in pre-prod due to the change in the sql, but it should be minimum due to fact its for a specific booking and chance of multiple updates in departure/arrival are minimal.  …
=> [CAS-191]-Get latest departure,arrival for CAS3 booking report

detekt-baseline-main.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingCancelSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
Previously the logic to get a booking for a given premises was fully defined in the premises controller. Whilst some of this logic is specific to premises (e.g. checking if the booking belongs to the given premises), the majority of the logic is generic when retreiving booking.
Because we’re going to add an endpoint to retrieve a booking by its ID only (i.e. no premise ID) to support new withdrawal logic, the common ‘get booking’ logic needs moving into the BookingService
This commit also adds a small premises summary to the Booking API response. This allows the controller to validate that the premises id is as expected, and the premises name will be of use to the UI in subsequent changes
There are no functional changes on this PR, just refactoring
=> Move get booking logic from controller into booking service

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-262
Existing 'manage booking permissions' are retained for viewing and cancelling bookings, with applicant being added to the allowed list for cas1
=> CAS1 Allow applicant to view & withdraw booking

.circleci/config.yml
CAS2 have decided to move our e2e tests from a dedicated repo, into the same repo similarly to CAS3.
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/482
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/495
Once this work is complete we'll archive our old [e2e repo](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e).
=> CAS2 E2E tests are now run from the frontend repo

src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
These are no longer needed. We'll need to make sure the corresponding UI changes are deployed before / as soon as these changes are live, as this will be a breaking change
=> (APS-250) Remove withdrawal reasons

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
In some cases it's going to be useful to show an application's region when listing (for example) tasks.
=> Return region with `ApprovedPremisesApplication`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
All users will need to view an assessment (except when the offender is a limited access offender and they don’t have permissions to view), so we’ll open up permissions to all logged in users.
=> (APS-265) Loosen permissions when viewing assessments

doc/how-to/run_seed_job_remotely.md
This updates the docs to make copy/pasting commands easier, and also adds a link to the Azure log queries, as the seed logs are not available via Kubernetes.
=> Update seeding docs

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderDetailsDataSource.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/ApDeliusContextApiOffenderDetailsDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/CommunityApiOffenderDetailsDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/ConfiguredOffenderDetailsDataSourceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-263
The code previously implicitly assumed that the results from the delius offender details API were being returned in the same order as the list of the CRNs requested. We’ve changed the code to remove this assumption and link results by matching on CRNs.
This PR also fixes an inconsistency between delius API and community API behaviour in the event of error, ensuring a ClientResult.Failure is returned for each CRN requested.
=> Fix mapping bug when using delius offender api

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/TypedTask.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-223
This PR is in preparation for sharing the functionality with the /tasks endpoint, reducing duplication. At which point we can then add additional functionality required by APS-223. There is no functional change
The changes significantly reduce duplication when retreiving tasks for reallocation. Previously this request could be redirected to one of four different services (one for each specific type and one for all types). Now all requests go to a single service and a single SQL query.
This may be slightly less performant than the previous approach when requesting a specific task type. If we find there are performance problems it's an easy fix because all requests now go through a single function. In this case we'd add a specific …
=> Refactor GetReallocatedTasks Functions to reduce duplication and provide generic functionality

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/Withdrawables.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt
This adds a new `WithdrawablesService` that contains the source of truth for all things that are "withdrawable", we then can add a `withdrawAllForApplication` function that withdraws everything that is "withdrawable" for an application in one shot. I've had to add a new internal reason for placement application / requests that shows they were withdrawn as a side effect of the whole application being withdrawn.
=> (APS-267) Ensure all things related to an application are withdrawn when an application is withdrawn

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This PR makes several enhancements to the /tasks/reallocatable endpoint such that it can support requests sent to the /tasks endpoint. These are
1. Allow requests from users with the role CAS1_MATCHER
2. Add the option to filter on the allocated user
Subsequently, requests for /tasks endpoint is now forwarded to the reallocatable logic
The end goal is to have a single one-size-fits-all tasks endpoint
=> Use /tasks/reallocatable code to service /tasks requests

doc/how-to/verify_email_sending.md, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/EmailNotificationServiceTest.kt
This adds some more verbose error logging for Notify, so we can confirm email sending will work as expected in production.
=> More verbose error logging for notify

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
This is needed to filter by AP Area. Ordinarily, we’d extend the `ApprovedPremisesUser` here, but the code generator doesn’t like extensions of an already extended type.
=> (APS-282) Add APArea to `UserWithWorkload`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AppealEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AppealTransformer.kt, src/main/resources/db/migration/all/20240130114858__create_table_for_appeals.sql, src/main/resources/static/_shared.yml, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AppealEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AppealTransformerTest.kt
> See [APS-236 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-236).
This PR introduces appeals for when an application is rejected. An appeal can be created for an application using the `POST /applications/{applicationId}/appeals` endpoint. The body of a request to this endpoint looks like:
```json
{
"appealDate": "2024-01-01",
"appealDetail": "Some information about the appeal",
"reviewer": "A Name",
"decision": "accepted",
"decisionDetail": "Some information about the decision"
}
```
An appeal can only be created by a user if they have the `CAS1_APPEALS_MANAGER` role (see #1411) and can access the application.
This PR does not include an endpoint for viewing an appeal, as this is part of APS-238.
=> [APS-236] Introduce appeals for CAS1 applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-223
Before this PR, the /tasks endpoint would return tasks assigned to the calling user, with some additional limited filtering options. This version of the endpoint is not currently used by the UI and as such we can make breaking changes safely
ThisPR redefines the /tasks endpoint to return tasks for any user, with an optional ‘allocatedUserToId’ to replicate the previous /tasks endpoint behaviour. The end point also provides paging and various other filters.
This allows us to deprecate /tasks/reallocatable and /tasks/{taskType} as the same functionality is now provided by the generic /tasks endpoint
https://dsdmoj.atlassian.net/browse/APS-283 and https://dsdmoj.atlassian.net/browse/APS-284 have been created to subsequently remove usages …
=> Redefine /tasks endpoint to provide generic search 

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesAssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
If there is an ‘active’ assessment when an application is withdrawn, a notification will be sent to the person currently allocated to the assessment.
A temporary feature flag has been added to allow us to control when this feature goes live in production. A JIRA ticket https://dsdmoj.atlassian.net/browse/APS-285 has been created to track its removal.
=> Send notifications to assessor on app withdrawal

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/AppealTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt
> See [APS-238 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-238).
This PR introduces the `GET /applications/{applicationId}/appeals/{appealId}` endpoint to get information about a particular appeal. It extends the work in #1426 to introduce appeals.
=> [APS-238] Add endpoint to view an appeal on an application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
If a placement request has a booking associated with it, but that booking has been cancelled, as per existing behaviour, it will have a status of ‘not matched’. Therefore, a placement request with this state should also be withdrawable.
As part of this commit some logic defined in the PlacementRequestTransformer has been moved into a common entity function to reduce duplication
=> Fix placement request withdrawable logic bug

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
UI PR is here https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/498
This adds pagination to `/submissions`, which lists all submitted CAS2
applications.
We are using the existing utility functions and `Page` response already
in the API, and utilised by CAS1/3's `getAllApprovedPremisesApplications` method. 
* The sorting is hardcoded as ascending "submitted_at" because we do not yet have UI/need
to set the sort order from the frontend. 
* We're using the default page size for now, but may need to customise that in the near future.
* We have set the page`param` to be optional in order not to break the existing frontend - if
no page param is given, then all the results are returned, which means
we will not break the existing UX on the frontend.
=> Paginate CAS2 submissions end point

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
We'd like referrers to see status updates on an
application. These are only applied to
applications after they've been submitted.
This adds the `statusUpdates` via the ApplicationsTransformer.
=> Return Status Updates on CAS2 Submitted Applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-290
If an application is submitted, a workflow manager should be able to withdraw it. This commit updates the application withdrawal logic which will be automatically used when returning a list of withdrawables to the UI
=> Allow CAS1 Workflow Manager to withdraw apps

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/ValidatableActionResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt
This relates to the second bullet point on https://dsdmoj.atlassian.net/browse/APS-292
Most of the work on this PR is changing the placement request and booking withdrawal/cancellation endpoints to be idempotent to ensure that when withdrawals are cascaded (particularly via the Withdrawal service), we don't end up withdrawing the same entity multiple times (which would lead to multiple notifications)
=> Placement Requests withdrawals should cascade to Bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
Relates to bullet point 1 on https://dsdmoj.atlassian.net/browse/APS-292
A placement request with a booking can be withdrawn, and with prioir changes this will automatically cascade to bookings.
=> Placement requests with bookings can be withdrawn

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/notification/EmailNotificationAsserter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/EmailNotificationServiceTest.kt
The application withdrawal tests have been updated to demonstrate asserting that an email has been sent
=> Add ability to assert on emails in int-tests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationRegionEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt
Note - A majority of the change to stop applicants being able to remove bookings was already implemented via commit 0f15943e. But, additional changes were required for APS-294 specifically:
* Removing some permissions removal not captured by 0f15943e
* Removing some complexity in withdrawables service that is no longer required because withdrawals cascade from placement requests to bookings (i.e. an applicant withdrawing a placement request or 'parent' entity is sufficient for it to cascade down to a booking)
* Updating integration tests to ensure cascades happen from placement request to booking for applicants
=> Applicants shouldn't be able to withdraw bookings

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/StatusUpdateDetailEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/StatusUpdateEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2PersistedApplicationStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2PersistedApplicationStatusDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/StatusUpdateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationStatusTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/StatusUpdateTransformer.kt, src/main/resources/db/migration/all/20240206092803__add_cas2_status_update_detail_table.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/StatusUpdateServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationStatusTransformerTest.kt
* I'm not a Kotlin/SQL expert, would appreciate any feedback about better way of doing this.
* This is quite a big PR because we are in a rush to have work un-blocked for Frontend. 
* DOES NOT INCLUDE: 
* updating Domain Events or MI reports - this can come in near future.
* the Details for Further Information - this not confirmed yet
We [previously introduced ](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1113)a set of CAS2 specific Application Statuses, that are applied by Assessors.
We now need to introduce an optional sub-level of category on those statuses, which we are calling 'Status Details'.
A Status (e.g. 'Offer declined') could have none or several Details on it (e.g. 'Change of circumstances', 'No Reply/No Response'). 
This is proposing
1. Display the …
=> Add an optional list of `StatusDetails` to CAS2 Application `StatusUpdates` 

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
Relates to [APS-293](https://dsdmoj.atlassian.net/browse/APS-293)
I've made the changes specified in the associated ticket, and at the same time i've made the withdrawal logic work in the same way for all 4 entity types, making things more predictable and, hopefully, easier to change. Specifically:
- add a method to determine if entity is withdrawble for the user to all four entity services
- calling code is now responsible for checking if user has permissions to withdraw (this required for cascading where this check is to be skipped)
- withdrawing is always idempotent
- withdrawing will cascade down to child types and log errors if those cascading withdrawals unexpectedly fail
Because of the cascading, withdrawals are now effectively depth-first traversing a tree made up of applications, …
=> Placement Application Withdrawal Changes

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationNoteEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationNoteService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationNotesTransformer.kt, src/main/resources/db/migration/all/20240213111046__create_cas2_application_notes_table.sql, src/main/resources/static/_shared.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationNotesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationNoteServiceTest.kt
We would like CAS2 users to add notes to submitted applications. 
We are introducing this in parts - initially just enabling the ability for Nomis users to create notes on any applications they have submitted.
In this PR we have
* Introduced `cas2_application_notes` new table, with foreign keys to `cas2_applications` and `nomis_users`. 
* Introduced new endpoint `submissions/{applicationId}/notes` restricted to users with POM role
* Added Service layer logic that restricts Note creation to submitted apps, and only if user created application
This is following a similar pattern in CAS1, but as our users and application models are different we've continued to use our own namespace/new tables. 
We will introduce the functionality to return Notes on a SubmittedApplication shortly. 
We will …
=> Allow Nomis users to add a Note to CAS2 Applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt
These were previously not unique and causing
problems. There have been no Status
Details created by the frontend yet so I don't
think there's a problem changing these ID's now.
=> Add unique UUID's for seeded statusDetails

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
Refer [CAS-176](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-176) for more information
This PR is to change in the CAS3 booking's cancellation by adding additional steps to move the corresponding assessment to ready-to-place state. 
We already completed the change to move the assessment to closed state(Refer [CAS-50](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-50)) and this is reverse flow of moving from closed assessment to ready-to-place when booking is cancelled.
This change to achieved by calling existing service `AssessmentService.acceptAssessment()` and intentionally catching all the exception thrown from new service call to preserve the existing cancellation flow. 
The user has alternative option …
=> [CAS-176]-Move the CAS3 assessment to read-to-place state when the corresponding booking is cancelled

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ApprovedPremisesApplicationStatus.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
If an entity is withdrawn directly by a user (i.e. it's not a casacading withdrawal), we will update the application status in the following circumstances:
1. If a placement request is withdrawn and there are no other active placement requests, change the status to 'PENDING_PLACEMENT_REQUEST' (meaning a placement_application is required)
2. If a booking is withdrawn and there are no other active bookings, change the status to 'AWAITING_PLACEMENT'
=> Update application status on withdrawal

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DomainEventsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt, src/main/resources/application.yml, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/main/resources/static/domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/AssessmentAppealedFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt, src/test/resources/application-test.yml
> See [APS-239 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-239).
This PR introduces the `approved-premises.assessment.appealed` domain event type and amends the logic for creating appeals to include this event.
The new domain event looks like this:
```json
{
"id": "00000000-0000-0000-0000-000000000000",
"applicationId": "00000000-0000-0000-0000-000000000000",
"assessmentId": null,
"bookingId": null,
"crn": "X123456",
"occurredAt": "2024-02-07T12:34:56.789Z",
"data": {
"id": "00000000-0000-0000-0000-000000000000",
"timestamp": "2024-02-07T12:34:56.789Z",
"eventType": "approved-premises.assessment.appealed",
"eventDetails": {
"applicationId": "00000000-0000-0000-0000-000000000000",
"applicationUrl": …
```
=> [APS-239] Introduce domain event for created appeals

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/notification/EmailNotificationAsserter.kt, src/test/resources/application-test.yml
This relates to https://dsdmoj.atlassian.net/browse/APS-308
This is regression testing existing emails in code for withdrawal scenarios
=> Add IT regression tests for withdrawal emails

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-343
Previously the caller could get tasks of all types, of a specific type. The new ‘types’ param allow the caller to specify multiple types to be returned.
The existing ‘type’ param is deprecated in favour of the new more flexible ‘types’ param
=> Add option to filter on multiple types to /tasks

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/StatusUpdateEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2ApplicationsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/StatusUpdateService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmittedApplicationTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/TimelineEventsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2StatusUpdateEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/StatusUpdateTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmittedApplicationTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/TimelineEventsTransformerTest.kt
https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-213
In order to show several different types of events in a timeline component on the CAS2 UI, we are creating a standard shape for them on the presentation/transformation layer of the API. We currently need to show - notes, status updates,
and when the application was submitted.
([copy is slightly different to screenshot above](https://mojdt.slack.com/archives/C04T6SC31HA/p1707926701170309?thread_ts=1707926423.047549&cid=C04T6SC31HA))
We will follow an existing pattern set by CAS1 for an Application return a list of `TimelineEvents` components, but as our data has a different shape, and as we are already namespacing CAS2 work, we are creating a new `Cas2TimelineEvent` component.
We then introduce a …
=> CAS2 Timeline Events on an Application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
Refer [CAS-217](https://dsdmoj.atlassian.net/browse/CAS-217) for more information
The PR contains below 2 changes:
1. Revert the changes done as part of CAS-50, so that we are not closing referral after 'provisional-booking' is made.
2. Instead, close the CAS3 referral after booking is `confirmed`.
confirm:
advance?
[Find the build-and-deploy job in …
=> [Cas-217] - Close cas3 referral after booking is confirmed

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationRegionEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/EmailNotificationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-299
Note that ticket requests that this email is sent to applicants, AP and cru mailboxes. In the interest of keeping this PR manageable, this PR only addresses sending the email to applicants and AP
As part of this PR i've added some more regression testing for the existing booking emails in integration tests, and moved the CAS1 booking email logic into a standalone class. See commits for more information.
=> Add Booking Withdrawn Emails for Applicant and Premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt
> See [APS-289 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-289).
This PR updates the `AppealService.createAppeal` method to automatically create a new assessment for the application if the appeal was accepted.
The application will automatically be moved into the `"unallocatedAssessment"` status when this occurs due to the `@PrePersist` annotated method on the [`AssessmentListener` class](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/listeners/AssessmentListener.kt), so no explicit update of the status is needed within this PR, although the integration tests assert that this expected status change occurs.
=> [APS-289] Create a new assessment when an appeal is accepted

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationNoteEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2User.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ExternalUserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NomisUserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationNoteService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationNotesTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/TimelineEventsTransformer.kt, src/main/resources/db/migration/all/20240214170259__add_external_users_to_cas2_notes.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationNotesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationNoteServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationNoteTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/TimelineEventsTransformerTest.kt
https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-212 
We previously introduced Notes on an Application https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1470 that could be added a by a Nomis user (e.g. a Referrer/`POM`).
This PR allows users with the CAS2_ASSESSOR role to add notes to any submitted applications.
This is the first time we've come across an entity that could have either an ExternalUser or a NomisUser belonging to it - we discussed [introducing polymorphism in the previous PR, but tabled it at the time.](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1470#pullrequestreview-1875714328).
In this PR, rather than representing the polymorphism on the database level, I've [introduced a Sealed …
=> CAS2 Assessors can create Notes on an Application

doc/how-to/example_csvs/approved_premises_ap_area_email_addresses.csv, doc/how-to/run_seed_job_remotely.md, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApAreaEmailAddressSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt, src/main/resources/db/migration/all/20240216152435__add_email_address_to_ap_areas.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApAreaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedCas1ApAreaEmailAddressTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ApAreaTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/MockEmailNotificationService.kt
Second PR for https://dsdmoj.atlassian.net/browse/APS-299
The intial PR sends the email to applicants and AP - https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1503
This PR adds sending email to CRU by introducing an email_address column the ap_areas table. A seed job is also introduced to populate the CRU email addresses in prod/pre-prod
=> Send booking withdrawl notification to CRU inbox

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEventSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt
This adds an appeal URL to timeline events (when an appeal ID is present). This will allow the timeline view to link directly to an appeal when one has occurred.
=> (APS-368) Add an appeal URL to timeline events

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt
We want to link to appeals in the timeline, so all users should be able to see data for an appeal.
=> (Chore) Allow all users to see appeals data

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/TransitionalAccommodationReferralReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/TransitionalAccommodationReferralReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/TransitionalAccommodationReferralReportRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20240219141046__add_prisonname_to_cas3_application.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/TransitionalAccommodationReferralReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/ReportServiceTest.kt
Refer [CAS-208](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-208) for more information.
This PR contains below two changes:
1. Store `prison-name` at time of referral creation in CAS3 specific `temporary_accommadation_applications` table, the prison-name is retrieved from existing service `offenderService.getInfoForPerson()`. 
2. Populate the stored prison-name into existing cas3's `referral` report.
confirm:
advance?
Once we've merged we now need …
=> [CAS-208]- Store prison-name in CAS3 application table and show in referral report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/PlacementApplicationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApplicationReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/PlacementApplicationReportRow.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssertJExtensions.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-372
Use the ‘booking made’ domain event’s creation timestamp to determine when a booking was made
=> Add BookingMadeDate to App and PA Reports

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt, src/main/resources/db/migration/all/20240221091158__add_created_from_appeal_to_assessments.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesAssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
This adds a `createdFromAppeal` flag to Approved Premises assessments. If an appeal is accepted and a new assessment is created as a result, this flag is set to `true` in the database. This is then sent across in the API, so we can add the relevant flags on the frontend. It will also allow us to automatically allocate to CRU managers in a future PR.
=> (APS 370) Surface that an assessment is an appealed assessment so that staff are aware

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AppealEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AppealTransformer.kt, src/main/resources/db/migration/all/20240222105554__remove_reviewer_from_appeals.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/main/resources/static/domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AppealEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/AssessmentAppealedFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/AppealTestRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AppealTransformerTest.kt
This adds a `createdByUser` to the appeals response, rather than just the ID, allowing us to get more information about the user who created the appeal.
We also remove the `reviewer` field, as now the person who created the appeal is also considered to be the arbitrator of the appeal, so we no longer need this field.
=> (APS-383) Make appeal manager the arbitrator of an appeal

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Before this commit the API would ensure that when the user chooses ‘otherReason’ when withdrawing an application that free text was provided explaining why. This is no longer required in the new withdrawal solution as this reason isn’t available and currently it’s blocking withdrawal in production where the free text box has been removed on the UI, but not in the list of withdrawal reason.
=> Remove otherReason validation on CAS1 Withdrawal

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2SubmittedApplicationReport.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2/SubmittedApplicationReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ReportsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
References:
- https://dsdmoj.atlassian.net/browse/CAS2-193
- https://dsdmoj.atlassian.net/browse/CAS2-198
**User Story:**
As a Performance Analyst I want the created_at field adding to the list of fields extracted for the submitted applications report so that when I refresh a PowerBI dashboard with this information, the dashboard user can determine the time taken to complete an application.
**Further information:**
The time taken to complete an application is the difference between the application submitted_at timestamp and the application created_at timestamp.  This calculation is done in the dashboard itself so there is no requirement to calculate it during the report extraction.
The created_at field is included in the unsubmitted applications report but is renamed to startedAt, …
=> Cas2 193 add started at to submitted applications report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AppealEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AppealEmailServiceTest.kt
This sends notification emails to both the applicant and the appeal arbitrator if an appeal is upheld
=> (APS-384) Send notification email on successful appeal

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-388
When returning a list of withdrawable elements, the only time a Match Request should be returned is when it represents the start date/duration specified on the original application (i.e. the one that is automatically created when the application is assessed).
This provides a method for the applicant to withdraw a request for a booking on the original dates without withdrawing the whole application.
Previously we would also return the match requests created for Reuqests for Placements created after the application had been submitted. This is not required because the user can withdraw the Request for Placements themselves which will cascade down the corresponding Match Requests.
As part of this commit general improvements have been made …
=> The only withdrawable match request is the one created from the original application date

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/TransitionalAccommodationReferralReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/TransitionalAccommodationReferralReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/TransitionalAccommodationReferralReportRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20240222161046__add_releasedate_to_cas3_application.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/TransitionalAccommodationReferralReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/ReportServiceTest.kt
Refer [CAS-209](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-209) for more information.
This PR contains below two changes:
1. Capture and store `release_date` as first class field in CAS3 application.
2. Populate the stored `release_date` into CAS3's referral report
confirm:
advance?
[Find the build-and-deploy job in …
=> [CAS-209] - CAS3 - Store release_date as first class field and populate referral report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-395
The /applications/{id}/placement-applications endpoint has been enhanced to add an optional query param ‘includeInitialRequestForPlacement’, which is null/false by default. If set to true, an additional PlacementApplication of type ‘initial’ will be returned representing the request for placement implicit in the application submission (i.e. the one based upon the original applications’ arrival date).
This is actually modelled as a PlacementRequest in the database, so certain elements of this specific PlacementApplication should be used with care, specifically the ‘id’ field, which actually corresponds to a PlacementRequest ID. For more information on this approach, see the documentation on …
=> Optionally include 'initial' request for placement when returning placement applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
Refer [CAS-166](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-166) for more information.
There is an issue with the search showing results when the bedspace is not available, but this is not about the turnaround time.
A bedspace is booked from 21/2 to 26/2 with turnaround ending on 28/2.
It is showing an overlap on the 26/2 - but this property only has 1 bedspace so this bedspace should NOT be shown.
Note that the property does NOT come in the search for any of the dates in the range 21/2 until 28/2 except the 26/2 - which is the end date of the booking - so there is some bug with the way that the end date is being used in the search.
`Fix': Include the departureDate when querying to find existing booking which are closest to new search start …
=> [CAS-166]-CAS3-Bedspace search to include booking departure date 

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
When /applications/{id}/placement-applications returns a list of placement requests it includes a representation of the original request made when the application was assessed, by using the corresponding match request as a proxy. This should be returned even if the corresponding match request has been withdrawn, allowing users to see it in its withdrawn state
=> Return initial placement request even if withdrawn

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/allocations/rules/AppealedAssessmentRule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AppealEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/PlacementApplicationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApplicationReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/PlacementApplicationReportRow.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/allocations/rules/AppealedAssessmentRuleTest.kt
> See [APS-241 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-241).
This PR introduces several new columns regarding appeals to the application and placement application reports.
The new columns are as follows:
| Column name | Type | Description |
| --- | --- | --- |
| `assessmentAppealCount` | `int` | This will show the amount of appeals that have been made against this application and assessment |
| `lastAssessmentAppealedDecision` | `String` | This will show the appeal decision of the latest appeal record (Upheld or Rejected) |
| `lastAssessmentAppealedDate` | `Date` | This will show the date of the last appeal |
| `assessmentAppealedFromStatus` | `String` | This will store and show the original assessment decision so that it’s possible to see why things …
=> Add appeal data to application and placement reports

helm_deploy/values-preprod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUsageReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/ReportService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUsageReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/ReportServiceTest.kt
Refer [CAS-195](https://dsdmoj.atlassian.net/browse/CAS-195) for more information.
This PR is to run the CAS3 reports for 3 months instead of 1 month to see the performance of the report(testing purpose only).
This change is just for testing purpose to make sure the service performance is acceptable and work without any issue before we change the service to search based on `startDate` and `endate` instead of searching only for 1 month.
[CAS-195]: https://dsdmoj.atlassian.net/browse/CAS-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAS-229]-CAS3-reports-Configure and generate based on configured number of months

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas2AssessmentMigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmissionsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2AssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2MigrateAssessmentsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmissionsTransformerTest.kt
https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-251
We previously created the `Assessment` model, with a view to expanding its use on CAS2 here https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1514
Now we want to return it on the `Application` so that the frontend can render it. This may be an interim solution until we have completed all the [phases of our suggested Application refactoring ](doc/architecture/decisions/0021-introduce-cas2-assessments.md)
In a previous commit we introduced functionality to [create an Assessment whenever a CAS2
application is submitted](https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/e479df3f5556005cafb15598aed944668b67353e). This will have left any applications in …
=> Return Assessment on CAS2 Applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementDateEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationEmailService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/notification/EmailNotificationAsserter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationEmailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestEmailServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-392 and https://dsdmoj.atlassian.net/browse/APS-398
This PR makes miscellaneous changes to emails related to new withdrawl functionality
* Add additional personalisation to the request for placement withdrawal emails
* Add additional personalisation to the match request withdrawal emails
* Send a separate email for each arrival date defined for placement applications on submission (because these are split into multiple entities at this point)
* Send a placement request withdrawn email to applicant if the match request representing the original application dates is withdrawn
=> Add additional fields to withdrawal emails and send email per placement request

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2ApplicationsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/SeedCas2ApplicationTest.kt
~~DO NOT MERGE until we have tested the migration job we are currently testing has passed.~~ this can be merged now as we successfully ran the `update_cas2_applications_with_assessments` job in all environments and checked that all non-seeded submitted applications have assessments ☺️ 
we [previously introduced a function](https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/e479df3f5556005cafb15598aed944668b67353e) to create an Assessment when an Application is submitted. 
This commit ensures our seeded data matches what we would expect to see on real submitted applications.
I've used the `@SuppressWarnings("LongParameterList")` annotation because I don't see a way of reducing the parameters without making it less readable, any suggestions welcome!
=> Seed Assessments on Submitted Applications for CAS2

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BookingsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt, src/main/resources/static/api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingSearchServiceTest.kt
Refer [CAS-228](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-228) for more information.
This PR is to support crn based booking search.
The changes are:
1. Added optional query parameter `crn` into booking search api `bookings/search`
2. Changed the service and DB query to include `crn` in the search if its available
[CAS-228]: https://dsdmoj.atlassian.net/browse/CAS-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAS-228] booking search by crn

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TimeService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
Issue caused by a test using today’s date. Fix was to use a fixed date and provide a way to mock out the date provider in the implementation code
=> Tests were failing when ran on a leap-day

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-432
Previously we were returning unsubmitted placement requests. Because these don’t neccessarily have dates associated with them, an error occurred when rendering the withdrawable on the UI. We should not be returning unsubmitted placement apps as they are not surfaced anywhere else on the UI once the user navigates away from the creation forms.
=> Only submitted placement requests are withdrawable

.circleci/config.yml
This follows the instructions in:
https://playwright.dev/docs/ci#circleci
To avoid stamping on user’s permissions, we also have a user for each shard, with the login details stored as with a prefix (so `HMPPS_AUTH_USERNAME_1, HMPPS_AUTH_PASSWORD_1 etc etc), we then get the auth details for each shard in the setup process with a bit of Bash jiggery pokery and then run a selection of tests on each shard. This reduces the total runtime to around 3 minutes!
=> Run CAS1 e2es in parallel

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationEmailServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-431
If using the new withdrawal logic that splits requests for placements into an entity per date, use the new email template, allowing us to include more information on the email without breaking emails currently being sent in live
=> Use new Placement Request Submitted email template when splitting requests into 'one per date'

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-439
Whilst adhoc bookings were already being returned in the list of withdrawable elements (integration tests have been updated to prove this), before this commit when withdrawing an application this wasn’t cascaded to applicable bookings.
This commit ensures withdrawals cascade to any adhoc bookings (i.e. bookings not linked to a placement_request). Integration tests have been updated to assert on this, and also better assert on email personalisation values to differentiate between emails actually sent (i.e. differentiate between two ‘booking withdrawn’ emails for different bookings)
=> Withdraw adhoc bookings when application withdrawn

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingCancelSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableTreeBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationDomainEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestDomainEventServiceTest.kt
We have a requirement to be able to block entities from being withdrawn if they relate a booking that has arrivals. For example, given the following tree of entities:
```
application
-> placement application 1
-> placement request 1
-> booking with no arrival
-> placement app 2
-> placement request 2
-> booking with arrival
```
We should not be able to withdraw the application, placement application 2, placement request 2 and the booking with arrival.
To enable such behaviour we need to move towards a tree representation of an application’s entities when making decisions about what is and isn’t withdrawable.
Building and using the tree has other benefits, such as:
* Reducing code duplication (especially for cascading) and making withdrawals more consistent across all entity types
* Making …
=> Model entities in an in-memory tree to determine what needs withdrawing

src/main/resources/db/seed/local+dev+test/cas2_application_data/data_A1234AI.json, src/main/resources/db/seed/local+dev+test/cas2_application_data/document_A1234AI.json
We recently updated an offence history question[1]. This commit updates the seed data to match.
[1]
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/blob/786cbbe8a7c0a326859172972cd89471a708fa9b/server/form-pages/utils/questions.ts#L814
=> Update CAS2 seed data to match questions

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/AssessmentsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/AssessmentsTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmissionsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2AssessmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/AssessmentsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmissionsTransformerTest.kt
DO NOT MERGE until this PR has been merged: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1542 
This is the step [following this PR](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1524 ) and that to be merged first, once it is then this PR can be pointed at `main` branch 
https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-254 
This allows Assessors to update an Assessment by a PUT request to `cas2/assessments/{id}` with these string fields:
- nacroReferralId
- assessorName 
Although an Assessment belongs to an Application, I've taken the choice here to make the end point only `assessments` and not e.g. `applications/{applicationId}/assessments` because of the work we hope to do to refactor assessments …
=> Allow Assessor to update assessment

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
We’re currently returing the default 10 days for all assessments in the frontend which isn’t correct
=> (APS-455) Add dueAt to assessment summaries

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/AssessmentsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/AssessmentService.kt, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2AssessmentTest.kt
[Jira ticket CAS2-255](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-255)
**Not to be merged until https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1542 is merged** (although they could probably be merged independently, this branch contains some changes/refactorings introduced in that branch).
We're [now](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1514) creating an Assessment when a CAS2 Application is created.
This PR adds a route (`/assessments/{assessmentId}`) accessible to Assessors and Admins to allow API consumers to fetch one of these Assessments. Although an Assessment belongs to an Application, we've kept the endpoint separate (i.e. not including a reference to the Application ID) to keep …
=> Add route for getting an Assessment

src/main/resources/db/seed/local+dev+test/cas2_application_data/data_A1234AI.json, src/main/resources/db/seed/local+dev+test/cas2_application_data/document_A1234AI.json
Updates CAS2 seed data after changing the application schema to move HDC dates into their own task at the top of the task list.
=> Update CAS2 seed data

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WorkingDayCountService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WorkingDayCountServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentEmailServiceTest.kt
The email notifications when people were allocated assessments were off by one, because we were counting the number of working days including today when stating how many days they have to complete the assessment (inclusive), instead of the difference in working days between the due date and today's date (exclusive).
This adds a new `getDifferenceInWorkingDays` function and uses it in the email service to let the user know how many TOTAL working days they have to complete an assessment.
=> (APS-455) Fix off by one error in emails

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WorkingDayCountService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WorkingDayCountServiceTest.kt
We suspect that the introduction of mockkStatisc was causing test instability issues in circle. This change uses the TimeService in WorkingDayCountService to retrieve the current LocalDate, which can then be mocked in the unit test without mockkStatic
=> Remove use of mockkStatic for test stability

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
These details are only used once an application is submitted, so capturing them before submission doesn’t add any value
=> Remove CAS1 User Details from App Update API

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeOperations.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/notification/EmailNotificationAsserter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeOperationsTest.kt
If a booking has an arrival, any related entity (match request, request for placement, application) cannot be withdrawn and are marked as blocked. Such entities will not be returned in the withdrawable list, and any attempt to withdraw one of these entities will result in a 400 error.
As part of this commit the WithdrawalTest has been effectively rewritten as so many existing tests broke. This class should now be more concise and each test has a complete description of the entity tree.
=> Bookings with arrivals blocks ancestor withdrawals

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesRoomsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/TemporaryAccommodationBedspaceSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BedTransformer.kt, src/main/resources/db/migration/all/20240306145525__add_enddate_to_bed.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoomEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RoomServiceTest.kt
Refer [CAS-235](https://dsdmoj.atlassian.net/browse/CAS-235) for more information
This PR is to add an `endDate` to the CAS3 beds table to indicate the availability of the particular room. Similar to archive property but using `endDate`.  
I have added optional `endDate` to to the API which creates room and change the service to store the endDate in the CAS3 specific 'beds` table. 
This PR contains below changes:
1. Modify existing POST API `/premises/{premisesID}/rooms` by adding optional `endDate`
2. Modify existing GET API `/premises/{id}/rooms` by adding optional `endDate`
3.  Modify existing GET API `/premises/{id}/rooms/{roomId}` by adding optional `endDate`
4. Change the service to store the endDate into `beds` table and retrieve the same.
Note:We will have separate story to modify …
=> [CAS-235] -  Add end_date column to beds table for Cas3 premises

src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml
The frontend updates the Assessment via a form like so
We originally thought that the frontend could send an empty string back for any fields not entered in the form, but the restClient strips out empty fields.
Because either of these fields could be `null`, we do not need to require that they both be sent by the frontend.
Because it's a PUT request, the API will still update both values sent, even if they are `null`
```
assessmentEntity.apply {
this.nacroReferralId = newAssessment.nacroReferralId
this.assessorName = newAssessment.assessorName
}
```
I don't think this needs any further testing IMO, as we would be testing the workings of the OpenAPI typing, and that Kotlin can assign `null` to things, but open to changing it if anyone feels strongly.
=> Make CAS2 Assessment update fields nullable

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationNoteService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationNotesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationNoteServiceTest.kt, src/test/resources/application-test.yml
JIRA https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-8
_As a referrer
I want to know when a note has been added to a referral I have made
So that I can reply in a timely manner to progress the referral_
This uses the `EmailNotificationService` to send an email to the referrer when a Note is added by an ExternalUser - I don't think we need to specify the role of the External User in this case, because the only other users able to leave a note are Assessors currently, and presumably the referrer should be notified whenever someone who is not a POM leaves a note.
I've also added some CAS2-specific date formatting to the date service, as we display dates differently than the other CAS projects.
For the edge case that a Nomis user does not have an …
=> Email Referrer when an Assessor adds a Note

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesRoomsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoomEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RoomServiceTest.kt
Refer [CAS-240](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-240) for more information.
This PR is to update the bedEnddate if its not already existing for CAS3 bed. The below changes where added as part of this PR
1. Expose existing `created_at` DB column as JPA entity element to run business rule.
2. Add a Entity Query to find existing active bookings which are overlapping with given 'bedEndDate` to make sure we are not allowing to add `bedEndDate` if we have existing bookings.
3. Service change to allow update `bedEndDate` with below business rule.
1. Don't allow add `bedEndDate` if already existing for the Bed.
2. Don't allow to add `bedEndDate` if its before bed `creation date`
3. Don't allow to add `bedEndDate` if any active existing …
=> [CAS-240] - Update bedEndDate with business rule

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WorkingDayCountServiceTest.kt
This updates the `bedCount`s where they are used to only include beds that either do not have an `endDate` or have an `endDate` of later than the current date.
=> (APS-459) Allow beds to be archived

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This adds two new fields to sort by:
- `person` to sort by the offender’s name; and
- `allocatedTo` to sort by the allocated user’s name
=> (APS-338) Allow sorting tasks by person and allocated user

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt
When returning the bed summary, only list the “live” beds (i.e do not have an `endDate` or have an `endDate` of later than the current date)
=> (APS-459) Hide archived beds in bed summary

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationNoteService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationNotesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationNoteServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/MockEmailNotificationService.kt, src/test/resources/application-test.yml
[CAS2-10 Jira ticket](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-10)
> As an assessor
> I want to know when a note has been added to a referral I have reviewed
> So that I can review it in a timely manner to progress the referral
This PR adds functionality for sending an email to Assessors when a Referrer leaves a note on an Application.
It also adds some helper functions, such as one for pre-filling the `reply-to` email ID for the CAS2 team so we no longer need to manually pass it in everywhere that function is called.
=> Email the Assessors when a Referrer leaves a note

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationStatusUpdatesReport.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2/ApplicationStatusUpdatesReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ReportsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
Reference these JIRA tickets for information: [CAS2-115](https://dsdmoj.atlassian.net/browse/CAS2-115) and [CAS2-114](https://dsdmoj.atlassian.net/browse/CAS2-114)
**Introduction**
The JSON structure of the data field in the domain events table for a record with an event type `CAS2_APPLICATION_STATUS_UPDATED` is as follows:
```JSON
{
"eventType":"applications.cas2.application.status-updated",
"eventDetails":{
"applicationId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"applicationUrl":"http://localhost:3000/applications/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"personReference":{
"noms":"XXXXXXX",
"crn":"XXXXXXX"
},
"newStatus":{
"name":"moreInfoRequested",
"label":"More information requested",
"description":"The prison offender manager (POM) must provide information requested for the …
```
=> Cas2 115 extend status updates report with status details

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
This PR is to consider the newly added `bedspace enddate` in bedSpace search to filter out the beds which are not archived by the endate.
=> [CAS-199]-CAS3-Consider bedspace enddate in bespace search functionality

helm_deploy/values-test.yaml, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/FactoryUtils.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/OffenderUtils.kt, src/test/resources/application-test.yml
> See [APS-427 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-427).
This PR updates the configuration to switch the data source for offender details and offender risks to the AP Delius Context API in the `test` environment. This will allow us to manually test that we get the information we expect from the AP Delius Context API and confirm that it is safe to disable the Community API as a source of this information.
In order to enable this change, several integration tests have been modified in order to mock/expect the AP Delius Context API as the source of this information. These changes include:
- Updating the API specification to prevent a `Person` with `UnknownPerson` incorrectly being deserialised as a `FullPerson` instance
- Modifying the WireMock stubs …
=> [APS-427] Enable AP Delius Context API as the offender data source for test env

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeOperations.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeOperationsTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-475
Several legacy adhoc bookings are linked to potentially unrelated placement requests. This behaviour was removed in commit 2d96a4d37567fde3f91a7a9172b459a91fb30625.  To avoid such adhoc placements being unintentionally withdrawn when (unrelated) ancestor elements are withdrawn, we mark them as exempt from cascade.
Exempting such makes sense in the general context because when creating an adhoc booking the user doesn’t explicitly link it to an application, it is automatically assigned to an application with the required CRN (if such an applciation exists). Therefore, it’s unexpected for an adhoc to be withdrawn automatically if an application withdraws the application.
The withdrawal tree toString has been updated to highlight when …
=> Adhoc bookings are exempt from cascade withdrawals

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEventSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/db/migration/all/20240313090552__add_triggered_by_user_to_domain_event.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/DomainEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-490
This PR adds 'triggering_user_id' to the common domain_events table and automatically populates it with the calling user's user id. For consistency with other entries in the table, no FK constraint is defined against the user, and a left join is used when retrieving the user to be included in timeline entries, as shown below:
=> Capture triggering user in domain events and show on Timeline

helm_deploy/values-prod.yaml
This PR updates the configuration to switch the data source for offender details and offender risks to the AP Delius Context API in the production environment.
Following the deployment of this change to `test` (#1513) as well as `dev` and `preprod` (#1404), we now have confidence that this change will work as expected and deliver some performance improvements.
This change still needs to be enabled locally (through WireMock and/or [ap-tools](https://github.com/ministryofjustice/hmpps-approved-premises-tools)), but this doesn't prevent deployment to production.
See the PRs below for more context about this configuration change:
- #1200
- #1220 
- #1257 
- #1298 
- #1317 
- #1354 
- #1404 
- #1513
=> Enable AP Delius Context API as the offender data source for production

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This is specifically for withdrawal logic. In this case the placement will be excluded from withdrawal cascading.
This is required because we can’t fully backfill the ‘adhoc’ boolean for existing placements, so we have to be cautious and treat them as adhoc placements.
=> If placement adhoc state unknown, treat as adhoc

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
Whilst there should only ever be 0 or 1 placement requests returned when requesting getPlacementRequestForInitialApplicationDates, due to data inconsistencies there are a small number of applications that will return multiple placement requests.
We know that only one of these placement requests relate to the initial application dates, and the rest relate to placement_applications, but we have no programmatic way of 'fixing' this link for those placement requests.
=> Allow many ‘initial’ match requests to be returned

detekt-baseline.xml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
We’ve been getting an error in certain circumstances when querying for tasks. My suspicion is that doing a `LEFT JOIN` instead of an `INNER JOIN` is causing non-AP assessments to be included. I’ve created a temporary accommodation Assessment in some of the task lisiting tests to prove this theory and it seems to ring true.
=> `INNER JOIN` approved_premises_applications when listing tasks

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt
Ticket ref: https://dsdmoj.atlassian.net/browse/CAS2-318
The following secondary status details are missing from the 'Referral Cancelled' status and need to be added:
No property available
No female property available
No adapted property available
No suitable property available
Incomplete referral
Created in error
=> CAS2-331 added 6 x missing status details for 'Referral Cancelled'

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt
We’ve noticed when making multiple appeals, the timeline shows multiple events because we’re carrying out multiple JOINs on the query. I’ve gone through a number of permutations of using the `DISTINCT` operator, but nothing seems to work as we expect, so I’ve opted for calling `distinctBy` in the service method, which seems to do the trick. As the number of events is unlikely to get unmanageable, we’re not asking the system to do too much extra work (either on the application or database side)
=> (APS-450) Return distinct domain events in timeline

helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
The findAllAdhocOrUnknownByApplication was not filtering out bookings not related to the application.
=> Fix bug that would withdraw unrelated placements

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeOperations.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeOperationsTest.kt
We previously had a bug in the code where withdrawing an application would inadvertently cascade to adhoc bookings from other applications.
Whilst this bug has been fixed and specific regression tests added for the specific scenario, we want to add additional guard rails in the cascade withdrawal logic to ensure is not possible for cascades of any entity types. This is especially important as withdrawal cascades are somewhat opaque on the UI as the user it not explicitly told which entities will be withdrawn on cascade.
This commit adds a check in the withdrawal logic to ensure that all entities being withdrawn belong to the same application as the root entity being withdrawn.
Note that this implementation isn’t perfect as the check only occurs after the root entity has already been …
=> Check to ensure withdrawal is limited to same app

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1FixPlacementApplicationLinksJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MigrateCas1FixPlacementApplicationLinksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/migration/Cas1FixPlacementApplicationLinksJobTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-438
Placement Applications accepted before November were not linked to their corresponding Placement Requests. This relationship is impotant to:
1. Differentiate the placement request created for the initial application dates from those created for additional request for placements (placement_application)
2. Allow withdrawals to correctly cascade from placement_applications to their corresponding placement_requests and bookings
=> Add migration job to add missing links between placement_applications and placement_requests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmissionsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/OffenderServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmissionsTransformerTest.kt
We have an 'assessor's dashboard' page on CAS2, which queries the `/submissions` endpoint to retrieve paged results of all submitted applications across all time.
The response times for this are very slow https://dsdmoj.atlassian.net/browse/CAS2-318 
Part of the reason for this could be that we are making two calls to integration APIs in order to retrieve a `FullPerson` type.
1. Here when we get the `offenderSummary` 
https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/938a6dda5c012a3b80080ef109d80de6f63fdeee/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt#L86 
2. And then to get the `inmateDetail` 
https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/938a6dda5c012a3b80080ef109d80de6f63fdeee/src/main/kotlin …
=> Move `personName`, `crn` and `nomsNumber` to top level `Cas2SubmittedApplicationsSummaries`

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BedUtilisationReportRow.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt
This PR [CAS-244](https://dsdmoj.atlassian.net/browse/CAS-244) is to change the calculation of occupancy rate in Occupancy Report based on Bedspace start and end date. This will include:
1. The Occupancy Rate in the Occupancy Report will be calculated as follows:
occupancy percentage = bookedDaysActiveAndClosed / bedspaceOnlineDays
2. Add new columns to the report:
- bedspaceStartDate - set to the Creation Date of the Bedspace
- bedspaceEndDate - set if it not null
- bedspaceOnlineDays this will be calculated as the number of days between these dates:
- bedspaceStartDate or report start date - whichever is LATER
- bedspaceEndDate or report end date - whichever is EARLIER
4. Remove the column totalDaysInTheMonth
[CAS-244]: https://dsdmoj.atlassian.net/browse/CAS-244?atlOrigin=eyJpIjoiNWRkNT …
=> [CAS-244] - Update occupancy rate calculation in Occupancy Report based on Bedspace end date

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1FixPlacementApplicationLinksJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/migration/Cas1FixPlacementApplicationLinksJobTest.kt
Relates to https://dsdmoj.atlassian.net/browse/APS-438
* Logging improvements
* Don't disregard applications with one or more placement apps with decisionMadeAt Set. Only disregard them if they all have it set
* Add manual fixes into migration for cases where we couldn't programmatically determine lines, but could when reviewing applications manually
* Update migration logic to ignore/leave alone placement applications already linked to placement requests
=> Placement Application to Placement Request Migration Job Improvements

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmissionsTransformer.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/OffenderServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmissionsTransformerTest.kt
https://dsdmoj.atlassian.net/browse/CAS2-336 
as we now have the `personName`, `crn`,`nomsNumber` fields as top level fields ([see this PR](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1621) and [this UI one](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/583)), we can
simplify how we are getting the person's name from the `offenderDetailsDataSource`.
I'm also slightly changing the error behaviour -previously we called the function `getInfoForPersonOrThrowInternalServerError` which would throw an error if there person was 'Not
Found'. For our purposes here in CAS2, I don't think we need to throw an error at this point - if the person is not found on Nomis/Delius then we still want to go ahead and show the application, but with …
=> CAS2-336: remove `Person` on Cas2SubmittedApplicationSummary

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/NoticeTypeMigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/resources/db/migration/all/20240319095635__add_notice_type_field_to_applications.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/NoticeTypeMigrationJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This adds a new `noticeType` field to applications, to allow us to get/set the notice type of an application via the frontend and eventually replace the `isEmergencyApplicaiton` field.  The values are:
- `emergency` - less than 7 days between when the application was created and the arrival date
- `shortNotice` - less than 28 days between when the application was created and the arrival date
- `standard` - more than 28 days between when the application was created and the arrival date
There is also a backfill task to backfill the status of all applications. Once the work is implemented in the frontend to send the `noticeType` directly, we can simplify some of the short notice and emergency code and have one source of truth for an application's notice type, as well as assign short notice …
=> (APS-514) Add notice type field to applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1FixPlacementApplicationLinksJob.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/migration/Cas1FixPlacementApplicationLinksJobTest.kt
UUIDs are now defined as actual UUIDs to capture invalid UUIDs on startup
Also now capturing and logging runtime errors during migration as these are otherwise swallowed
=> APS-438 Fixed incorrect UUID in Cas1 Fix PA LinksJob

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/TransitionalAccommodationReferralReportGenerator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/TransitionalAccommodationReferralReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/TransitionalAccommodationReferralReportRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20240319141046__add_pdu_to_cas3_application.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/TransitionalAccommodationReferralReportsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/ReportServiceTest.kt
This PR [CAS-251](https://dsdmoj.atlassian.net/browse/CAS-251) includes:
1. Capture and store pdu as first class field in CAS3 application.
2. Populate the stored pdu into CAS3's referral report
[CAS-251]: https://dsdmoj.atlassian.net/browse/CAS-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAS-251] Add PDU to database and Referrals report

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/NoticeTypeMigrationJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
Storing all those UUIDs in two arrays gave us memory issues
=> (Fix) Carry out one update task per page of data on Notice Type migration job

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Now we’re relying on the created at date (at least temporarily) to get the noticeType, we need to ensure that the date the application is created is consistent (rather than being a random date in the past) to avoid flaky tests. This sets that `createdAt` date to now, so when we set the arrivalDate as 10 days or 7 months from now, we get a predictable response for the noticeType
=> (Fix) Set createdAt in UpdateApplicationCas1 test

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
This will ensure the link to the booking then appears on the timeline in the UI
=> APS-528 Populate bookingId property on booking changed evt

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
Ref JIRA ticket [CAS2-341](https://dsdmoj.atlassian.net/browse/CAS2-341)
**User Story**
As a CAS2 user
When I request a list of applications
Then the most recently created should be at the top of the list
**Technical Notes**
The `findAllCas2ApplicationSummariesCreatedByUser` function has been modified to order the results by descending `createdAt` by adding an `ORDER BY` clause to the SQL.
An additional integration test has been included in `Get all applications returns 200 with correct body` which checks that two applications are returned in correct order.
[CAS2-341]: https://dsdmoj.atlassian.net/browse/CAS2-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CAS2-341 change sort order for applications

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/OffenderServiceTest.kt
https://dsdmoj.atlassian.net/browse/CAS2-338
Following investigating the slow response times of the /submissions endpoint, we think we can increase the efficiency  by bulk searching for CRN's. This will also help when we introduce the Prison dashboard.
Previously we iterated through each application and [make an individual call for the OffenderSummary here](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/938a6dda5c012a3b80080ef109d80de6f63fdeee/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt#L86 )
This PR
* uses the `offenderDetailsDataSource.getOffenderDetailSummaries` method to search for a list of CRN's, and then return a map of `crn` -> `personName`. 
* The map can then be used by the `SubmissionsController` to map …
=> CAS2-338: Bulk search CRNs for CAS2 Submissions 

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/StringHelpers.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/StringHelpersTest.kt
This PR updates all 4 withdrawal timeline event descriptions to use consistent formatting. Examples below:
=> APS-521 show placement app and match request withdrawal reason in timeline

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentEmailServiceTest.kt
Email logic is now in the Cas1AssessmentEmail service, isolating the logic and making it easier to make future changes
=> APS-530 Move assessment withdrawn email logic into CAS1 Assessment Email Service

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20240321121046__add_name_to_cas3_application.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This PR [CAS-271](https://dsdmoj.atlassian.net/browse/CAS-271) includes:
- Add new field *name* to the database
- Save the offender name (first name and surname) retrieved from nDelius to the table when CAS3 application is submitted
[CAS-271]: https://dsdmoj.atlassian.net/browse/CAS-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAS-271] Add Name to database to support finding Referrals and Bookings by Name

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ReportsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/Cas2ExampleMetricsRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ReportsService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
When deleting an old reports endpoint, I noticed that we could probably do with some tidying up of the reports.
This PR
* deletes unused 'example-report' report
* tightens up report endpoint tests
* introduces enum for the report name (see commit message for reasoning)
=> CAS2-121 refactor the reports end point

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1ValidateApAreaUserMapping.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1UserMappingService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1UserMappingServiceTest.kt
Reduced delay (integration teams suggested no delay way fine)
Updated user mapping service to ensure that an area will always be returned and an exception thrown otherwise
Renamed UserMappingService to Cas1UserMappingService as it’s returning a CAS1 specific entity (ApAreaEntity)
=> APS-404 Cas1ValidateApAreaUserMapping job improvements

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
Ref: [CAS2-334](https://dsdmoj.atlassian.net/browse/CAS2-334)
**User Story**
As a consumer of the CAS API
When I make a request to /applications indicating via a query param that I want either in progress or submitted applications
Then I receive the relevant applications
**Technical implementation**
Added optional param `isSubmitted` and if true returns submitted applications, if false returns those without a submission date, and if absent returns all.
[CAS2-334]: https://dsdmoj.atlassian.net/browse/CAS2-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CAS2-334 add optional isSubmitted param

.circleci/config.yml
This adds a status to Jira tickets when a branch with a ticket ID is deployed, so we can see at a glance the status of a given ticket.
=> (APS-534) Add jira_update to environment deploys

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/CalendarRepository.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CalendarRepositoryTest.kt
The calendar view is only used in the North East, but we’ve had a report that “deleted” beds are still showing in the booking calendar. We will probably be revisiting all this functionality soon, but for now let’s update the calendar view to remove all beds with a end_date before the start_date of the calendar view’s query. This way, we can still see historical bookings if necessary, but remove all old beds for current and future views.
=> (APS-526) Hide retired beds in calendar view

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntityReportRow.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ApprovedPremisesType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt, src/main/resources/db/migration/all/20240321120638__make_ap_type_column_on_approved_premises_applications_table.sql, src/main/resources/db/migration/all/20240321120711__migrate_pipe_and_esap_applications_to_ap_type_column_on_approved_premises_applications_table.sql, src/main/resources/db/migration/all/20240321120835__remove_is_pipe_application_and_is_esap_application_columns_from_approved_premises_applications_table.sql, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationSummaryQueryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/allocations/rules/EsapAssessmentRuleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskDeadlineServiceTest.kt
> See [APS-473 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-473).
This PR adds support for Mental Health Approved Premises (MHAP) within CAS1 applications. There are two ways to specify that an application is MHAP when updating or submitting an application:
- Setting `isMhapApplication` to `true`
- Setting `apType` to `"mhap"`
Using the `apType` enum is preferred for future usage, but `isMhapApplication` has been introduced for backwards compatibility by analogy with the current usage of `isPipeApplication` and `isEsapApplication`. Only one method can be used; for example, setting both `isMhapApplication` to `true` and `apType` to `"mhap"` will return a validation error. This is to avoid having to decide precedence or assign arbitrarily when the values …
=> [APS-473] Add support for Mental Health Approved Premises when updating or submitting an application

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
More detailed context in Jira ticket https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-200
We had an incident in the dev environment where an application was submitted (a 'submitted at' date was given to it in the database) but the Domain Event failed to emit, because the prison code was missing from the Prison API. 
Here we ensure that this won't happen again by:
- If the API is down/unsuccessful: catching any `UpstreamApiExceptions` thrown by the Prison API (e.g. Not Found) when we try to `apply` the prison code to the Application Entity, and transforming the error into a General Validation Error to be handled by the UI. 
- If the API call succeeds but the prison code is missing: throwing an `UpstreamApiException` error with appropriate message, …
=> CAS2-217: prevent submissions when there is no Prison Code

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AssessmentMoreInfoBugFixSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/SeedAssessmentMoreInfoBugFixTest.kt
There is a known issue that affects assessments where a user has requested further information, and goes back to edit the respons, selecting ‘no’ beacause they don’t want to trigger a re-request. This inconsistent state leads to an infinite loop when the UI is attempting to validate the answers.
This commit introduces a seed job the updates the ‘sufficient information’ response to ‘yes’ to break the infinite loop. It can be used to ‘fix’ assessments in this inconsistent state
=> APS-538 Add job to fix broken ‘further info’ assessments

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedUtils.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2ApplicationsSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt, src/main/resources/db/seed/local+dev+test/cas2_application_data/data_A1234AI.json, src/main/resources/db/seed/local+dev+test/cas2_application_data/document_A1234AI.json, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/SeedCas2ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas2AutoScriptTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/SeedUtilsTest.kt
https://dsdmoj.atlassian.net/browse/CAS2-305
As the frontend work is now completed to throw validation errors on HDC/CRD dates that don't meet the requirements below, we need to ensure our seeded data for in-progress applications has valid dates, otherwise the task will not show as 'complete'. 
There is a risk that if we change or remove the `hdc-licence-dates` task on the frontend then this function will become out of date, but we have the same problem with the JSON we  build the applications from currently so I think it's bearable?
In this PR is a utility function that creates dates to this criteria:
* HDC cannot be more than 6 months before CR, but must be before the CRD
* CRD must be more than 21 days in future
And is then used in the auto script and local seeding job.
=> CAS2-345: Calculate HDC dates for seed data

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
> See [APS-523 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-523).
This PR introduces the ability to sort CAS1 assessments using the `dueAt` field.
As CAS1 assessments do not have a due date, the `GET /assessments` endpoint will return a `400 Bad Request` response if this sort field is used for the CAS1 service.
=> [APS-523] Allow sorting CAS1 assessments by `dueAt` field

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskDeadlineService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TaskDueMigrationJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskDeadlineServiceTest.kt
This commit changes the placement application due at calculation to use the submission date instead of the creation date.
The previous behaviour isn’t generally an issue because users can’t start creating a request for placement on the UI and then return to it later unless they bookmark it, which is unlikely.
=> APS-549 Use placement_app submission date for due at calcs

src/main/resources/db/migration/all/20240325170535__backfill_new_release_date_field_on_cas3_referrals.sql
This PR [CAS-225](https://dsdmoj.atlassian.net/browse/CAS-225) will populate the release date field in temporary accommodation application from data json field
[CAS-225]: https://dsdmoj.atlassian.net/browse/CAS-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAS-225] Populate Release Date in Temporary Accommodation Application table from json

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
Before making any more changes to the update user logic i’ve given the tests a tidy up and added a test for each field that triggers an entity update
=> Tidy up user update on change tests

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/main/resources/static/cas2-api.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
JIRA ticket: https://dsdmoj.atlassian.net/browse/CAS2-333
**User Story**
With page param:
As a consumer of the CAS API
When I make an index request to /applications?page=x
The I should receive the correct page of results
And any relevant metadata (e.g. total count)
Without page param:
When I make an index request to /applications
The I should receive all the correct applications
**Technical implementation**
The existing pattern recently introduced in this PR to the Submissions controller has been reused:
https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1413
=> CAS2-333 add optional page parameter

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/converter/StringListConverter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1BackfillUserApArea.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1UserMappingService.kt, src/main/resources/db/migration/all/20240327151433__capture_team_codes_on_migration.sql, src/main/resources/db/migration/all/20240328091447__capture_created_and_updated_on_user.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/MigrateCas1UserApAreaTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/converter/StringListConverterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
In preparation for capturing and updating ap area in the users table we need to be able to track changes to a user’s team code.
This commit adds a new column to capture team code and updates the existing ap area backfill to also backfill the team codes
New 'created at' and 'updated at' column is added to the user entity to help track when a user was last updated in the database.
=> APS-404 Backfill user.teamCodes and capture user updatedAt

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas3UpdateApplicationOffenderNameJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/main/resources/static/_shared.yml, src/main/resources/static/codegen/built-api-spec.yml, src/main/resources/static/codegen/built-cas2-api-spec.yml, src/main/resources/static/codegen/built-cas3-api-spec.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateApplicationOffenderNameJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
This PR [CAS-276](https://dsdmoj.atlassian.net/browse/CAS-276) includes:
- Create a migration job for CAS3 to feed the name field in Temporary Accommodation Application table with the full name of the offender from nDelius
[CAS-276]: https://dsdmoj.atlassian.net/browse/CAS-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAS-276] Migrate name field data from nDelius to Database

helm_deploy/values-prod.yaml
PR to enabled CAS3 domain events in Prod. The events are
- person.arrived.updated
- person.arrived
- person.departed
- person.departed.updated
We need to deploy this on 2nd April after [CAS-204](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1489?selectedIssue=CAS-204) and [CAS-292](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1489?selectedIssue=CAS-292) are ready for prod deployment.
[CAS-204]: https://dsdmoj.atlassian.net/browse/CAS-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CAS-292]: https://dsdmoj.atlassian.net/browse/CAS-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CAS-105]-Enable cas3 remaining domain events in prod

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesSeedJob.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedApprovedPremisesTest.kt
The `emailAddress` was missing from the "update" process when seeding Approved Premises.
=> Fix: update email AP email address when re-running seeding

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa.specification/UserSpecifications.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationRegionEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/UpdateAllUsersFromCommunityApiJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt, src/main/resources/db/migration/local+dev+test/R__1_create_dev_users.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LocalAuthorityAreaEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserCaseSensitivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/MigrateCas1UserApAreaTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PremisesTransformerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
There are two parts to this PR
1. Update AP Area and Team Codes on the user entity whenever the user is updated (we only update ap area if originating request is for CAS1)
2. Use user.apArea when determining which ap area the user belongs to
=> APS-404 Update and use user's ap area property for CAS1 (Do not merge)

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/CancellationReasonTransformer.kt, src/main/resources/db/migration/all/20240326122914__add_sort_order_col_to_booking_cancellation_reasons.sql, src/main/resources/db/migration/all/20240402150339__update_cas1_booking_cancellation_reasons.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationReasonEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
This PR introduces a sort order column to booking cancellation_reasons. Cancellation reasons are sorted by sort order and then name, where lowest sort order numbers (0) are shown first.
=> APS-544 Update CAS1 booking cancellation reasons

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestEmailService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestEmailServiceTest.kt
The ‘additionalDateSet’ personalisation was missing, but is used in the template.
This is only an issue for withdrawal emails related to the original application dates
=> ASP-594 Add correct personalisation for PR withdrawn email

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SentryService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/EmailNotificationServiceTest.kt
Whilst some exceptions if notify can be ignored (e.g. user not on guest list for test environments, invalid email address), we should be raising alerts if the message sent to notify does not include all of the personalisation expected of the corresponding template
=> APS-594 Log in sentry if email has missing personalisation

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1BackfillUserApArea.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/MigrateCas1UserApAreaTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt
Previously the ap area was not populated if the staff details could not be found. Because the user.ap_area_id is required to show the users on the users page, we really need this to be populated with something, even for inactive users.
This change updates the ap area backfill to fall back to probationRegion.apArea where the staff user details cannot be retrieved
=> APS-404 Update ApArea backfill to always populate ap area

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserCaseSensitivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
Previously we only populated users.ap_area_id for CAS1 users, because we didn’t want logins to fail for CAS3 users if the ap area couldn’t be resolved.
We then realised that this caused an issue when viewing the user management page, as this page list users regardless of which CAS they first logged into, meaning some of these users would not have an ap_area_id value defined. This led to errors as all CAS1 users are assumed to have an ap_area_id defined.
This change ensures that users.ap_area_id will always be populated. A more long term solution is required to ensure that CAS3/2 logins do not have to resolve users.ap_area_id as this is unreleated to these systems
=> APS-404 Populate ap_area_id for any new user, regardless of the CAS

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas3UpdateApplicationOffenderNameJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateApplicationOffenderNameJobTest.kt
This PR [CAS-295](https://dsdmoj.atlassian.net/browse/CAS-295) is:
- To fix the log for the offenders crn been processed 
- Change the exception when the offender is not found in nDelius 
[CAS-295]: https://dsdmoj.atlassian.net/browse/CAS-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CAS-295 Add logs for migrate offender name from nDelius

src/main/resources/static/cas2-domain-events-api.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas2/Cas2StatusFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2DomainEventTest.kt
This field was previously made required here:
https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1560/files#diff-ede7289ac96e28a0df3cb05d249672fb0be71380ba3278b33c4ce1be19068b23 such that all new status update events would have
a list or empty list of details, but this did not
apply to older events, which is causing the API to error
https://ministryofjustice.sentry.io/issues/5135641959/
By making it not a required field on the API model this should allow the API to return old status
update events. This seems preferrable to
undertaking a risky migration on production data
to set empty lists on any updates that do not have this field.
=> make statusDetails not required for domain events

src/main/resources/db/migration/all/20240402174247__backfill_bed_enddate_for_archived_premises.sql
This PR is to back-fill the bedSpace end-date for the CAS3 premises which are already `archived`.
=> [CAS-291]-Backfill the bedspace end date as current date for archived premises

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2SubmittedApplicationReport.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
We were previously using the `Instant` created on
the event data, which did not take into account
timezones/british summer time.
Using the `occurred_at` timestamp means we are
using an OffsetDatetime/ `TIMESTAMP WITH TIMEZONE` which is the same format used for
`application.created_at` and means it should
reflect the correct local time at which the event
happened. It also means we don't have to dig into
the JSON data to find the the timestamp.
This change is happening in the SQL query itself - we don't have unit tests for these queries, and
it's difficult to test in integration tests, see
this commit for information
https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/260b1c6ded66c71d8495eca6512d9663be0dfe9e
But I think we have enough confidence by checking
that the …
=> (CAS2-377) Fix submitted time shown for CAS2 submitted report
