- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AppealDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AppealDomainEventServiceTest.kt
This relates to https://dsdmoj.atlassian.net/browse/APS-620 where the user is getting a null pointer when attempting to create an appear.
This PR also moves the appeals domain event logic into a standalone class
> APS-620 Allow for null NOMS Number in appeal domain events

- src/main/resources/db/migration/all/20240408090349__make_ap_q_code_unique.sql
We had an error in our seeding data that used the same q_code for two approved premises. This change ensures data like this will be refused during any future seeding.
> APS-621 Make approved_premises.qcode unique

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This allows us to optionally return completed tasks instead of incomplete tasks (which is the default).
This makes the SQL a tad more complex. When we have time we should really think about refactoring to have actual Task entities which map to the relevant Assessment / Placement Application / Placement Request, but this is probably OK for now.
> (APS-602) Show completed tasks in task allocation section

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
Replace the word ‘booking’ with ‘placement’ for all booking events
Add premises name to booking made event, and use the UI Date/Time format for easier to read dates
https://dsdmoj.atlassian.net/browse/APS-586
> APS-568 Update booking domain event descriptions

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DomainEventsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/AssessmentAllocatedFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SnsDomainEventListener.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt
- src/test/resources/application-test.yml
> See [APS-496 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-496).
This PR introduces the `approved-premises.assessment.allocated` domain event type. This is emitted in two scenarios:
1. when an application is submitted and the assessment is first generated; or
2. when the assessment is reallocated.
Additionally, the event contains information about whether the assessment was assigned automatically.
> [APS-496] Introduce 'assessment allocated' domain event type

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/allocations/UserAllocator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SentryService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/allocations/UserAllocatorTest.kt
Whilst such issues are logged at warn level, these are only useful once we know there is an issue (i.e. the user has informed us). This commit also raises a message in sentry so we can immediately investigate and rectify such issues.
> APS-628 Raise error if allocator rule returns invalid user

- src/main/resources/application.yml
Without this we can’t start up in local
> APS-496 Add default assessment-allocated-event-detail url

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/PlacementApplicationEntityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
This updates the changes made recently to `PlacementApplicationDecision` to enable easy conversion from JPA enum to API enum and vice-versa. Hopefully this is a pattern we can replicate elsewhere.
> (Chore) Improve enum conversion

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/StatusUpdateTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmissionsTransformerTest.kt
We're working towards displaying the latest status update for submitted applications on a dashboard for users:
This commit adds a nullable `latestStatusUpdate` field to the query used after a GET request to `/applications?isSubmitted=true`.
As an Application can have many Status Updates and we just want the latest one, it's using a LEFT JOIN to go and get the relevant status update connected to each submitted application. 
We will need to do some performance testing to understand more about how efficient this will be - we don't currently have any Gatling setup, so we should do this manually when we have the frontend implementation. This endpoint will always be queried in pages, and from looking at production data most applications have no more than 6 status updates, so we don't think the …
> Add latest status update to submitted applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserServiceUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/ApprovedPremisesApplicationEntityTest.kt
See Jira [APS-617: Add mental health and recovery focused as user qualifications](https://dsdmoj.atlassian.net/browse/APS-617)
In this PR we add two new user qualifications for handling tasks related to particular types of premises:
- `recovery-focused` for applications with the `RFAP` type
- `mental-health-specialist` for application with either `MHAP_ST_JOSEPHS` or `MHAP_ELLIOTT_HOUSE` type
The mapping between types of application and the user qualifications are made in `ApprovedPremisesApplicationEntity.getRequiredQualifications()`.
Through the `TaskEntity` it's now possible to filter tasks according to these "required qualifications" as they related to types of premises.
> APS-617: Add qualifications for Recovery-focused and Mental Health premises

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
This PR is to allow booking departure date can be same as bedspace's enddate instead of stoping the booking.
Currently the booking validation stops the booking to be completed if the departure date is same as bedSpace endDate.
> [CAS-316]-Bugfix to allow booking departure date is same as bedspace enddate

- detekt-baseline.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/service/GetAllApprovedPremisesApplicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DbExtension.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/IsPerClass.kt
Now we want to show users applications that are still awaiting a placement request, we need to be able to filter applications by AP Area (I imagine this will be a requirement more generally anyway, now we've rolled out nationally).
As well as adding the AP Area filtering I've also made the long-wished for (at least by me!) ability to share database context between tests. Previously testing the database has meant we've had to have a ton of tests that have setup/teardown steps that run before every test and mean adding new functionality will add more latency to an already slow test suite. 
I haven't yet deleted the old application search tests (we'll still need some as the new tests run directly on the service), but I will do that assuming we're happy with this new approach.
> (APS-603) Allow applications to be filtered by ap area

- detekt-baseline.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
If a user reallocates a task and they attempt to reallocate a previously reallocated task again, this results in duplicate tasks, which has caused confusion in the past. 
This throws an error if the task has already been reallocated and the user attempts to reallocate it again.
> (APS-661) Ensure task cant be reallocated multiple times

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationTimelineNoteEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1RedactAssessmentDetailsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationTimelineNoteService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineNoteTransformer.kt
- src/main/resources/db/migration/all/20240415124848__make_timeline_note_user_nullable.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationTimelineNoteEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesAssessmentEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1RedactAssessmentDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1RedactAssessmentDetailsSeedJobTest.kt
https://dsdmoj.atlassian.net/browse/APS-573
This is required for a specific assessment in production where we want to remove all elements of the assessment data/document except for ‘sufficient-information-confirm’
> APS-573 Add seed job to remove assessment details

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DomainEventsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DomainEventTransformer.kt
- src/main/resources/application.yml
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PlacementApplicationAllocatedFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DomainEventTransformerTest.kt
- src/test/resources/application-test.yml
> See [APS-496 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-496).
This PR introduces the `approved-premises.placement-application.allocated` domain event type. This is emitted in two scenarios:
1. when a request for placement is submitted; or
2. when the request for placement is reallocated.
**NB**: this PR is currently set to merge into `APS-496-api-workflow-manager-reviews-task-allocation-history` instead of `main` for clarity, as this PR depends on changes introduced in #1699. This PR should not be merged until after that one.
> [APS-496] Introduce 'request for placement allocated' domain event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ApprovedPremisesApplicationStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonalTimelineTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApprovedPremisesUserFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/TimelineEventFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonalTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/model/ApprovedPremisesApplicationStatusTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonalTimelineTransformerTest.kt
> See [APS-590 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-590).
This PR introduces the `GET /people/{crn}/timeline` endpoint. This works similarly to calling the `GET /applications/{applicationId}/timeline` endpoint for each application associated with a particular CRN.
A successful response from the personal timeline endpoint looks like this:
```jsonc
{ // PersonalTimeline
"applications": [
{ // ApplicationTimeline
"id": "00000000-0000-0000-0000-000000000000",
"createdAt": "2024-01-01T12:34:56.789Z",
"status": "started",
"createdBy": { // User
"id": "00000000-0000-0000-0000-000000000000",
"name": "Some User",
"deliusUsername": "SOMEUSER",
"email": "some.user@example.com",
"telephoneNumber": "01234 567890",
"isActive": true,
"region": {
"id": …
```
> [APS-590] Introduce personal timeline endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt
- src/main/resources/static/cas2-api.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
The frontend would like to start sending this query param to this existing endpoint /cas2/applications?prisonCode="AB"
When a prison code is provided to our existing endpoint as a query param, we should now include all application summaries where the user's active case load ID matches the application’s referring prison code.
> CAS2-398 add prisonCode query param

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationDocumentsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationSummaryQueryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTimelinessTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AuthTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedDetailQueryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryQueryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CalendarTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MoveBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAcctAlertsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAdjudicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRiskToSelfTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRoshTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysSectionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysSelectionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOffencesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementMetricsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProblemResponsesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TurnaroundTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
I’ve picked some ‘low hanging fruit’ to migrate to the new InitialiseDatabasePerClassTestBase, where it’s clear there won’t be any issues retaining the database state between tests. These are typically tests where all but one tests are checking calls fail if permisisons are missing.
> Increase use of InitialiseDatabasePerClassTestBase

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
This attempts to fix the occasional issues with Wiremock port collisions due to race conditions by shuffling the list of possible ports, as well as improving the logging so we can see what has happened if / when it goes wrong again.
> (Chore) Attempt to fix Wiremock ports

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
This contains two main changes/fixes:
1. The `findSubmittedCas2ApplicationSummariesCreatedByUser` query was failing when a pageable object was passed in - from debugging the hibernate/sql going on, it looks like it was failing
when trying to do the count query, when there was a LEFT JOIN in place.
This adds a [custom countQuery](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/Query.html#countQuery()) that is much simpler than
the select query. 
I've added in custom `countQueries` wherever I think they could simplify things.
2. Return `latestStatusUpdate` on `findAllCas2ApplicationSummariesByPrison` and `findAllCas2ApplicationSummariesCreatedByUser` - we should return these fields on any query that potentially returns submitted applications
> CAS2-407:  fix status updates

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
The premises tests are probably one of the worst-performing tests in CI. This seperates them out to make them easier to read, as well as sharing some of the database context in some of the tests, which should hopefully shave a minute or so off the total run time 🤞 
There's definitely more scope for improvement here, but I didn't want to sink too much time into it 😅
> (Chore) Tidyup premises tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationDeliveryUnitEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/db/migration/all/20240412134527__add_pdu_id_to_users.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
This PR [CAS-319](https://dsdmoj.atlassian.net/browse/CAS-319) includes:
- Add a new column PDU to the users table
- When the user logged in the portal part of the process is to get the user details from nDelius we will check the PDU assigned to this user. 
- If there is no PDU assigned to the user then it will updated with the PDU from nDelius
- If the user have a PDU but is different from the PDU in nDelius will be updated with the PDU from nDelius
[CAS-319]: https://dsdmoj.atlassian.net/browse/CAS-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAS-319 Check and update user PDU when logging in the portal

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/service/GetAllApprovedPremisesApplicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
This adds a boolean to indicate is an application has any associated placement requests or applications. To test this, I’ve created a placement application and placement request for two applications and added their IDs to a list - `applicationIdsWithRequestsForPlacement`
When validating if a returned summary matches the application, we can then check if the application’s ID is contained in the `applicationIdsWithRequestsForPlacement` list - if it does, we know the expected value should be true, otherwise it’s false.
> (APS-677) Add a `hasRequestsForPlacement` field to an Application

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
https://dsdmoj.atlassian.net/browse/CAS2-410
Previously we had added the `getHdcEligibilityDate` to the ApplicationSummary interface, but not returned the field from the database query. This fixes that issue, and introduces some refactoring that might help us avoid this in future.
> CAS2-410: Return `hdcEligibilityDate` on ApplicationSummary

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
This allows CRU managers to see at a glance what assessments are awaiting information requests from PPs.
> (APS-643) Add an `info_requested` task status

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas2-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
This PR contains the work required for the first bullet point of [CAS2-401](https://dsdmoj.atlassian.net/browse/CAS2-401)
Tasks:
* API: add personName as field to Cas2ApplicationSummary
We currently return for ApplicationSummaries a full Person result, which includes a lot of data, and causes issues with how we handle whether the person has been found/is restricted.
We propose that we follow the standard set for /submissions and just return a personName which will be ‘Unknown’ if person not found or restricted.
This will mean we can then do a bulk search with the CRNs more easily, and just get the person’s name.
[CAS2-401]: https://dsdmoj.atlassian.net/browse/CAS2-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAS2-401 refactor application summaries (add personName)

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
Adds additional Reports API request date validation and updates error details. It now also throws a bad request error if the start date is the same as the end date or the end date is after today's date.
> Reports API date validation

- .circleci/config.yml
- detekt-baseline.xml
- gradle.properties
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserAllocationsEngineTest.kt
This is a grabbag of attempts to _try_ and improve build times. 
I started by changing the gradle.properties (which I think will only help us locally). There's a degree of cargo-culting there (see https://stackoverflow.com/questions/45327617/very-very-slow-gradle-build-on-android-studio), but it all seems to make sense.
I then noticed that the build was running twice, so have attempted to fix that, which shaves about a minute off the build time. I also noticed that the `UserAllocationsTest` had some expensive setup, so have shared the database context there.
> (Chore) Attempt to improve build times

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RequestForPlacementService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RequestForPlacementTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/RequestsForPlacementTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/PlacementApplicationEntityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/PlacementRequestEntityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RequestForPlacementServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RequestForPlacementTransformerTest.kt
> See [APS-587 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-587).
This PR introduces the `GET /applications/{applicationId}/requests-for-placement` and `GET /applications/{applicationId}/requests-for-placement/{requestForPlacementId}` endpoints, which can be used to retrieve a list of requests for placement and a specific request respectively.
These endpoints use the newly-introduced `RequestForPlacement` schema, which provides a unified abstraction over both placement applications and placement requests. In the future both of these will be fully merged into the request for placement concept.
> [APS-587] Add API endpoints for Requests for Placement

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentClarificationNoteTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
A user has reported that once they have made an information request, it's impossible to see what the initial request was. I've added the ability to review it in the assess screen in https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1742, but I think it'll be useful to show this information in the timeline too for audit purposes.
> (APS-691) Return information requests in timeline

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmissionsTransformerTest.kt
Our dashboard for displaying lists of applications to referrers needs the author's name - this PR gets the name from the `nomis_users` table in the sql queries that return `ApplicationSummaries` and adds it to the API model.
Note: the ApplicationSummary is shared across the models on `/applications` and `/submissions` [(we are aware this is a bit of tech debt we need to address) ](https://dsdmoj.atlassian.net/browse/CAS2-325) - the submissions end point does not need to see this author name atm, so I'm not currently returning it in the SubmissionsTransformer.
> CAS2-408: return author's name on ApplicationSummaries

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
This commit splits the createTask into separate private methods for readabiltiy, before adding an additional arg to optional mark as placement requests and placement applications as withdrawn
> APS-695 Exclude withdrawn tasks from pending task count

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingCancelSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1WithdrawPlacementRequestSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeOperationsTest.kt
To address APS-687 we added a seed job to withdraw match requests (placement_requests) via a seed job.
When tested in pre-prod we saw an error sending the email due to:
`Status code: 400 {"errors":[{"error":"BadRequestError","message":"Missing personalisation: withdrawnBy"}],"status_code":400}`
This PR refactors how the Withdrawal Context model to provide a more consistent approach to identifying who or what triggered withdrawal of the entity. This is then subsequently leveraged to ensure we can always a determine a 'withdrawn by' value for withdrawal emails, regardless of whether it was triggered by a user or a seed job.
> APS-687 Withdrawal emails are now sent if triggered by seed jobs

- .circleci/config.yml
When we build the project in the CircleCI build step, we throw away all the generated build info in the `~/.gradle` directory, meaning when we start our test steps, we have to initialise Gradle all over again, adding a couple of minutes to each test step.
This updates the build step to share everything in the `~/.gradle` home directory with the test steps, reducing the amount of time Gradle takes to spin up. We also remove the `checkout` step as we don't need this as the workspace is shared.
Now the build step is more effective, we can increase the number of parallel containers used in our integration tests and this will have more effect as we're spending less time in each container repeating the setup process.
> (Chore) Share workspace more effectively in CI

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
Ref: JIRA ticket [CAS2-413](https://dsdmoj.atlassian.net/browse/CAS2-413)
This PR contains the work required for the third sub task of [CAS2-401](https://dsdmoj.atlassian.net/browse/CAS2-401)
Tasks:
- API: remove the Person field on application summaries and use the bulk search for getMapOfPersonNamesAndCrns to get CRNs
We currently return for ApplicationSummaries a full Person result, which includes a lot of data, and causes issues with how we handle whether the person has been found/is restricted.
We propose that we follow the standard set for /submissions and just return a personName which will be ‘Unknown’ if person not found or restricted.
This will mean we can then do a bulk search with the CRNs more easily, and just get the person’s name.
[CAS2-401]: …
> CAS2-413 remove the person field on application summaries and use bulk search

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationNotesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2MigrateAssessmentsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonOASysRiskToSelfTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonOASysRoshTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonRisksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/JwtAuthHelper.kt
We would like to allow Nomis users with the
'Licence Case Admin' (LICENCE_CA) role to be able
to have READ permissions for CAS2 applications
from their prison.
This change adds the LICENCE_CA role,
alongside POM, to GET requests for `/applications`
The only role-based configuration on the API for
CAS2 is via the
`OAuth2ResourceServerSecurityConfiguration` file -
once users get past this configuration they are
dealt with as Nomis or External Users regardless
of specific role. Therefore I think our current
integration tests should mostly give us confidence
that LICENCE CA should not have elevated
permissions - the same rules affecting POMs (e.g.
won't see applications from other prisons, won't
be able to see content of unsubmitted
applications) will apply, and we can test that
they do …
> CAS2-417: Add Licence Case Admins to CAS2

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/resources/db/migration/all/20240424102921__add_has_domain_event_field_to_assessment_clarification_notes.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentClarificationNoteEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
We will shortly be introducing a proper domain event for when information requests are created. To ensure we don't double up events in the timeline, this adds a `hasDomainEvent` boolean to the `AssessmentClarificationNoteEntity`, which defaults to `false`. We then filter out any entities which has this set to `true`. This will allow us to create new domain events without timelines doubling up, and also will allow us to find all notes which don't have a domain event when we're backfilling.
> (APS-673) Add a has domain event field to clarification notes

- detekt-baseline.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/DomainEventUrlConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventServiceTest.kt
This adds a new `DomainEventUrlConfig` class that allows us to get url templates for a domain event type directly, instead of having to pass them as `@Value` annotated strings in our service classes, which is getting unweildy. It also allows us to easily map domain events to URL templates elsewhere in our code.
> (Chore) Add Configuration class for Domain Event URLs

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1InformationReceivedMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas1InformationReceivedMigrationJobTest.kt
This fetches all info requests with a `hasDomainEvent` of false, creates a domain event and then sets the `hasDomainEvent` value to true
> (APS-673) Add a job to create info request domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ReferralRejectionReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ReferralRejectionReasonTransformer.kt
- src/main/resources/db/migration/all/20240423171511__referral_rejection_reasons_table.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ReferralRejectionReasonEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt
This PR [CAS-340](https://dsdmoj.atlassian.net/browse/CAS-340) is to add and end point for the Referral Rejection Reasons `/reference-data/referral-rejection-reasons` for temporary accommodation
[CAS-340]: https://dsdmoj.atlassian.net/browse/CAS-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAS-340 Add referral rejection reasons Api end point

- detekt-baseline.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1InformationReceivedMigrationJob.kt
We hit a RuntimeException when running this in preprod, because a user doesn’t exist. We want to cleanly recover from this and continue.
I’m hoping that this issue won’t come up in prod, but I want to run this again in preprod and see how many errors we get. If there are only a handful, I think this will be safe to run in prod. If we get any errors in prod, we can note down which ones have come up and decide how to proceed from there.
> Catch RuntimeExceptions in InformationReceived job

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1InformationReceivedMigrationJob.kt
The RuntimeException that gets thrown when we can’t get things upstream is the default Kotlin `RuntimeException`, not the imported Java one
> Catch Kotlin RuntimeException

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ApprovedPremisesApplicationStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/service/GetAllApprovedPremisesApplicationsTest.kt
previously the endpoint only allowed filtering on one status, now multiple statuses can be provided
> APS-727 applications/all supports filtering on statuses

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/listeners/AssessmentListener.kt
- src/main/resources/db/migration/all/20240425143644__update_information_request_statuses.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
We’ve noticed that assessments with a status of `REQUESTED_FURTHER_INFORMATION` were not showing correctly. After some investigation I discovered that the status was getting set, but then immediately being set back to `ASSESSMENT_IN_PROGRESS` with a subsequent update, which is obviously not what we want.
I’ve updated the AssessmentListener to immediately short circuit if the application’s status is `REQUESTED_FURTHER_INFORMATION`, as well as updated the tests to give a more realistic scenario.
I’ve also added a simple SQL query that gets all assessments with pending clarification notes, then updates their associated application’s status to `REQUESTED_FURTHER_INFORMATION`. I could have added a seed job, but this seemed like overkill.
> (APS-643) Set information requested status correctly

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
- src/main/resources/application.yml
We have an issue in production retreiving alerts from the prison API where the response exceeds our limit of 750000. This commit doubles that limit to 1.5MB
> APS-724 Increase web client buffer size

- src/main/resources/application.yml
This is to unblock a production issue for an application with a large number of alerts.
This is a short term fix and paging/limiting results and/or buffering efficiencies should be considered to resolve this correctly. A new endpoint would be needed on probation-integration context if paging/limiting was requried
> APS-724 Increase prison api buffer size

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas3UpdateApplicationOffenderNameJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/CalendarServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
In several places we have an ignoreLao boolean parameter in the code. The intention of this is to indicate that restrictions on viewing LAO offenders can be ignored (otherwise an unathorised access problem will be returned). I often misread this as ‘don’t return offenders with LAO’, which is incorrect. I’ve renamed this variable for clarity
> Rename ignoreLao to ignoreLaoRestrictions

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/PlacementRequestEntityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
> See [APS-707 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-707).
This PR introduces three new ways to sort the results provided by the `GET /tasks` endpoint. Sorting is performed using the `sortBy` and `sortDirection` query parameters. The `sortBy` parameter has been updated by adding new variants to the `TaskSortField` enum defined in the OpenAPI specification:
- `completedAt`
- `taskType`
- `decision`
The corresponding SQL query in the `TaskRepository` has been modified in order to support these new sorting options.
Additionally, a set of integration tests has been introduced to verify that sorting works as expected for both existing and new sort fields in both directions.
> [APS-707] Introduce additional sort fields for `GET /tasks` endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/resources/db/migration/all/20240426124413__add_referral_rejection_reason_id_to_cas3_application.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationAssessmentEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentStateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
This PR [CAS-336](https://dsdmoj.atlassian.net/browse/CAS-336) is to:
- Extend the existing Api end point `/assessments/{assessmentId}/rejection` to accept the temporary accommodation parameters `referralRejectionReasonId` and `isWithdrawn`
- Save the referral assessment rejection reason in the DB
[CAS-336]: https://dsdmoj.atlassian.net/browse/CAS-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAS-336 Capture referral rejection reason for temporary accommodation

- .circleci/config.yml
When we’re running the E2Es against after an API deploy, it’s extremely unlikely any accessibility issues will be found, so let’s add an option to skip these in the API pipeline. I've also added another container to the parallel run, which cuts the runtime further to about 7 minutes in total.
> Speed up CAS3 E2Es

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1DuplicateApplicationSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationDomainEventService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/SeedCas1DuplicateApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationDomainEventServiceTest.kt
Note the following Javadoc provided on the Seed Job Class:
Creates a duplicated version of an existing application, up to the point of submission.
There are limitations to this approach:
1. Depending upon the age of the source application, the JSON data stored in 'data' may not be in the format expected by the latest version of the UI, and as such it may be not be possible to submit the application
2. The index offence event number for the source application must still be active, otherwise delius processing of events will fail
3. Unlike when a new application is created, fresh Risk data will not be retrieved from OASys. It is the user's responsibility to ensure this is up-to-date
Given this, the seed job should be used judiciously and only in situations where it is not …
> APS-725 Add Seed Job to duplicate an application

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/StaffMemberService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/StaffMemberServiceTest.kt
If we can't find a keyworker for a specific booking, we want to fail silently rather than blowing up. As this is still somewhat of an issue, we still want to alert Sentry. Going forward, we'll want to handle when keyworkers leave a premises as well as be able to handle transfers etc.
> (APS-728) Allow a booking to be viewed if key worker no longer at premises

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1DuplicateApplicationSeedJob.kt
This commit reconfigures the Tier API Web Client to allow it to be used for requests originating from seed jobs (i.e. requests that didn’t originate from an API call the CAS API).
This is similar to the change made for Prisons API on commit 3709d82769b1da4917678cb61f68a8262c65e523
> APS-725 Reconfigure Tier Web Client to support seed job

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
APPROVED_PREMISES_REQUEST_FOR_PLACEMENT_CREATED was incorrectly coded as a TimelineEventType.approvedPremisesPlacementApplicationAllocated
> Fix timeline event type for CAS1

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApStaffUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApStaffUsersSeedJobTest.kt
We have a list of 1,248 AP Staff who are set up correctly in Delius. We're going to seed them.
They don't need any internal roles or qualifications. Some of the AP staff being seeding will already 
be present in the service and some of those will have existing Roles and Qualifications.
We need to be confident that we aren't clearing those Roles and Qualifications.
In fact this is why we are introducing the new `ApStaffUsersSeedJob` rather than
using the `UsersSeedJob` -- which does clear those roles and qualifications.
> APS-558: Seed AP staff users

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt
We don't want to provide links to in-progress assessments.
See APS-756: https://dsdmoj.atlassian.net/browse/APS-756
> APS-756: Suppress link to assessment in timeline event for ASSESSMENT_ALLOCATED

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RequestForPlacementService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RequestForPlacementTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/RequestsForPlacementTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RequestForPlacementServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1Cas1WithdrawableServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RequestForPlacementTransformerTest.kt
Currently the code in the Cas1WithdrawalService.isDirectlyWithdrawable function retrieves the complete set of WithdrawableEntities for the whole application, despite only being concerned with WithdrawableEntities for the specific placement request/placement application. This will become a performance issue if/when we start calling external APIs to determine if an entity is withdrawable (as is planned). Before any such change is made we should modify this methods to test against a subset of the tree (i.e. where the root node is placement application/placement request)
> APS-753 add isDirectlyWithdrawable flag to request for placements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
Throw an error if report date range is greater than or equal to the maximum duration in months.
> Update report date range

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt
Update the ‘isDirectlyWithdrawable’ functions to only build a withdrawable tree for the entity of interest, instead of the whole application. This is a pre-requisite to adding in calls to delius to determine booking state, ensuring we don’t make any uneccessary calls
> APS-735 Optimise how we determine if PA/PR withdrawable

- .circleci/config.yml
The CAS1 tests have moved from being a seperate repo to now being housed within the UI repo. 
This PR ensures that the post-merge tests for this repo run from the new location
> Update CAS1 E2E tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2ApplicationsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/SeedCas2ApplicationTest.kt
Ref: https://dsdmoj.atlassian.net/browse/CAS2-380
Soft delete submitted applications once their CRD date has been reached.
Referrer dashboards only.
> CAS2-380 added conditional release date filter

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PrisonReleaseTypeEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PrisonReleaseTypeTransformer.kt
- src/main/resources/db/migration/all/20240503124516__prison_release_types_table.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PrisonReleaseTypeEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt
This [PR CAS-372](https://dsdmoj.atlassian.net/browse/CAS-372) is to add new endpoint to referral data for prison release types. The type for temporary accommodation will be:
- Conditional release date (CRD) licence
- End of custody supervised licence (ECSL)
- Licence, following fixed-term recall
- Licence, following standard recall
- Parole
- Post sentence supervision (PSS)
> CAS-372 Create Api endpoint for types of prison release

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskDeadlineService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TaskDueMigrationJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskDeadlineServiceTest.kt
> See [APS-563 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-563).
This PR makes sure that all applications that are submitted after 1pm on a working day or on a non-working day (weekends or bank holidays) have their effective submission date set to 9am on the next working day before performing the deadline calculation. This prevents time from being effectively lost due to out-of-hours submissions.
This working pattern adjustment is timezone-aware: it correctly accounts for both winter (GMT/UTC) time and summer time (BST/UTC+1), as well as the weekends where the clocks change.
> [APS-563] Account for afternoon and non-working-day submissions in deadline calculations

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskDeadlineService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskDeadlineServiceTest.kt
> See [APS-562 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-562).
The deadline for requests for placement has been identified by users as being too long - the correct timeframe is two working days. This PR implements the correct deadline.
**NB:** this PR is based on the branch for #1835 as it depends on the fixed deadline logic. That PR should be merged before this one.
> [APS-562] Reduce deadline for requests for placement to 2 working days

- .circleci/config.yml
https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1856
attempted to remove the dependency on the Playwright Docker image but
ultimately failed. I couldn't workout how to fully install all the
dependencies needed without using the docker image. This means we will
have to avoid updating the version of Playwright/test in the UI repo
unless we also update the docker image here
> CAS1 E2ES: Reinstate Playwright docker image

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/GroupedDocuments.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DocumentTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DocumentFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DocumentTransformerTest.kt
We have observed rare cases where the community API has returned a document without a name specified.
This commit filters out such documents as we cannot automatically generate a filename without knowing the file extension/type, which is not provided.
> APS-774 filter out docs with null name

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeliusService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DeliusServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeBuilderTest.kt
When building the Cas1 Withdrawable Tree for a placement we now check the status of the placement in delius wrt. arrivals. If the placement has been marked as arrived in delius we ‘block’ the withdrawal as we would if the placement was marked as arrived in CAS1. We also include a specific note in the withdrawal tree indicating that 1 or placements have arrivals marked in delius and as such can’t be withdrawn.
Use of this functionality is controlled by the “cas1-check-delius-withdrawal-status” feature flag, which will return false by default
There is no caching on the delius referrals endpoint that we use to retrieve this data. Caching wouldn’t make sense in this context because we always want the latest state wrt. arrivals. If we find that the endpoint is being invoked too often we could …
> APS-735 Check Placement Arrival Status in Delius on Withdrawal

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeliusService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DeliusServiceTest.kt
There are currently several reasons why a placement may not have a corresponding referral in delius:
* referral did exist in delius but was hard deleted on placement withdrawal
* domain event processing failed (e.g. inactive index offence issue)
In these cases instead of throwing an error when checking if the referral has an arrival, we instead return false
> APS-735 If not in delius, referralHasArrival returns false

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DocumentTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationDocumentsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DocumentTransformerTest.kt
We have found that filtering on conviction ID leads to users not being able to access document they’d like to link to the document. We've used a feature flag so we can disable this is if there are any unforeseen side effects
> APS-524 Don't filter docs on conviction for CAS1

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt
Adds a condition to only include in the bedspace count returned from `premisesSummaryGet` the number of bedspaces with no end date or an end date in the future.
> Only return unarchived bedspace count from getPremisessSummary

- detekt-baseline-main.xml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/AssessmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/StatusUpdateEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas2StatusUpdateMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2ApplicationsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2AutoScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/StatusUpdateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/AssessmentsTransformer.kt
- src/main/resources/db/migration/all/20240509091500__add_status_updates_to_assessments.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas2-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2AssessmentEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2StatusUpdateEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2MigrateStatusUpdatesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/StatusUpdateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/AssessmentsTransformerTest.kt
We previously began some work on CAS2 to introduce the concept of an Assessment - [there's more info in this ADR](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/doc/architecture/decisions/0021-introduce-cas2-assessments.md). 
Having an Assessment concept will allow us to eventually simplify the increasingly complex ApplicationEntity, and allow for some logic on the status of Applications to be decoupled from statuses given by Assessors. [More info on the ticket here](https://dsdmoj.atlassian.net/browse/CAS2-325).
This PR aims to begin work to re-point Status Updates from Applications, to Assessments.
Status Updates are updates given by Assessors on the state of their work on the Assessing side of things. They are more like a record of an event - we keep a list …
> CAS2-326: Add an Assessment to Status Updates

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NomisUserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/NomisUserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NomisUserEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/NomisUserServiceTest.kt
Reverts ministryofjustice/hmpps-approved-premises-api#1858
It seems that though the tests passed we get an error locally:
```
org.springframework.dao.InvalidDataAccessApiUsageException: Modifying queries can only use void or int/Integer as return type! Offending method: public abstract uk.gov.justice.digital.hmpps.approvedpremisesapi.jpa.entity.NomisUserEntity 
```
Though production appears to work with an existing assessor accessing their applications, and we have no new exceptions it must surely be present should a new user be created. This suggests we should role it back quickly to avoid an issue.
The problem itself suggests that the `@modifying` flag must return a void or int, and we return an entity as to avoid having to do another query to find the record. Slightly interesting that …
> Revert "Fix/nomis user create race condition"

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RequestForPlacementTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RequestForPlacementTransformerTest.kt
Previously we used placements on the application as a whole to determine if a placement_application’s status is ‘placementBooked’. This commit fixes that and instead uses the placements associated with the specific placement_application to determine this.
> APS-794 Fix CAS1 Request for Placement PA Status Transform

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
This commit ensures that if the Cas1AutoScript fails to run startup of the service is not blocked, and any changes made to the database are rolled back
> APS-768 Cas1AutoScript shouldn’t block startup on failure

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationSummaryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/StatusUpdateTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/SubmissionsTransformer.kt
- src/main/resources/db/migration/all/20240515100000__create_cas_2_summary_views.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/SubmissionsTransformerTest.kt
Ref: https://dsdmoj.atlassian.net/browse/CAS2-437
TLDR: this PR removes some of the complex and common SQL logic out of the application layer into a database VIEW which can then be used with [JPA query methods](https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html).
The /cas2/applications endpoint is used by the frontend to provision the referrer dashboards.
Recently those dashboards have been extended with new logic such as fetching results by page, prison code and submitted/not submitted. Our approach was to add new query methods with mostly duplicate SQL each time. We knew this wasn’t going to be too sustainable but with national roll out planned we pushed through and compounded the problem.
[We now want to add in another piece of logic to automatically filter out old …
> CAS2-437 move SQL logic to database VIEW

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestEmailServiceTest.kt
This PR ensures that all code sending emails for CAS1 do so via a specialised email service (e.g. Cas1AssessmentEmailService). This simplifies the subsequent changes required to ensure a CRU-specific reply-to email address is used for all CAS1 emails.
> APS-716 CAS1 Email Tidy in preparation for using CRU email address for Reply-To

- src/main/resources/db/migration/all/20240515143555__add_missing_indexes_to_fks.sql
There are several FKs used in reports or hibernate relationships that are not indexed. This commit adds those missing indexes
> APS-791 Add missing indexes for FK columns

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This PR removes two feature flags for features that have been live for over a week without issues:
* cas1-remove-document-conviction-id-filters
* cas1-check-delius-arrival-status-on-withdrawal
> APS-799 Remove feature flags

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/OffenderServiceTest.kt
Can be merged after this Tools update https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/67 ✅ 
And this UI update https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/700 ✅  
And this API update https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1879 ✅ 
_As a POM 
When I try to create an application
With a prison number for a person who is not within my active prison
Then I am not allowed to continue_
This PR checks the inmate detail's `agencyId` against the user's `activeAgencyId`. If they are not within the same prison, then we return an unauthorised error.
More info about when this check is done and where data is from here in Confluence https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4887511138/Integration+APIs+for+o …
> CAS2-465:  Restrict offender search to within the user's active prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/listeners/AssessmentListener.kt
- src/main/resources/db/migration/all/20240515124313__update_incorrect_request_further_information_statuses_where_a_decision_is_made.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentClarificationNoteEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
> See [APS-751 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-751).
This PR fixes the bug introduced in #1805 which prevents any state transition when the current state is `REQUESTED_FURTHER_INFORMATION`. This prevents an update to the assessment from changing the status, but also prevents a decision being made changing the status, which is incorrect.
A test has been introduced that verifies the expected behaviour as outlined in #1805 to make sure that this change does not cause the original bug to reappear.
Additionally, a Flyway migration has been added to update any applications that have been affected by this bug.
> [APS-751] Fix applications getting stuck in the 'further information requested' state when a decision is made while a clarification note is pending

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonalTimelineTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonalTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonalTimelineTransformerTest.kt
- src/test/resources/application-test.yml
> See [APS-798 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-798).
This PR updates the behaviour of the `GET /people/{crn}/timeline` endpoint so that events for both regular applications and offline applications can be retrieved for a given CRN. The `cas1-provide-offline-application-events-in-personal-timeline` [feature flag](doc/architecture/decisions/0022-handling-feature-flags-with-flipt.md) can be used to configure this behaviour: when `false` (by default), the current behaviour of only showing events for regular applications will be applied.
To support this, the `ApplicationTimeline` API schema has been modified so that the `status` and `createdBy` properties are no longer required (as offline applications do not contain this information), and a new …
> [APS-798] Show events associated with offline applications in the personal timeline

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateUsersPduFromCommunityApiMigrationTest.kt
This PR CAS-322 is to get the last Borough that CAS3 users have been assigned in nDelius:
- We check the latest start date for the user in a team. We get the Borough code and we validate to see if this PDU exists in CAS
- We find some situations that the user is assigned multiple teams at the same time. Some of there are regional teams we need to check them to get a valid PDU in CAS
> CAS-322 Migrate CAS3 users PDU from nDelius when the user have more than one team

- doc/how-to/access_database_remotely.md
- script/remote_db
We've known since private beta that a direct connection to the production database is risky. [Recently there was a problem with pre-production data and we wanted to increase friction should anyone be performing writes](https://mojdt.slack.com/archives/C03K0HB0LBE/p1715848495094489).
We update some documentation before making this script put the user into a read-only session by default, rather than read/write.
We give instructions on how to turn it back to write, if that's really needed.
Should the user try a write action by default, on any environment, they'll get the following error:
> Chore/remote db script defaults to read-only in all environments

- script/local_db
We have some documentation on how to use an IDE to help with this[1] however sometimes it is useful to have a raw SQL prompt, in the same way we do on real environments via `script/remote_db`.
This script gets us straight onto the locally running container with a PSQL REPL.
[1] https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4750868858/API+database+reader+Connecting+to+Remote+DBs
> Add a script to help devs directly connect to the local postgres container

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/resources/db/migration/all/20240524103521__remove_duplicated_booking_confirmation.sql
This [PR CAS-385](https://dsdmoj.atlassian.net/browse/CAS-385) is to fix a bug in production when a booking have two confirmation records.
- Will add Transactional around the create confirmation to make sure that it will rollback if its failed
- Remove the duplicated record for the affected booking
> CAS-385 Bookings have duplicated confirmation records

- src/main/resources/db/migration/all/20240528084000__create_live_view.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
Ref: https://dsdmoj.atlassian.net/browse/CAS2-440
**User Story**
As a referrer
I want old applications to disappear from my dashboards
So that they do not clutter up the space
**Description**
This feature will automatically hide applications from dashboards once certain criteria are met. 
**Acceptance Criteria**
API: Soft delete submitted applications once a period of 14 days has elapsed from when the following statuses were applied to them:
- Referral withdrawn
- Referral cancelled
- Awaiting arrival
> CAS2-440 soft delete by status

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/HttpLoggingFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SentryService.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
This is only enabled for local deployments.
If enabled a sentry error will be logged, meaning we’d spot this quickly if the configuration was enabled in any other environment.
Note in the sample log below that we only log application/json responses and not binary responses (in this case, a report file)
```
2024-05-23 12:35:48.729  INFO 56857 --- [nio-8080-exec-4] u.g.j.d.h.a.config.HttpLoggingFilter     : Request  | request.uri=/applications, request.user=JIMSNOWLDAP, request.method=GET, request.pathPattern=/applications, request.serviceName=approved-premises, request.id=7807a750-b333-4efe-a649-70be48dd732e 
2024-05-23 12:35:48.729  INFO 56857 --- [nio-8080-exec-4] u.g.j.d.h.a.config.HttpLoggingFilter     : Response [{"createdByUserId":"aa30f20a-84e3-4baa-bef0-3c9bd51879ad","status":"start …
```
> APS-831 Add ability to log API Request/Response for local deploys

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WiremockManager.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/TestPropertiesInitializer.kt
This PR changes how we assign the port to wiremock to resolve port-clashes we’re seeing when running tests concurrently in the pipeline
1. The port range is no longer limited. Instead we use ServerSocket(0) to offer up any available open port
2. We don’t ‘lock’ the port to the java process once determined (by capturing it in the WiremockPortHolder as an object variable). This avoids issues when there are multiple spring boot contexts within one java process, something which is possible when running multiple spring boot integration tests with differing spring configuration
3. Instead of stopping wiremock after each test, we instead leave it running and instead reset it’s state. Whilst not strictly required because the port is ‘locked’ by the shared file, this ensures the port is also …
> Change how tests allocate wiremock ports

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/LostBedsController.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/LostBedsTest.kt
> See [APS-801 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-801).
This PR introduces the CAS1-specific API specification (cas1-api.yml), starting with the 'lost beds' API endpoints. These new endpoints replicate the behaviour of the existing lost beds endpoints in the `PremisesController` as applied specifically to CAS1.
The configuration for the CAS1-specific spec has the `useTags` property set to `true` to allow for controllers to be decomposed more easily (for example, by default all endpoints starting with `/premises/` would be put into the `PremisesController`).
This PR is the first of a two-stage process to implement APS-801, as removing the CAS1-specific logic from the existing endpoints requires the frontend to make the switch in all environments …
> [APS-801] Introduce `/cas1/` namespace for lost beds endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/AssessmentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationNoteEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas2NoteMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationNoteService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/AssessmentNoteService.kt
- src/main/resources/db/migration/all/20240524130000__add_notes_to_assessments.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas2-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2NoteEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationNotesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2MigrateNotesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationNoteServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/AssessmentNoteServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationNoteTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/TimelineEventsTransformerTest.kt
This PR is the work required to carry out the first part of the task to repoint notes to assessments as described in:
https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4897341539/Associate+Application+Notes+with+Assessments+CAS2-327
**Database**
Since we cannot achieve our desired status in one step since we need to ensure that we don’t break the front end, we need to introduce an interim database schema which we can use to ensure continuity across both the front and back ends.  The interim schema will be:
This means temporarily having both the existing `application_id` field and the new `assessment_id` field in the database until the front end is changed to use a new endpoint.  Swapping the front end functionality so that the `cas_2_assessments.id` to …
> CAS-327 Repoint notes to assessments - part 1

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationDomainEventServiceTest.kt
When a APPROVED_PREMISES_PLACEMENT_APPLICATION_WITHDRAWN domain event is created, capture the corresponding placement application’s id (UUID) in domain event metadata as CAS1_PLACEMENT_APPLICATION_ID
This is required for an efficient JOIN in updated reports
> Added metadata for application withdrawn domain event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/asserter/EmailNotificationAsserter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt
Prior to this commit we were checking for a specific time value in email personalisation, but if the test started and finished in different minutes of the hour this test could fail.
A better solution would be to manage a mutable/fixed clock during integration tests so we can ensure the system clock used in code reports a known date-time, but that is a non-trivial change
> Improve CAS2 Status Update Test Stability

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationSummaryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt
- src/main/resources/db/migration/all/20240528090000__add_abandoned_at_to_cas2_applications.sql
- src/main/resources/db/migration/all/20240528100000__create_cas_2_summary_views_add_abandoned.sql
- src/main/resources/static/cas2-api.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2ApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationAbandonTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt
Given the referrer has an in progress application
When they withdraw the application
Then it will no longer appear on their in progress dashboard
When they try to request, submit or update an abandoned application
Then the service will not permit it
https://dsdmoj.atlassian.net/browse/CAS2-216 
UI PR here: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/727
We want to allow users to flag in progress applications as abandoned. In order to do this we will add an `abandonedAt` value to CAS2 Applications - similar to the `submitted_at` value, this timestamp will determine whether an application has been abandoned or not.
We chose to use the terminology of 'abandoned' because 'withdrawal' or 'cancel' could apply to applications post-submission rather than in …
> Cas2-216: Abandon an in-progress application

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1OutOfServiceBedReasonMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
- src/main/resources/db/migration/all/20240524115141__create_cas1_out_of_service_beds_table.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1OutOfServiceBedEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1OutOfServiceBedReasonEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MigrateCas1OutOfServiceBedsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas1OutOfServiceBedReasonTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas1OutOfServiceBedTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/migration/Cas1OutOfServiceBedReasonMigrationJobTest.kt
> See [APS-805 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-805).
This PR introduces the `cas1_out_of_service_beds` and `cas1_out_of_service_bed_reasons` tables and associated JPA entities as an intended future replacement for the concept of lost beds within CAS1.
Currently, the data models for these are very close to the existing lost beds model, although we expect these that they will diverge significantly as we implement Match and Manage functionality.
A migration job is provided that copies all CAS1-appropriate `lost_bed_reasons` to the `cas1_out_of_service_bed_reasons` table, which will simplify the process of migrating the existing lost beds when it becomes necessary.
> [APS-805] Introduce database model for CAS1 out-of-service beds

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/LostBedsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserServiceUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CapacityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/LostBedsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1FutureManagerUserAccessTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1LegacyManagerUserAccessTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
Jira: [APS-827: Reduce scope of interim "Manage" section](https://dsdmoj.atlassian.net/browse/APS-827)
We are developing some improved and extended features in the 'manage' section
of CAS1. Our needs are to:
1. continue to offer (a subset of) the existing 'manage' features to users in the
North East
2. develop new and improved features in a hidden / feature flagged space to be rolled
out first to the existing manage users in the North East and then nationally.
To support this we introduce two new roles:
This role will have access to a sub-set of the existing manage features:
- ✅ view list of premises (`/premises`)
- view information for particular premises (`/premises/{premisesId}`)
- ✅ view arriving today
- ✅ view departing today
- ✅ view upcoming arrivals
- ✅ view upcoming departures
- …
> APS-827:  Add roles for "legacy" and "future" MANAGE sections

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UpdateEventNumberSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/SeedCasUpdateEventNumberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/DomainEventTestRepository.kt
This commit adds a seed job that can be used to update the event number and associated offence id/conviction id for a given application.
It will also update the event number in any Application Assessed, Application Submitted or Booking Made domain events (these are the only domain events for which probation-integration needs a valid deliusEventNumber value)
This job has been created to allow us to recover from situations where the event number associated with an application do not exist in delius (i.e. they have been deleted in delius). In this case domain event processing in probation-integration will fail. Once the event number has been updated for an application and its associated domain event's, those domain events can be replayed using the Cas1DomainEventReplaySeedJob, and they …
> APS-835 Add Seed Job to Update a CAS1 Application Event Number

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/OutOfServiceBedsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedCancellationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedCancellationTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedReasonTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedTransformer.kt
- src/main/resources/db/migration/all/20240529143616__create_cas1_out_of_service_bed_cancellations_table.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1OutOfServiceBedCancellationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1OutOfServiceBedEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoomEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas1OutOfServiceBedCancellationTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedCancellationTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedReasonTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedTransformerTest.kt
> See [APS-802](https://dsdmoj.atlassian.net/browse/APS-802) and [APS-803](https://dsdmoj.atlassian.net/browse/APS-803) on the Approved Premises Jira board.
This PR introduces API endpoints to view and manipulate out-of-service beds in CAS1. Out-of-service beds are the intended replacement for the current lost beds model and were introduced in #1920.
Currently these endpoints are functionally almost identical to the existing lost beds endpoints, except that logic spread across multiple classes in the service layer have been coalesced into a single `Cas1OutOfServiceBedService`. This provides a way for out-of-service beds to diverge from the existing lost beds model without breaking backwards compatibility.
[APS-802]: https://dsdmoj.atlassian.net/browse/APS-802?atlOrigin=eyJpIjoiNWRkNTljNzYx …
> [APS-802][APS-803] Introduce API endpoints for CAS1 out-of-service beds

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentDomainEventService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentDomainEventServiceTest.kt
Capture the AP Type at the point of initial submission and again, if provided as part of the assessment submission.
assessmentAccepted domain event creation moved from AssessmentService to the Cas1AssessmentDomainEventService.
A new DomainEventEntity MetaDataName added to capture requested AP Type - CAS1_REQUESTED_AP_TYPE
On application submission, the requested AP Type is recorded in the meta data. 
ApType added to AssessmentAcceptance and recorded as part of a APPROVED_PREMISES_APPLIATION_ASSESSED domain event. 
[Link](https://dsdmoj.atlassian.net/browse/APS-823) to ticket
> APS-823 capture application requiredPremisesType on application and assessment submission

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/listeners/ApplicationListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/listeners/AssessmentClarificationNoteListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/listeners/AssessmentListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/listeners/BookingListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
Before this PR we used JPA Listeners to manage updating the application status when a miscellaneous entities were persisted.
Not only does this make comprehension of the code difficult, it technically isn’t allowed according to the JPA Spec, and has caused us issues when attempting to update to Spring 3 / Hibernate 6:
“In general, the lifecycle method of a portable application should not invoke EntityManager or Query operations, access other entity instances, or modify relationships within the same persistence context. A lifecycle callback method may modify the non-relationship state of the entity on which it is invoked.”
This commit calls the Listener components directly as an intermediate step towards using a state machine to manage application state.
As part of this change the order …
> APS-863 Don’t use JPA Callbacks to Update App Status

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateUsersPduFromCommunityApiMigrationTest.kt
This [PR CAS-322 ](https://dsdmoj.atlassian.net/browse/CAS-322) is to improve the migration process to assign to the user a PDU that match the latest active team with a valid PDU in CAS3. In same cases the user have many teams in nDelius not all of them have a valid PDU in CAS3.
> CAS-322 Migrate CAS3 users PDU from nDelius

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/TransitionalAccommodationReferralReportGenerator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
This [PR CAS-391](https://dsdmoj.atlassian.net/browse/CAS-391) is to fix the value shown in the referralRejected column in the report:
- Show **Yes** if the HPT rejected the referral and selected one of the available options
- Show **No** in all other cases
> CAS-391 Fix an issue with referral rejected in referrals report

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ReportsTest.kt
Replaced  CAS1 Report endpoints with a single report endpoint, specified in the CAS1 API spec, which takes the required report as a path parameter (enum).
Original CAS1 Report endpoints have been marked as deprecated.
> APS-850: new CAS1 specific report endpoint to replace existing, multiple report endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
Before this change we would return an unhandled exception as a 500 ‘internal server error’ back to the UI, but not raise an alert in Sentry. This meant we were relying on the UI to raise a Sentry Alert. Not only is this not the correct ownership of responsibility, this meant that we were getting unhelpful alerting information being raised as the UI doesn’t know what caused the error.
This commit ensures all unhandled exceptions are logged in sentry.
> APS-872 Capture internal server errors in sentry

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationAutomaticEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/resources/db/migration/all/20240607130747__create_placement_applications_automatic_table.sql
- src/main/resources/db/migration/all/20240607134906__backfill_legacy_placement_applications_automatic_records.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
For reporting purposes we need to generate a unique UUID for any request for placement that is part of the original application (i.e. where approved_premises_applications.arrival_date is defined)
This will be captured in a new table placement_applications_automatic and backfilled for existing applications which have an arrival_date defined.
> APS-864 Generate unique id on all placement requests

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentDomainEventServiceTest.kt
We were previously using the value of the API type to populate the MetaDataName.CAS1_REQUESTED_AP_TYPE metadata. This is inconsistant with how we capture this value on application submission.
> APS-823 - Use internal enum for CAS1 assess aptype metadata

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/OutOfServiceBedsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PersistedFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
> See [APS-847](https://dsdmoj.atlassian.net/browse/APS-847), [APS-848](https://dsdmoj.atlassian.net/browse/APS-848), and [APS-849](https://dsdmoj.atlassian.net/browse/APS-847) on the Approved Premises Jira board.
This PR introduces several query parameters to the `GET /cas1/out-of-service-beds` API endpoint to refine the results returned:
- `temporality`: If provided, filters the results to only those with the given temporality. This parameter accepts multiple values, e.g. `temporality=past&temporality=current`. The default if not provided is equivalent  to specifying `current` and `future` to maintain backwards compatibility.
- `premisesId`: If provided, filters the results to only those in the premises with the given ID.
- `apAreaId`: If provided, filters the results to only those …
> [APS-847][APS-848][APS-849] Implement filtering, sorting, and pagination for `GET /cas1/out-of-service-beds` API endpoint

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
Trailing slashes are unneccesary and we’ve found these are causing issues after upgrading to spring boot 3
> APS-365 - Remove trailing slashes from test URLs

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
Whilst unlikely, it is technically possible to change dates on the UI by bookmarking the date change page, or constructing the URL manually, as was observed in production. This commit ensures that such changes will be blocked, ensuring the database isn’t in a logically inconsistant state.
> APS-904 Block date changes on cancelled bookings

- helm_deploy/values-dev.yaml
In the dev environment we are seeing a lot of "OutOfMemory" errors
https://ministryofjustice.sentry.io/issues/4087001141/events/c756ea1594044f2c876c7501549d1afe/?environment=dev&project=4503931792392192
17 in the last 24 hours
61 in the 30 days
These are contributing to intermittent E2E test failures.
In this commit I believe we increase:
- memory limit from 1 to 1.5Gi
- request memory from 512Mi to 1Gi
- XMx (max heap) to 1000m
This is based on a previous config change made to the prod env: https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/d72ef2136c811a2ee417d948682569ef502bc695
NOTE
`kubectl top pod` tells us that MEMORY is currently 857Mi
> CHORE: Increase memory in dev env

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserServiceUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
This role will be used for members of the national CRU team. We'll
use it to grant access to
- managing out-of-service bed across all areas / premises
- withdrawing placements
- creating a manual adhoc placement
These are features which live within the "manage" section of the service
but aren't for the use of AP managers or AP staff.
Currently the `WORKFLOW_MANAGER` role has been used for this purpose
but this is confusing an incorrect as `WORKFLOW_MANAGER` is a role
for CRU team members who can (re)allocate tasks: assigning assessors.
We have a new feature "CRU Members views all out of service beds" which
in the UI is being offered to `FUTURE_MANAGER`s via a tile from the homepage.
This should actually be granted to the new `CRU_MEMBER` role. To get there
we'll:
- open this …
> APS-858: Add CRU_MEMBER role

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationStatusUpdatesReport.kt
- src/main/resources/db/migration/all/20240614123435__use_jsonb_for_domain_events_data.sql
The domain_events.data column stores JSON data. We use data stored in this column in a lot of reports, and it has been noted that these reads are causing notable performance hits (e.g. it can add seconds to query execution times).
This commit updates domain_events.data to use the ‘jsonb’ type instead of the ‘json’ type. This should significantly improve read speed, in exchange for a slight performance penalty on inserts. As we typically only insert a handful of domain events per thread of execution, if any at all, this is an acceptable trade off.
See https://dsdmoj.atlassian.net/browse/APS-825 for test evidence. I've ensured that domain events are still processed by probation-integration, and timelines can still be rendered
> APS-825 - Use jsonb for domain_events.data

- src/main/resources/application-local.yml
In dev (and other enviornments) the environment variables are set in values-[env].yml files in the helm_deploy folder. All of these environments (except the deprecated test env) have legacy-allocator-enabled to be false. In order to make local development (via ap-tools) more like other environments I think legacy-allocator-enabled should be false.
Here I also set 'priority' to match other envs.
> Set local allocation rules to match dev

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
- src/main/resources/application.yml
Our new cas1-api.yml is being used to generate Kotlin code and Typecript types but isn't yet available to view via the Swagger UI interface.
This commit provides access via:
https://approved-premises-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html?urls.primaryName=CAS1%20API
> CHORE: Serve up new CAS1 OpenAPI spec via Swagger UI

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/ApAreaMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/ApplicationStatusMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1BackfillUserApArea.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1FixPlacementApplicationLinksJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1OutOfServiceBedReasonMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1ReasonForShortNoticeMetadataMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UserDetailsMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/TaskDueMigrationJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/ApAreaMigrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1ReasonForShortNoticeMetadataMigrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/MigrateCas1FixPlacementApplicationLinksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/MigrateCas1OutOfServiceBedsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/MigrateCas1UserDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/migration/Cas1FixPlacementApplicationLinksJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/migration/Cas1OutOfServiceBedReasonMigrationJobTest.kt
This PR adds a migration job to backfill app reason for short notice and short notice description into metadata.
Whilst we could have used a SQL based migration for this, testing in pre-prod showed this took over 40 seconds to run for each metadata value which would lead to a non-trivial prod outage on deploy (assuming it runs without issue over that length of time).
This PR also moves all the cas1 migration jobs into a cas1 specific package
> APS-853 migration job to backfill app reason for short notice

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1ReasonForShortNoticeMetadataMigrationJob.kt
The migration job could not lazy load metadata associated with a domain event because the domain was being loaded outside of the transaction currently in scope. This commit fixes that by extending the scope of the transaction
> APS-853 - Fix short notice migration job transaction issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
Resolves issue with 'null' appearing as a reason, on the timeline, when a booking is not made and failureDescription has not been populated (is null).
> APS-909 : Handle null failureDescription when booking not made.

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/ClockConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ControllerUtils.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/ApplicationReportProperties.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/util/CsvJdbcResultSetConsumer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/util/ExcelJdbcResultSetConsumer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationJsonSchemaEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesAssessmentJsonSchemaEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseDetailFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MutableClockConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SimpleApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationDomainEventServiceTest.kt
- src/test/resources/application-test.yml
See https://dsdmoj.atlassian.net/browse/APS-854 for a link to a spreadsheet that defines the updated report
This commit provides a rewrite of the CAS1 RAW Applications Data Report, adding and removing several fields and outputting the report as a CSV.
The commit also adds the Cas1SimpleApiClient in an attempt to make tests interacting with the API to setup test data more readable.
Instead of replacing the original report, this report is added as a new version of the original report. This allows us to feature flag the availability of the report on the UI as we’re not currently in a position to backfill required data in production.
> APS-854 - Revise CAS1 Application Raw Data Report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MutableClockConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1RequestForPlacementReportTest.kt
Previously we relied on the open-api default value of ‘false’ for includePii, but testing has shown that this is resolving to true in code.
This commit manages the default values in controllers instead, and updates the reports tests that check PII to ensure the default behaviour is observed
> APS-855 - CAS1 Report PII shouldn’t be returned by default

- src/main/resources/db/migration/all/20240618100000__create_cas_2_summary_views_change_id_type.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
Without the fixes contained in this branch upgrading spring boot and Hibernate results in:
- a JPA class cast exception (since UUID id is cast to TEXT in SQL but then has type UUID in the entity)
- mockkstatic no longer working in the associated CAS 2 integration tests
Adding these features to main now since:
- it will help reduce the number of changes in the forthcoming merge of the upgrade branch
- there is no reason for them not to be merged in beforehand
Note that the new view creation SQL is as per [20240528100000__create_cas_2_summary_views_add_abandoned.sql](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/src/main/resources/db/migration/all/20240528100000__create_cas_2_summary_views_add_abandoned.sql) except `cas_2_application_summary` and it's dependent …
> Cas 365/remove id cast and mockkstatic

- .circleci/config.yml
If an E2E job fails on main in circle ci, we’re seeing the following error when attempting to send an alert to slack
```In order to use the Slack Orb (v4 +), an OAuth token must be present via the SLACK_ACCESS_TOKEN environment variable.```
This commit should resolve the issue by adding the hmpps-common-vars context to the three e2e jobs
> Fix E2E Slack Alerting on Failure

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
For the CAS2ApplicationTest `return unexpired applications when applications GET is requested()` unexpired datetimes should be within the past 14 days and expired datetimes occur more than 14 days in the past.
Before this change: 
```
fun unexpiredDateTime() = OffsetDateTime.now().randomDateTimeBefore() // default 14
fun expiredDateTime() = unexpiredDateTime().minusDays(14)
```
However `unexpiredDateTime()` could feasibly generate a datetime with the same date as today in which case `expiredDateTime()` would generate a datetime 14 days in the past and therefore deemed unexpired.  For example:
If now is 15:30:42 on 21/06/24:
expiredDateTime = "21/06/24 15:30:42" - 14 days
expiredDateTime = "07/06/24 15:30:42"
The `cas_2_application_live_summary` [view SQL …
> Unexpired dates should not be more than 13 days in the past.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ProfileController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/GetUserResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Adds a new /profile/v2 endpoint which provides a more meaningful response in the event that a Staff record, for the logged in user, can't be found in Delius. 
Instead of a 500 response, which the current profile endpoint returns when the staff record can't be found, the new endpoint will return a new response which provides:
- deliusUserName (username / record searched for in Delius)
- loadError (present when the staff record cannot be found)
- user (present when the corresponding record has been found in Delius)
> APS-914 update profile response for non staff members

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CalendarService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/CalendarServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
This is no longer used, as we no longer have the option of using Community API instead of the AP Delius Context when get calling getOffenderSummariesByCrns
> Remove unused ‘forceApDeliusContextApi’ variable

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RequestForPlacementTransformer.kt
- src/main/resources/db/migration/all/20240613080116__add_is_withdrawn_to_placement_application.sql
- src/main/resources/db/migration/all/20240613082914__backfill_withdrawn_placement_applications.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/RequestsForPlacementTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/SeedCas1WithdrawPlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RequestForPlacementTransformerTest.kt
This allows current 'decision' value to be kept when an application is withdrawn rather than being overwritten with a withdrawn decision. 
Backfill script will set the isWithdrawn property on existing records where a withdrawn decision already exists. 
WITHDRAW and WITHDRAWN_BY_PP PlacementApplicationDecision values are marked deprecated in the entity.
**NOTE** : This cannot be merged until APS-893 has gone live.  
APS-893 covers the removal of the two deprecated decisions ('WITHDRAW', 'WITHDRAWN_BY_PP') in the UI. 
Merging this change in prior to the corresponding UI change will result in additional records to be backfilled.
> APS-892 - Added isWithdrawn property to placementApplication entity

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
Without this change upgrading spring and hibernate to later versions causes a SQL exception since we are attempting to update a jsonb field with string data.  Casting to jsonb will resolve this error.  Casting also requires a change to use SQL rather than JPQL.
> CAS-365 cast updatedData as jsonb and change to SQL.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventBuilderTest.kt
This [PR CAS-434](https://dsdmoj.atlassian.net/browse/CAS-434) is to fix an issue for the person departure update domain event to make sure that the event type raised is personDepartureUpdated
Also add checks for the another tests in the Domain Event Builder to assert the type of the domain events
> CAS-434 Fix an issue when calling person departure update domain event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedRevisionEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedRevisionTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/CollectionUtils.kt
- src/main/resources/db/migration/all/20240626154305__create_cas1_out_of_service_bed_revisions_table.sql
- src/main/resources/db/migration/all/20240626154329__migrate_cas1_out_of_service_bed_details_to_new_revisions_table.sql
- src/main/resources/db/migration/all/20240626154404__drop_moved_columns_from_cas1_out_of_service_bed_table.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1OutOfServiceBedEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1OutOfServiceBedRevisionEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas1OutOfServiceBedDetailsTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedRevisionTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedTransformerTest.kt
> See [APS-901](https://dsdmoj.atlassian.net/browse/APS-901) on the Approved Premises Jira board.
This PR introduces a timeline for out-of-service beds such that a complete record of what information has changed, when, and by whom is provided:
```jsonc
{
"id": "00000000-0000-0000-0000-000000000000",
"createdAt": "2024-01-01T12:34:56.789Z",
"outOfServiceFrom": "2024-01-02",
"outOfServiceTo": "2024-01-03",
"bed": { // NamedId
// ...
},
"room": { // NamedId
// ...
},
"premises": { // NamedId
// ...
},
"apArea": { // NamedId
// ...
},
"reason": { // Cas1OutOfServiceBedReason
// ...
},
"referenceNumber": "AB123456",
"notes": "Some notes",
"daysLostCount": 2,
"temporality": "past", // Temporality
"status": "cancelled", // Cas1OutOfServiceBedStatus
"cancellation": { // …
```
> [APS-901] Implement immutable updates and timeline for CAS1 out-of-service beds

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/resources/db/migration/local+dev+test/R__1_create_dev_users.sql
See:
- UI: Addition of `CAS1_E2E_CRU_MEMBER_*` https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1902/commits/1c96a5affd5849ea0929336520ad7d74817085f2 for "Restrict 'View all OOSBs to CRU Member role'"
- AP-Tools: seeding/stubbing of Delius user (`SHEILAHANCOCKNPS`) used for this persona https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/71
> CAS1: Seed Delius user in dev/local envs for testing 'CRU Member' persona/role

- src/main/resources/db/migration/all/20240621101458__cas1_backfill_application_timeliness.sql
This commit provides a SQL migration to populate the approved_premises_application.timeliness value for any application where it isn’t currently set. This is ensure the value is always available in reports.
This value was only populated in the database as-of 2024-03-20. This migration will only update applications where the value is currently null (i.e. from before 2024-03-20).
The logic used to determine the timeliness values matches that used in the UI (noticeTypeFromApplication.ts), which is applied as part of the application submission logic.
> APS-943 Backfill CAS1 Application Timeliness

- src/main/resources/db/migration/all/20240614124559__backfill_cas1-ap-type-metadata-on-app-submission.sql
- src/main/resources/db/migration/all/20240614124560__backfill_cas1-ap-type-metadata-on-assessment.sql
Now this is being via the API, we need to backfill any previously submitted and assessed application metadata
Note - this should only be merged once the corresponding UI functionality (APS-822) has gone live
> APS-853 - Backfill CAS1_REQUESTED_AP_TYPE metadata

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentReferralHistoryNoteTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentReferralHistoryNoteTransformerTest.kt
This [PR CAS-367](https://dsdmoj.atlassian.net/browse/CAS-367) is to return null in message details when the rejection reason is not specified. To cover the scenario for the previous assessments rejected and not show message details for them
> CAS-367 Return null in message details when the rejection reason is not specified

- src/main/resources/static/_shared.yml
The FullPersonInfo and RestrictedPersonInfo types are not used in the API or any UI code.
These are being removed to avoid confusion with new types that we’re going to add to differentiate Person Summary responses
> APS-964 - Remove unused person types

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UpdateNomsNumberSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedUpdateNomsNumberSeedJobTest.kt
This commit adds a seed job that allows us to update the NOMS number associated with a given CRN on applicationa and bookings. This is required when the NOMS number is updated in delius, which is rare, but can happen.
This helps reduce the number of 404 errors we see when the inmate cache is refreshed because we’re removing usage of invalid NOMS numbers.
> APS-978 - Add Update NOMS Number Seed Job

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas3UpdateDomainEventTypeForPersonDepartureUpdatedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateDomainEventTypeForPersonDepartureUpdatedJobTest.kt
This [PR CAS-434](https://dsdmoj.atlassian.net/browse/CAS-434) is to create a job to fix the current person departure domain events with incorrect event type. 
This job will update the event type in the data field for the current domain events from  **accommodation.cas3.person.departed** to **accommodation.cas3.person.departed.updated**
> CAS-434 Fix issue with existing person departure updated domain event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/InmateDetailsCacheRefreshWorker.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/PreemptiveCacheRefresher.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CacheRefreshExclusionsInmateDetailsEntity.kt
- src/main/resources/db/migration/all/20240702113929__create_cache_refresh_exclusions_inmate_details.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/cache/preemptive/InmateDetailsCacheRefreshWorkerTest.kt
When a NOMS number can’t be found in the prisons-api, we receive a 404. If this occurs multiple times when refreshing inmate details in the cache (via InmateDetailsCacheRefreshWorker), we start to receive Sentry errors that this has occurred.
It’s possible that the resolution to the issue (typically Delius or NOMIS having the wrong NOMS number for the CRN) may take days or weeks. In the meantime we no longer need to see the cache refresh warnings, and we should stop attempting to refresh the inmate details as it will fail.
This commit provides a mechanism to exclude NOMS from inmate details cache refresh. Entries can be added to the cache_refresh_exclusions_inmate_details table using SQL
> APS-987 - Add config to exclude NOMS from cache refresh

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BedUtilisationReportData.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedUtilisationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUsageReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/util/Cas3ReportsTestHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt
This [PR CAS-414](https://dsdmoj.atlassian.net/browse/CAS-414) is to fix a performance issue when generate utilisation report in CAS3 for all regions. Which includes:
- Reduce the amount of data retrieved in the report queries by changing it to sql queries 
- Get all the information needed for bedspace, bookings and lost bed space in one query instead of calling the database for each row in the report
- Return only the data related to temporary accommodation which is needed in the report
> CAS-414 Fix performance issue when generate CAS3 utilisation report for all regions

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UpdateNomsNumberSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedUpdateNomsNumberSeedJobTest.kt
This commit updates the seed job to only update applications that have a specified ‘old’ noms number. This can be used to ensure we don’t update applications/bookings that already use the new noms number. Generally updating such applications wouldn’t be an issue, but it would lead to a redundant and confusing application note being added to the application.
> APS-978 - Update Noms Number Seed Job Improvements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/ReferenceDataController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedReasonEntity.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ReferenceDataTest.kt
In this PR we implement a new (and first) reference data endpoint within the `/cas1/` namespace:
```
GET /cas1/reference-data/out-of-service-bed-reasons
```
This will allow us to develop and expose our new `OutOfServiceBedReason`s away from the legacy `LostBedReason`s.
However, we do need to retain our imported legacy `LostBedReason`s to support our data migration. Read on:
We will be migrating `LostBed` records to `OutOfService` bed records. To support this our `OutOfServiceBedReason` entities are seeded from the original `LostBedReason` entities. Importantly this includes the UUIDs to preserve the foreign key relationships (`LostBed.lost_bed_reason_id` == `OutOfServiceBed.out_of_service_bed_reason_id`).
See our [update_cas1_out_of_service_bed_reasons][] "migration_job" which has been …
> APS-956: Expose CAS1 out-of-service bed reasons

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/OutOfServiceBedsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserServiceUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
> See [APS-936 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-936).
This PR introduces the `CAS1_JANITOR` user role and applies it as a prerequisite for a user to access the `POST /premises/{premisesId}/out-of-service-beds/{outOfServiceBedId}/cancellations` endpoint.
This new role is intended to be expanded in future to allow a small number of users various permissions to modify or remove data beyond the capabilities of regular users.
> [APS-936] Introduce `CAS1_JANITOR` user role as prerequisite for out-of-service bed cancellation

- .circleci/config.yml
This is replacing the CAS1 specific approved-premises-team-events
> APS-999 Send slack events to #cas-events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
When a placement is made it is created using the Delius Event Number selected when the corresponding application was first created. At the point of the placement being created this event number may no longer be active. This has led to some user confusion becuase they’re used to seeing contact logs for new referrals in delius against the latest event.
This commit adds the event number a placement was created against to the ‘booking made’ timeline entry, making it easier for users to determine against which event number the placement was created.
> APS-998 - Add event number to CAS1 placement made timline

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BedUtilisationReportData.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedUtilisationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUsageReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/util/Cas3ReportsTestHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt
This [PR CAS-414](https://dsdmoj.atlassian.net/browse/CAS-414) is to fix a performance issue when generate utilisation report in CAS3 for all regions. Which includes:
- Reduce the amount of data retrieved in the report queries by changing it to sql queries 
- Get all the information needed for bedspace, bookings and lost bed space in one query instead of calling the database for each row in the report
- Return only the data related to temporary accommodation which is needed in the report 
- Add integration tests to check the new report queries
> Fix performance issue when generate CAS3 utilisation report for all regions

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
Commit https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/c4b088c11b8fd0269dc3a85f74962a1f1130016a removed the usage of placement_application.decision to store if a request for placement was withdrawn. Due a lack of regression we didn’t capture that this modified the behaviour of the /tasks endpoint as as such it started to return withdrawn requests for placements (because the SQL relied on the withdrawn state being set in the decision).
This commit fixes that logic and adds regression tests to ensure withdrawn requests for placements and assessments are not returned by the endpoint.
> APS-1010 - Don't present withdrawn requests for placement for assessment

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LocalAuthorityAreaEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingDomainEventServiceTest.kt
This PR moves the code that creates a CAS1 Booking Made and Booking Not Made Domains Event into a new Cas1BookingDomainEventService, in preparation for adding metadata to the events.
See ticket for examples of domain events captured locally when testing change
> Move CAS1 BookingMade and NotMade events into DomainEventService

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt
Ref: https://dsdmoj.atlassian.net/browse/CAS2-506
New sub status required to cover scenario when prisoners are transferred to another prison and the referral has to be cancelled titled: "Person transferred to another prison".
> CAS2-506 Add new sub status under Referral Cancelled.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/main/resources/db/migration/all/20240703153901__backfill_cas1_booking_made_event_placement_request_id.sql
- src/main/resources/db/migration/all/20240705104459__backfill_cas1_booking_not_made_event_placement_request_id.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingDomainEventServiceTest.kt
Add Placement Request ID Metadata to Booking Made/Not Made Domain Events, including backfilling existing entries, where possible (see notes in migration files)
> APS-972 - Add Placement Request ID Metadata to Booking Made/Not Made Domain Events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
- src/main/resources/db/migration/all/20240704135216__delete_assessed_request_for_placements_domain_events.sql
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/RequestForPlacementAssessedFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationDomainEventServiceTest.kt
Added arrival date and duration to the domain event to clarify which request the decision is for.
Existing Request For Placement decision (assessed) domain events are cleared from the DB.
Recording this domain event isn't actually live yet so clearing them out is not a problem.
> APS-922 : API - Domain Event for Placement Application Decisions

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/TestPropertiesInitializer.kt
Before this commit a random name was given to the database generated for an integration test. This made it difficult to find the database created for the most recent execution of the integration tests.
This commit shortens the fixed part of the database name and suffixes it with an epoch milli, a number that will always increment. This ensures that the database used for the latest execution of tests will always appear last in the list of the available databases
> Use incrementing num for integration test db name

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
We will be migrating existing LostBed records to the new OutOfServiceBed models. As `LostBed.notes` are nullable we won't enforce the presence of notes on the `OutOfServiceBedRevision` entity yet. Instead we use a validation step within the `OutOfServiceBedService`.
Once the new OOSB system is released and the `LostBed` data has been migrated we can make `OutOfServiceBedRevision.notes` non-nullable
> APS-953: Enforce presence of OutOfServiceBedRevision.notes

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1AutoScriptTest.kt
This commit adds configuration for two new users to test LAO scenarios in CAS1
* LAOFULLACCESS
* LAORESTRICTED
It also adds pre-created applications ready for submission for the following CRNs, both created by LAOFULLACCESS:
* X400000 exclusion for LAOFULLACCESS (whitelist)
* X400001 restricted from LAORESTRICTED (blacklist)
> APS-950 - Add Seeded Applications and users for testing LAO

- renovate.json
Before this commit renovate woud rebase any branch it has created whenever it was behind main by > 1 commit. This leads to many circleci jobs being executed, using up circle resources.
Renovates default configuration for rebasing is:
“It will use behind-base-branch if configured to automerge or repository has been set to require PRs to be up to date”
Where base-branch is
“Renovate will rebase whenever the branch falls 1 or more commit behind its base branch”
This commit changes the rebase strategy to only rebase renovate branches where there is a confluct (i.e. the gradle config has been updated on the main)
For more information, see https://docs.renovatebot.com/configuration-options/#rebasewhen
> Stop renovate constantly rebasing branches

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt
See https://dsdmoj.atlassian.net/browse/APS-1008 for test evidence
Before this change users with the LAO Qualification could not navigate to an LAO application when using the ‘all applications’ screen on the Apply tab.
This commit allows users with the LAO Qualification to view LAO offenders names on the ‘all applications’ screen, and provides a link to click through to the application, as they can do elsewhere in the application.
The previous behaviour was (presumably) in place because the LAO qualification is not sufficient to apply for a new application, and this logic continued to the ‘All Applications’ screen which is also on the Apply Tab. Despite being on the Apply Tab, the all application screen is really a general purpose application search so loosening of restrictions here is …
> APS-1008 - Apply LAO Qualification to CAS1 ‘All Applications’

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DailyMetricsReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementMatchingOutcomesReportTest.kt
The /reports endpoint is deprecated and should no longer be used.
The UI is using the /cas1/reports so this update ensures the tests better reflect usage of the API in prod
> APS-948 Repoint all CAS1 report tests to use /cas1/reports

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
Added original booking information to the description which includes detail about the booked premises and booking start and end dates. 
Added user inputted information text to timeline when reason for cancelling is 'Other' and a text narrative has been added.
> APS-1000: Provide cancelled booking information on Timeline

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
- src/test/resources/application-test.yml
This feature flag is no longer required (the functionality is enabled in all environments)
> APS-967 - Remove offline-application-timeline feature flag

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
Before this commit we would return a BadRequestProblem if we could not determine the user’s region. This was incorrect becuase the fault was not in the request, but instead the issue was don’t know which region to assign the user to. Furthermore, by returning a 400 we were not raising any sentry alerts when this issue happened.
This commit changes such errors to return a RuntimeException (as this should never occur), which leads to a 500 being returned to the caller
> Return 500 if can’t determine user region, not 400

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/Cas1OutOfServiceBedsReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/Cas1OutOfServiceBedReportRow.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1OutOfServiceBedRevisionEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/Cas1OutOfServiceBedReportGeneratorTest.kt
> See [APS-954 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-954).
This PR introduces a new report for out-of-service beds, accessible using the `GET /cas1/reports/outOfServiceBeds` endpoint. This report is functionally almost identical to the existing lost beds report and is intended as a drop-in replacement for the CAS1 use case.
> [APS-954] Introduce out-of-service beds report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeOperationsTest.kt
During investigation of production issues related to withdrawals we’ve noted that it would be very helpful if when showing the CAS1WithdrawableTree in the log we included whether each element in the tree is already withdrawn. This commit captures that information and shows it when rendering the tree to the logs
```
Application(), withdrawn:N, withdrawable:Y, mayDirectlyWithdraw:Y
---> PlacementRequest(), withdrawn:N, withdrawable:N, mayDirectlyWithdraw:N
------> Booking(), withdrawn:N, withdrawable:Y, mayDirectlyWithdraw:N
---> PlacementApplication(), withdrawn:N, withdrawable:N, mayDirectlyWithdraw:N
------> PlacementRequest(), withdrawn:Y, withdrawable:N, mayDirectlyWithdraw:N
---------> Booking(), withdrawn:N, withdrawable:Y, mayDirectlyWithdraw:N
---> PlacementApplication(), …
```
> Show if entity withdrawn in CAS1WithdrawableTree

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
This commit fixes a bug where a ‘RestrictedPerson’ type was returned for an applicaiton’s ‘person’ information when
1. The application related to an LAO offender
2. The user requesting the information had the LAO Qualification (i.e. they had adequate permissions to view the application)
This didn’t make sense because the rest of the application information _was_ being returned, and only the name was being redacted.
Test evidence from local testing is on the ticket - https://dsdmoj.atlassian.net/browse/APS-1052
> CAS1 Provide FullPerson info if can view app

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/NoticeTypeMigrationJob.kt
CAS 365, = null changed to IS null, required for Spring 3.2.
> CAS 365, = null changed to IS null, required for Spring 3.2.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/UnhandledExceptionProblem.kt
Whilst we already alert on unhandled exceptions, we are not alerting when the code explicitly throws an InternalServerErrorProblem or NotImplementedProblem. This commit resolves that.
As part of this change we now throw a new UnhandledExceptionProblem if we can’t handle an exception. This better describes the problem, and avoids the issue of the InternalServerErrorProblem that we used to return being alerted on again by the new code in logInternalServerErrorProblem.
> APS-1073 - Alert on InternalServer & NotImplemented Problems

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
As a pre-requisite to allowing assesors to be assigned tasks, we need to ensure they can view any assigned tasks on the UI without a permissions error ocurring. This commit enables that functionality.
> APS-1067 - Allow  assessor users to list assigned tasks

- src/main/resources/db/migration/all/20240716164234__add-indexes-to-optimise-task-workload-query.sql
This commits adds indexes to ‘task’ types in database to optimise any query that determines which tasks are allocated to a given user. We include ‘reallocated_at’ in this index because this is always checked alongside the allocated_to_user_id (because if reallocated, these tasks are effectively inactive and should be ignored)
> APS-1079 - Add indexes to optimise task workload query

- .circleci/config.yml
- Dockerfile
- build.gradle.kts
A PR to upgrade Java to version 21.  Changes to `build.gradle.kts` and CircleCI `config.yml` file.
Requires an upgrade to bytebuddy to be compatible with Java 21.
> CAS-365 Upgrade Java from 17 to 21.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/AssessmentNoteService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/StatusUpdateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/AssessmentNoteServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/StatusUpdateServiceTest.kt
Change captureException() to captureMessage() results in NotFoundException no longer needed.  See: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1961#discussion_r1662114917
> CA-365 remove inadvertent use of AWS NotFoundException.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/CsvBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1OutOfServiceBedSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/EntityUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1OutOfServiceBedSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
> See [APS-924 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-924).
This PR introduces a new type of seed job (`approved_premises_out_of_service_beds`) that can be used with the `script/run_seed_job` shell script and/or internal `POST /seed` API endpoint. This allows for the seeding of CAS1 out-of-service beds in various states.
As seed jobs operate on a per-row basis, an out-of-service bed is identified by the `premisesId`/`bedId` pair, and determines whether to create a new out-of-service bed or update an existing one based on whether it has already encountered that particular pair.
For example, a CSV describing the below table would create two out-of-service bed records, where one has an update to change the end date, reason, and reference number; and the …
> [APS-924] Introduce seed job for CAS1 out-of-service beds

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RepositoryUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/util/RepositoryUtilsTest.kt
> See [APS-1065 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-1065).
Currently the `GET /cas1/out-of-service-beds` does not always sort as expected. This issue was not caught by unit or integration testing, which tests all sort fields in both ascending and descending order, and in the tests sorting works correctly.
The underlying issue is that the `findAllById` method provided on the `CrudRepository` interface (and by extension, our JPA repositories) explicitly does not guarantee the order of the returned results. The order is therefore dependent entirely on how the results are returned from the database, which may be non-deterministic.
This PR therefore introduces a new utility method to wrap the `findAllById` method while guaranteeing the order of the …
> [FIX][APS-1065] Ensure out-of-service beds always sort correctly

- src/main/resources/db/migration/all/20240719085843__add_placement_application_application_id_index.sql
We have been observing version poor performance from the /applications/all endpoint with high page numbers. This fundamental index was missing. Adding it resolves these performance issues
> APS-1090 Add placement_application -> application_id index

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApprovedPremisesRoomsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApprovedPremisesSeedJob.kt
Existing SQL causes an error when upgrading Spring boot:
`SELECT p FROM PremisesEntity p WHERE ap_code = :apCode AND TYPE(p) = :type
`
Changing to this which resolves the problem:
`SELECT p FROM ApprovedPremisesEntity p WHERE apCode = :apCode`
> CAS-365: Update SQL to use ApprovedPremisesEntity and apCode.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingSearchServiceTest.kt
This [PR CAS-402](https://dsdmoj.atlassian.net/browse/CAS-402) is to fix an issue with the sort by name in bookings for CAS3. This PR:
-  Split the booking search for CAS3 as will include the offender name which is returned from the temporary accommodation application
- The name in the search query will be used to order the bookings when is sorted by name
> Fix an issue with sort by name in CAS3 bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt
In the previous commit 9f4e9d27ddef316f312a30707963a6fdd344a43c we updated the PreemptiveCacheMetadata class to use a custom version of Spring’s HttpMethod that will remain marshallable after upgrading to Spring Boot 3.
This commit also uses this custom HttpMethod in the Redis serialization configuration, which also breaks after the spring boot 3 upgrade.
> CAS-365 - Use custom HttpMethod for Redis Serialization

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateApplicationOffenderNameJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementMatchingOutcomesV2ReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1RequestForPlacementReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
This PR is to make sure that when a call is made to Approved premises and delius endpoints the CRN is provided in uppercase as these endpoints are case sensitive
> Upper case CRN when call Approved-premises-and-delius endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
This being added in preparation for supporting Female APs, allowing us to add it in suitable places on the UI.
This is currently hardcoded to ‘Male’ as only applicants for Male APs are supported. As support for female APs is added this will be derived dynamically.
> APS-1022 - Add CAS1 ‘Gender for AP’ API property

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateApplicationOffenderNameJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementMatchingOutcomesV2ReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1RequestForPlacementReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
This PR is to revert the change to pass upper case CRN when calling Approved-premises-and-delius endpoints. 
The current code is expecting that if the user pass a CRN in lower case it will not return any data. Changing it to pass a CRN in uppercase will associate the data with the lower CRN which may causes some issues.
> Revert Upper case CRN when call Approved-premises-and-delius endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt
This [PR CAS-483](https://dsdmoj.atlassian.net/browse/CAS-483) is to fix in issue in calculate the Actual Nights Stayed to include start date in CAS3 booking report
> Fix an issue in CAS3 Booking report to calculate Actual Nights Stayed

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt
After reviewing the ap-and-delius-context open api spec i’ve found a field that we include in our response model that isn’t provided by the API. This commit deprecates that field to make it clear in the code that it isn’t currently populate whilst we determine what to do about this fields usage
> Deprecate unpopulated ap-delius-context field

- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
We missed the `hateBasedOffences` risk characteristic which we'll use when finding and booking CAS1 spaces
> APS-1068: add missing risk characteristic (CAS1 spaces)

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/OffenderDetailsCacheRefreshWorker.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CaseNotesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAcctAlertsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAdjudicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRiskToSelfTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysRoshTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysSectionsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOASysSelectionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonOffencesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonOASysRiskToSelfTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonOASysRoshTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2PersonRisksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOffender.kt
After this commit we are in the position to remove the cache and the corresponding cache worker
> Deprecate community api getOffender and cache

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/OffenderDetailSummary.kt
OffenderDetailSummary is from the community api model. Instead we should be using [CaseSummary] which is the model provided by ap-and-delius, which has been tailored for CAS usage. Currently we use both which is confusing and duplication of effort.
See APS-1085 for some notes on how to replace usage of this class in some circumstances. Note that OffenderDetailsUtils provides functions to convert between these two types
> Deprecate OffenderDetailSummary

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/OffenderDetailSummary.kt
- src/main/resources/application.yml
Testing in dev has identified that the default buffer size is insufficient when calling the probation offender search api. This commit increases the size of that buffer.
> Increase probation offender search api client

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas3UpdateUsersPduFromCommunityApiJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This commit allows users with the role ASSESSOR to be considered when allocating/reallocating assessments of placement applications by including them in the task’s users list.
This commit also changes permissions on various endpoints required to complete the assessment of a placement application, ensuring users with the ASSESSOR role can access them.
> APS-969 - Allow ASSESSORs to assess placement_applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt
This commit removes repeated use of the same property traversal in PersonTransformer. This helps clarifies the key entities in various result data classes, in preparation for some rationalisation and simplification work, with the ultimate aim of removing data classes bound to the community API
> APS-1085 Improve PersonTransformer readability

- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
When we book a space in an AP it is for a specific type and particular gender, as per `Cas1SpaceBookingRequirements` -- but when searching for available spaces we allow the matcher to search for availability in multiple types of premises and in premises for both genders.
To do this we introduce a `Cas1SpaceSearchRequirements` API model.
> APS-1068: Add Cas1SpaceSearchRequirements API model allow searching for multiple ApTypes and Genders

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
An example captured from dev:
```
uk.gov.justice.digital.hmpps.approvedpremisesapi.problem.InternalServerErrorProblem: Internal Server Error: Unable to get Person Info for CRN: X320742. Response type is class uk.gov.justice.digital.hmpps.approvedpremisesapi.model.PersonInfoResult$NotFound
```
> improve placement requests crn not found error

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/CasSimpleResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationDeliveryUnitEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/UpdateUsersPduFromCommunityApiMigrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This PR adds some regression tests for updating pdu logic, refactors the code to remove duplication and then captures more information when a PDU can't be found to help determine why mapping failed for a given user.
> APS-1106 - Provide more info when a PDU can't be found for a user

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BookingsReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/ReportsTestHelper.kt
BookingsReportData.referralDate previous required an implicit converstion from a timestamptz field in the database to a LocalDate value in the Kotlin Model. This relies on JPA/Hibernate to determine how to convert between these two types (and understand in what timezone this should be applied). As of Hibernate 6 this conversion is no longer supported.
This commit removes this implicit conversion and instead manages the conversion ‘in code’ using the JDK timezone (which is Europe/London on deployment). Regardless of HIbernate compatibility, this results in code that better identifies the type of the database column we are using to provide this data.
I've also updated the integration test to set an application submission date as this would have caused the test to fail on the spring boot 3 …
> CAS-365 - Remove CAS3 Booking Report implicit JPA Timestamp to Date conversion

- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
**NB: This follows on from https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/2120**
---
Now that we have modelled "space characteristics" (a combination
of premises characteristics and room characteristics) and are
using these to make a space booking with lists of:
- `essentialCharacteristics`, and
- `desirableCharacteristics`
It's clear that the more abstract concepts of `needCharacteristics` and
`riskCharacteristics` should be UI concerns only. We are
already intimately involved with these raw space characteristics on
the UI, e.g. in https://github.com/ministryofjustice/approved-premises-ui/blob/7d7041a6a99934b89afc6834928ad4f7eb0fa360/server/utils/placementCriteriaUtils.ts
> APS1068 Search for spaces using space characteristics

- doc/how-to/run_seed_job_remotely.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedCharacteristicsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1RedactAssessmentDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/ApStaffUsersSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedApprovedPremisesBookingCancellationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedApprovedPremisesOfflineApplicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedApprovedPremisesRoomsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedApprovedPremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedAssessmentMoreInfoBugFixTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1ApAreaEmailAddressTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1BookingAdhocPropertyTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1DomainEventReplayTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1DuplicateApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1LinkBookingToPlacementRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1WithdrawPlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCasUpdateEventNumberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/SeedCas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedExternalUsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedNomisUsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedScaffoldingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedTemporaryAccommodationBedspaceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedTemporaryAccommodationPremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedTemporaryAccommodationSmokeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedUpdateNomsNumberSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedUpdateUsersFromApiTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedUsersTest.kt
Before this commit when running a seed job the API required that the ‘.csv’ extension was not included when specifying the filename. This has proven to be counter-intuative and leads to user error.
> Drop implicit ‘.csv’ for seed job execution

- src/main/resources/application.yml
When we have experienced extreme load issues, we’ve found that the default connection pool timeout of 30s is exacerbating the issue as by the time the connection becomes available we’ve had a client timeout/give up, so the request is no longer required.
This commit reduces that timeout to 15 seconds to try to allow clients to fail fast in these circumstances
> Reduce connection pool timeout

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
This [PR CAS-465](https://dsdmoj.atlassian.net/browse/CAS-465) is to use bulk retrieval of person information when there are a group of offenders that need to retrieve their person information. This will improve the performance of the code and reduce the number of calls to `/probation-cases/summaries` Api end point
- Create a new function `getInfoForPersons` to get a bulk of person information and use it instead of the current `getInfoForPerson` function in case there are a group of offenders. This function will call `getOffenderSummariesByCrns` to unify the point to get offenders information.
- Change the current `getInfoForPerson` to use the new function
- Replace the code when currently call the old function to use the new one when there are a group of offenders that need to retrieve …
> Change to use bulk retrieval of person information when there a group of offenders

- src/main/resources/application.yml
We have observed under load that we’re running out of connections. Enabling leak detection will help us close in on threads that are retaining the connection for an unexpected amount of time.
We’re currently setting this quite high (20 seconds), over time we can reduce this
Example log output. We can use the thread id to find more information in app insights:
```
2024-08-02 14:35:09.455  WARN 7610 --- [l-1 housekeeper] com.zaxxer.hikari.pool.ProxyLeakTask     : Connection leak detection triggered for org.postgresql.jdbc.PgConnection@488279d3 on thread http-nio-8080-exec-2, stack trace follows |  
java.lang.Exception: Apparent connection leak detected
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
at …
```
> APS-1129 - Add connection pool leak detection

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderDetailsDataSource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
This is a temporary solution to make the reason for 400 failures from probation integration more opaque. Ideally this should never occur, and if it does, we should instead call the bulk endpoint multiple times
> CAS-465 Return 500 if bulk requesting info on > 500 crns

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/SpaceSearchController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1SpaceSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceSearchResultsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/CollectionUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceSearchResultsTransformerTest.kt
> See [APS-1093 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-1093).
This PR introduces the ability for users to be able to search for available spaces in Approved Premises. A search is performed by `POST`ing to the `/cas1/spaces/search` endpoint with a request body like:
```json
{
"startDate": "2024-07-22",
"durationInDays": 84,
"targetPostcodeDistrict": "SE5",
"requirements": {
"apTypes": [
"normal",
],
"spaceCharacteristics": [
"single"
],
"genders": [
"male"
]
}
}
```
To which the API will respond with a list of candidate premises matching the search criteria and their availability, which looks like:
```json
{
"searchCriteria": {
"startDate": "2024-07-22",
"durationInDays": 84,
"targetPostcodeDistrict": "SE5",
"requirements": {
"apTypes": [
"normal",
], …
```
> [APS-1093] Implement `POST /cas1/spaces/search` endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ProfileController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/UpdateAllUsersFromCommunityApiJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/GetUserResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UpdateUsersFromApiSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApStaffUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserCaseSensitivityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedUsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
This PR fixes some edge cases with how /profile/v2 behaves:
* If a call to /profile/v2 leads to an existing user being updated and the Delius staff record doesn't exist, a loadError will be returned instead of a 500 status code
* If a call to /profile/v2 leads to a user record being created, an update was immediately attempted as UserService was not setting createdOnGet to true on the GetUserResponse response. This PR corrects that behaviour
This PR also replaces the GetUserResponse data class with a sealed hierarchy, forcing callers to deal with the StaffRecordNotFound outcome, and deprecates various functionality to try and reduce complexity in UserService
> /profile/v2 return LoadError if user update attempted and staff record not found

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/InmateDetailsCacheRefreshWorker.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/OffenderDetailsCacheRefreshWorker.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/PreemptiveCacheRefresher.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/cache/preemptive/InmateDetailsCacheRefreshWorkerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/cache/preemptive/OffenderDetailsCacheRefreshWorkerTest.kt
Analyse of cache misses in production suggests that the refresh worker is stopping prematurely due to redis lock timeouts. This results in an indeterminate number of entries in the cache never being updated by the worker, resulting in user requests being slow as these trigger cache updates instead.
This commit helps address these issues as follows:
1. Adds logging and a sentry alert when the refresh worker ends premature. This includes information to help determine what an optimal lock timeout would be
2. Sorts the noms numbers to refresh randomly to ensure that even if the worker ends prematurely, we’re not just refreshing the same batch of noms numbers (this assumes the SQL query returns them in a consistnet order, that is indeterminate)
3. Adds a log when the inmate cache refresh …
> APS-1151 - InmateDetails Cache Refresh Improvements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
Before this commit we would throw an error if any offenders being retrieved for the CRU Dashboard couldn’t be found, or are restricted.
This led to issues viewing the CRU Dashboard in pre-prod where Delius is not often refreshed, despite us taking regular copies of the CAS database.
This commit changes the CRU Dashboard endpoint to instead return the FullPerson sealed types for NotFound/Restricted, which are handled as expected on the UI (e.g. not clickable links)
Before:
After:
> APS-1152 - Show NotFound/Restricted Offender on CRU Dashboard

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/PreemptiveCacheRefresher.kt
- src/main/resources/application.yml
We’re observing that the cache lock duration is currently insufficient to refresh the entire cache.
This commit increases it from 2 minutes to 10 minutes to help us determine how long will be required once the cache state has normalised (i.e. fully refreshed).
The downside of a longer lock is that no other instance will be able to pick up the cache refresh work if the worker unexpectedly dies. Given that the cache being 100% up to date is not mission critical, a maximum delay of 10 minutes before the refresh worker starts again should not be an issue.
> APS-1151 - Increase pre-emptive cache lock duration

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RequestResponseLoggingFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/UserVersionFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonalTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Add a 'version' property to the user response which is a hash of a the permission properties on a user's record. 
Add RequestResponseLoggingFilter which adds a header, X-Cas-User-Version, to all CAS 1 Api responses which is a version hash for the user making the request. 
The intention is that the UI recognises the change in the version value of the  logged in user, against the value returned in the API call and looks to fetch the updated user record (with updated permissions)
> APS-1117 : user version

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/InmateDetailsCacheRefreshWorker.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/WebClientCache.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PreemptiveCacheTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DatesTest.kt
**Increase cache refresh lock to 30 minutes**
This commit decreases the sleep when a cache entry doesn’t need refreshing from 50ms to 25ms. Presumably the sleep was adding to protect overloading prison api, which isn’t required if we don’t refresh a record
The thinking behind setting the lock to 30 minutes:
* After each check we sleep a minimum of 25ms, or 50ms if a call to prison api is made
* There are 29958 cache records in production
* Assuming every entry needs refreshing that is a minimum of 25 minutes, without considering overhead of calling prison api.
* Note that lock timeout is only required to ensure another instance picks up the work if this instance crashes, so it should really be set to a value higher than how long we think it will typically take
**Improve stat logging for …
> APS-1151 - Cache Refresh Worker Enhancements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
We have observed that either due to a bug or a backup/restore issue in pre-prod, users can have the same role assigned multiple times. Whilst this issue is mostly prevelant in pre-prod, there is a single occurance of this in prod too. This can be checked by running
select u.id, u.name, r.role, count(r.role)
from user_role_assignments r
inner join users u on u.id = r.user_id
group by u.id, u.name, r.role
having count(r.role) > 1;
This commit updates the removeRoleFromUser to remove all ocurrances of the roles recorded against a user.
> APS-1089 - RemoveRole should remove duplicates

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1DuplicateApplicationSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
This commit renames two functions on OffenderService:
* getInfoForPerson -> getPersonInfoResult
* getInfoForPersons -> getPersonInfoResults
This seems trivial, but these functions now reflect the name of the class they return which are already confusing enough in their genericness! It helps disambiguate from functions that return PersonInfoSummaryResults (Which will be better named in a subsequent commit)
> Rename getInfoForPerson to getPersonInfoResult

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
Ensure that duplicates are removed from the user's role list and the list is sorted before calculating user version to ensure consistent responses. 
Uppercase Delius username when executing query to retrieve roles by username.
> APS-117: Normalise user roles list before calculating user version

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt
- src/main/resources/static/api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
This has been superseded by the /applications/{applicationId}/requests-for-placement endpoint
> APS-1011 - Remove /applications/{id}/placement-applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApOASysContextApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CaseNotesClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/GovUKBankHolidaysApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/HMPPSTierApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ManageUsersApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/NomisUserRolesApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ProbationOffenderSearchApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/ThrowableUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PreemptiveCacheTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WiremockManager.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/client/BaseHMPPSClientPreemptiveCacheTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/client/BaseHMPPSClientRetryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/resources/application-test.yml
If API requests fail with a connection error (other than timeout) or with 500, 501, 502 or 503, the API client will now retry the request 1 additional time.
This helps work around stale connection errors we’ve observed in production where an idle connection in the netty connection pool has (presumably) been timed out by the target server. Given how intermittent this issue is in production,  a retry should, with luck, provide us with a working connection.
The error we’ve been seeing is “Connection prematurely closed BEFORE response; nested exception is reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response”. A specific integration test has been added for this scenario.
> APS-1149 - Add retries to API calls

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CacheService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/client/BaseHMPPSClientPreemptiveCacheTest.kt
This commit completes the removal of the offender details cache now that is has been cleared in production.
As part of this work I had to update the PreemptiveCacheTest to use the prisonsApiWebClient and the communityApiWebClient no longer has a pre-emptive cache configured
> APS-1155 Remove offenderDetails Cache

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt
- src/main/resources/db/migration/all/20240807112608__add_domain_event_schema_version_column.sql
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingCancelledFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
Before this commit, the CAS1 booking cancelled domain event details did not provide:
1. The date (and only the date) of when the cancellation occurred
2. The datetime of when the cancellation was recorded
The domain event did provide a datetime for when the cancellation occurred, but the time was always set to midnight UTC. This is currently being used by probation-integration services to set the time the contact occurred. This has resulted in two issues:
1. The cancellation appears to happen at either midnight or 1am, depending on the current daylight savings
2. If multiple cancellations happen for the same CRN in the same day, due to limitations in contact recorded only one contact is seen (despite referrals being correctly deleted in Delius).
This commit introduces the values mentoned …
> APS-1134 - Add fields to CAS1 booking cancelled domain event

- src/main/resources/static/domain-events-api.yml
In commit e80e1e3 we introduced some additional mandatory fields to the CAS1 booking cancelled event.
This leads to an error when rendering an application timeline that includes ‘legacy’ CAS1 booking cancelled events. In this case we see an error beacuse the new mandatory fields are not in the legacy event JSON.
This commit provides a short term fix for the issue by making the new CAS1 event fields optional so we can still unmarshall legacy event JSON for the timeline.
Note that these _are_ mandatory on the receiver and will always be populated by the API so once we have a proper fix in place to deal with legacy domain event schemas on the timeline we should revert this change.
> APS-1134 Fix timeline bug for legacy cas1 booking cancelled events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/client/BaseHMPPSClientRetryTest.kt
ba71b6e990f51a60434c193fee1fb34ed2ff912f introduces retrying calls to API calls.
The intention was to only retry on specific status codes, but due to a combination of bad retry logic and a bad test, the code was retrying for all status codes. This commit fixes that.
> APS-1149 Only retry specific status codes

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/resources/db/migration/all/20240808140000__add_pdu_id_column.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Ref: CAS-438, https://dsdmoj.atlassian.net/browse/CAS-438
As a part of the CAS-307: Capture PP's PDU and other core information in referral from Delius work, we are now planning to record and save the ID of the probation delivery unit (PDU).
In ticket CAS-366: FE: Implement new user journey in FE with pre-populated nDelius data the form will now return the PDU id as first class field called probationDeliveryUnitId. This needs to be saved into the db alongside the name of the PDU (determinable via the existing probation_delivery_units table).
Create a new probation_delivery_unit_id field and save the value returned from the UI probationDeliveryUnitId in it.
> Cas 438 persist pdu id to applications table

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingRequirementsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/db/migration/all/20240731111858__create_cas1_space_booking_table.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequirementsEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingRequirementsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
> See [APS-1094 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-1094).
This PR implements the `POST /cas1/placement-requests/{placementRequestId}/space-bookings` API endpoint introduced in #2077, which allows a user to create a new booking for a space in an Approved Premises.
A new booking is created by `POST`ing to the endpoint with a request body like:
```jsonc
{ // NewCas1SpaceBooking
"arrivalDate": "2024-09-01",
"departureDate": "2024-09-30",
"premisesId": "00000000-0000-0000-0000-000000000000",
"placementRequestId": "00000000-0000-0000-0000-000000000000",
"requirements": { // Cas1SpaceBookingRequirements
"apType": "pipe",
"gender": "female",
"essentialCharacteristics": [
// Cas1SpaceCharacteristic
// ...
],
"desirableCharacteristics": [
// …
```
> [APS-1094] Implement API endpoint for creating a new CAS1 space booking

- src/main/resources/db/migration/all/20240812103000__create_cas_2_summary_views_make_32_days.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AppealEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ArrivalEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CancellationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ConfirmationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ExtensionEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LostBedCancellationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NonArrivalEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenderDetailsSummaryFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationOffenderDetailFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TurnaroundEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3BookingCancelledEventDetailsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3PersonArrivedEventDetailsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas3/Cas3UpdateDomainEventTypeForPersonDepartureUpdatedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TestBookingSearchResult.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RandomData.kt
Ref: https://dsdmoj.atlassian.net/browse/CAS2-505
Applications where the status is withdrawn, cancelled or awaiting arrival and created greater than 32 days in the past can be excluded from the applications list (previously 14 days).
VIEW recreated with 32 day INTERVAL period (previously 14).  This VIEW replaces the one created in [20240618100000__create_cas_2_summary_views_change_id_type.sql](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/src/main/resources/db/migration/all/20240618100000__create_cas_2_summary_views_change_id_type.sql).
Tests updated so that valid/unexpired dates are within the past 32 days (previously 14) and expired times are at least 33 days in the past.
> CAS2-505 Change soft delete period from 14 to 32 days.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/MDCHandlerInterceptor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
The MDCHandlerInterceptor only required access to the delius username, but the function it used to access this on UserService was loading the whole user from the database, triggering 3 SQL queries.
This was also operating outside of our exception handler, meaning we weren’t returning a 503 if we had database connection issues.
> APS-1180 - The MDC Filter was unnecessarily loading the user

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1SpaceSearchRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
> See [APS-1159 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-1159).
This PR formalises the behaviour of the CAS1 space search endpoint according to the document linked in https://dsdmoj.atlassian.net/browse/APS-1159.
This is done by introducing integration tests for each specific type of filter:
- A test for AP gender has been introduced, but is `@Disabled`, as currently CAS1 only supports APs for male offenders and the filter currently has no effect.
- A test for AP type and a test for multiple AP types has been introduced. This already behaves as expected except for an issue with `"MHAP"` not deserialising to an `ApprovedPremisesType` value - this has been altered to use `ApprovedPremisesType.MHAP_ST_JOSEPHS` as the exact MHAP information is not currently …
> [APS-1159] Iterate on CAS1 space search filtering

- build.gradle.kts
A recent change broke importing the gradle config into a fresh intellij project (because in this cases there is no directly in invoked task). This commit fixes that issue.
> Fix gradle intellij import issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/OutOfServiceBedsController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
Going forward we will not maintain the concept of a booking being assigned to a bed. Therefore, we should not check for such conflicts when updating an out of service bed (OOSB). Note that this is already the case when creating an OOSB.
This change is required to avoid unexpected errors in production related to bookings that _have_ been allocated to a bed in the legacy version of match and manage.
> APS-1193 - OOSB update shouldn’t check for booking conflicts

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/LostBedsController.kt
- src/main/resources/static/cas1-api.yml
These have been replaced by the out-of-service-beds endpoints.
> APS-801 Deprecate CAS1 lost-beds endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentTransformerTest.kt
Ref: https://dsdmoj.atlassian.net/browse/CAS-412
In order to display PDUs for referrals list, and sort those lists by PDUs, the GET /assessments API endpoint needs to:
- Return the PDU name alongside the existing data for each referral (this should be the PDU of the application)
- Enable new sort field by PDU (alphabetical sort on PDU name)
> CAS-412 return pdu and enable sort by pdu

- doc/how-to/modifying_domain_event_schemas.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/DailyMetricsReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingCancelledFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DailyMetricsReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/config/ClientResultRedisSerializerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/DailyMetricsReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1RedactAssessmentDetailsSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventWorkerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonSchemaServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/JsonSchemaServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/ObjectMapperFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Cas1DomainEventsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DomainEventHelpers.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/TimeExtensions.kt
This PR will adapt the V1 JSON persisted for a APPROVED_PREMISES_BOOKING_CANCELLED domain event to be compatible V2 JSON schema on-the-fly, whenever the domain event JSON is required. This adaption will add the two attributes ‘cancellationRecordedAt’ and ‘cancelledAtDate’
This is required for the following scenarios:
1. When loading domain event details to render on the timeline (in the DomainEventDescriber)
2. When probation-integration retrieves the domain event json via the API
This change allows us to revert the short term fix introduced by https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/ed66ab01ddc5d54705132cb9db43bb28d8befb38, which made the cancellationRecordedAt and cancelledAtDate attributes in the domain event schema optional to allow us to deserialize …
> APS -1134 - Map CAS1 Booking Cancelled Event json v1 to v2 on-the-fly

- helm_deploy/values-preprod.yaml
This [PR CAS-451](https://dsdmoj.atlassian.net/browse/CAS-451) is to set Java heap memory to match prod configuration
> CAS-451 Setting Java heap memory to match prod configuration

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
Ensures that the query to get out of service beds will always return the most recent record / revision for a bed and apply temporalities correctly.
> APS-1197: Update query for finding oos beds

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
Ensures that the query will ignore out of service bed records which have been cancelled and only return those out of service bed records which are still active.
> APS-1192: Update query for finding oos beds

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/SpaceBookingController.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
‘statuses’ are not considering in filtering, sorting or in the body of the response. These will be added in a subsequent iteration.
> APS-1214 - Add CAS1 API to list space bookings for premises

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/assessmentservice/AcceptAssessmentTest.kt
We have observed issues in production where a user clicks on the ‘reallocate’ button multiple times for a given task if the backend is being slow to respond. This results in multiple copies of the assessment being created in the backend.
Whilst we have double click protection on the reallocate button this has a debounce setting of 1 second, so doesn’t block users from click the button multiple times over a longer period.
Previously we’ve used Optimistic Locking to solve these issues (i.e. @Version attribute on Entities). Whilst this helps us ensure the database is consistent (i.e. we don’t end up with multiple assessments) this will result in a generic assessment being returned to the user, and an alert being raised in sentry. A pessmistic lock acquired before reallocation results in a …
> APS-1171 Acquire lock when allocating assessments

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
When migrating to spring boot 3 hibernate 6 is struggling to generate a count query for the out of service beds query. This commit explicitly defines a count query to work around this issue
> CAS-365 - Add explicit count query for OOSB

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
This [PR CAS-547](https://dsdmoj.atlassian.net/browse/CAS-547) is to remove the crn parameter from the assessment end point as it was replaced by the new parameter crnOrName
> CAS-547 Remove crn parameter from assessment api endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ValidationErrors.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/AuthorisableActionResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/ValidatableActionResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/EntityUtils.kt
CasResult should be used in instead of these types, simplifying both the production and handling of Service Results
> Deprecate ActionResult types

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PageCriteriaFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
When checking for out of service bed conflicts we were consider _all_ revision dates for related out of service bed record. This commit changes the logic to only consider the latest revision for a relation out of service bed record.
A similar fix to a different query was made via https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/01b63d5cf9fe0bf0acbcf4921f5fa26c724fb943
> CAS1 OOSB conflict check defect fix

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BedSearchController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
This [PR CAS-464](https://dsdmoj.atlassian.net/browse/CAS-464) is to extend the current bedspace search to include filtering results by the following property attributes:
- Shared Property
- Single Occupancy
The change made is to create a CTE to return the premises Ids that match the filtering criteria. 
I added another condition in the where condition for Shared Property and Single Occupancy to include the properties that they don't have property attributes.
> CAS-464 Extend bedspace search to include property attributes

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/db/migration/all/20240830155841__add_colomns_to_cas1_space_booking.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
application id will be required for manual bookings (i.e. those not linked to a placement_request)
key worker name is required to support filtering in queries
> Add columns to cas1_space_bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderDetailsDataSource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/ClientResultFailureArgumentsProvider.kt
There are several functions in OffenderService that can be used to retrieve offender details whilst also considering Limited Access Restrictions.
All of these functions have at least one of the following issues:
* Makes use of or returns community-api types (deprecated), instead of types provided by ap-and-delius-context
* Retrieves user access information even if the caller indicates that restrictions should be ignored via the ignoreLaoRestrictions boolean arg
* Uses the now deprecated OffenderDetailsDataSource, which adds an additional layer of complexity and obfuscation. This indirection  is no longer required as we’re not switching between community-api and ap-and-delius-context for offender information. This typically also leads to code that maps from the ap-and-delius-context types …
> Add definitive function to retrieve offender details

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
This [PR CAS-586](https://dsdmoj.atlassian.net/browse/CAS-586) is to fix an issues in bookings tabs. 
The issue happened when there are multiple bookings with the same arrival or departure dates and there are greater than the search result page size. Order by start/end dates asc/desc will result in: 
- Bookings are not showing in the bookings tab as expected
- Booking is showing multiple times in different pages
The PageRequest start returning duplicated booking or miss a booking in the search result. 
To fix this issue I change the booking sort to support sorting by multiple columns. And change the booking results to sort by start/end date and then by offender name this make sure that the search result don't show the booking in different pages and show all the bookings expected in the …
> CAS-586 Fix issues in booking tabs

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DestinationProviderEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/JsonSchemaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LocalAuthorityAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/MoveOnCategoryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PostCodeDistrictEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationAreaProbationRegionMappingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationDeliveryUnitEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationRegionEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ReferralRejectionReasonEntity.kt
- src/main/resources/application.yml
- src/main/resources/hibernate-ehcache.xml
- src/test/resources/application-test.yml
This commit enables an in-memory (i.e. per container) second level hibernate cache.
This cache has only been applied to read-only reference data that is managed via the flyway schema migrations. This ensures that the cache will always be correct because a change in migration would come via a new release (all containers would be restarted, flushing the caches).
Note that this cache is managed by Hibernate, and is not linked to Spring’s Redis cache that we use for various function-level caches. This was a deliberate choice to keep this initial implementation simple.
All caches share the same default settings. For reference, this is show many rows exist in production for each cached entity:
ap_areas - 7
cancellation_reasons -  22
cas1_out_of_service_bed_reasons - 7
characteristics - 66 …
> APS-1122 - Spring Boot 3 - Use 2nd Level Cache for Ref Data Entities

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Add users summary endpoint. This endpoint is identical to /users, but it returns a light weight response, meaning no additional SQL queries are requried for each user in the list.
After implementing /users/summaries it was observed that we were making two additional database calls for each user being listed due to eager loading. This commit converts these relationships to be lazy loaded
> APS-1230 - Add endpoint to get user summaries and lazy load user relationships

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ForbiddenProblem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremiseServiceTest.kt
This is similar to the existing /premises/{premisesId}/summary, but only returns the fields currently being shown on the CAS1 premises UI (i.e. it doesn’t include bookings, which will instead be provided by /premises/{premisesId}/space-bookings)
> APS-1268 - Add CAS1 specific premises summary endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TurnaroundTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This [PR CAS-379](https://dsdmoj.atlassian.net/browse/CAS-379) is to allow the value of zero days for turnaround when:
- Create/update a property
- Change the turnaround for a booking
It will return the same validation message type isNotAPositiveInteger when the value of turnaround days is negative integer
> CAS-379 CAS3 allow turnaround to be zero

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BedSearchController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
This [PR CAS-464](https://dsdmoj.atlassian.net/browse/CAS-464) is to extend the  bedspace search Api endpoint to accept a list of property and bedspace attributes for filtering. The current values will be:
-  sharedProperty
- singleOccupancy
> CAS-464 extend bedspace search to receive a list of attributes

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEventSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt
- src/main/resources/application.yml
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationTimelineTransformerTest.kt
Whilst we reuse the same APPROVED_PREMISES_BOOKING_MADE domain event for space bookings, we are populating the domain_events.cas1_space_booking_Id instead of domain_events.cas1_booking_Id to allow us to easily differentiate between the two types when rendering the timeline
This commit also adds a cas1SpaceBooking timeline url type to allow the UI to differentiate between legacy bookings and cas 1 space bookings when linking to the corresponding view placement page
The screenshot below shows how a legacy booking and a cas1 space booking appear on the timeline. Note that view placement link for CAS1 space booking is incomplete. This requires a change in the UI to recognise the new URL type (via APS-1268)
> APS-1244 - Create Booking Made Domain Event for CAS1 Space Bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Change to authorisation for task reallocation on CAS1 requests.
The check is now for presence of the permission CAS1_VIEW_MANAGE_TASKS rather than the role CAS1_WORKFLOW_MANAGER. 
The CAS1_VIEW_MANAGE_TASKS permission has been added to the CAS1_WORKFLOW_MANAGER role.
> APS-1029:  Change to authorisation for task reallocation on CAS1 requests.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
If the user who created a request for placement on the application did not originally created the application, they should also receive a booking made email
> APS-1264 - send placement request booking email to placement request creator

- src/main/resources/application.yml
previously this was set to 30 seconds. given our API client timeout is also 30 seconds, this meant that we’d typically timeout the client before timing out calls to case notes. this commit changes the prison-api timeout to 25 seconds to ensure it will timeout before timing out the client
> decrease case-notes-api client timeout

- src/main/resources/db/migration/all/20240909111543__harmonise_out_of_service_bed_reasons_across_all_envs.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ReferenceDataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/MigrateCas1OutOfServiceBedReasonsTest.kt
Before this commit the cas1_out_of_service_bed_reasons reference data was populated using the update_cas1_out_of_service_bed_reasons migration job, which copied the data from the lost beds reasons table.
This is awkward when testing locally because we have to remember to run the migration job step.
This commits adds a migration script that populates the update_cas1_out_of_service_bed_reasons, where they don’t already exist. This will have no affect on environments where this data is already populated (e.g. prod, preprod, dev)
> APS-1274 Harmonise OOSB Reasons across environments

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/NotFoundResourceProblem.kt
We currently receive Sentry Alerts for NoResourceFoundException errors because our custom exception handler doesn’t know how to deal with this exception (note, this exception has only started appearing since upgrading to spring boot 3).
This PR adds exception handling for NoResourceFoundException, ensuring we no longer receive sentry alerts for these issues. Note that a WARN is still logged.
> APS-1285 Add exception handler for NoResourceFoundException

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BedSearchController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationDeliveryUnitEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BedSearchResultTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationBedSearchResultFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
This [PR CAS-463](https://dsdmoj.atlassian.net/browse/CAS-463) is to extend the current functionality of bedspace search to be a able to search bedspaces in up to 5 Pdus. We need to maintain the current functionality by allowing to pass the Pdu name util the UI work is done. Changes are:
- Maintain the current property `probationDeliveryUnit` and make it not required as it will be replaced with a new parameter `probationDeliveryUnits` that  will allow to pass a list of Pdus (this property will be removed after the UI work is done)
- New property `probationDeliveryUnits` which allow to pass a list of Pdu Ids (this will be changed to required after the UI work is done)
- Include the PDU information for each bedspace in the search results response
> CAS-463 Extend bedsearch to search up to 5 PDUs

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
a change was made on https://github.com/ministryofjustice/hmpps-approved-premises-api/commit/e8c803178839a27feec829a36edc2ecd803b1c95 to sending booking emails to placement request creators, if it’s a different user to the application creator. This change did not work because it assumed the relationship between booking and placement request was populated when the code was called, which was not the case.
This commit reworks the functionality in Cas1BookingEmailService, updating the function to be explicitly provided with the placement request (PlacementApplicationEntity). It also adds an integration test for this scenario.
> APS-1264 send booking made email to pr creator

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Prior to this commit roles were used to determine if various CAS1 entities could be withdrawn. We now use permissions
This commit also adds the ability for JANITOR and CRU_MEMBER to withdrawal all entity types.
> CAS1 - Add ability to withdraw all entities to JANITOR and CRU_MEMBER

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
This change limits viewing reports to the CAS1_REPORT_VIEWER role by introducing a CAS1_REPORTS_VIEW permission
> APS-9191 Only CAS1_REPORT_VIEWER can view CAS1 reports

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt
This commit also:
* Refactors the getPremiseSummary code to use a transformer to map from the entity model into the API Model
* Makes all fields on Cas1PremiseSummary mandatory
> APS-1259 - Add AP Area to Cas1PremiseSummary API Model

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
SAR discovery (via github discovery) needs access to /v2/api-docs. This commit allows access to this endpoint without authentication
> Allow access to any api-docs

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedUsageRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt
This [PR CAS-589](https://dsdmoj.atlassian.net/browse/CAS-598) is to fix an issue when generate the bedspace usage report for all regions. It reduce the number of bedspaces to include only bedspaces for temporary accommodation service and filter it by region
> CAS-598 Fix issue to generate bedspace usage report for all regions

- src/main/resources/application.yml
The default URL configurations in application.yml should match those used for local deployments.
> APS-1294 Use correct default ap-and-delius-context config

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
This commit ensure that booking withdrawn emails for a given request for placement are sent to the person who created that request for placement, if not the same as the application’s creator.
> APS-1288 - Send booking withdrawn email to placement app creator

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/db/migration/all/20240911103906__add_cancellation_columns_to_cas1_space_booking.sql
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This PR also excludes cancelled space bookings when listing placements for a premises
> APS-1286 - Add cancellation fields to space booking data model

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/PreemptiveCacheRefresher.kt
- src/main/resources/application-local.yml
Before this commit the PreemptiveCacheRefresher would start cache refresh threads as soon as soon as it was constructed. This would lead to the cache refreshers starting their work before the spring application was ready to handle requests.
Issues with this approach have been noted in dev where we seed data during spring startup, leading to potential deadlocks on the database.
Furthermore, these threads don’t need to start ASAP, and should really wait until spring is ready.
This commit ensures the cache refreshers once spring has fully started
> Start Cache Refresher once spring has started

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingDomainEventServiceTest.kt
The goal of this PR is to extract the create booking withdrawn domain event logic from the booking service into the Cas1BookingDomainEventService, and refactor it to allow for the logic to be re-used for space bookings
> APS-1286 Refactor CAS1 booking withdrawn domain event logic in preparation for space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
Correct wording on validation error message when creating a booking from a placement request
> APS-1279: Correct wording on validation error message

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/resources/db/migration/local+dev+test/20240913092812__remove_unused_test_users.sql
- src/main/resources/db/migration/local+dev+test/R__1_create_dev_users.sql
Overtime we have collated several test users are deployed to local environments (and sometimes also dev/test).
This commit removes all test users that are not currently used for either manual or automated testing.
This commit removes these users completely (deletes them)
bernard.beaks
panesar.jaspal
These users will not be added to any new environment:
SHEILAHANCOCKNPS
APPROVEDPREMISESTESTUSER
CAS-LOAD-TESTER
> Remove unused test users

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/UserVersionFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This header is included alongside the X-CAS-User-Version header to support the UI detecting and handling user configuration changes.
To get the user id we had to use a slightly more ‘clunky’ bit of SQL that results in more code needed to interpret the results, but this ensures we’ll always get the user id even if the user has no roles set.
> Add X-CAS-User-ID Header for CAS1

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
As the /cas1/premises/{premiseId} endpoint is going to be used for premise summaries, we need to ensure that all roles that access this page have the neccessary permissions
> APS-1335 - Assign CAS1_PREMISES_VIEW_SUMMARY to relevant role

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BookingsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingSearchServiceTest.kt
This [PR CAS-545](https://dsdmoj.atlassian.net/browse/CAS-545) is to extend the booking search to be enabled to search by name or crn. This includes:
- Extend the current Api end point to have a `crnOrName` new parameter. The current parameter `crn` will be removed from the endpoint when the UI work is done
- When search by CRN should match the search term. In case of name can be full/partial match.
- Refactor the code by removing the ApprovedPremises service related code as it not longer be use by the service
> CAS-545 Extend bookings Api to search bookings by name or CRN

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
This [PR CAS-635](https://dsdmoj.atlassian.net/browse/CAS-635) is to add order by the following order (pdu name, premises name and bedsapce name) by alphabetical order to the bedspace search results.
Also refactor integration tests.
> CAS-635 Extend bedspace search to return ordered results

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
We have observed issues in production where a user clicks on the ‘reallocate’ button multiple times for a given task if the backend is being slow to respond. This results in multiple copies of the assessment being created in the backend.
Whilst we have double click protection on the reallocate button this has a debounce setting of 1 second, so doesn’t block users from click the button multiple times over a longer period.
Previously we’ve used Optimistic Locking to solve these issues (i.e. @Version attribute on Entities). Whilst this helps us ensure the database is consistent (i.e. we don’t end up with multiple assessments) this will result in a generic assessment being returned to the user, and an alert being raised in sentry. A pessimistic lock acquired before reallocation results in a …
> APS-1173 - Acquire lock when allocating placement apps

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
This [PR CAS-640](https://dsdmoj.atlassian.net/browse/CAS-640) is to make premises notes nullable in temporary accommodation bedspace search result
> CAS-640 Make premises notes nullable in bedspace search result

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/resources/db/migration/all/20240919144438__link_cas1_application_to_cru_management_area.sql
- src/main/resources/db/migration/all/20240919144714__backfill_cas1_application_cru_management_area.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This PR adds a new 'default_cru1_management_area_id' column to approved_premises_application
Initially this will always be derived from the AP Area's default Management Area. In subsequent commits we will use the ‘Women’s Estate’ Management Area if the application is for a female.
This PR also backfills the management area for any submitted applications.
> APS-1315 Capture CRU Management Area on Application Submission

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/PreemptiveCacheRefresher.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/NoOpSentryService.kt
- src/test/resources/application-test.yml
This isn’t required for testing and creates quite a bit of noise when the database is being reset at the same point in the time the refresh job runs.
> Disable pre-emptive cache refresh during tests

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/ApStaffUsersSeedJobTest.kt
The Class Name didn’t match the filename which meant the tests weren’t being ran in circle.
The build should have been broken as the tests weren’t using the correct error message. This has now been fixed.
> Fix ApStaffUsersSeedJobTest class name

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/resources/db/migration/all/20240923113600__add_cru_management_fields_to_user.sql
- src/main/resources/db/migration/all/20240923152108__backfill_user_cru_management_area.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedRevisionTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This PR adds two new fields to the users table:
* cas1_cru_management_area_id
* cas1_cru_management_area_override_id
The former will always be updated when ap area is updated, using the ap areas default management area value.
This commit also backfills the cas1_cru_management_area_id value for existing users.
The latter will be configurable via an API call to be added in a subsquent commit.
> APS-1314 Add CRU Management Area to user

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BookingsController.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
This [PR CAS-637](https://dsdmoj.atlassian.net/browse/CAS-637) is to remove the `crn` parameter from booking api endpoint as it was replaced by `crnOrName` parameter
> CAS-637 Remove CRN from booking Api endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1346
We have several endpoints that allow filtering of results on AP Area ID. These need updating to support filtering on CRU Management Area ID instead. The option to filter on AP Area ID should be deprecated in favour of CRU Management Area
This PR updates `PlacementRequestsController.placementRequestsDashboardGet` (tested by `PlacementRequestsTest.Dashboard`). In the SQL this will work by filtering on the CRU Management Area linked to the application i.e. (`approved_premises_applications.cas1_cru_management_area_id`).
This is a back end change only and does not require any change to the front end (for now).  Therefore although we are passing `apAreaId` to the API, we are doing a SQL search joining on `cruManagementAreaId`.
Note that for AP …
> APS-1346 Filter by CRU management area id.

- src/test/resources/application-test.yml
Before this commit endpoint caching was enabled during integration tests. I think this was leading to failures  depending upon test execution order
> Disable caching during integration tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/api.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/StaffUserDetailsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
This PR copies existing functionality from the shared /users endpoint to /cas1/users. Specifically:
* get user by id
* delete user - only used by CAS1
* update user - only used by CAS1
This is in preparation for changes to the update user endpoint. It allows us to simplify the implementation logic, and also explicitly state the ApprovedPremiseUser type in the response
A ticket has been created to remove delete user/update user from the shared endpoint once the ui is using the new endpoints - APS-1363
> APS-1314 Add CAS1 Users Endpoints

- build.gradle.kts
This commit adds .env file support to the gradle bootRun task. This will help us simplify configuration of upstream URLs and credentials in ap-tools by allowing the same env file to be used by gradle or docker based API resources
> Add .env file support to boot run

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1349
Change tasks GET to filter by CRU management area id as well as AP area id, (until the front end is switched over to use the CRU management area id at which point the AP area join can be removed).
We have several endpoints that allow filtering of results on AP Area ID. These will need updating to support filtering on CRU Management Area ID instead. The option to filter on AP Area ID should be deprecated in favour of CRU Management Area.
This PR updates TasksController.tasksGet (tested by TasksTest). We only need to support this when filtering on assessments and placement applications (don’t add this for placement requests filtering - this is deprecated and will most likely be removed at some point). In the SQL this will work by filtering …
> APS-1349 Add filter by CRU management area id.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
Changed functionality for filters when retrieving space bookings : 
- Added 'historic' filter -  only departed bookings are returned (presence of actual departure date). 
- Removed exclusion of departed bookings, previously these were not included in the resulting data set.
> APS-1365 : Modify Space Booking residency filters

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3BookingGapReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ProbationRegionTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/CAS-541
Initial work to generate a bookings gap report.
There is no requirement for this to become a downloadable report as yet.  The scope of the ticket was to generate an initial first pass of a booking gap report which we can pass to the HPT team to get some feedback.  An integration test has been added however if this report is to become a formal report accesses via the UI additional test coverage will be required (along with unit tests).
The report is a list of gap ranges for each room, of every premises, in every region for all dates.  Each row contains the details of a single gap, showing the date when the gap occurred (inclusive dates).  The report also contains the number of days the room was empty (calculated from the gap date range) and …
> CAS-541 Booking gap report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOutOfServiceBed.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
Before this commit the code populating the ‘outOfServiceBedsCount’ when viewing a premise considered any out of service bed record linked to the premise regardless of the start and end date as ‘current’.
> Fix bed count for cas1 premise summary

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApprovedPremisesUserFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonalTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementMatchingOutcomesV2ReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1CruManagementArea.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApArea.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
This commit adds CRU Management Area fields to the ApprovedPremisesUser API Model to support:
* Determining which CRU Management Area the user is in (when retrieved via /profile/v2)
* Logic to determine/set/get override configuration for the user management page
This commit is quite large because i had fix existing test data where entries in the users table were created for CAS1 testing and the CRU Management Area was not set, something which wouldn’t be the case in production (it’s logically mandatory for CAS1 users)
> APS-1314 - Return User's CRU Management Area details in the API

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/SchedulingConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/scheduled/Cas1ExpiredApplicationsScheduledJob.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1UsersTest.kt
- src/test/resources/application-test.yml
This commits adds a spring-based scheduled task that makes use of a redis-based distributed lock to ensure that task only runs on one instance of the application.
This is being added as a basic check that the distributed lock acts as expected in our deployment environments.
> Add simple scheduled task with distributed lock

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1CruManagementAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1CruManagementAreaSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
- src/main/resources/db/migration/all/20240927144633__add_auto_allocation_field_to_cru_management_area.sql
- src/main/resources/db/migration/dev+test/R__9_cas1_cru_management_areas.sql
- src/main/resources/db/migration/local/R__4_cas1_cru_management_areas.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1CruManagementAreaEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1CruManagementAreaTest.kt
This commit adds an ‘assessmentAutoAllocationUsername’ property the Cas1CruManagementAreaEntity, to be used for auto allocation. This field isn’t currently in use, this will follow in a subsequent commit.
This commit also adds a seed job that can be used to update a CRU Managment Areas email and auto allocation configuration.
The default values for assessmentAutoAllocationUsername in local/dev/test are set to match their helm equivalents
> APS-1345 - Add auto allocation config to CRU Management Area (2)

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/resources/db/migration/local/R__4_cas1_cru_management_areas.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1AutoScriptTest.kt
This commit adds default roles to the CRUWOMENSESTATE user for local deployments. It also overrides their CRU Management Area to be the women’s estate management area, and sets them as the auto allocation user for assessments
> APS-1234 - Seed Women’s Estate Test User in local environment

- src/main/resources/db/migration/local+dev+test/R__1_create_dev_users.sql
Without this we get errors when trying to view the users page
> APS-1345 - Ensure seed test users have cru management area set

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa.specification/UserSpecifications.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
We need to enhance GET `/users` as follows:
- add an optional filter on `users.cas1_cru_management_area_id`. This will be similar to the existing `ap_area_id` which should be deprecate in favour of this filter
- ~~add an additional field in the response providing the id and name of the user’s `Cas1CruManagementAreaEntity`. This should already be available ‘for free’ as it has already been added to the ApprovedPremisesUser API type.~~ This has already been done.
> APS-1350 add cru filter to users list

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SnsDomainEventListener.kt
This commits sets the lowest possible poll timeout on the SQS listener used during integration tests to minimise waiting when the spring context shutdowns at the end of tests.
> Configure IT SQS Listener to optomise shutdown

- script/remote_db_tunnel
I’ve found that intermittently the port forward port isn’t immediately availbale after creation. This commit adds a small sleep before creating the optional CLI connection to avoid connection issues
> Improve remote_db_tunnel stability

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1344
If the feature flag `cas1-womens-estate-enabled` is true and `isWomensApplication` is set to true on submission of the application, set `application.cas1_cru_management_area_id `to the ‘Women’s Estate' entry. 
To do this we can use the hardcoded UUID already in the `Cas1CruManagementAreaEntity`:
```
companion object {
val WOMENS_ESTATE_ID = UUID.fromString("bfb04c2a-1954-4512-803d-164f7fcf252c")
}
```
This change will be done in ApplicationService.submitApprovedPremisesApplication
This new test is as per the existing test `Submit standard application does not auto allocate the assessment, sends emails and raises domain events` but with:
- `isWomensApplication = true` in the submission post
- mocking the feature flag …
> APS-1344 Set CRU Management area to Womens Estate if isWomensApplication is true.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt
To ensure consistency with the existing, non-namespaced endpoint the following have been added to the new, namespaced endpoint: 
- filtering by area. Added optional `apAreaId`  query parameter
- bed count is returned in the summary data.  This is a 'live' bed count for the given premises, how many beds the premises has live at the time,  and not an 'available' bed count which would incorporate booking data ( i.e. live beds - booked beds).
There is only one consumer of the new summary query.   The data returned by the query has been changed to retrieve only that needed rather than complete premises records.  This was primarily due to the need for bed count, which is calculated when the query is executed, rather than being data persisted in the records themselves.
> APS-1418: Update Cas1 Premises Summary endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
Whilst space bookings cannot currently be directly withdrawn on the UI, they can be withdrawn indirectly by withdrawing the associated application.
This leads to a domain event entry for space booking withdrawal but the timeline describer trys to render this using a regular booking entity, which fails because a regular booking with that ID doesn’t exist.
This PR adds a simple timeline description for space booking withdrawal to resolve the error. This will be replaced with a complete message in a subsequent commit.
> APS-1286 Add simple timeline description for space bookings

- build.gradle.kts
previously if the env var value had an ‘=‘ symbol we weren’t correctly reading the full value
> Tighten up ENV VAR reading logic

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApprovedPremisesSeedJob.kt
Amended the seed service job which makes changes to existing Approved Premises records, to update the Gender field.
> APS-1289: Updated seed job to recognise gender change in AP

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1394
Changed access from users with role CAS1_WORKFLOW_MANAGER to those who have CAS1_VIEW_CRU_DASHBOARD permission.
> APS-1394 Throw error if user does not have correct permission

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
Before this commit if a user had cruManagementAreaOverride set, the value of user.cruManagementArea was reverted to the default value whenever a user was updated from delius, essentially removing the override.
> Don’t revert CRU Management Area on user update

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
This is required by the CAS1 UI to support filtering and showing the CRU Management Area for users that tasks can be assigned to
> APS-1442 - Add CRU Management Area to UserWithWorkload

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ProfileController.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
The CAS1 UI will update its view of the user by calling /profile/v2 whenever a change in the user’s hash is detected (via the X-CAS-User-Version header). When this update is required, there is no need to invoke delius to check for any other updates, because the change in the version header indicates that our persisted user is already up to date.
This commit adds a ‘readOnly’ option to /profile/v2 that will supress any attempts to update the user from delius. This will help us avoid getting into ‘infinite update loops’ if we consider a field updated from delius in the X-CAS-User-Version header, and that field’s value is constantly changing.
> APS-1444 Add ‘read only’ option to /profile/v2

- build.gradle.kts
We currently use bootRunLocal to start the API from ap-tools. This task hardcodes the spring profile being used to ‘local’. To support running tests against upstream services, we want to be able to run against the ‘dev’ profile. Therefore, this commit introduces a new ‘bootRunDebug’ task that is identical to ‘bootRunLocal’ but removes the hardcoded profile.
The calling ap-tools code already sets the active profile in the env var, so this will not breaking existing behaviour
> APS-1362 - Add bootRunDebug task, removing hardcoded profile

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/FutureBookingsReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/TransitionalAccommodationReferralReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/util/ReportingUtils.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BedSearchResultTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/OffenderDetailsUtils.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
This [PR CAS-474](https://dsdmoj.atlassian.net/browse/CAS-474) is to extend the response of the bedsearch Api endpoint for temporary accommodation to include the following details for the other occupants booked into the property at that time:
- Name
- Sex
- Assessment Id
> CAS-474 Extend bedspace search api response to include more offender details

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt
This [PR CAS-643](https://dsdmoj.atlassian.net/browse/CAS-643) is to use  getPersonSummaryInfoResults instead of getOffenderSummariesByCrns to get offender details
> Change future bookings report to use getPersonSummaryInfoResults

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
Ref: [https://dsdmoj.atlassian.net/browse/APS-1400](https://dsdmoj.atlassian.net/browse/APS-1400)
`Cas1SpaceBookingType` is returned from `/premises/{premisesId}/space-bookings/{bookingId}`; request for placement id is required by the UI.
> Add request for placement Id to Cas1SpaceBooking type.

- applicationinsights.json
This PR forms part of [API-1357](https://dsdmoj.atlassian.net/jira/software/c/projects/APS/boards/1328?selectedIssue=APS-1375), reviewing our usage of app insights (which is larrrrrge!)
I have updated the app insight config to not track redis, as there seems little business need for this
I have also reduced the sampling for the health and info endpoint to 5%, as [per this guidance](https://docs.google.com/document/d/1uG7Ne1_B2RwgREI-iMXHVnyQfuIQykDVfMQ1k-h-xHk/edit)
> remove redis tracking from app insights

- helm_deploy/values-dev.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedOnStartupService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EnvironmentService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1AutoScriptTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/SeedOnStartupServiceTest.kt
This commits adds logic to CAS1 auto seeding to ensure that the required users for e2e tests in the test/dev environments exist on startup, when running in test/dev environments. This works by using the spring profile name.
It also ensures all test users are assigned all available qualifications, reflecting the current configuration.
Whilst this change helps ensure the dev/test environments are correctly configured, it also simplifies running tests locally against upstream services in dev
> APS-1362 Auto Seed Test Users for test/dev environments

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpaceBookingDayPlanner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpaceBookingDayPlannerResultRenderer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpaceBookingPlanningModels.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpaceBookingDayPlannerTest.kt
This PR adds a SpaceBookingDayPlanner service. Given a list of rooms and space bookings, this will attempt to optimally assign a a space booking to each room, where possible.
Subsequent commits will make use of this planner to plan occupancy over a period of time for a given premise, which will then be used for occupancy calculation
> APS-1448 - Add Space Booking Day Planner Logic

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingRequirementsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/db/migration/all/20241028103820__add_criteria_to_space_booking.sql
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingRequirementsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
Before this commit a space bookings ‘essential’ and ‘desirable’ criteria were derived from its associated placement request requirements.
This commit
1. Add persistence of ‘essential’ criteria on the space booking entity (just named ‘criteria’), populating this from the space booking creation POST
2. Populating the space booking ‘essential’ criteria from the space booking entity when returning a space booking (instead of the placement request)
3. Deprecates the ‘desirable’ criteria when creating a space booking, and no longer populating it when returning a space booking. This will be removed by a subsequent commit.
> APS-1446 - Capture criteria on space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/asserter/DomainEventAsserter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
This PR implements Space Booking Timeline for Match and Manage V2
Changes included in this PR :
- Updated CAS1 API to return list of timeline events
- Added getTimeline function to cas1 domain event service 
- Updated timeline query to incorporate spaceBookingId parameter
> APS-1241: Implement Space Booking Timeline M&M V2

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
This [PR CAS-480](https://dsdmoj.atlassian.net/browse/CAS-480) is to change the way that bedspaces are filtering by wheelchair. It changes to filter bedspaces with rooms have wheelchair attribute instead of properties with wheelchair attribute
> CAS-480 Filter bedspaces which have room wheelchair attribute

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
This PR CAS-1207 is to fix an issue showing overlap people staying in a bedspace when their bookings was cancelled
> Fix an issue showing overlap people staying in a bedspace when their bookings was cancelled

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentReferralHistoryNoteTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentReferralHistoryNoteTransformerTest.kt
This [PR CAS-440](https://dsdmoj.atlassian.net/browse/CAS-440) is to change to return data domain as json instead of string
> CAS-440 Change to return data domain as json instead of string

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/DomainEventUrlConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DomainEventsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/application.yml
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingKeyWorkerAssignedFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Cas1DomainEventsFactory.kt
- src/test/resources/application-test.yml
Adds domain event when assigning a keyworker to a booking
Adds the domain event to the API
Adds a keyworker assigned timeline event
Adds a domain event describer to provide required timeline narrative when a keyworker has been assigned to a booking
> APS-1368: Create a domain event when keyworker is assigned to a booking M&M V2

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
This [PR CAS-600](https://dsdmoj.atlassian.net/browse/CAS-600) is to ignore case sensitivity when HPTs search by CRN in referrals and bookings
> CAS-600 Ignore case when HPTs search by CRN

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ProfileController.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
This has been superceded by /profile/v2, which is now used by both CAS1 and CAS3
> Remove /profile endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/db/migration/all/20241104104349__add_delius_event_number_to_space_booking.sql
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This commit persists a delius_event_number to the cas1_space_bookings table.
Whilst each booking logically must have a delius_event_number, there are a non-trivial number of bookings created via offline_applications where the event number is not known, and without a corresponding APPROVED_PREMISES_BOOKING_MADE domain event to derive this from. For this reason, the new column is optional.
> APS-1486 - Add DeliusEventNumber to SpaceBooking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
All usernames are stored in upper case in the database, so when retrieving users we should user an uppercase username.
This is no automated regression test for this as it’s alot of work to create the scenario, and any regression would be highlighted when attempting to seed bookings
> APS-1447 - Fix username resolution seeding space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
Whilst cas1_space_bookings.delius_event_number is nullable and domain events require a non-null value, we will guarantee that this is always set to a value for any space bookings that has not already occurred.
APS-1488 will be used to manage backfilling this value when migrating from bookings to space bookings
> APS-1486 - Use space booking event no. for domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingRequirementsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingRequirementsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This commit removes all fields from Cas1SpaceBookingRequirements other than essentialCharacteristics, as none of the other fields were used when creating a space booking, or used by the UI when returning a space booking.
It also updates the transformer logic to derive essential requirements from the space booking itself, instead of the placement request.
> APS-1492 - Simplify Cas1SpaceBookingRequirements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/db/migration/all/20241105112719__make_space_booking_placement_request_nullable.sql
- src/main/resources/db/migration/all/20241105153718__make_space_booking_created_by_nullable.sql
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenABooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOfflineApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This PR includes changes that allows us to migrate a subset of legacy `bookings` where:
1. There is no corresponding linked placement request (the case for all offline applications and adhoc bookings)
2. There is no corresponding APPROVED_PREMISES_BOOKING_MADE domain event
This is a small subset of bookings, but some have arrival/departure dates in the future so they must be migrated
As a side effect of this change, the following fields are no longer mandatory on the SpaceBooking API type:
* assessmentId
* bookedBy
> APS-1492 - Support migrating bookings to space bookings for offline applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeliusService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DeliusServiceTest.kt
This PR retrieves the arrival and departure date from delius when migrating bookings to space bookings, and saves them on the space booking, if defined.
> APS-1496 - Populate arrival and departure dates when migrating booking to space booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningModelsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpacePlanningModelsFactoryTest.kt
This avoids lazy loading criteria for each relevant space booking
> Pre-fetch space booking criteria for planning

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
Removed expected departure date from CAS1 Arrival endpoint
Removed setting of previousExpectedDepartureOn but left the field in place, on the `PersonArrived` domain event.  
Discussion with David 7/5 we thought there would likely be value in this being captured and while API definitions are in a state of flux, worth keeping for the time being.
> APS-1460: Removed expected departure date from Cas1 Arrival endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/db/migration/all/20241107145256__add_migrated_management_info_from_to_space_bookings.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenABooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
This PR falls back to 'legacy' arrival and departure data captured on a `booking` when seeding an equivalent `space booking`. This will only be used if a corresponding record cannot be found in Delius.
> APS-153 - Use legacy cas1 management data for seeding space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
- src/main/resources/static/cas3-api.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
This[ PR CAS-1213](https://dsdmoj.atlassian.net/browse/CAS-1213) is to remove `/reports/referrals` Api as is no longer in use and is replaced with `/reports/{reportName}`
> CAS-1213 Remove Referral end point from CAS3 reports end points

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/SpaceBookingDates.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingStatusTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingStatusTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingSummaryStatusTestHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
- Generate all space booking statuses based on `expectedArrivalDate` / `expectedDepartureDate` / `actualArrivalDate` / `actualDepartureDate`
- The exception is the `notArrived` status which is driven by the `nonArrivalConfirmedAtDateTime`(i.e. if this is set then `notArrived`) - Spoke with @RobBoothMOJ on this
- For reference business-logic see the related ticket: https://dsdmoj.atlassian.net/browse/APS-1370
> Generate status for space booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningModelsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpacePlanningModelsFactoryTest.kt
Whilst rooms have many characteristics, only a handful can be considered mandatory on a `placement_request`. Given this, this commit limits the characteristics considered for planning to those that will have an impact on planning. This considerably simplifies the planning output as irrelevant characteristics on the room are no longer shown
> APS-1453 - Limit space planning to specific characteristics

- build.gradle.kts
Ref: https://dsdmoj.atlassian.net/browse/APS-1475
The gov notify email client is currently at version 5.2.1.
> APS-1475 Upgrade gov notify Java client to 5.2.1.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
This [PR CAS-486](https://dsdmoj.atlassian.net/browse/CAS-486) currently when get all application is calling delius api endpoint for each crn. This PR is to change the call to delius api to bulk of crns
> CAS-486 Bulk call to delius api to get offender details when get all applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningModelsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/planning/SpacePlannerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpacePlanningModelsFactoryTest.kt
This commit removes isArsonDesignated and isGroundFloor from consideration when planning space booking. isArsonDesignated is legacy criteria, and isGroundFloor may be re-added in future iterations as required.
> APS-1535 - Revise criteria considered for planning

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
A previous PR / piece of work captured Non arrival information for a space booking. 
This PR provides the way to retrieve that captured information.
> APS-1543: Added non-arrival information to API returning a space booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
Update `cas1SpaceBookingService.recordDepartureForBooking` to return a success outcome if the same required values in `Cas1NewDeparture` the are already set on `existingCas1SpaceBooking`. If different values are already set, return a conflict error as per the current behaviour when `existingCas1SpaceBooking.actualDepartureDateTime` != null
> Make record departure endpoint idempotent

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
Add placeholders for find and book beta roles:
* CAS1_CRU_MEMBER_FIND_AND_BOOK_BETA
* CAS1_AP_MANAGER_FIND_AND_BOOK_BETA
This is required to push out an updated API definition for the UI to add these roles to the admin ui.
> APS-1544 - Add CAS1 find and book private beta roles to api

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationStatusService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationStatusServiceTest.kt
- Move CAS1 booking functionality, when withdrawing a booking from BookingService to `Cas1ApplicationStatusService`.
- Add functionality in `Cas1SpaceBookingService`  -`withdraw` to update the application status for the withdrawn booking.
- Implement the processing to change the application status for a withdrawn / cancelled booking in `Cas1ApplicationSatusService`.
Consideration to be given to whether a space booking being withdrawn as part of 
`Cas1WithdrawableTreeOperations` should instigate a change to the associated application’s status.
A failing test : 
`Withdrawing a match request for original app dates cascades to applicable booking entity and updates the application status`
demonstrates the withdrawal of a Space Booking when traversing the associated entity tree for a withdrawn …
> APS-1300: Update Application Status when withdrawing Space Booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/MoveOnCategoryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
Changed the Space Booking Departure API 
- moveOnCategory no longer mandatory 
- when no moveOnCategory is supplied the system defaults to the 'Not Applicable' move on category to ensure ongoing compatibility with Probation Integration for which this field is mandatory.
> APS-1254: Update Space Booking Departure API , moveOnCategory no longer mandatory

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CharacteristicService.kt
Change the CAS3 bedspace search to use property name characteristics column. when filter bedspaces by attributes
> Change CAS3 bedspace search to use property name characteristics

- .github/workflows/codeql.yml
- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
HMPPS dps gradle spring boot plugin has been updated from version 5.15.6 to version 6.0.6 in the Kotlin template project so we should be using this version in the CAS API too.
HMPPS DPS gradle spring boot plugin version 5.15.6:
Spring version: 3.2.5
Kotlin version: 1.9.22
HMPPS DPS gradle spring boot plugin version 6.0.6:
Spring version: 3.3.4
Kotlin version: 2.0.20
Upgrading HMPPS dps gradle spring boot plugin from 5.15.6 to 6.0.6 resulted in following error when running ./gradlew compileTestKotlin:
`Caused by: java.io.FileNotFoundException: .../hmpps-approved-premises-api/build/classes/kotlin/test/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest$Cas3GetApplication$Get_single_application_returns_200_with_correct_body_for_Temporary_Accommodation_when_a_user_with …
> APS-1474 upgrade DPS gradle spring boot plugin to 6.0.6

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/CasResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
Sometimes in a service we want to return a `CasResult.Error` ‘as is’ back to the caller. Before this commit we would have to ‘rebuild’ the `CasResult` specific type to make the generic arguments happy, despite the SuccessType generic not being used anyway in the `CasResult.Error` hierarchy. This was verbose and forced us to reassert information that was already in the original error, typically loosing context.
This commit adds a `reviseType` function to `CasResult.Error` to allow us to directly use the `CasResult.Error` instance by forcefully changing its generic.
It also makes use of the function in `PlacementApplicationService` to provide a working example.
> Add method to quickly recycle CasResult error

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DepartureReasonTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/db/migration/all/20241114110241__update_departure_reasons_for_breach_recall.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureReasonEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
Add Parent-Child relationship to Departure Reasons
- Added parent_reason_id to API, entity and table
- Created a new parent 'Breach / Recall' departure reason
- Populated the parent_reason_id field for children of the new parent with the new record's Id 
- Updated the child records to remove 'Breach / recall' text
- Implemented a change to the Cas1SpaceBookingTransformer to provide a composite name of parent and child 'Breach / recall' departure resons
> APS-1524: Add Parent-Child relationship to Departure Reasons

- src/main/resources/application.yml
This was previously 30 minutes which is proving insufficient to refresh the cache given the increasing number of applications in the database. This commit doubles it to 60 minutes
> Increase cache refresh TTL

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
When converting a booking into a space booking we want to use the existing bookings ID. This is ‘safe’ as we use UUID for IDs.
This will ensure that any domain event triggered against the space booking will still work, as the booking id is stored against the corresponding referral in delius
> APS-1256 - Use booking ID for migrated space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1SpaceSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt
This PR updates the space search results to only shows premises where `supports_space_bookings` is true
This is shown from local testing (only SWSC test premises are returned)
It also adds 'supports space bookings' to the premise basic summary result to support UI filtering
> APS-1554 - For space search only return premises supporting space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningModelsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpacePlanningModelsFactoryTest.kt
Before this commit a database query was ran to retrieve space bookings applicable for each day being planned.
This commit instead loads all space bookings that are active across a given date range, and uses this to find each applicable booking for the day (as we already do for out of service bed records).
This significantly reduces the number of database queries required.
This change has been made in preparation for reusing the planning models to calculate capacity wrt. characteristics that are of interest for space booking planning
> APS-1583 - Optimise planning model creation

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestBookingSummaryTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingSummaryTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestBookingSummaryTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt
Update CRU Dashboard to consider space bookings
Updated dashboard SQL (`allForDashboard`) to recognise space bookings in placement requests and `cancelled` and `matched` status' 
Updated `PlacementRequestTransformer` to handle providing a booking summary for Space Bookings as well as legacy bookings
> APS-1564: Update CRU Dashboard to consider space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpaceDayPlanner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningModels.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpaceDayPlannerTest.kt
This commit fixes a bug where a booking that requires a single room is sometimes placed into a room with multiple beds vs a room with a single bed and the ‘single bed characteristic’.
Whilst this was a legitimate bug, it does highlight a potential conflict in the order in whcih the following rules are applied:
1. Bookings are placed into rooms with the least surplus characteristics
2. If there are multiple competing rooms (after above goals are satisfied), single occupancy bookings will be placed into rooms with the least beds (ensuring minimum 'wastage' in these scenarios)
This can result in a single booking being put into a room with many beds because the single bed room has unrequired characteristics. This may not be desirable
> APS-1583 - Fix planning bug related to single rooms

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/db/migration/all/20241121081817__add_departure_notes_to_space_booking.sql
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
Two parts to this ticket. 
1. Remedy the issue that departure notes (provided when recording a departure) was not being persisted. 
2. Provide departure information when retrieving a space booking.  This includes providing granular information when a parent-child departure reason is recorded, and departure notes.
Departure Notes not being persisted :
- Migration script to add departure_notes to table
- Added departureNotes to entity
- Added departureNotes to the Cas1SpaceBooking returned when getting a space booking
Provide Departure Information when retrieving a space booking : 
- Created a Cas1SpaceBookingDeparture object which contains information relating to departure
- Provides distinct information on parent departure reason, if it exists
- Now includes notes, which had been omitted …
> APS-1594: Add departure information when Getting Space Booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RequestResponseLoggingFilter.kt
- src/main/resources/application-local.yml
Output Bearer Token when running locally
This commit updates the RequestResponseLoggingFilter to output the caller’s bearer token when running locally.
We are protected from this being enabled in production environments in multiple ways:
1. The RequestResponseLoggingFilter is disabled by default
2. On startup the RequestResponseLoggingFilter checks which profles we’re using and will error (stopping startup) if we’re in a non-test environment
3. The RequestResponseLoggingFilter will always create a Sentry alert when it runs. This wll be visible if somehow this was running in an environment connected to sentry
4. The Bearer token is logged at TRACE level, which is not enabled by default
> Show bearer token in logs when running locally

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingSummaryTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingSummaryTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingSummaryTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestBookingSummaryTransformerTest.kt
Updated Get Placement Request to consider Space Bookings
- Marked `PlacementRequestDetail` cancellations as deprecated.  Cancellations aren't used by the UI.
- Added `type` to BookingSummary which indicates type of booking - `legacy` / `space`
> APS-1565: Updated Get Placement Request to consider Space Bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt
Added filter to only return active Non Arrival Reason records.
> APS-1580: Updated Get Non Arrival Reasons to exclude inactive records

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/db/migration/all/20241125113607__drop_index_cas1_space_bookings_premises_id_placements_request_id.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
Ensure there are no active legacy Bookings or active Space Bookings when creating a Space Booking.
Drop the cas1_space_bookings_premises_id_placement_request_id_idx index as it is not required.
> APS-1568: Ensure no active Bookings when creating a Space Booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1DeliusBookingImportEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusBookingDataSeedJob.kt
- src/main/resources/db/migration/all/20241122150114__add_cas1_delius_booking_import.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1ImportDeliusBookingDataSeedJobTest.kt
We need to import a CSV of delius booking data to backfill space bookings, via`Cas1BookingToSpaceBookingSeedJob`. This commit adds a seed job to validate and subsequently import that data.
Given the target table is truncated before each run, and the high numbers of rows in the CSV file, this does not operate in a transaction.
> APS-1601 - Add seed job to import delius booking data

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/AbstractUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/AllCasUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/Cas3UsersSeedJob.kt
This commit refactors seed jobs such that they only required spring manage instances on construction. This will then allow us to simplify the `SeedService` by converting all seed jobs into spring-managed components and delegate to spring when retreiving the required seed job.
To achieve this the `UserSeedJob` has been made abstract and specific usages of it in `SeedService` are sastified using context-specific seed job definitions.
> Seed Jobs should only use Spring Managed Instances

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1DeliusBookingImportEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusBookingDataSeedJob.kt
- src/main/resources/db/migration/all/20241125152438__make_delius_booking_import_exp_departure_date_nullable.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1ImportDeliusBookingDataSeedJobTest.kt
This commit makes the value of cas1_delius_booking_import.expected_departure_date NULLABLE, are there is a single  record that does not not have a departure date set and will not have one set when the final import is ran
> APS-1601 - Make cas1 delius import departure date optional

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremiseCapacitySummaryTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremiseCapacitySummaryTransformerTest.kt
This is has been added to avoid the UI having to make additional API calls for premise information
> APS-1583 - Add CAS1 premise summary to capacity response

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
Check Placement Request doesn't have an active Space Booking when creating a legacy booking.
> APS-1608: Check Placement Request doesn't have a Space Booking when creating legacy booking

- .gitignore
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/StaffMemberService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/StaffMemberServiceTest.kt
This commit removes the deprecated AuthorisableActionResult from StaffMemberService, replacing it with CasResult
> Use CasResult in StaffMemberService

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
Acquire lock when creating a Space Booking
This guards against double POSTs when creating Space Bookings.
Pessimistic lock is acquired on Placement Request using the pattern established by LockableAssessmentRepository
> APS-1609:Acquire lock when creating a Space Booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BookingsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
`Booking.keyWorker` is only used by CAS1, and CAS1 is no longer populating it, or showing it on the UI. It will be replaced by `SpaceBooking.keyWorker`
```
select service from bookings where key_worker_staff_code IS NOT NULL group by service;
-- success --
service
-----------------
approved-premises
-- activity count = 1
```
Given this, this commit marks it as deprecated and stops populating it when retrieving a booking.
> APS-1625 - Deprecate and stop populating Booking.keyworker

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/FaviconController.kt
This has been added to remove unhelpful warning logs when a favicon is requested
> Add empty favicon

- src/main/resources/application-local.yml
* Force color-coded logs in local deployments
* Format Hibernate logs in local deploys. Previously we used spring’s `show-sql: true` config to log hibernate SQL when deployed locally. This logged to STDOUT so wasn’t formatted in the same way as other logs.
> Improve local log output

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/resources/db/migration/all/20241128085222__add_optimistic_lock_to_space_booking.sql
Add optimistic lock to Cas1 Space Bookings
Adds a version column to the entity and table which allows JPA @Version to detect concurrent amendments to the same record.
This approach is already in use on Bookings, Placement Applications, Placement Requests.
> APS-1610: Add optimistic lock to Cas1 Space Bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/cas1/Cas1ApplicationFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
* updates the CAS1 Space Booking Domain Event service to remove the need to force non-nullness on arrival and departure dates, instead having the non-null values passed in as part of the function call
* introduces a Cas1ApplicationFacade to simplify how certain application properties are retrieved when an entity could be linked to an application or an offline application
> APS-1638 - CAS1 Domain Event Improvements

- src/main/resources/static/cas1-api.yml
This commit fixes the cas1-schemas references in cas1-api.yml for out of service bed types. This incorrect reference is only an issue when viewing the yml file in intellij.
> Fix cas1-schema refs

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineTransformer.kt
- src/main/resources/application.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
When a link to a view space booking is shown on the timeline the wrong url was being used for local deploys. In all other deploys the configuration was incorrectly named in helm so was not used. This commit fixes those issues
> APS-1635 - Fix space booking timeline url

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/MoveOnCategoryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1DeliusBookingImportEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusBookingDataSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1ImportDeliusBookingDataSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenABooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
* update the booking to space booking seed job to populate additional information from a legacy booking, if referral information can’t be located in Delius
* changes the booking to space booking seed job to retrieve delius data from the `cas1_delius_booking_import` table, instead of retreiving more limited data from the ap-and-delius API
> APS-1605 - Populate additional fields when migrating bookings to space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
This commit fixes an issue caused by there being multiple entries in the departure reason code table with the same legacy delius code. One entry is a enabled, the other is not. This results in a `Query did not return a unique result: 2 results were returned` error.
This commit fixes this issue by getting a list of matching reason codes, taking the enabled one if it exists.
> APS-1498 - Fix Space Booking Migration Reason Code Resolution

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
When we import key worker information from delius we do not have the data the keyworker is assigned at. This commit modifies the API model to ensure that this value is always potentially null when being returned
> APS-1498 - Spacebooking Key Worker Assigned at is always nullable

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApprovedPremises.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
This PR adds some sanity checks to the booking to space booking seed job in preparation for changing the job to delete bookings after they have been migrated:
1. Block execution of the job in production
2. Ensure the related premise can support space bookings
> APS-1545 - Add sanity check to booking to space booking migration

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
This PR updates the booking to space booking migration logic to update any domain events linked to the original booking to instead ‘point’ to the newly created space booking
> APS-1485 - Migrate booking domain events to space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
When a Booking is removed as part of the Space Booking migration, any DateChange entries related to the old booking should also be removed. Otherwise a FK reference error will occur. Note that date changes are captured as domain events, so this data will still be available for space bookings.
> APS-1545 - Booking to Space Booking - remove old DateChanges

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/AllCasUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/CharacteristicsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UpdateNomsNumberSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UpdateUsersFromApiSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApStaffUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApprovedPremisesBookingCancelSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApprovedPremisesRoomsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApprovedPremisesSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AssessmentMoreInfoBugFixSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1CruManagementAreaSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1DomainEventReplaySeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1DuplicateApplicationSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusBookingDataSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1LinkBookingToPlacementRequestSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1OutOfServiceBedSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1PlanSpacePlanningDryRunSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1RedactAssessmentDetailsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UpdateEventNumberSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1WithdrawPlacementRequestSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/Cas2ApplicationsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/ExternalUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2/NomisUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/Cas3UsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/TemporaryAccommodationBedspaceSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/TemporaryAccommodationPremisesSeedJob.kt
This simplifies the `SeedService` as it no longer has to manually inject dependencies.
> Convert seed jobs to spring beans

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderRisksDataSource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/datasource/OffenderRisksDataSourceTest.kt
Before this commit the `OffenderRisksDataSource` recorded a RuntimeException in sentry if risks couldn’t be loaded. The error message implied that processing of the thread had failed/errored because of this error, but that’s typically not the case as the calling code can continue if risks arne’t known (and will error itself if it can’t).
> Improve Risk Datasource Error Message

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/AbstractUsersSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CacheClearTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CalendarTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedScaffoldingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedUsersTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt
Removed CAS1_MANAGER role from service
Substituted CAS1_MANAGER with CAS1_FUTURE_MANAGER where applicable, to ensure continuity of service for users.
> APS-1199: Removed CAS1_MANAGER role from service

- src/main/resources/db/migration/all/20241204095849__temporarily_readd_users_staff_identifier.sql
This is to avoid errors during the rollout of the related to change to production, as live code will still expect this column to exist.
> APS-1645 - Temporarily readd users.delius_staff_identifier

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
The offender access API will return a HTTP 400 error code if more than 500 CRNs are requested.
> Proactively catch bad offender access requests

- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
Space Search should filter premises based upon application's associated gender
First part of ticket APS-1654  
Requires the addition of applicationId to the space search parameters to be able to determine gender requirement from application.  
Added initially as optional, prior to requisite change in the UI after which it will be changed to be mandatory.
> APS-1654: Space Search filter on application gender

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationTimelineNoteEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1DuplicateApplicationSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1RedactAssessmentDetailsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UpdateEventNumberSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1WithdrawPlacementRequestSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationTimelineNoteService.kt
- src/main/resources/db/migration/all/20241205110116__add_space_booking_id_to_timeline_note.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationTimelineNoteEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1RedactAssessmentDetailsSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationTimelineNoteServiceTest.kt
This PR removes `ApplicationService. addNoteToApplication` and redirects all calls to the `ApplicationTimelineNoteService`, as the extra layer of indirection had no value and complicates changes
It then adds `cas1_space_booking_id` to the timeline note table
> APS-1658 - Add ability to record a space booking id against a timeline note

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/StaffDetail.kt
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/StaffMemberFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/model/StaffDetailTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DomainEventTransformerTest.kt
Receivers (ap-and-delius-context) are no longer expecting domain events `staff member` to include a staff identifier value. This commit removes that value as it is not required.
> APS-1642 - Remove staffIdentifier from domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedColumns.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusBookingDataSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UpdateSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningModelsFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningService.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1UpdateSpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOfflineApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1UpdateSpaceBookingSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpacePlanningModelsFactoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingRequirementsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This commit adds a seed job that can update a space bookings event number, and associated characteristics.
An event number can only be updated if the space booking is linked to an offline application for which no event number is assigned. In all other scenarios the `Cas1UpdateEventNumberSeedJob` should be use to update the application’s event number which will cascade to the space booking (change to be made in a subsequent commit)
> APS-1658 - Add seed job to update space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
When migrating bookings to space bookings, only populate the room critiera types that we will allow users to define when creating a space booking via the UI/API
> APS-167 - Only migrate criteria of interest to space bookings

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
Before this commit we saw intermittent
duplicate key value violates unique constraint "characteristics_property_name_service_scope_model_scope_key"
due to the use of random model scopes sometimes clashing with existing database entries.
> Fix test stability issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
Previously we disabled emitting CAS1 arrival and departure domain events because there was functionality available on the user interface to record arrivals and departures, but we did no want this being sent to delius as the functonality was incomplete.
There is no longer ‘record arrival/departure’ functionality available to users in prod so it’s safe to re-enable these domain events to support testing of space booking management.
> Emit CAS1 arrival and departure events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
Before this commit if no keyworker was defined in the delius data the keyworker name would be set to “null null”
> APS-1669 - booking to space booking keyworker fix

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1SpaceSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceSearchResultsTransformerTest.kt
Space Search should filter premises based upon application's associated gender. 
`Cas1SpaceSearchRequirements` 
- `applicationId` is now mandatory 
- `genders` is deprecated
`Cas1SpaceSearchService.findSpaces`
- Gender is obtained from the associated application (via `applicationId`) `is_womens_application`
- modified the filter query to apply gender filter using `approved_premises.gender`
> APS-1654: Space Search filter premises on application gender

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/CaseDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
This allows the UI to determine if an offender is an LAO, even if they have access to the offender. This matches a similar property on `FullPerson`
> Add `FullPersonSummary.isRestricted` to the API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AppealsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
This PR tidys up the CAS1 Get Application Tests to better reflect the implementation. It also changes the implementation to use the new `canAccessOffender ` function to check offender access
> APS-1689 Improve CAS1 Get Application LAO test coverage & remove use of deprecated function

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
Before this commit, it was possible to retrieve placement request details even if you did not have access to the Offender details due to the offender being an LAO. Whilst the Person info was redacted in this case, application detail was not. Note that the UI wasn’t showing any of the sensitive application information, but regardless we should not be returning it from the API and should instead return a 403.
Given that the UI doesn’t link to placement requests if the user doesn’t have access to an LAO offender, this _isn’t_ a breaking change
> APS-1689 - Get placement request should 403 if user can't access LAO offender

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
Corrects issue where the `occurredAt` timestamp was being set to the arrival date / departure date rather than the system's  timestamp. 
Updated the timeline output (DomainEventDescriber) to include the time in the generated output, to display, for an arrival / departure.
> Arrival and Departure domain events displaying on timeline

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingRequirementsTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingRequirementsTransformerTest.kt
This commit updates the create space booking api to make use of the new `Cas1SpaceBookingCharacteristic` type, which limits space bookings to 6 characteristics.
> Limit space booking characteristics in the API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
This is in preparation for moving the 'booking changed' domain event logic into the `Cas1BookingDomainEventService`
> Tidy Cas1BookingDomainEventService and add Integration Test for Booking Amended Domain Event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/resources/db/migration/all/20241213153445__add_offline_application_name.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OfflineApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnOfflineApplication.kt
* Add `name` column to offline applications
* Update space booking search to return space bookings linked to offline applications, and consider the name on the offline application
* Auto seed a space booking linked to an offline application in local dev environments
This PR will be followed by a PR to backfill `offline_applications.name`
> APS-1707 - Add name to offline applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventMigrationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/MutableClockConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Cas1DomainEventsFactory.kt
Before this commit we tested domain event migrations by having the Cas1DomainEventFactory return JSON matching all potential schema versions. Currently only `DomainEventType.APPROVED_PREMISES_BOOKING_CANCELLED` supports two different schema versions.
This code was difficult to understand, and only worked if the fields added to the latest schema version could be derived from fields already in the domain event.
This commit sacrifices cleverness in favour of readability, instead adding an explicit test in DomainEventTest for every domain event version migration (currently there’s only one for `DomainEventType.APPROVED_PREMISES_BOOKING_CANCELLED`) and updating the factory to only every return domain events for the latest schema version
> APS-1675 - Simplify CAS1 Domain Event Migration Testing

- doc/how-to/modifying_domain_event_schemas.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PersonArrivedFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingManagementDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/WebTestClientExtensions.kt
Domain event schema version control is used to identify older domain events that don’t have a ‘recordedBy’ element in the JSON and backfill the value with the domain event’s triggered by user, if available.
The primary purpose of this migration is to make v1 domain events schema valid. `recordedBy` is not used to render the timeline, and these old domain events will not be consumed externally, so the imperfect nature of the back fill is acceptable
> APS-1675 - Capture recordedBy on CAS1 arrival domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningService.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/planning/SpacePlanningServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
This commit adds the option to exclude a given space booking id when calculating a premises occupancy. This will be used when retrieving capacity as part of amending the referenced booking.
> APS-1727 - Optionally exclude booking from capacity calculations

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventMigrationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PersonDepartedFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas1DomainEventTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementDomainEventServiceTest.kt
Domain event schema version control is used to identify older domain events that don’t have a ‘recordedBy’ element in the JSON and backfill the value with the domain event’s triggered by user, if available.
The primary purpose of this migration is to make v1 domain events schema valid. `recordedBy` is not used to render the timeline, and these old domain events will not be consumed externally, so the imperfect nature of the back fill is acceptable.
> APS-1718 Capture recordedBy on CAS1 departure domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
This is not currently in use by CAS1 and will be replaced by space booking amendments
> APS-1730 remove cas1 from bookings extensions endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1SpaceSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceSearchResultsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/CollectionUtils.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceSearchResultsTransformerTest.kt
When the Space Search Service was originally written, it was expected that the results would include availability for each returned premise. This is no longer the case and is managed by a separate API.
This commit removes the ‘placeholder’ code added to provide capacity, simplifying the response from the space search service.
It doesn’t make any functional changes to the code
> Remove unused availability info from space search

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3PremisesServiceTest.kt
This [PR CAS-1322](https://dsdmoj.atlassian.net/browse/CAS-1322) is to split the current Premises Service by creating a new CAS3 premises Service
> CAS-1322 Split the current Premises Service by creating a new CAS3 premises Service

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingDaySummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedSummaryTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesDayTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingDaySummaryTransformer.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedSummaryServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingDaySummaryServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OutOfServiceBedSummaryTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesDayTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingDaySummaryTransformerTest.kt
Implement Day Summary Endpoint. 
GET /cas1/premises/{premiseId}/day-summary/{date}
Given a premises id and a specific date, the endpoint returns information on capacity, bookings and out of service beds for the given date. 
3 Separate commits covering 3 parts of functionality : 
- Populate capacity information (and date fields)
- Populate booking information with filtering and sorting implemented
- Populate out of service bed information
Release Type still to be determined
> APS-1676: Day Summary Endpoint 

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
Before this commit a RestrictedPerson would be returned when retreiving a placement request, even if the calling user has the ‘Limited Access’ qualification.
This commit changes the PlacementRequest qualification to consider this qualification. This subsequently allows space bookings to be created for LAOs where the user has the ‘limited access’ qualification
To support this a new version of `OffenderService. getPersonInfoResult` is added that accepts the LimitedAccessStrategy, with the existing functions being deprecated.
> APS-1768 - Allow Space Booking creation for LAOs

- script/run_seed_from_excel_job
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/SeedFromExcelController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedXlsxService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedPremisesFromSiteSurveyXlsxJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedRoomsFromSiteSurveyXlsxJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyPremiseFactory.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1PremisesFromSiteSurveyXlsxTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1RoomsFromSiteSurveyXlsxTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedXlsxScaffoldingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DataFrameUtils.kt
Before this PR we had to provide the premises ID when updating/creating rooms from the site survey XLSX. This commit changes the ‘seed XLSX’ API, removing the need to provide the premises ID and instead finding the premises using the QCode defined within the spreadsheet itself
> APS-1733 - Simplify XLSX Seeding API Calls

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1DeliusBookingImportEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedColumns.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusReferralsSeedJob.kt
- src/main/resources/db/migration/all/20250102135809__delius_booking_import_changes.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1ImportDeliusReferralsSeedJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
Renamed seed job from Cas1ImportDeliusBookingDataSeedJob to Cas1ImportDeliusReferralsSeedJob
The import CSV now includes referrals that were not created via CAS1, meaning they don’t have a booking ID. This commit accounts for this change
* Made booking_id optional and added new a ‘random’ primary key column
* Mapped Hostel_Code value to premises_qcode
* Validated code and date fields to return null if values are recognised as invalid
> APS-1769 Update Cas1ImportDeliusBookingDataSeedJob to new format

- .circleci/config.yml
While working on automated process to generate swagger docs, we discovered that we needed to change how we notify our UI repos of changes to the api. 
Currently, this is done after each merge to main. The problem with this is the to get the new automatically generate api docs the api changes need to be deployed to dev first because the UI can generate the types from it.
> Create new circleci to trigger cas3 github action after deployment to dev

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
Before this commit if a placement request had been marked as ‘unable to match’ but then previously had a space booking created, it was still being returned on the placement request dashboard as unable to match.
This commit also improves the placement request dashboard API tests cover additional scenarios, improving regression testing
> APS-1773 - Placement Request with Space Booking should not appear as be unable to match

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/SeedCas1BookingToSpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
This commit changes the booking to space booking seed job to use qcodes in the CSV instead of premise ids. QCode are more readible and remain consistent across environments/installs.
> APS-1752 - Use qcode for booking to space booking seed job

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/main/resources/static/domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt
This PR updates the CAS1 booking changed domain event to capture the previous date values, if changed. It populates these values for booking changes.
> APS-1730 capture previous values on booking amend domain event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt
Add a function to get offender info in batches and update Cas3ReportService to use this function for batching requests.
This is being added as batching functionality will be required for some new CAS1 seed jobs
> APS-1752 - Add get person info in batches function

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3VoidBedspaceCancellationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3VoidBedspaceReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3VoidBedspacesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedUtilisationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3VoidBedspaceReasonTransformer.kt
- src/main/resources/db/migration/all/20250107135009__add_prefix_cas3_to_lost_beds_tables_and_rename_them_to_void_bedspaces.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas3/Cas3VoidBedspaceReasonEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DeletePremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DeleteRoomTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/VoidBedspacesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3PremisesServiceTest.kt
This [PR CAS-1343](https://dsdmoj.atlassian.net/browse/CAS-1343) is to add cas3 prefix to lost bed tables and rename them to void bedspace. Tables:
- lost_beds
- lost_bed_cancellations
- lost_bed_reasons
> CAS3-1343 Add prefix cas3 to void bedspace tables 

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/StaffMemberService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/NoOpSentryService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/StaffMemberServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt
If probation-integration returns a 404 when retrieving team details for a premise we want the API to return an empty list for staff, as to not block usage of the corresponding UI. In this scenario a sentry alert will be raised.
> Return empty staff list if team info not found for a given qcode

- src/main/resources/db/migration/dev+test/R__5_create_bookings_for_cas3_eofe.sql
- src/main/resources/db/migration/dev+test/R__5_create_bookings_for_cas3_kss.sql
This [PR CAS-1343 ](https://dsdmoj.atlassian.net/browse/CAS-1343) is to change lost bed tables names for dev and test scripts
> CAS-1343 Change lost bed tables names for dev and test scripts

- src/main/resources/db/migration/all/20250107135009__add_prefix_cas3_to_lost_beds_tables_and_rename_them_to_void_bedspaces.sql
This PR CAS-1343 is to:
- Remove lost bed tables constraints for tables lost_beds and lost_bed_cancellations
- Add new void bedspace tables constraints for tables cas3_void_bedspaces and cas3_void_bedspace_cancellations
- Remove the entry from flyway_schema_history in dev database:
```
DELETE FROM  flyway_schema_history
WHERE script = '20250107135009__add_prefix_cas3_to_lost_beds_tables_and_rename_them_to_void_bedspaces.sql';
```
> CAS1343 Update lost bed tables constraints

- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
This commit temporarily re-adds ApprovedPremisesBedSearchParameters until it can be fully removed from the UI code
> Re-add ApprovedPremisesBedSearchParameters

- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
This commit temporarily re-adds ApprovedPremisesBedSearchResult until it can be fully removed from the UI code
It also removes ApprovedPremisesBedSearchParameters which was incorrectly re-added
> Re-add ApprovedPremisesBedSearchResult

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedRoomsFromSiteSurveyXlsxJob.kt
For the seed room characteristics from Excel site survey data, output the difference in room characteristics between the existing room entity and the updated room entity usinng the [JaVers](https://javers.org/) library.  This is [already done](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/14f7408f3eae062a5b55df9694fddafc23ff4ba6/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedPremisesFromSiteSurveyXlsxJob.kt#L197) when a premise is updated via the equivalent job.
> Add diff when updating room to log output.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
Previously a RuntimeException would not trigger a rollback of a seed job.
This commit ensures an exception is thrown if the seed job fails for any reason, which will lead to the transaction being rolled back
> Rollback seed transaction if any errors occur

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
This PR removes usage of `userService.getUserForRequest()` from various service-level functions, instead taking the current user as a function argument.
This allows the functions to be used by seed jobs, where a user isn’t set on the request context
> APS-1787 pass user into application & assess functions

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/BadRequestProblem.kt
It has been observed that when we log a `BadRequestProblem` exception that has been created for a `FieldValidationError`, the error message is typically not very helpful:
‘There is a problem with your request’
This occurs because a `FieldValidationError` only contains a map of invalid parameters. When this is converted into a `BadRequestProblem` by the `EntityUtils`, no error detail (summary of the error) is provided to the `BadRequestProblem`.
Because the `AbstractThrowableProblem` doesn’t include the error parameters in the default exception message, we are left with the default unhelpful message shown above.
Whilst the ‘correct’ solution may be to include the invalid params in an ‘errorDetail’ string when constructing the `BadRequestPoblem` in `EntityUtils`, i’m concerned that this …
> Improve FieldValidationError exception message

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1CreateTestApplicationsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EnvironmentService.kt
- src/main/resources/db/seed/local+dev+test/cas1_application_data/application_document.json
- src/main/resources/db/seed/local+dev+test/cas1_application_data/assessment_data.json
- src/main/resources/db/seed/local+dev+test/cas1_application_data/assessment_document.json
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1CreateTestApplicationSeedTest.kt
Add a seed job to create test applications that either pending submission, or pending matching
This job uses co-routines when creating applications. limitedParallelism is set to 10 to ensure we don’t exceed the size of the JDBC connection pool. Otherwise we start seeing timeouts waiting on connections in the pool. Adding additional parallelism didn’t produce any notable gains, although that my not be the case in other better-sized environments.
> APS-1787 add seed job to create applications with pending request for placements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
This [PR CAS-1238](https://dsdmoj.atlassian.net/browse/CAS-1238) is to change get application to return not found response when Cas3 application was deleted
> CAS-1238 get application returns not found when Cas3 application was deleted

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationTimelineNoteEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SoftDeleteApplicationTimelineNotes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationTimelineNoteService.kt
- src/main/resources/db/migration/all/20250113125352__add_deleted_at_to_application_timeline_notes.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationTimelineNoteEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1RedactAssessmentDetailsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1DuplicateApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1SoftDeleteApplicationTimelineNotesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1WithdrawPlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCasUpdateEventNumberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedUpdateNomsNumberSeedJobTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1722
- add a nullable column `application_timeline_notes.deleted_at` of type `timestamptz`. Default to null
- update the code that returns the application timelines to filter out notes where `deleted_at` is not null (i.e. update `ApplicationTimelineNoteRepository.findApplicationTimelineNoteEntitiesByApplicationId)`
- add a seed job that given a list of `application_id` and `application_timeline_note_id`, will soft delete timeline notes by setting `deleted_at` to the current date/time.
- Validate that the `application_timeline_note_id` belongs to the given `application_id` (this is an additional level of validation to ensure we’re not deleting the wrong timeline note)
- once deployed to production we should soft delete the timeline note amended …
> Aps 1722 soft delete timeline note

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingDaySummaryTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingDaySummaryServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesDayTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingDaySummaryTransformerTest.kt
Before this commit the CAS1 premise day summary would return an error if a booking had characteristic outside of the following list
```
@JsonProperty("hasEnSuite") HAS_EN_SUITE("hasEnSuite"),
@JsonProperty("isArsonSuitable") IS_ARSON_SUITABLE("isArsonSuitable"),
@JsonProperty("isSingle") IS_SINGLE("isSingle"),
@JsonProperty("isStepFreeDesignated") IS_STEP_FREE_DESIGNATED("isStepFreeDesignated"),
@JsonProperty("isSuitedForSexOffenders") IS_SUITED_FOR_SEX_OFFENDERS("isSuitedForSexOffenders"),
@JsonProperty("isWheelchairDesignated") IS_WHEELCHAIR_DESIGNATED("isWheelchairDesignated")
```
This commit changes the API to support all characteristics that could be linked to a space booking
> Fix CAS1 day summary characteristics bug

- src/main/resources/db/migration/dev/R__8_create_cas3_application_and_assessment.sql
- src/main/resources/db/migration/local+dev+test/R__1_create_dev_users.sql
This commit tidies up some SQL migration scripts related to test users, making them more readible
As noted in comments, seeding of test users should ideally be managed by the user seed job via 3__user.csv.
To test this i diff’d the output from the following SQL. The only difference was the IDs for users generated by the seed job, as expected
```
select
u.id,
u.name,
u.email,
u.delius_username,
a.name as "new application area",
cru_management_area.name as "cru management area (default)",
cru_management_area_override.name as "cru management area (override)",
string_agg(r.role,', ' ORDER BY r.role) roles
from users u
inner join ap_areas a on a.id = u.ap_area_id
left outer join user_role_assignments r on u.id = r.user_id
left outer join cas1_cru_management_areas cru_management_area on …
```
> APS-1792 - Simplify user seeding in local+dev+test

- helm_deploy/values-test.yaml
This ensures that the `test` environment has the same number of replicas as production
> APS-1756 - Use default replicaCount in `test` for load test

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
This [PR CAS-1375](https://dsdmoj.atlassian.net/browse/CAS-1375) is to fix an issue when calling get offender details and the crn is in lower case
> CAS-1375 Upper case crn when call getPersonInfoResult in premises service

- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
We should be using characteristics to filter results on premise types instead of the discrete apType enumeration.
This commit also adds an integration test demonstrating filtering on ap types using characteristics.
> APS-1835 Deprecate space search apType options

- script/run_migration_job
- script/run_seed_from_excel_job
- script/run_seed_job
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedXlsxService.kt
Before this commit we were not catching `Throwable` types. Because we’re using `@Async` it’s possible that these are swallowed and not logged.
> Improve seed job error handling

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1CreateTestApplicationsSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1CreateTestApplicationSeedTest.kt
This commit updates the create test application seed job to support seeding applications with a space bookings. This is required to support load testing.
Example config:
```
creator_username,crn,count,state,premises_qcode
JIMSNOWLDAP,X320741,50,AUTHORISED,
JIMSNOWLDAP,X320741,50,BOOKED,Q713
```
Example output
> APS-1829 - Enhance test app seed job to include bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UpdateApplicationLicenceExpiryDateJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1UpdateApplicationLicenceExpiryDateJobTest.kt
[https://dsdmoj.atlassian.net/browse/APS-1617](url)
> APS-1617 Updated job to use the correct json path.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OutOfServiceBedTest.kt
If a CRU Member requires access to Out of Service Beds (OOSB) functionality, they should be assigned the ‘CRU Member Out of Service Beds’ role. Anyone currently with teh ‘CRU Member’ role in production has already been assigned the ‘CRU Member Out of Service Beds’ role
> APS-1641 Remove OOSB permissions from CRU Member

- src/main/resources/static/_shared.yml
- src/main/resources/static/api.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas2-api.yml
- src/main/resources/static/cas2-domain-events-api.yml
- src/main/resources/static/cas3-api.yml
- src/main/resources/static/cas3-domain-events-api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/main/resources/static/domain-events-api.yml
Running the gradle openApiGenerate task currently results in the following issues:
"Illegal schema found with $ref combined with other properties"
"Empty operationId found for path"
Resolving these issues requires:
- remove sibling properties when using `$ref`
- adding missing `operationIds` (using existing defaulted values so that generated code does not change)
See more information in the comment descriptions.
After these changes the gradle openApiGenerate task runs with fewer complaints:
```
./gradlew openApiGenerate
Configuration on demand is an incubating feature.
> Configure project :
Setting max test processes to recommended half of available: 5
Setting max test processes to recommended half of available: 5
Setting max test processes to recommended half of available: 5
Running …
```
> Chore/fix openApiGenerate gradle task issues

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusReferralsSeedJob.kt
This commit adds an option to seed jobs to process rows in parallel using co-routines. This is disabled by default, and currently only enabled for the Cas1 Import Delius Referrarl Seed Job
Stats from running that job locally with a complete import, showing processing time decreased from 10 minutes to 2.2 minutes.
*With co-routines*
Seed request complete. Took 133923 millis and processed 297603 rows |  2.2 minutes. 221831 rows in cas1_delius_booking_import
*Without co-routines*
Seed request complete. Took 618490 millis and processed 297603 rows |  10 minutes. 221831 rows in cas1_delius_booking_import
> APS-1796 Add option to seed job to process rows in parallel

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
- src/main/resources/application.yml
This commit enables retry on timeout for ap-and-oasys and reduces its timeout threshold from 10 seconds to 4 seconds. Observations have shown that when we do get a timeout and a 500 is returned to the UI a retry triggered by the UI succeeds.
The timeout of 4 seconds is based upon the 99th percentil response time of 340 milliseconds, with only one request taking longer than 4 seconds (without timeout) in January so far.
> Enable ap-and-oasys retry on timeout

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1DeliusBookingImportEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BackfillActiveSpaceBookingsCreatedInDelius.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingManagementInfoService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusReferralsSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/db/migration/all/20250127085455__add_delius_id_to_referral_imports.sql
- src/main/resources/db/migration/all/20250127085906__add_delius_id_to_space_bookings.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1BackfillActiveSpaceBookingsCreatedInDeliusTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1BookingToSpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1ImportDeliusReferralsTest.kt
This PR captures the Delius ID provided in the delius referral export when backfilling booking information from Delius for space bookings. It does this in two places
1. When migrating CAS1 legacy `Bookings` to `SpaceBookings`
2. When creating `SpaceBookings` for accepted referrals created directly in Delius
This will be used to provide a report to Delius of CAS1 bookings ID for backfilled bookings (point 2 above), allowing domain events to be processed
> Capture Delius ID when creating/backfill Space Bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusReferralsSeedJob.kt
Running the delius import seed job concurrently in preproduction is causing memory issues. Whilst we investigate and resolve we’re disabling this behaviour to unblock our ability to import delius referrals for testing
> APS-1796 - Disable concurrent seed jobs

- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
Just a miss, the TimeLineEventCntent Patyload gets pulled in by the domain events, the change was made by 'bala' in the _shared.yml and I guess our new cas2v2 api wasn't in yet.
> fix: includes a missed built api file for TimelineEventContentPayload

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/swagger/SwaggerConfiguration.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/resources/application-test.yml
We have found that the intial load of open api docs takes quite some time leading to ‘broken pipe’ errors, presumably because the client gives up and times out.
This commit preloads the open docs in all environments other than local. Local tests suggests that the initilisation runs concurrent from start, so shouldn’t have too much of an effect on startup times. Regardless, we have disabled this for local deployments where the endpoints are rarely used.
This commit also removes the CAS-specific open api docs that don’t include shared elements.
> Preload & Simplify Open Api Docs

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementMatchingOutcomesV2ReportTest.kt
Only users with a `CRU Member` role should have the ability to create a booking.
As all CRU users in production have the `CRU Member` role, we can remove this permission from the `Workflow Manager` role
**User with no CRU Member Roles**
**User with CRU Member Role**
**User with CRU Member Find and Book Beta Role**
> Remove BOOKING_CREATE perm from WORKFLOW_MANAGER

- .circleci/config.yml
We noticed that the config being used here was very different from the config in CAS UI repo itself. CAS3 UI Repo config looks fresher than this version and so we decided to update this one to match cas3 ui config
> Sync CAS3 Circle CI e2e config

- .circleci/config.yml
We cant just call `checkout` in circle ci becaus we need to checkout cas 3 repo and not the api repo.
Reintroduce steps that were removed as part of from https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/2893
> Clone CAS3 repo to run e2e in circle ci

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/TypedTask.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt
Placement requests were previously treated as tasks, meaning they can be allocated to specific users (similar to assessments and placement requests). This approach is no longer used and has been replaced by the CRU Dashboard.
This PR removes support for placement requests for the tasks endpoints.
A subsequent PR will remove the PlacementRequest reallocated_at and allocated_to properties from the code
> APS-1863 Remove placementRequest from tasks endpoint

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ImportDeliusReferralsSeedJob.kt
This commit makes fixes to the seed job concurrent procesisng to avoid memory issues, and subsequently re-enables concurrent processing for the `CAS1 Improt Delius Referrals Seed Job`.
The fix uses a semaphore to ensure there are only 5 processing or pending co-routines at any moment in time when processing the CSV. We found that if a coroutine was created for every row in the CSV immediately we encountered out of memory exceptions. Note that the import CSV file has 298132 rows.
If we to use a CSV reader that allowed us to stream the CSV rows instead of loading them all in to memory, this restricton may not be required.
The commit also configures locally ran instances of the service to have the same heap space as production (512MB)
> APS-1796 Re-enable concurrent process of delius import

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
This PR is to remove duplicate calls to delius to check if the user have access to the applications when calling Get `/applications` api endpoint
> CAS-486 Remove duplicate calls to delius when getting applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1TimelineService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ApprovedPremisesApplicationStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineNoteTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ApplicationTimelineTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PersonalTimelineTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1TimelineEventFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PersonalTimelineTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ApplicationTimelineTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PersonalTimelineTransformerTest.kt
[https://dsdmoj.atlassian.net/browse/APS-1857](url)
> APS-1857 Copied cas1 timeline api types to cas1 schema.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PlacementRequestSummaryTransformer.kt
- src/main/resources/static/api.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1813
As discussed on [APS-1804](https://dsdmoj.atlassian.net/browse/APS-1804) the /placement-requests/dashboard is very inefficient for a few reasons:
- returns more data than is actually required
- poor SQL optimisation, leading to many queries being ran per placement request. This is exacerbated by returning more data than required.
Task
- Design and implement a new GET `/cas1/placement-requests` endpoint. 
- Whilst we should aim to make it easy for the UI team to switch to this new endpoint, we should review all arguments passed in to determine if any are no longer required (`crn` and `apAreaId` are not used anymore, there may be others)
[APS-1804]: https://dsdmoj.atlassian.net/browse/APS-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
> APS-1813 new cas1 placement requests endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedRoomsFromSiteSurveyXlsxJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyPremiseFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1RoomsFromSiteSurveyXlsxTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1870
- Change `roomCode` calculation to `$qCode-$roomNumber`. Currently we introduce a space before/after the hyphen, which is not consistent with the CSV import
- Change `bedName` calculation to `${row.roomNumber} - ${row.bedNumber}` (note that there are spaces before/after the hyphen). Currently we’re just using the bed number
- Add validation to ensure all beds have unique names in a given premise. If they don’t, throw an error, halting processing of the row
- When reading Room Name and Bed Number, if the value is numeric, we need to format it to remove any decimal points.
> APS-1870 standardise site survey room import

- build.gradle.kts
Running the gradle openApiGenerate task currently results in the following issues:
"More than one inline schema specified in allOf:. Only the first one is recognized. All others are ignored."
Resolving these issues requires:
- upgrading the openAPI generator plugin version from 7.7 to 7.11
- setting new property `removeEnumValuePrefix = true`
See more information in the comment descriptions.
After these changes the gradle openApiGenerate task should run without complaining about the inline schema issues.
> chore/upgrade openapi plugin version from 7.7 to 7.11.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
Placement requests have not been assigned and treated as Tasks since February 2024.
For this reason, this commit removes placement requests from the workload calculations as they’ll always return a value of 0. It also deprecates the various task-specific fields on the `PlacementRequestEntity`
> APS-1863 Remove placement requests from task calculations

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1BedSummaryTransformer.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1BedSummaryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
Ref: [APS-1875](https://dsdmoj.atlassian.net/browse/APS-1875)
Create a new `cas1/premises/{premiseId}/beds` endpoint
This will be similar to the existing shared endpoint (`PremisesController.premisesPremisesIdBedsGet`), but it should return what is required for the beds list screen. Create a `Cas1PremisesBedSummary` type for this. Also note that the existing SQL loads information about CAS3 load beds. This is not required
[APS-1875]: https://dsdmoj.atlassian.net/browse/APS-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APS-1875 - Add new Cas1PremisesBedSummary type.

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3PremisesServiceTest.kt
This PR CAS1312 is to prevent users from archiving a property when there are a booking in provisional, confirmed, or active status. 
I added it as a feature until the UI done their change to handle the Api response
> CAS-1312 Prevent users from archiving a property with an existing bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
This commit changes how we retrieve other space bookings for a given premise and CRN:
* limit the results to 100 - there should never be this many bookings at a premise for a CRN. Adding this limit helps us minimise ‘false negative’ perforamnce issues when loading testing with a single CRN
* move sorting into kotlin. Given that the results will always be quite small, it’s faster to sort in kotlin
> APS-1943 - Optimise CAS1 ‘other space bookings’ query

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningModelsFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/planning/SpacePlanningModelsFactoryTest.kt
This PR also adds some regression tests and some additional checks to protect `spaceBookingsForEachDay` from callers providing cancelled bookings
> APS-1970 Capacity Calculation should consider non arrivals

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2UserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TurnaroundTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt
This [PR CAS-1455](https://dsdmoj.atlassian.net/browse/CAS-1455) is to link the CAS3 booking service with the controllers and remove getBookings function until split the controllers
> CAS-1445 Link CAS3 Booking Service with Controllers

- src/main/resources/application.yml
Before this commit no timeout is set on SQL queries. This means that code waiting on locks can hang for an indeterminate length of time. It would be preferrable if such code errored after a reasonable wait, which also helps investigate timeout issues as we’ll be alerted to the timeout.
This change was tested by adding the following SQL query into an API request:
```
@Query(value = "select count(*) from pg_sleep(120)", nativeQuery = true)
fun slowQuery(): Unit
```
The request timeed out after 60 seonds:
```
org.springframework.dao.QueryTimeoutException: JDBC exception executing SQL [select count(*) from pg_sleep(120)] [ERROR: canceling statement due to user request] [n/a]; SQL [n/a]
```
resulting in a 500 being returned
```
GET /cas1/reference-data/departure-reasons - 500
Request took …
```
> Set SQL timeout of 60 seconds

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationV2ReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1RequestForPlacementReportRepository.kt
This PR replaces LEFT OUTER JOINs with more efficient LEFT OUTER JOIN LATERAL joins, allowing us to better filter subquery results within the subquery itself
> Use Lateral Joins in CAS1 Reports

- README.md
- src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/ApplyJourneyStressSimulation.kt
- src/gatling/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/gatling/simulations/BookingsTimeSimulation.kt
The Gatling load tests in this repository are now deprecated as we have migrated load tests to the new `hmpps-load-testing-probation` repo
> Deprecate load tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This is required when showing space bookings on the view placement request screen.
This does add some redundancy when retreiving space bookings when viewing a premise, but this has minimal database overhead as we only fetch the premise once in `Cas1SpaceBookingService`
Captured output locally:
```
{
"id": "090d86ad-2e3f-4cb8-a780-d8cb20d5d45d",
"person": {
"name": "Aadland Bertrand",
"isRestricted": false,
"crn": "X320741",
"personType": "FullPersonSummary"
},
"premises": {
"id": "d8d0f07b-6e91-42db-b397-b1159de911fc",
"name": "SWSC Men Premise 1"
},
"canonicalArrivalDate": "2028-05-12",
"canonicalDepartureDate": "2028-07-06",
"expectedArrivalDate": "2028-05-12",
"expectedDepartureDate": "2028-07-06",
"characteristics": [],
"actualArrivalDate": null,
"actualDepartureDate": null, …
```
> Add premises to Cas1SpaceBookingSummary

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/RoomEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UpdateRoomCodesJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedRoomsFromSiteSurveyXlsxJob.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenARoom.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApprovedPremises.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1UpdateRoomCodesJobTest.kt
When the room codes for NE premises were initially loaded, they used a room code prefixed with a value that isn’t included in the site surveys (i.e. they don’t use QCodes). This commit adds a migration job to update those room codes to match the format expected if loaded from the site surveys
> Add migration job to fix CAS1 room codes

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementMatchingOutcomesV2ReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
Before this commit we excluded withdrawn requests for placement from the placement matching outcome report. Because any ‘not matched’ request for placment is withdrawn once the arrival date has passed, this meant we never saw ‘not matched’ entries in historical reports.
This commit now included entries where the request for placement was subsequently withdrawn
> APS-2025 - Add withdrawn entries to placement matching report

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedTestBase.kt
The following options are redundant as they’re set by default on`files.writeString`
```
StandardOpenOption.CREATE,
StandardOpenOption.TRUNCATE_EXISTING
```
> Simplify test CSV creation

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationV2ReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1ApplicationV2ReportTest.kt
This commit updates the CAS1 Application Report V2 to use first class fields to determine the following:
* initial_assessor_agree_with_short_notice_reason
* initial_assessor_reason_for_late_application
* initial_assessor_reason_for_late_application_detail
This removes the last bit of code that was reading the assessment data JSON directly which was a) inefficient as we’re not using JSONb and b) should be treated as a black box by the API as is liable to structurely change
> APS-1966 Use 1st class properties for short notice reports

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1921
_First:_
Rewrite the existing query as-is to use a CTE that returns all placement requests meeting the criteria other than status, but does outputs a status value
Use that first query as input into the second query that will then apply any status filtering, if required, removing duplication of status logic
_Then:_
Update the first query to output fields required for the change required on this ticket e.g.
- booking_arrival
- booking_premises_name
- space_booking_arrival
- space_booking_premise_name
Then in the second query add logic to pick the non null values to output (either booking or space booking)
Also see Slack chat [here](https://mojdt.slack.com/archives/C03K0HB0LBE/p1739185989519529).
> APS-1921 SQL modifications for allForCas1Dashboard()

- src/main/resources/static/_shared.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
The UI is going to stop using these in favour of expected and actual arrival/departure dates
> Deprecate space booking canonical date API fields

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt
To simplify the space search API we want to remove `Cas1SpaceSearchRequirements`. Before this commit only one of the 4 properties in this class were being used.
This commit deprecates all fields on `Cas1SpaceSearchRequirements` and introduces a new `spaceCharacteristics` property on `Cas1SpaceSearchParameters` to replace the deprecated field
> Deprecate Cas1SpaceSearchRequirements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderRisksService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderRisksServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
The PR renames `OffenderRisksDataSource` to `OffenderRisksService`. A subsequent commit will move the function in `OffenderService` into `OffenderRisksService` and callers will call the `OffenderRisksService` directly.
This is part of work to make the `OffenderService` smaller, more manageable and more cohesive.
This PR also adds a missing regression test around retrieving offender risks for LAOs
> Create Offender Risks Service

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationCas1DomainEventServiceTest.kt
This PR removes usage of `offenderService.getRisks` and instead calls the `offenderRiskService` directly. this removes several redundant calls that retrieve the offender
> APS-2036 remove redundant calls when retrieving risks

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
Note that the `premisesPremisesIdBookingsGet` function updated in PremisesController now uses the CAS3 strategy as the function is only ever called by CAS3 (previously it included CAS1 logic)
> Remove use of deprecated offender functions

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2027
- Add deliusEventNumber to Cas1SpaceBookingSummary.
- Add deliusEventNumber to transformToSummary() which transforms Cas1SpaceBookingEntity to Cas1SpaceBookingSummary.
- Update associated transformToSummary transformer unit test.
- Add deliusEventNumber to Cas1SpaceBookingSearchResult type.
- Add deliusEventNumber to transformSearchResultToSummary() which transforms Cas1SpaceBookingSearchResult to Cas1SpaceBookingSummary.
- Update associated transformSearchResultToSummary transformer unit test.
Acceptance criteria (unit tests only) discussed in this associated Slack correspondence: https://mojdt.slack.com/archives/C03K0HB0LBE/p1740585245549299
> APS-2027 - Add deliusEventNumber to Cas1SpaceBookingSummary.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1OffenderEntity.kt
- src/main/resources/db/migration/all/20250303081728__add_cas1_offender_table.sql
[https://dsdmoj.atlassian.net/browse/APS-2021](url)
> APS-2021: Cas1 offender entity.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3PremisesSummaryTransformer.kt
- src/main/resources/static/api.yml
- src/main/resources/static/cas3-api.yml
- src/main/resources/static/cas3-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3PremisesSummaryTransformerTest.kt
This [PR CAS-1385](https://dsdmoj.atlassian.net/browse/CAS-1385) is : 
- To create a new CAS3 premises summary Api endpoint 
- Depreciate the existing one as is used currently only by CAS3
- The exiting premises summary Api endpoint will be removed after CAS3 UI will migrate to use the new one
> CAS-1385 Create CAS3 premises summary api endpoint

- .dependencycheckignore
- build.gradle.kts
This issue only effects the gatling classpath, which is not deployed to production.
There is not currently a fix for this issue, but in time the gatling module will be removed as it has been superseded by https://github.com/ministryofjustice/:hmpps-load-testing-probation
> Suppress pebble CVE

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1BedDetailTransformer.kt
- src/main/resources/static/api.yml
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1BedDetailTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1BedDetailTransformerTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2014
- Create a new `/cas1/premises/{premisesId}/beds/{bedId}` endpoint that returns a `Cas1BedDetail`.
- `Cas1BedDetail` will be the same as `BedDetail` but characteristics will be a list of `Cas1SpaceCharacteristic`
- Deprecate `/premises/{premisesId}/beds/{bedId}` and add a note saying `/cas1/premises/{premisesId}/beds/{bedId}` should be used
> APS-2014 remove characteristic pairs

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This commit ensures `actualArrivalDate` and `actualDepartureDate` are populated on `Cas1SpaceBookingSummary` when mapped from a `Cas1SpaceBookingEntity`. It also adds some missing tests for mappings.
> Populate actual dates on Cas1SpaceBookingSummary

- build.gradle.kts
Commit aa4d15e09fa0f68ae6dc49a75017930536c81508 added an ignore list for the owasp dependency check plugin. This led to errors when building, presumably due to it causing a mismatch between the plugin version used in gradle and the cached CVE database. This commit pins the version of the plugin to the latest available version which appears to resolve these issues
> Pin OWASP Dep Check Version

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
Typically we reduce the timeout time based upon production data on response times. For ap-and-delius some reponses take up to 9 seconds (due to large bulk requests for offender information), so the default timeout of 10 seconds is suitable
> Enable retry on timeout for ap-and-delius

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedRoomsFromSiteSurveyXlsxJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1RoomsFromSiteSurveyXlsxTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DataFrameUtils.kt
Before this commit site survey imports fails the first time it tries to create a bed when one already exists in a different room. Now it checks all beds before failing, making it easier to find all issues in a single attempt.
> Collate existing room errors on site survey import 

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-1908
GET /cas1/placement-requests
The SQL `PlacementRequestEntity.allForCas1Dashboard` assumes that there is only one active booking/space booking associated with a placement request. Update it to use the space booking with the earliest arrival date when populating bookingArrivalDate and bookingPremisesName.
> APS-1908 Return earliest space booking records

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1OutOfServiceBedsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OutOfServiceBedTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2063
- Add an CAS1_OUT_OF_SERVICE_BED_CANCEL permission.
- Add this permission to the CAS1_CRU_MEMBER_FIND_AND_BOOK_BETA role
- Update the /premises/{premisesId}/out-of-service-beds/{outOfServiceBedId}/cancellations endpoint to require this permission
- Update tests to use CAS1_CRU_MEMBER_FIND_AND_BOOK_BETA instead of CAS1_FUTURE_MANAGER
- Remove CAS1_CRU_MEMBER_ENABLE_OUT_OF_SERVICE_BEDS from cancel bed test
> APS-2063 Add CAS1_OUT_OF_SERVICE_BED_CANCEL permission

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/Cas1OutOfServiceBedsReportGenerator.kt
- src/main/resources/db/migration/all/20250310140644__add_bed_on_hold_to_out_of_service_beds_reasons.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1OutOfServiceBedsReportTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2064
Ref: https://dsdmoj.atlassian.net/browse/APS-2065
- Add a new entry to `cas1_out_of_service_bed_reasons` with the name ‘Bed on hold’
- Update the out of service bed report (`Cas1OutOfServiceBedsReportGenerator`) to exclude any entries where the reason for the bed being out of service is ‘Bed on hold’. To do this hardcode the ‘Bed on hold’ ID in the code.
'Bed on Hold' appears as a reason in the UI automatically when creating an out of service bed:
The 'Bed on hold' reason is also shown when viewing the list of out of service beds:
'Bed on hold' is also shown as the reason when viewing the out of service bed record itself:
> APS-2064 & APS-2065 Add bed on hold

- .circleci/config.yml
* Config to run new `cas3_e2e_playwright_tests` job in API pipeline
* This job will run alongside `cas3_e2e_tests` until `cas3_e2e_playwright_tests` has full replaced it - currently the new one covers the reporting e2e tests which have now been removed from the e2e tests run by `cas3_e2e_tests`. 
* This will be the approach going forward (add to one / remove from the other)
> Pipeline Config for new cas3_e2e_playwright_tests job

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
This commit updates the `offenderService.isLao` function to use `apDeliusContextApiClient` client directly instead of via the now deprecated `offenderDetailsDataSource`
> Remove use of deprecate code in isLao

- src/main/resources/db/migration/all/20250312105010__update_cas1_delius_reason_codes.sql
Arrested / In custody / Recalled - Code ‘1H’. (there are other entries with 1H, leave as is)
Admitted to hospital - Code 'H'
CAS2 - Code ‘CAS2’
CAS3 - Code ‘CAS3’
Positive alcohol test/ use (Breach / Recall) - Code ‘PAT’
Behaviour/ increasing risk in AP (Breach / Recall) - Code 'D' (we have an existing entry 'Behaviour / increasing risk'. Relabel and revive this entry)
> APS-1877 Add missing delius reason codes for CAS1

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingManagementInfoService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1BookingManagementInfoServiceTest.kt
When converting bookings to space bookings we look up the `NonArrivalReason` using the legacy code provided in the delius referral import.
We have recently introduced multiple entries in the `non_arrival_reason_codes` table for delius code ‘1H’. This leads to an error when importing bookings with these non arrival reasons:
`Query did not return a unique result: 2 results were returned`
This commit updates the booking to space bookings code to use a specific reason code when `1H` is encountered, avoiding the aforementioned error
> Booking to Space Booking Non Arrival Code Fix

- .circleci/config.yml
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-140?atlOrigin=eyJpIjoiMmM1MzMxYTVkYjI2NDg5YTg3NGZlNDVmMmFjNTE3NzUiLCJwIjoiaiJ9)
As we have a new CAS2 Bail repo making use of the API (namespace `CAS2V2`) we want to add the Bail e2e tests to the list of tests that are run before deploying to pre-prod to avoid regressions.
As no pre-prod or prod environments are currently in use for CAS2 Bail, this step is not required to pass before deploying to pre-prod, but will be the case in the future.
> Run CAS2 Bail e2e tests after deploying to dev

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
If a space booking has a non arrival recorded it shouldn’t be possible to withdraw/cancel it. Furthermore, any related placement request or application should not be withdrawable (as per the current behaviour for space bookings with an arrival)
> Block withdrawal for non-arrived space bookings

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/Cas1OutOfServiceBedsReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1OutOfServiceBedsReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/Cas1OutOfServiceBedReportGeneratorTest.kt
Before this PR the complete list of Beds across all CASs was passed to the `Cas1OutOfServiceBedReportGenerator` for consideration. This PR only passes Beds to the `Cas1OutOfServiceBedReportGenerator` where they have an associated out of service bed entity. This should considerably speed up the report generation time
This considerably decreases the size of the input to the report. The report itself is still inefficient and would be better implemented via SQL that only considers records within the given time frame, instead of starting with a large set of beds and then checking each one to see if there’s an OOSB within the given time frame
> APS-2061 - Optimise OOSB Bed Report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
This simplifies UI testing and logically any CRU member with access to the find and book beta should also have access to out of service beds. We’ve checked current permissons and all beta users have future manager, which also has this permission.
> Give all OOSB permissions to Find and Book Beta Role

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/DomainEventUrlConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2v2/Cas2v2SubmittedApplicationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2v2/Cas2v2StartupScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2StatusUpdateService.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/main/resources/db/seed/local+dev+test/cas2v2_application_data/document_A1234AX.json
- src/main/resources/static/cas2-domain-events-api.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2StatusUpdateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2SubmissionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2v2/Cas2v2ApplicationServiceTest.kt
We need to back out the change to domain events and find a different way for differentiate the cas2v2 submitted applications
> Revert cba 400

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequirementsEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequirementsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequirementsEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS1SubjectAccessRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt
Before this PR we were using an enum generated from API specs to map `ApType` and `Gender` on `PlacementRequirement`. This is a problem because we’re also using ordinal based mapping in the database, instead of name based mappings. This means if the ordering of the generated enum changes, then subsequent retrievals from the database could be wrong.
This commit doesn’t fix the ordinal mapping issue, but does introduce internal manually created enums with a warning comment making it less likely for the ordering of the enum to be changed.
> Use internal enum for PlacementRequest Ap Type

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedUtilisationReportRepository.kt
This [PR CAS-1501](https://dsdmoj.atlassian.net/browse/CAS-1501) is to include the bedspaces without created at date in the occupancy report
> CAS-1501 CAS3 Occupancy report to include bedspaces without created at date

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt
Before this PR, when checking if a proposed departure date is after the booking’s arrivals date, we would compare it to the expected arrival date. This is not the correct behaviour if an arrival has occurred. In that case we should compare it to the actual arrival date.
Local testing of this is shown below:
* Create booking 15/1/2030 - 25/1/2030
* Change to 16/1/2030 - 26/1/2030
* Record arrival for 5/1/2025
* Change end date to 6/1/2025
> APS-2137 Update space booking amendment validation bug

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2v2/Cas2v2ApplicationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2v2/Cas2v2PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2v2/Cas2v2SubmissionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2OffenderService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2SubmissionTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2v2/Cas2v2ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2v2/Cas2v2OffenderServiceTest.kt
feat: remove exclusion restriction globally in cas2 bail
> CBA-411-cas-2-assessor-cannot-view-an-application-submitted-for-a-crn-with-an-exclusion

- helm_deploy/values-dev.yaml
this change was applied incorrectly as the configuration was added to the `env` section instead of the `namespace_secrets` section
> APS-2109 Use secret for dev app insight connection string

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/DomainEventUrlConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/scheduled/Cas1ExpiredApplicationsScheduledJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/DailyMetricsReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestCas1DomainEventServiceTest.kt
This commit adds a new boolean property `DomainEventType.emittable` used to indicate if any domain events of this type are emittable. This is currently only used by CAS1.
This commit updates the logic in `Cas1DomainEventService` to observe this logic and updates `APPROVED_PREMISES_REQUEST_FOR_PLACEMENT_CREATED.emittable` to false, to give us a domain event type to use in our tests.
Subsequent commits will set `emittable` to true for all domain event types that are never currently emitted
> APS-2154 Add DomainEventType.emittable config

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1CruManagementAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1CruManagementAreaSeedJob.kt
- src/main/resources/db/migration/all/20250327095253__add_cas1_cru_management_area_auto_allocation.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1CruManagementAreaEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1CruManagementAreaTest.kt
https://dsdmoj.atlassian.net/browse/APS-2156
This commit updates the `Cas1CruManagementAreaEntity` to include day specific assessment allocation configuration. This is not currently used by code.
Once these allocations are used by the code, the existing `assessment_auto_allocation_username` value will be removed.
> APS-2156 Add day specific assessment auto allocation configuration

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3DomainEventService.kt
- src/main/resources/db/migration/all/20250328142746__add_cas1_placement_request_id_to_domain_event.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DomainEventEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventServiceTest.kt
https://dsdmoj.atlassian.net/browse/APS-2168
With the introduction of cas1 change requests it’s likely we’ll need a way to group domain events relates to a given placement requuest. We currently use Domain Event Meta data to do this reporting, but it’s not an efficient way to query the data.
This commit adds a new indexed column `domain_events.cas1_placement_requests` to resolve these issues
> APS-2168 - Add placement_request_id to domain_events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/scheduled/Cas1ExpiredApplicationsScheduledJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventServiceTest.kt
This PR simplifies how domain events are persisted by moving previously bespoke arguments 'trigger source' and 'emit' into the internal `DomainEvent` model, making the 'save domain event' functions take one-and-only-one argument - the internal `DomainEvent` model.
> APS-2154 Simplify CAS1 domain event persistence

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskDeadlineService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/DatesTest.kt
See https://dsdmoj.atlassian.net/browse/APS-1373
When we send an email related to an emergency assessment we are showing the deadline time as 10am, despite is being 11am local time. This issue only start happening after the change to british summer time (UTC+1).
We are persisting deadlines correctly in the database, but when we render this time in the assessment allocated email we formatting with specifying any timezone information the offset associated with the deadline is being used (UTC).
This commit changes time in email rendering to use Europe/London.
For consistency the `OffsetDataTime` should probably be created with a Europe/London offset, but equally anything rendering the time shouldn’t assume the given `OffsetDateTime` is in the required timezone.
> APS-1373 Fix CAS1 deadline time for emergency assessments

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1CruManagementAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/allocations/rules/EmergencyAndShortNoticeAssessmentRule.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1CruManagementAreaEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1CruManagementArea.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/MutableClockConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/allocations/rules/EmergencyAndShortNoticeAssessmentRuleTest.kt
https://dsdmoj.atlassian.net/browse/APS-2156
This commit changes the emergency and short notice automatic assessment allocation logic to use the day-specific allocation configuration.
This commit deprecates the old allocation configuration. This will be removed once this change has gone live without any issues
> APS-2156 - Use day-specific assessment auto allocation config

- src/main/resources/db/migration/dev/R__9_cas1_cru_management_areas.sql
- src/main/resources/db/migration/local/R__4_cas1_cru_management_areas.sql
We have recently changed CAS1 assessment auto allocation to be day-specific. This commit adds configuration for the local and dev environment to fix end to end tests.
> APS-2156 Add day-specific auto alloc config for dev/test

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2v2/Cas2v2SubjectAccessRequestRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/subjectaccessrequests/SubjectAccessRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas2v2/Cas2v2ApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas2v2/Cas2v2NoteEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas2v2/Cas2v2StatusUpdateDetailEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS2SubjectAccessRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas2v2IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SubjectAccessRequestServiceTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2SubjectAccessRequestServiceTest.kt
The SubjectAccessRequestService has an existing function getSarResult. That calls three other functions:
getCAS1Result
getCAS2Result
getCAS3Result
Each one calls a different repository to load data about applications for the respective service.
We have added getCAS2v2Result. Following the existing pattern this new function calls a specific Cas2v2SubjectAccessRequestRepository. Here we search for applications, assesments, notes, status updates using cas_2_v2_applications and cas_2_v2_users.
We have extended the existing Cas2v2ApplicationEntityFactory and created two new factories - Cas2v2NoteEntityFactory, Cas2v2StatusUpdateDetailFactory.
We found a test in CAS2SubjectAccessRequestServiceTest which had no annotation so wasn't being run. We've annotated it.
We extended the …
> Cba 431 create a sar endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AppealService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AppealServiceTest.kt
This PR ensures that the application has a status of ‘rejected’ when creating an appeal. This fixes a bug we have observed where multiple users can create an appeal for the same application if they don’t navigate away from the application page.
This PR also removes deprecated code and replaces it with `CasResult`
> APS-2178 - Check application status when creating an appeal

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Cas1UserRoleJsonFileGenerator.kt
- src/main/resources/static/codegen/built-cas1-roles.json
Before this commit the `built-cas1-roles.json` wasn’t putting linebreaks for each entry in the array, leading to merge conflicts for small permission changes.
This commit tweaks the object mapper configuration to add these line breaks, which will hopefully reduce merge conflicts and also make the file more readible. It also sorts permissions alphabetically to further avoid merge issues
> Improve `built-cas1-roles.json` formatting

- src/main/resources/application-debug.yml
This is temporary additionl whilst we’re making changes to ap-tools. It allows us to simply enable debug logging whilst using profiles other than ‘local’
> Add a debug profile

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/Cas2ApplicationServiceTest.kt
**PR summary**
* There are cases we have found where an application has no status updates linked to it. 
* Under these circumstances we now assign the application and send the required emails
> Prison transfers - assign application if no status update linked

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2v2/Cas2v2ReferenceDataController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2PersistedApplicationStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2PersistedApplicationStatusDetail.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2PersistedApplicationStatusFinder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2v2PersistedApplicationStatusFinder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2StatusUpdateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas2StatusUpdateEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas2v2/Cas2v2StatusUpdateEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2ReferenceDataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2StatusUpdateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/model/reference/Cas2PersistedApplicationStatusFinderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/StatusUpdateTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2v2/Cas2v2StatusUpdateTransformerTest.kt
In the Bail UI we inherit the status updates from CAS2. These are defined in code [here](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt)
This list needs to be changed as set out in [this ticket](https://dsdmoj.atlassian.net/browse/CBA-434). Since some fields don't make sense for the different services, e.g. HDC licence and CPP details (CAS2) or  Previous unspent convictions (Bail), we need to differentiate the updates. The updates are referenced by UUID in other areas of the code, e.g. the [live applications SQL for the application repository](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/main/src/main/resources/db/migration/al …
> CBA-434-implement-new-status-details-content-in-assessor-view

- src/main/resources/application.yml
Because we have both spring data redis and spring data jpa installed, we see many of the following warnings on startup:
```
Spring Data Redis - Could not safely identify store assignment for repository candidate interface uk.gov.justice.digital.hmpps.approvedpremisesapi.jpa.entity.ApAreaRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
```
It’s not clear why we’re seeing this, because the repositories its referring to are of type `JpaRepository`.
Regardless, we can stop this warning by disabling repository support for …
> Disable spring data redis repositories

- helm_deploy/values-dev.yaml
- src/main/resources/db/migration/dev-truncate/R__1_truncate_cas2.sql
- src/main/resources/db/migration/dev-truncate/R__2_truncate_cas3.sql
- src/main/resources/db/migration/dev/R__1_create_premises.sql
- src/main/resources/db/migration/dev/R__4_create_rooms_and_beds.sql
- src/main/resources/db/migration/dev/R__6_clear_cas2_applications.sql
- src/main/resources/db/migration/dev/R__7_clear_cas2_domain_events.sql
Before this commit any environment using the `dev` profile would truncate various tables truncated whenever the API starts.
This commit moves the truncation SQL into a new folder and old applies that folder for deployments to the ‘dev’ environment on the MOJ cloud platform. Any local deployments using the `dev` profile wll no longer truncate tables on startup.
This will break any deployments using the `dev` profile. To fix this, run the following:
```
delete from flyway_migrations where script = 'R__3_clear_applications.sql';
delete from flyway_migrations where script = 'R__6_clear_cas2_applications.sql';
delete from flyway_migrations where script = 'R__7_clear_cas2_domain_events.sql';
```
> Make truncation optional for dev profile

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3BookingGapReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3TurnaroundEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedUtilisationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3TurnaroundTransformer.kt
- src/main/resources/db/migration/all/20250408132209__add_prefix_cas3_to_turnarounds_table.sql
- src/main/resources/db/migration/dev/R__5_create_bookings_for_cas3_eofe.sql
- src/main/resources/db/migration/dev/R__5_create_bookings_for_cas3_kss.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas3/Cas3TurnaroundEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3BedspaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas3TurnaroundTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUsageReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BedSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3TurnaroundTransformerTest.kt
Move turnaround to CAS3 namespace and rename table and entity
> Firebreak Move turnaround to CAS3 namespace

- src/main/resources/application.yml
Before this commit we would see the following message several times on startup
```
Missing cache[uk.gov.justice.digital.hmpps.approvedpremisesapi.jpa.entity.LocalAuthorityAreaEntity] was created on-the-fly. The created cache will use a provider-specific default configuration: make sure you defined one. You can disable this warning by setting 'hibernate.javax.cache.missing_cache_strategy' to 'create'. |
```
This commit disables this warning as this is the behaviour we want, and we have set the default cache settings in `hibernate-ehcache.xml`
> Suppress hibernate 2nd level cache warning

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3ConfirmationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3FutureBookingsReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedUtilisationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BookingsReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3ConfirmationTransformer.kt
- src/main/resources/db/migration/all/20250408161202__add_prefix_cas3_to_confirmations_table.sql
- src/main/resources/db/migration/dev/R__5_create_bookings_for_cas3_eofe.sql
- src/main/resources/db/migration/dev/R__5_create_bookings_for_cas3_kss.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas3/Cas3ConfirmationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/MigrateBookingStatusTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas3ConfirmationTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BookingsReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3ConfirmationTransformerTest.kt
This PR is to move confirmations to Cas3 namespace and rename table and entity
> Firebreak move confirmations to Cas3 namespace

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PersonalTimelineTest.kt
Whilst we limit the number of applications returned to the timeline to 50, before this commit we were still loading them into memory.
This commit ensures we only ever load a maximum of 50 applications (and 50 offline applications) into memory when loading the timeline.
The solution isn’t perfect - we could theoretically load 50 regular applications and 50 offline applications into memory, despite only returning 50 of those combined. Given this logic is a fix to handle large timelines when running performance tests reusing the same CRN, this is deemed acceptable.
> Limit applications loaded into memory when loading the CAS1 timeline

- src/main/resources/db/migration/test/20230802101239__remove_users.sql
- src/main/resources/db/migration/test/20230802101240__remove_bookings.sql
These migrations only apply to the test environment.
They remove users and bookings, but reviewing the `all` migrations applied before these, neither add users or bookings. I suspect these migrations were added as a way to clear down the test environment, which should have really be done as a one-off direct SQL execution
> Remove unnecessary test migrations

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1StartupScript.kt
As we’re moving to using the dev profile locally this ensures there’s a draft application available in dev
> Create draft CAS1 application for dev profile

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DestinationProviderEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/JsonSchemaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LocalAuthorityAreaEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PostCodeDistrictEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationAreaProbationRegionMappingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationDeliveryUnitEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationRegionEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ReferralRejectionReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestRejectionReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3VoidBedspaceReasonEntity.kt
This resolves the warning we see on startup…
```
org.hibernate.orm.cache                  : HHH90001003: Read-only caching was requested for mutable entity
```
There are a few ‘read only’ entities that have not been tagged as Immutable because some integraton tests rely on being able to update them via JPA/hibernate (caching is enabled for integration tests). Ideally we’d update these tests to not use the JPA model directly if writing to the database
> Mark read only entities as immutable

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventWorker.kt
- src/main/resources/application-local.yml
- src/main/resources/application-localdev.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventWorkerTest.kt
- src/test/resources/application-test.yml
The async-save code was added to potentially improve perforamnce when persisting domain events. Load testing shows that other areas of the application typically cause performance issues (i.e. the database), and as such this code has never been used. This commit removes this code.
> Remove unused async domain event code

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
This change will allow the domain events in CAS2V2 to correctly display the URLs instead of localhost
This will be tested manually in ndelius preprod to verify it's working and monitored closely in prod
> Add the domain event url variables for test, preprod, and prod

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt
https://dsdmoj.atlassian.net/browse/APS-2196
The get case detail cache retains offence information for a given CRN. Before this commit it was cached for 6 hours, which causes issues for emergency referrals where an event has been created very recently.
This commit changes the TTL from 6 hours to 10 minutes.
> APS-2196 Change ‘get case detail’ cache TTL to 10 minutes

- helm_deploy/values-dev.yaml
- helm_deploy/values-test.yaml
We recently added a seed config for dev & test environments only, better defining the CAS1 & CAS3 tests users, removing any roles they shouldn’t have. This commit ensures that config is used in the dev & test environments
> Use dev+test seed in dev & test environments

- detekt.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
- src/main/resources/db/migration/all/20250416134643__add_resolved_to_change_requests.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1ChangeRequestEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1ChangeRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
This commit adds a boolean `resolved` to the change request entity, used to indicate if a change request is resolved. This is requried to support ‘closing’ a change request if the corresponding placement is cancelled, or in a state such that the change request is no longer relevant.
A change request will be resolved if
- It’s accepted
- It’s rejected
- The corresponding placement is in a state such that the change request is no longer relevant
This commit also removes the `decision made at` value and replaces it with `resolved at`, which will be the same date/time.
> Add `cas1_change_requests.resolved`

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationV2ReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1ApplicationV2ReportTest.kt
https://dsdmoj.atlassian.net/browse/APS-2186
This commits updates the application report to provide the value of `situation` for the `release type` column if the value of `releaseType` is `inCommunity`. This reflects the fact that users are asked to select a secondary ‘sub option’ when chosing `inCommunity` on the UI
> APS-2186 - Update release type logic for CAS1 app report

- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
This commit removes the `premises` property from `Cas1TimelineEventContentPayload` as it will not apply to all payload types. It moves it onto the individual payload definitions where required.
> APS-2186 Simplify `Cas1TimelineEventContentPayload`

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2149
**Planned transfer specific logic:**
A planned transfer cannot be created (and must return an error) in the following scenarios:
- booking has not been marked as arrived
- booking has been marked as non arrived
- booking has been marked as departed
- booking has been cancelled
**Appeal specific logic:**
An appeal cannot be created and must return an error in the following scenarios:
- booking has been marked as arrived
- booking has been marked as non arrived
- booking has been cancelled
> APS-2149 Add specific validation logic and tests for appeals and planned transfers

- .circleci/config.yml
Users used for the E2E tests for CAS3 have been [updated in the UI repository](https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/pull/1279) -- this PR applies the same update to the configuration for this test running from the API. The relevant variables (`CAS3_E2E_...`) have now been added to the CircleCI config.
> Update CAS3 E2E users variables

- .circleci/config.yml
Env vars on CircleCI for the API follow the `CAS3_E2E_...` format. All env vars in test setup are now following this.
> Use correct env vars

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This is required to make logic in the front end more consistent wrt. space bookings that have been cancelled
> Add `isCancelled` to `Cas1SpaceBookingSummary`

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationReasonEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas1-roles.json
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2034
Following a discussion with @davidatkinsuk on 23/04/25 and based on some of the comments during review it was agreed to change some of the controller logic related to this PR.  The changes were essentially to add the approve appeal logic as a separate space booking appeal endpoint:
- Add new end point /cas1/premises/{premisesId}/space-bookings/{bookingId}/appeal
- Add new type Cas1ApprovedPlacementAppeal which is same as Cas1NewSpaceBookingCancellation but with a mandatory placementAppealChangeRequestId
- Create new controller function appeal() (which cancels space booking and approves change request), similar to cancelSpaceBooking()
- Make new controller function transactional.
---------------------
The original requirements were: …
> APS-2034 modify booking cancellation endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
- src/main/resources/static/cas2-schemas.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt
After discussion with @gregkhawkins  the only change the Backend is going to make is surface an additional field `omuEmailAddress`
which will always be populated with the offender management email address (from that big spreadsheet) and then the FE is going to do the relevant business logic to display it in the right way.
> CAS-1592 surfaced omuEmailAddress

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationAssessedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationExpiredEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationSubmittedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationWithdrawnEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/AssessmentAllocatedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/AssessmentAppealedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingCancelledEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingChangedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingKeyWorkerAssignedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingMadeEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingNotMadeEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/Cas1DomainEventEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/FurtherInformationRequestedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/MatchRequestWithdrawnEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PersonArrivedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PersonDepartedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PersonNotArrivedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PlacementApplicationAllocatedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PlacementApplicationWithdrawnEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/RequestForPlacementAssessedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/RequestForPlacementCreatedEnvelope.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
This commit updates all CAS1 domain event envelopes to use a common interface. This allows us to then define the envelope type associated with each domain event type on `DomainEventType`, ensure the referenced type is actually an envelope. We can then use this new configuration in the `Cas1DomainEventService` when unmarshalling domain event json without the need for a large, difficult to read `when` structure.
This helps us move towards to moving all high-level domain event configuration into the `DomainEventType`, making it much easier to understand what is required when adding a new domain event
> APS-2054 Introduce common domain event envelope interface

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ChangeRequestsController.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2208
https://dsdmoj.atlassian.net/browse/APS-1916 implemented a single end point for creating change requests.
It has been decided to split this existing endpoint into three separate endpoints, each of which will deal with the creation of a specific change request i.e. planned transfer, appeal and extensions.
The existing POST for creation of a change request is:
POST /cas1/placement-requests/{id}/change-requests
This will become three separate endpoints:
```
POST /cas1/placement-requests/{id}/change-requests/planned-transfer
POST /cas1/placement-requests/{id}/change-requests/appeal
POST /cas1/placement-requests/{id}/change-requests/extension
```
**_Note: creating an extension change request currently throws BadRequest as per the requirements …
> APS-2208 Add separate POST endpoints for appeals, transfers and extensions.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
Before this commit any user assessing a placement appeal also needed the `CAS1_SPACE_BOOKING_WITHDRAW` permission, alongside the `CAS1_PLACEMENT_APPEAL_ASSESS`. This commit modifies withdrawal permission checks to remove this requirement.
> APS-2024 - Tidy up PLACEMENT_APPEAL_ASSESS permissions

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskDeadlineService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskDeadlineServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2083
**Background**
The timeliness expectations for assessments are within 10 working days of allocation to an assessor.  This includes up to 5 working days for an information request to be made to Probation Practitioners where additional information is required to make a decision on suitability. Assessments for emergency applications (those submitted for arrivals within 7 days) will be assigned to the CRU Manager.  Where applications are submitted by 1pm, these should be assessed within 2 hours.  If submitted after 1pm, they should be completed no later than 11am on the following working day.   Assessments for short notice applications (those submitted for arrival between 8 and 28 days) will also be assigned to the CRU Manager.  These should …
> APS-2083 Update timeframes from 2 days to 5 days.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
This is to allow us to performance test moving space booking id from a dedicated column to metadata, enabling one-to-many relationships between domain events and space bookings, required for transfer domain events
> APS-2231 - Add `CAS1_SPACE_BOOKING_ID` metadata name

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AppealDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/scheduled/Cas1ExpiredApplicationsScheduledJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1BookingToSpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCasUpdateEventNumberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AppealCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventServiceTest.kt
The `Cas1DomainEvent` data class was being used when both saving and retrieving domain events, but most of the parameters were not being used when getting the domain event. 
This PR splits the class into separate get/save versions.
> APS-2057 - Stop using common class to get/save domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApAreaEntity.kt
- src/main/resources/db/migration/all/20250425115307__remove_unused_ap_area_columnns.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApAreaEntityFactory.kt
These have been moved to the `cas1_cru_management_areas` table
> APS-1363 - Remove unused ap_areas columns

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/db/migration/all/20250425123534__add_transfer_info_to_space_booking.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
We need to record if a space booking is an emergency or planned transfer to know if emails should be triggered on arrivals. This commit captures that information.
> APS-2227 - Add transfer info to space booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingActionsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingsActionsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
This commit adds the concept of actions, which are used to determine if a user can do something on a given entity (in this case space bookings). Actions have two purposes:
1. To provide the UI a list of available actions, allowing it to selectively render options
2. To check that a given action is allowed when it is attempted by a given user
This allows us to remove duplication of logic across the API and UI and change this logic in the API without needing UI changes.
Actions have been added for creating change requests
> Add Space Booking Actions

- .circleci/config.yml
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-551?atlOrigin=eyJpIjoiNzRlODNlNzAzMWU5NDk3YThlMDg5ZTM0OTNiMTlmYjkiLCJwIjoiaiJ9)
Previously this was non-blocking as CAS2 Bail hadn't launched into private beta. As this is now live code, these tests will be required to pass before deploying to preprod, bringing it in line with the other UIs.
> [CBA-551] Make CAS2 Bail e2e tests required for preprod deployment

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingChangedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/LegacyTimelineFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/BookingChangedTimelineFactoryTest.kt
Extract logic from the `DomainEventDescriber` class and put it into a standalone `LegacyTimelineFactory`. This is in preparation for making changes to the logic.
Both versions of the timeline rendering still work after this change:
> Refactor booking changed domain event describer

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ChangeRequestTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/StringHelpers.kt
- src/main/resources/db/migration/all/20250501171254__add_change_request_space_booking_index.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
Update `Cas1SpaceBookingSummary` to include a list of open change request types, replacing the current booleans `plannedTransferRequested` and `appealRequested`
> APS-2246 - Add a list of open change request types to booking summary

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UpdateEventNumberSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/asserter/DomainEventAsserter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
This commit ensures the ‘booking made’ emails and domain events are triggered for emergency and planned transfers.
> APS-2269 Trigger booking email/domain event for transfers

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ReportGenerator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
This also upgrades POI, resolving CVE CVE-2025-31672
A change was made in POI that meant it no longer observed the ordering of columns as provided to to the `toDataFrame` function. To fix this we explicitly call the `reorderColumnsBy` function on the dataframe
> Upgrade data frame

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
This commit allows emergency transfers to be backdated up to 7 days in the past
> APS-2269 Allow backdated emergency transfers

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingActionsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingsActionsServiceTest.kt
* Update actions to block transfer if an active transfer exists
* The validation logic in the emergency transfer function duplicates that `Cas1SpaceBookingActions`. This commit updates the function to reuse the actions logic.
> APS-2269 Update transfer action logic and reuse

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2249
API: Create a new Cas1SpaceBookingService.shortenSpaceBooking method in the service, if the departure date for the existing booking is after the departure date supplied in the Cas1ShortenSpaceBooking supplied then send the “[Booking Amendment](https://docs.google.com/spreadsheets/d/1vRzoK0NDLjmWT6p6DWAEbhV5kBudgRveTyEWJnT1PjE/edit?gid=1424773734#gid=1424773734)” email.
Recipients:
1. The probation practitioner who created the application
2. Application case manager
3. AP manager
4. The person who created the corresponding placement application (if applicable - this might not be the same person who created the application)
5. CRU inbox
> APS-2249 Send emails when space booking is shortened.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/DomainEventSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingChangedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/DomainEventUtils.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/EmergencyTransferCreatedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlacementAppealAcceptedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlacementAppealCreatedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlacementAppealRejectedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlannedTransferRequestAcceptedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlannedTransferRequestCreatedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlannedTransferRequestRejectedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ApplicationTimelineTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/BookingChangedTimelineFactoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ApplicationTimelineTransformerTest.kt
Before this commit schemaVersion was part of the domain-event-specific content payload. Because all domain events have a schema version, this has been moved to the `Cas1TimelineEvent`, reducing the amount of copy-paste code. It has been temporarily retained for the Booking Amended payload type because this field is currently in use by the UI
> APS-2267 - Always set timeline payload for booking changed event regardless of schema version

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementMatchingOutcomesV2ReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SimpleApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
This is being temporarily added until the placement report can report on all placements (i.e. once all regions have migrated to space bookings)
> APS-2275 Add placement id to matching outcomes report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1EmailUtils.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/springevent/ArrivalRecorded.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/MockCas1EmailNotificationService.kt
Emails are sent on arrival for any space booking that was created for an emergency transfer.
This commit introduces the user of spring events to ‘notify’ the email service that an arrival event has occurred. This minimises the amount of mocking required in the main service functions and better decouples services, simplifying unit testing
> APS-2227 - Send emergency transfer emails

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ApplicationTimelineTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ApplicationTimelineTransformerTest.kt
Before this commit we only provided a complete descritpion of the user that created a timeline event. This is overkill as the UI only needs the username. This commit deprecates the existing `createdBy` value and adds a new simpler `createdBySummary` value
> Add createdBySummary to timeline events

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1OutOfServiceBedsReportTest.kt
This commit updates the out of service bed report integration test to explicitly state assertions instead of deferring to a report generated by the code under test
> Improve OOSB Report Integration Test

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/springevent/BookingSpringEvents.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/ClockConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/allocations/rules/EmergencyAndShortNoticeAssessmentRuleTest.kt
Add internal event data classes when creating, amending or cancelling a space booking, in preparation for using spring events for 'intra service' communication, and in preparation for adding additional fields to these calls
> APS-2267 introduce internal booking events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3ApplicationTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3ApplicationTransformerTest.kt
This [PR CAS-1421](https://dsdmoj.atlassian.net/browse/CAS-1421) is to return the application in Rejected status when the HPT rejects the assessment linked to the CAS3 application
This will be behind a feature flag EATURE-FLAGS_CAS3-APPLICATIONS-INCLUDE-REJECTED-STATUS until the UI done the work to show it in a Rejected tab
> CAS-1421 Application status as Rejected when the assessment is rejected by HPT

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SpringEventPublisher.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestDomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/springevent/ChangeRequestSpringEvents.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestDomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
Update logic that triggers domain events and emails related to change requests to use spring events. This helps reduce the amount of mocking in unit tests and decouples code
> Use Spring Events for Change Request Logic

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventDescriber.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingCancelledTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingChangedTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingMadeTimelineFactory.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/DomainEventUtils.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventDescriberTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/BookingCancelledTimelineFactoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/BookingMadeTimelineFactoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/Cas1DomainEventTestUtils.kt
Move logic to build a timeline description for the ‘booking made’ and 'booking cancelled' timeline entries into a `LegacyTimelineFactory`, adding a payload to allow the UI to build the description going forward
timeline entries shown for a booking below (space bookings rendered similarily)
> APS-2267 add content payloads to booking domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ValidationErrors.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/CasResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/asserter/DomainEventAsserter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/asserter/EmailNotificationAsserter.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt
This PR refactors the code to reuse common logic for validation and application of updating and creating space bookings, ensuring that common domain events are raised for shortened bookings, emergency transfers and planned transfers.
> APS-2267 - Raise Common Domain Events and Emails for Shortened, Emergency Transfer & Planned Transfer

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2250
- ~~send booking changed domain event when booking is shortened~~
- remove "reason" from API type and associated logic since it is [no longer required](https://mojdt.slack.com/archives/C03K0HB0LBE/p1746523751781129?thread_ts=1745998375.954829&cid=C03K0HB0LBE)
- ~~refactor common update/shorten email logic~~
_NB. Previous PRs already merged have added in the feature to send a domain event when a booking is shortened, therefore this PR and ticket scope is reduced to removing reason for shortening a booking only._
> APS-2250 remove reason for shortening a booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingActionsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingActionsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
Ref: [APS-2278](https://dsdmoj.atlassian.net/browse/APS-2278)
Add shorten request action.
**Acceptance Criteria:**
- Given I don’t have the permission CAS1_SPACE_BOOKING_SHORTEN, when I access the endpoint then I am shown the message "User must have permission 'CAS1_SPACE_BOOKING_SHORTEN'"
- Given the space booking does not have an arrival marked against it, when I determine the list of Actions, then SHORTEN is an available action
- Given the space booking has a non arrival marked against it, when I determine the list of Actions, then SHORTEN is not an available action
- Given the space booking has an associated departure date, when I determine the list of Actions, then SHORTEN is not an available action
- Given the space booking has an associated cancellation, when I determine the list …
> APS-2278 Add shorten request action.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingCreateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingCreateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
This commit introduces a `ValidatedCreateBooking` that is now required to create a new space booking. This ensures the booking request is validated before being created.
The `ValidatedCreateBooking` contains the space booking that is going to be created. This is helpful because it provides us with access to the pre-persisted space booking, including its ID, which is required to fully populate related domain events (this is the primary motivator for this change)
> APS-2267 Enforce validation before creating a space booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CAS1SubjectAccessRequestRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequirementsEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequirementsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
- src/main/resources/db/migration/all/20250513174936__allow_null_placement_requirements_gender.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequirementsEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS1SubjectAccessRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1ApplicationV2ReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1RequestForPlacementReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequirementsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt
This field has been superseded by `approved_premises_applications.is_womens_application` and regardless, is always populated as male by the UI.
This commit removes the property from the entity model and API, and makes it nullable in the database for subsequent removal in a future commit once this change has been deployed
> APS-2148 - Remove PlacementRequirements.gender

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PremisesSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt
The UI no longer populates the `requirements` value, instead using `spaceCharacteristics` to provide filter criteria. This PR removes the `requirements` property and corresponding type
> APS-2300 Remove deprecated space search fields

- build.gradle.kts
As we’ll be removing the open api generation logic in the near future, this hack is good-enough to enable downloading sources
> Fix download sources in intellij

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingManagementInfoService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1BookingToSpaceBookingTest.kt
When migrating a booking to space booking, if the original booking doesn’t have a corresponding booking made domain event (i.e. for offline applications), populate its delius event number using the delius export
> APS-1633 - Backfill space booking event no. from delius info

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/WebClientCache.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/client/PreemptiveCacheTest.kt
If cache metadata states that a responseBody is available but that responseBody entry doesn’t exist in the cache, automatically remove the metadata from the cache as inconsistent state will not automatically resolve and we’ll always receive a `CachedValueUnavailable` error when attempting to retrieve from the cache until it’s hard TTL is reached.
We now also raise a sentry alert when this happens, as this really _shouldn’t_ happen
> APS-2318 Automatically remove corrupted cache metadata

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1UpdateActualArrivalDateSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SimpleApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1UpdateActualArrivalDateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1UpdateActualArrivalDateSeedJobTest.kt
This allows us to replay the domain event with the correct arrival date, if required.
> Update Arrival Job should also update domain event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/Cas2ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CAS2SubjectAccessRequestRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationSummaryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2SubmittedApplicationReport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2UnsubmittedApplicationsReport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2/SubmittedApplicationReportRow.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2ReportsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/Cas2ApplicationsTransformer.kt
- src/main/resources/db/migration/all/20250430103605__merge_cas2_application_entity_with_cas2v2_application_entity.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas2-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas2/Cas2ApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas2/Cas2ApplicationSummaryEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS2SubjectAccessRequestServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationEntityTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/Cas2ApplicationsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/Cas2ApplicationsTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2v2/Cas2V2ApplicationsTransformerTest.kt
https://dsdmoj.atlassian.net/browse/CBA-590
https://dsdmoj.atlassian.net/browse/CBA-626
https://dsdmoj.atlassian.net/browse/CBA-629
https://dsdmoj.atlassian.net/browse/CBA-639
This adds persistence for the new bail fields across cas2 application entities and summaries. It updates the application entity, transformer, service and controller.
There is a new value called applicationOrigin. This is populated in the 2 services with one of three values identifying the type of CAS2 application. This is already being prepopulated in CAS2 HDC - More info https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/5338431579/ADR+CAS2+Data+Change+-+Application+Origin
There is a new value called bailHearingDate. This is solely for CAS2 Bail so should be nullable. This is a primary value on the entities as it is …
> feature: cas2v2 entities, services, & transformers

- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2333
All the API paths for the new change-request objects have a format like `/cas1/placement-request/{placementRequestId}/appeal` whereas the original placement-request paths have the form `/cas1/placement-requests/{id}/withdrawal` (notice the plural for placement-requests). This inconsistency is rather messy to handle given the hierarchical structure of path definitions in the UI.
Since the API work is not live as yet, introducing this breaking change will not impact any users.
`s` added to `placement-request` for the following endpoints:
From:
GET /placement-request/change-requests
POST /placement-request/{placementRequestId}/planned-transfer
POST /placement-request/{placementRequestId}/appeal
POST …
> APS-2333 Make placement-requests urls consistent

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2v2/Cas2v2ApplicationTransformerTest.kt
This one's a beauty. The linter was failing because the file named Cas2V2ApplicationsTransformerTest.kt contains the class Cas2v2ApplicationsTransformerTest.
Fair enough, so the file was renamed to Cas2v2ApplicationsTransformerTest.kt in line with the other files in the test suite. The linter was re-run and it failed again. The file of that name is not present on the file system:
```
find . -name Cas2V2ApplicationsTransformerTest.kt
```
The linter insists the file is named wrong.
APFS is case in-sensitive, I couldn't find a way to rename the file in place so I've renamed the file to a*new* filename.
> test(no-ticket): fixed file name for transformer test

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2/Cas2UserEntity.kt
- src/main/resources/db/migration/all/20250523095335__add_cas2_user_to_the_cas2_application.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/cas2-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/Cas2ApplicationsTransformerTest.kt
https://dsdmoj.atlassian.net/browse/CBA-646
The current cas2 application entity has a field that records created by user, currently this is a nomis user, we need it to support delius users. In the cas2v2 system it leverages a new user entity (cas2 user) which is able to accept either auth source as a user type.
To compound this nomis users are identified by a primary identifier of a number (long) and delius users are identified by an alphanumeric (string).
Changing the user type of created by users in the cas2 application would involve a high degree of risk as all existing, nomis based, applications would need to be migrated to the new user type.
To mitigate this we propose to add a field to the cas2 application of type cas2user that supports both nomis and delius user.
All new …
> Cas2UserEntity

- src/main/resources/db/migration/all/20250513171535__remove_domain_events_placement_request_id.sql
This has already been removed in code via a06e316a6da63c762ceb347a54bbd342ab95ac7a. This commit is removing it from the database.
> APS-2168 Remove domain_events.cas1_placement_request_id

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationInBatchesJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UpdateApprovedPremisesApplicationWithOffenderJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas3/Cas3MigrateNewBedspaceModelDataJob.kt
- src/main/resources/db/migration/all/20250527172300__cas3_premises_table.sql
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas3/Cas3MigrateNewBedspaceModelDataJobTest.kt
JIRA: https://dsdmoj.atlassian.net/browse/CAS-1569
We are trying to gradually create the tables required for this new database architecture and migrate the data:
* Create the new `cas3_premises` table using flyway
* Create an entity and repository for this new table
* Migrate the CAS3 related data from the `premises` and `temporary_accomodation_premises` into our new new `cas3_premises` table
> Bedspace model refactor - migrate data to new cas3_premises table

- build.gradle.kts
E2E tests have uncovered some additional cases where a nullable value is being returned in a JPA query that has been returned null (some of these were resolved in the upgrade commit - 5ec7b69b9ab58e7b6752bb23e9fa149370309d9c)
Temporarily reverting the upgrade so we can review all the code to find any over occurances of this issue.
> APS-2348 - Revert spring upgrade to 3.5.0

- build.gradle.kts
This is a pre-req to get us to the latest version of open-csv before manually upgrading dependency commons-beanutils to a newer version not currently used by open-csv, resolving CVE-2025-48734
> Upgrade open csv

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AppealEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2SubmittedApplicationReport.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2v2/Cas2v2ApplicationStatusUpdatesReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2v2/Cas2v2SubmittedApplicationReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2v2/Cas2v2UnsubmittedApplicationsReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BedspaceSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingSearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TestBookingSearchResult.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BedSearchServiceTest.kt
This commit updates various JPA ‘result row’ interface definitions to correctly indicate if a value is nullable.
It also renames some result rows that only apply to CAS3 to make this clear (nullability on certain shared tables differes for CAS1/CAS3).
It also removes some unused repository code
> APS-2348 - Ensure JPA result nullability is correct

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedMoveEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BedMoveEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1BookingToSpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
When migrating a booking to a space booking, the existence of a corresponding entry in `bed_moves` blocks deletion of the `booking` entry. Usage of bed_moves was removed in 08/24 as we stopped tracking bed allocation in CAS1. This information doesn’t need migrating to space bookings. Bed moves were only ever captured for the NE region.
This commit updates the booking to space booking migration logic removing any linked entries in bed_moves. This follows the established pattern of removing any information related to the legacy booking entry.
This commit also deprecates the bed move table, in preparation for its removal once all CAS1 bookings have been migrated to space bookings
> APS-2295 - Remove bed_move entries on space booking migration

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1OasysController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/LaoStrategy.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OASysNeedsQuestionTransformer.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NeedsDetailsFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OAsysTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OASysNeedsQuestionTransformerTest.kt
This is similar to the existing shared `GET /people/X320741/oasys/sections` endpoint, but:
1. It has a clear name, better expressing its purpose and result
2. It filters out questions from sections 4&5 (currently filtered out in the UI)
3. It indicates if a question is optional, allowing us to move the optionality logic out of the UI and into the API. This will allow us to make changes to optionality going forward without having sync UI and API changes
This PR also makes some internal changes to CRN permission checks to allow calling code to determine if a record didn't exist for the given CRN (previously the code would instead return a 'forbidden' outcome, which isn't strictly correct)
> APS-2264 Add CAS1 OASys optional needs endpoint

- build.gradle.kts
CVE-2025-26791 relates to DOMPurify, which is used by swagger ui. Upgrading to a later version of the starter to see if this resolves the issue
> Upgrade to latest springdoc-starter

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/model/reference/Cas2PersistedApplicationStatusFinderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1RequestForPlacementServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BedSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/Cas2v2ApplicationUtilsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/ReferralHistoryNoteHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/SeedUtilsTest.kt
Whilst technically this is fine, it often leads to the IDE importing it by mistake when we really want the default assertj `assertThat` function. To assert on CasResult the `assertThatCasResult` function should be used instead.
> Remove overloaded assertThat(CasResult)

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/MDCHandlerInterceptor.kt
Upgrade to the latest version of the Sentry Library
Clear the MDC after request is complete. We have observed unexpected MDC/Sentry Tags appearing on requests before this interceptor has ran. We believe this is because we’re not correctly tidying up the MDC on request completion.
> Upgrade sentry library & fix MDC leak

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1OasysController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OASysNeedsQuestionTransformer.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OAsysTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OASysNeedsQuestionTransformerTest.kt
* Rename endpoint ‘optional-needs-questions’ to ‘supporting-information-metadata`. This is in preparation for answers from health to this response in a subsequent commit, which aren’t directly related to naneeds
* Aligned with the previous change, rename CAS1 OASys group ‘needs’ to ‘supportingInformation’
* Rename the response type to better reflect what it contains
* Rename properties of `Cas1OASysSupportingInformationMetaData` to better reflect their purpose
> APS-2355 - CAS1 OASys Endpoint Naming Improvements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/WebClientCache.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/client/PreemptiveCacheTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/ClockConfiguration.kt
Static mocks are tricky because you need to remember to unset them once done. We’ve also found that mocking a commonly used function (`Instant.now()`) lead to errors when some other code used the the function before we’d had a chance to set a response e.g.
```
2025-06-03 14:26:34.375 ERROR 452 --- [Container#0-0-1] c.s.l.a.BatchingAcknowledgementProcessor : Error executing scheduled acknowledgement in io.awspring.cloud.sqs.sqsListenerEndpointContainer#0-0. Resuming. |
io.mockk.MockKException: no answer provided for class java.time.Instant.now())
```
This commit removes use of static mocks in PreemptiveCacheTest and replaces it with the pre-existing mutable clock
> Fix preemptive cache test flakiness

- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1OutOfServiceBedSeedJobTest.kt
This uncovered a failing verification that had been incorrectly added to a unit test (when updating an out of service bed the premises isn’t retrieved)
> Upgrade mockk

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1OasysController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OASysNeedsQuestionTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OASysOffenceDetailsTransformer.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OAsysTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OASysNeedsQuestionTransformerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OASysOffenceDetailsTransformerTest.kt
**Make CAS1 OASys Metadata Endpoint future proof**
This commit updates the cas1 metadata endpoint to return a container type, allowing us to add additional metadata to the response in the future (e.g. data record created/updated) without making a breaking change. The path of the endpoint has also been changes to reflect this.
This change is safe because the endpoint is not currently being used
**Add asssessment metadata to CAS1 OAsys answers**
Include date started/date ended to each CAS1 OAsys Answers response, as this is required on the UI
> APS-2355 - CAS1 OASys Endpoint Improvements

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
This [PR CAS-1746](https://dsdmoj.atlassian.net/browse/CAS-1746) is to add log when the user probation region is updated during the logging process in CAS3
> CAS-1746 Add log when the user probation region is updated

- helm_deploy/hmpps-approved-premises-api/Chart.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-prod.yaml
Ref: https://dsdmoj.atlassian.net/browse/APS-2092
This PR enables Prometheus alerting in `prod` and enables database alerts to be triggered in the `dev` environment when we have at least one connection.  This is to check that database alerting works as expected.
Once this is confirmed we can set the alerting threshold values to those appropriate for each environment.
> APS-2092 enable prometheus alerts for prod

- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedDetailQueryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryQueryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSummaryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CancellationQueryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CharacteristicQueryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1BedDetailTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1BedSummaryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/planning/SpacePlanningServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1LinkBookingToPlacementRequestTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1OutOfServiceBedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1RoomsFromSiteSurveyXlsxTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApprovedPremises.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/MigrateBookingStatusTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedUpdateNomsNumberSeedJobTest.kt
Where practical, replace usage of the `ApprovedPremisesEntityFactory` with `givenAnApprovedPremises()`. This is in preparation for adding a new column to the `ApprovedPremisesEntity`, which would require alot of test updates if they all used the factory directly
> APS-2375 - Use `givenAnApprovedPremises()` in all tests

- build.gradle.kts
- renovate.json
This should be manually updated, matching the version of hibernate provided by spring
> Exclude `hibernate-spatial` from renovate

- src/main/resources/db/migration/all/20250612095600__temporary_accommodation_characteristics.sql
**Background**
* The latest migration job work done in https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/3594 uncovered a data issue
* the migration job failed in preprod as some `room` characteristics are mapped to cas3 premises. We would expect only `premises` characteristics to be mapped to premises. 
* This query proved this theory:
* I think this is hanging around from this: https://dsdmoj.atlassian.net/browse/CAS-1203
* Flyway script to delete the mappings for room characteristics mapped to cas3 premises
> Cleanup temporary accommodations characteristics data

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedPremisesFromSiteSurveyXlsxJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1PremisesFromSiteSurveyXlsxTest.kt
A previous change updates the Premises Site Survey Seed job to set the CRU Management Area when creating a new Premises. This commit adds the same functionality when updating an existing premises.
> APS-2375 - Update CRU Management Area in Site Survey Seed

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1OasysController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3OASysOffenceDetailsTransformer.kt
- src/main/resources/static/api.yml
- src/main/resources/static/cas3-api.yml
- src/main/resources/static/cas3-schemas.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PeopleTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3OASysOffenceDetailsTransformerTest.kt
CAS3 currently uses the /people/$CRN/oasys/sections endpoint. This endpoint calls five different OASys APIs, despite CAS3 only requiring answers from two of them (offence details for metadata, and risk management for questions and answers).
This commit adds a new /cas3/person/CRN/oasys/riskManagement endpoint that only provides just the information required by the UI. This makes 2 calls to OASys API instead of 5.
> APS-2392 Add CAS3 OASys Endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas3/Cas3UpdateBookingOffenderNameJob.kt
There are some `offender_name` for the `bookings` table that are still null this PR attempts to run through null values first and enhance the logging too.
> CAS-1685: Pt2 Change logging and sorting for migration job

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1StartupScript.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/scheduled/Cas1ExpireUnsubmittedApplicationsScheduledJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/scheduled/Cas1ExpiredApplicationsScheduledJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1StartupScriptConfigTest.kt
This commit seeds an additional 4 applications when deploying locally:
* withdrawn before submission
* withdrawn after authorisation
* expired before submission
* expired after authorisation
To achieve this the expiry scheduled jobs have been refactored to allow us to access the application expiry logic from the `Cas1ApplicationSeedService`
> Seed CAS1 Expired and Withdrawn Apps in Dev

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingSearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseAccessFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseDetailFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas3BookingSearchServiceTest.kt
note that the integration test `Searching for Temporary Accommodation bookings correctly filtered single booking for a specific crn` expected no offender or permission information to be returned for the offender. This is because the two ap-and-delius mocks were not setup to respond to the given CRN and the deprecated function incorrectly interpreted the 404 as 'offender not found' instead of returning a general error
The new code does return a general error in this case so i've had to explicitly configure the mocks in the test to return an 'offender not found' response (i.e. the absence of results for a requested CRN)
> Remove use of deprecated function in cas3 booking search

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationService.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/service/GetAllApprovedPremisesApplicationsTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2388
This is being added as a replacement for `/cas1/applications`. It is being added for a few reasons:
- The new path makes it clearer that it’s returning applications created by the calling user
- It will also include withdrawn/cancelled applications. The current API used by the UI (/cas1/applications) doesn’t do this, and these are required for APS-2189
Internally this can use the same query as `/cas1/applications/all`, but:
- It doesn’t need paging (set page to maximum size)
- It’ll only return applications created by the calling user. To support this a new nullable `createdByUserId` argument will need adding to `findAllApprovedPremisesSummaries`
- It should always sort on `created_at` ascending
Deprecate `/cas1/applications` and any …
> APS-2388 add /cas1/applications/me endpoint to return all users applications

- .github/workflows/generate-cas1-ui-types.yml
- .github/workflows/generate-cas2-ui-types.yml
- .github/workflows/generate-ui-types.yml
This splits the workflows so changes to the relevant files for each UI are taken into account. The workflows are renamed so they can be differentiated easily in the Github Actions UI.
> Tidy up UI type generation workflows

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
This endpoint isn’t used by any CAS (and would only work for CAS1 requests anyway given permissions required)
> APS-1032 Remove unused /applications/{id}/assessment API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
- src/main/resources/static/cas1-schemas.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformersTest.kt
Use a `date` when returning arrival date in `Cas1ApplicationSummary` instead of a `date-time`. Ideally we’d be persisting this as a `date` only, as that’s how it is originally provided by the UI.
This ‘in-place’ change is safe as the UI only cares about the date element of the String, and we’ve tested this locally
> Fix type for Cas1ApplicationSummary.arrivalDate

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas3/Cas3UpdateBedSpaceStartDateJob.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas3/Cas3UpdateBedSpaceStartDateJobTest.kt
This PR adds a new migration script that sets the start date for beds, taking them from either the `created_date` or `arrival_date`
> CAS-1669: C3 BE Migration process to assign start date to bedspaces

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
- src/main/resources/static/api.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TurnaroundTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1FutureManagerUserAccessTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt
This PR makes it clear that arrival, departure and confirmation endpoints on ` /premises/{premisesId}/bookings/…` are not supported by CAS1, and adds an explicit check on the API call to verify this.
It then introduces a user access function `currentUserCanChangeBookingDate ` that allows us to remove all CAS1 usage of the function `currentUserCanManagePremisesBookings `
This change is being made as part of removing the workflow manager role. This removes the last usage of CAS1_WORKFLOW_MANAGER from the 'main' codebase
> APS-1032 Clarify /premises/{id}/… API support

- src/main/resources/static/codegen/built-cas1-roles.json
- src/main/resources/static/codegen/built-cas3v2-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTest.kt
This test could previously fail with errors like the following:
```
java.time.format.DateTimeParseException: Text '2025-05-22T05:22Z' could not be parsed at index 16
at uk.gov.justice.digital.hmpps.approvedpremisesapi.integration.cas1.Cas1ApplicationTest$GetApplicationsMe.Get_applications_me_returns_twelve_items_sorted_by_created_at_asc$lambda$3$lambda$2(Cas1ApplicationTest.kt:852)
```
I think this happens when the time is on 0 seconds. This commit should fix that issue by no longer converting dates to a string.
This commit also adds some generated components missed by prioir commits
> Fix CAS1 test instability

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/main/resources/static/codegen/built-cas1-roles.json
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
This is being done until we can ensure that all users in production that currently rely on this role have been migrated to an appropriate other rule (e.g. cru member)
> APS-1032 Temporarily re-add all permissions to workflow man

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1DuplicateApplicationSeedJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationCreationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationCreationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeBuilderTest.kt
Move the two cas1 withdrawal functions from `ApplicationService` into `Cas1ApplicationService`. This is a pre-req for a fix related to application status.
This included a slight change to the `Cas1WithdrawableService` logic, as it’s no longer possible for it to retrieve an application for another CAS, so validation around this was removed
> APS-2165 Move CAS1 app withdrawal logic into CAS1 service

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
Considering the integration tests required to test task sorting in `TaskTests.GetTasksTest.SortByTest` the following was noted:
- changing the sort direction from descending to ascending in `Get all tasks sorts by createdAt in descending order` [here](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/450565e5a3fd67758f1ba7f315f99989adee220a/src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt#L1591) resulted in the tests still passing
- changing the sort direction from ascending (default) to descending (`SortDirection.desc`) in [here](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/450565e5a3fd67758f1ba7f315f99989adee220a/src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt#L …
> Simplify Task integration tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas1-roles.json
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/main/resources/static/codegen/built-cas3v2-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
This is no longer assigned to any users in prod, and has been removed from the UI.
> APS-1032 Remove workflow manager

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas3/Cas3UpdatePremisesStartDateJob.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/main/resources/static/codegen/built-cas3-api-spec.yml
- src/main/resources/static/codegen/built-cas3v2-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas3/Cas3UpdatePremisesStartDateJobTest.kt
Summary
This Pull Request introduces functionality to update the startDate for temporary accommodation premises in the system. The update logic uses either the creation timestamp or, when absent, the oldest booking arrival date. Additionally, code is revised to include the corresponding migration job, and tests are added to validate the new functionality.
Main Changes
- Added a new repository method to fetch temporary accommodation premises by service with pagination (findTemporaryAccommodationPremisesByService).
- Introduced the Cas3UpdatePremisesStartDateJob class to implement the migration logic, updating startDate based on createdAt or the earliest booking arrival date.
- Modified the PremisesEntity to include createdAt with a @CreationTimestamp.
- Added the migration job logic to …
> CAS-1708: Migration process to assign start date to premises

- build.gradle.kts
This [PR CAS-1809](https://dsdmoj.atlassian.net/browse/CAS-1809) is to downgrade spring and jpa plugin versions as many developers had issues in Intellij complaining about Unresolved reference
> CAS-1809 Downgrade spring and jpa plugin versions

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementDateEntity.kt
This was used by seed jobs used to ‘flatten’ placement applications. These have now been removed.
> APS-2417 - Remove unused SQL

- src/main/resources/db/migration/all/20250702142438__backfill_missing_placement_application_dates.sql
When the prior backfill was ran, there was a single placement application that was submitted after the previous backfill job had run, but before the container running the new code was fully started. This meant the submission used the old code which didn’t populate the two new fields on placement application.
This commit adds an additional backfill job targetted at that placement application.
> APS-2417 Backfill missing placement application dates

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningService.kt
- src/main/resources/static/cas1-api.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1PlanningBedSummaryFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/planning/SpacePlanningServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
**Background**
This endpoint has been added as part of a spike to test performance when retrieving capacity for multiple premises. The endpoint will be further refined once user requirements are better understood.
Note that much like the existing capacity endpoint, the endpoint integration testing is limited as there is already detailed integration testing in the integration test for the `SpacePlanningService`
**Design Notes**
When determining capacity for a premises, we run 3 queries to retrieve data that is then crunched in-memory:
1. Get all space bookings in the requested time period
2. Get all beds in the premises, including characteristics
3. Get all out of service bed records applicable to the requested time period
To limit how much SQL we're running when determining capacity for …
> APS-2463 Add endpoint to get all premises' capacities

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/RoomEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas3/Cas3UpdatePremisesStartDateJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas3/Cas3UpdatePremisesStartDateJobTest.kt
This Pull Request adds the ability to determine the startDate of a premises based on the earliest startDate of its associated beds when no alternative data exists. It also updates the relevant unit tests to cover this new behavior.
Main Changes:
- RoomEntity.kt:
- Introduced a new method findAllByPremisesId in RoomRepository to fetch rooms by premises ID.
- Cas3UpdatePremisesStartDateJob.kt:
- Modified existing logic to incorporate bed start dates when determining a premises' startDate.
- Added fallback logic to check rooms and beds if no booking data exists for a premises.
- Cas3UpdatePremisesStartDateJobTest.kt:
- Updated test cases to validate the new logic for determining the premises startDate.
- Added and adjusted test setup for generating rooms and beds with specific start dates.
> CAS-1708: C3 BE migration start date premises fix start date

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1CapacityPerformanceTestJob.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
This provides a simple way to test performance of the capacity calculation algorithm against _all_ premises
> APS-2463 - Add migration job to support testing capacity calc

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt
- src/main/resources/static/_shared.yml
- src/main/resources/static/codegen/built-api-spec.yml
- src/main/resources/static/codegen/built-cas1-api-spec.yml
- src/main/resources/static/codegen/built-cas2-api-spec.yml
- src/main/resources/static/codegen/built-cas2v2-api-spec.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1WithdrawPlacementRequestsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationCas1DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationEmailServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
Remove all remaining code that reads values from the `placement_application_dates` table, updating the code to instead use `placement_applications.expected_arrival_date` and `placement_applications.duration`.
Once this is merged the only remaining use of placement dates is code that is populating the values, and the code that converts placement applications into placement requests, both of which can be updated to remove use of this table
> Remove read use of `placement_application_dates`

- src/main/resources/db/migration/all/20250707192500__cas3_void_bedspaces_add_premises_and_beds_foreign_keys.sql
**Background**
In previous PR, I commented about the need to drop a couple of foreign keys: 
https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/3823/files#r2185362168
I realised that this is actually not necessary, we can keep the foreign keys. The only thing we needed to keep in that flyway script was dropping the not null:
```
ALTER TABLE cas3_void_bedspaces
ALTER COLUMN premises_id drop not null;
```
We previously dropped a foreign key in `bookings` table that we discussed in `Dev checkin` because we were sharing a column - this was at the forefront of my mind when decided to drop the foreign keys above but dropping these latest foreign keys is not needed and a mistake.
**Solution**
* this PR adds back in the foreign keys I dropped unnecessarily.
**IMPORTANT**
* The …
> CAS3 V2 reinstate cas3_void_bedspaces foreign-keys

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3BookingAndPersons.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3v2PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3BedspacesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/v2/Cas3v2BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/v2/Cas3v2BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/v2/Cas3v2BookingServiceTest.kt
**Background**
1. Delivery of the new `GET /cas3/v2/premises/{premiseId}/bookings/{bookingId}`.
2. This endpoint was modelled on the `GET /premises/{premiseId}/bookings/{bookingId}` and so all functionality / integration tests and unit tests have been ported over and …
> CAS3 V2 Get Premises Bookings By Booking ID

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1OccupancyReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2477
The report provided by `Cas1OccupancyReportRepository` currently prefixes the premises name with the `ap_area.name`. It should instead prefix it with the `cas1_cru_management_area.name`. Otherwise, premises in the 'Women’s APs' management area will not be easy to find.
The cru management area for a premises is available on `approved_premises.cas1_cru_management_area_id`
> APS-2477 Change prefix from ap area to cru management area in occupancy reports

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1OasysController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementApplicationsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PeopleController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OAsysTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PeopleTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
Before this commit the code assumed that calls to `/users/access` would not return an entry for a requested CRN if the CRN does not exist. This is not the case, and an entry for the CRN will always be returned.
This commit notes this on the client for this endpoint and updates the code to remove any code related to the CRN not existing
> Upstream /users/access always returns requested CRNs

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BackfillActiveSpaceBookingsCreatedInDelius.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1BackfillActiveSpaceBookingsCreatedInDeliusTest.kt
Update the seed job that backfills referrals created directly in Delius to ensure if it’s ran multiple times multiple duplicate space bookings aren’t created
> APS-2499 - CAS1 Space Booking Backfill should be idempotent

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3v2BookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/v2/Cas3v2BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/v2/Cas3v2BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/v2/Cas3v2BookingServiceTest.kt
**Background**
1. Delivery of the new `GET /cas3/v2/bookings/{bookingId}`.
2. This endpoint was modelled on the `GET /bookings/{bookingId}` and so all functionality / integration tests and unit tests have been ported over and refactored to use the new data model.
> CAS3 V2 Get Booking By Booking ID

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/generated/Cas3UnarchiveBedspace.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3PremisesServiceTest.kt
This Pull Request introduces a new feature for unarchiving bedspaces in a premises and includes all required functionality, validations, and tests.
- New Model Added: Cas3UnarchiveBedspace for handling unarchiving of bedspaces with a required restartDate.
- New Endpoint: Adds a POST endpoint for unarchiving bedspaces in the Cas3PremisesController. Includes permission checks and validation logic.
- Service Layer Changes: Implements unarchiveBedspace in the Cas3PremisesService, adding validations for restart dates and archived bedspace checks.
- Validation Rules Added:
- restartDate must not be more than 7 days in the past or future.
- restartDate must be after the last archive's end date.
- The bedspace must exist and must currently be archived.
- Integration Testing: Comprehensive …
> CAS-1620: Create unarchive bedspace api endpoint

- helm_deploy/values-test.yaml
We disabled this during load testing, but it can now be enabled again
> Emit domain events in test

- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
Previously we used a legacy ‘booking’ url (which will be redirected to this new URL by the UI)
This PR also disables domain events in test to unblock testing this functionality. This was enabled last week but ultimately wasn't required
> APS-2555 - Use space booking URL in booking made emails

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationPlaceholderEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1RequestForPlacementReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationCreationService.kt
- src/main/resources/db/migration/all/20250722161242__placement_applications_automatic.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationCreationServiceTest.kt
We now have the concept of an entry in `placement_applications` being automatic (via the ‘automatic’ boolean value)
To avoid confusion, this commit renames the `placement_applications_automatic` table to `placement_applications_placeholder`, as it really represents a limited set of information about a request for placement that will be ‘promoted’ to an entry in the `placement_applications` table once the corresponding application is approved. we need this placeholder to enable reporting on these values before the application has been approved.
In time, `placement_applications_placeholder` will be fully replaced by `placement_applications`.
Typically we’d avoid renaming tables ‘in place’ because it can lead to errors whilst rolling out the correspodning code change. As this table does not …
> APS-2547 - Rename placement_applications_automatic table

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3BookingSearchResults.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3BookingSearchSortField.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3v2BookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/v2/Cas3v2BookingSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/v2/Cas3v2BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3BookingSearchResultTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas3/Cas3BookingEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas3/v2/Cas3v2ConfirmationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/v2/Cas3v2BookingSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas3v2ConfirmationTestRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TestCas3BookingSearchResult.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/v2/Cas3v2BookingSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/v2/Cas3v2BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3BookingSearchTransformerTest.kt
**Background**
1. Delivery of the new `GET /cas3/v2/bookings/search`.
2. This endpoint was modelled on the `GET /bookings/search` and so all functionality / integration tests and unit tests have been ported over and refactored to use the new data models.
> CAS3 V2 Booking Search API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SimpleApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1RequestForPlacementReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationCas1DomainEventServiceTest.kt
/assessments is deprecated for CAS1, and the /cas1 versions should be used instead
This also adds some additional coverage to the reports tests
> Use /cas1/assessments endpoints in reports tests and improve coverage

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/Cas1Premises.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoomEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenARoom.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt
We have quite a few queries/lazy loading being ran to populate `Cas1Premises`. We should monitor performance and consider flattening some of it down into a single query (similar to queries used for premises search)
> Add characteristics to `Cas1Premises`

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/MigrationJobType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingNotMade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1BookingNotMadeReallocationJob.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenABookingNotMade.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1BookingNotMadeReallocationJobTest.kt
This migration job moves booking not made records from reallocated placement requests to their non reallocated equivalents.
This will affect a small number of placement requests as the ‘placement request allocation’ functionality has not been used for over 18 months.
This is a pre-requisite for deleting reallocated placement requests from the database, which is a pre-requisite to making the placement-request to placement-application relationships one-to-one.
> APS-2586 - Add 'reallocate booking not mades' migration job

- src/main/resources/db/migration/all/20250729103452__delete_reallocated_placement_requests.sql
For a short period of time `placement_requests` were assigned to users to complete, much like assessments. Whenever a `placement_requests` entry was reallocated a complete copy of the row was taking, setting the existing row’s `reallocated_at` value to the current timestamp which is effectively a soft delete.
This functionality has not been used for over 18 months (The last one of these was reallocated almost 18 months ago: 2024-02-27), leaving our data model polluted with unused columns and rows that are soft deleted and never retrieved by the code. This is also a blocker to making the relationship between a placement_application and placement_request one to one (it’s currently one to many, but logically shouldn’t be).
There are 450 reallocated placements_requests that are effectively …
> APS-2586 - Delete reallocated placement requests

- helm_deploy/values-development.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
- src/main/resources/application-localdev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
The `assign-default-region-to-users-with-unknown-region` configuration option was only enabled in dev and test environments and only required when a test user is not configured with a known region.
After disabling this option locally I can login using all CAS1 & CAS3 test users, suggesting this option isn’t required.
> Remove ‘assign default region’ logic

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/DocumentsApi.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DocumentsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1DocumentsController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/APDeliusDocumentFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationDocumentsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1DocumentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DocumentTransformerTest.kt
The original get document endpoint is only used by CAS1. This commit creates a CAS1 specific version of this endpoint and deprecates the original endpoint
> Create `GET /cas1/documents/{crn}/{documentId}`

- build.gradle.kts
dbf99b0b05c1b86f43d822a7b66312857812be8e removed open api code generation, moving the `generateCas1Roles` from the compile finalize phase to the `assembly` task finalize phase.
Because devs don’t always run assembly, updates to this file were missed.
This commit moves the `generateCas1Roles` back into the compile finalize phase
> Always generate built-cas1-roles on compile

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/Cas3ValidationErrors.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/BadRequestProblem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/EntityUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3PremisesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt
This [PR CAS-1625](https://dsdmoj.atlassian.net/browse/CAS-1625) is to extend the bad request response to include id and value
> CAS-1625 Extend the bad request response to include id and value

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/CAS3PremisesUnarchiveEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/generated/events/EventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3DomainEventBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt
This Pull Request adds functionality for handling "premises unarchived" events within the CAS3 domain, including updates to event models, builders, services, and tests.
Main Changes:
- Event Type Extension: Added a new event type premisesUnarchived in the EventType enum.
- New Domain Model: Introduced CAS3PremisesUnarchiveEvent and its details to represent "premises unarchived" events.
- Entity Update: Extended DomainEventEntity with support for the new CAS3PremisesUnarchiveEvent.
- Service Logic:
- Added methods to build, save, and emit "premises unarchived" events in Cas3DomainEventBuilder and Cas3DomainEventService.
- Updated Cas3PremisesService to trigger "premises unarchived" events upon unarchiving premises.
- Test Enhancements: Updated Cas3PremisesServiceTest to include mock …
> CAS-1730: C3 BE Unarchive Premise Domain Event

- src/main/resources/db/migration/all/20250804095332__change_pending_property_status_to_active.sql
Ref: https://dsdmoj.atlassian.net/browse/APS-2594
Only one premises has a `pending` status which will be changed to `active` once this migration job has run.
> APS-2594 Set pending property status to active.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/migration/Cas1BackfillApplicationDuration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/migration/Cas1BackfillApplicationDurationJobTest.kt
This commit updates the backfill job for `approved_premises_application.duration` to always popualte the duration, regardless of whether an arrival date is provided, matching the behaviour expected by the UI.
> CAS1 application.duration will always be populated

- src/main/resources/db/migration/all/20250804141027__backfill_placement_app_authorised_and_requested_durations.sql
This is only populating ‘non automatic’ placement applications (by virtue of there not being any ‘automatic’ placement applications in the database currently)
For these placement applications there is no way for the authoriser to modify the duration, so the values will always be the same.
> APS-2620 Backfill placement app requested/authorised dates

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/cas1/Cas1RequestedPlacementPeriod.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/RequestForPlacement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RequestForPlacementTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/RequestsForPlacementTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RequestForPlacementTransformerTest.kt
It’s safe to remove RequestForPlacement.duration as it’s a relatively new field that the UI isn’t currently using
> APS-2620 Provide Request for Placement requested & authorised durations

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/ConfigureOpenEntityManagerInView.kt
- src/main/resources/application.yml
https://dsdmoj.atlassian.net/browse/APS-1127
Open Entity (Session) In View (OSIV) is enabled by default in Spring, and whilst simplifying development wrt. lazy loading JPA relationships, it results in a database connection being held open from it’s first usage to completion of the API request. This can lead to exhausted connection pools under load, especially when calls are being made to upstream services in the same thread that holds the connection.
Because removing OSIV can cause subtle issues (especially around object equality), we've decided to selectively disable it for certain paths that are causing particular issues. To support this we manually install the interceptor in the configuration class added by this commit.
This commit initially adds the interceptor to one endpoint as a …
> APS-1127 - Manually install Open Entity in View Interceptor

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3v2BookingController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3v2PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3DepartureEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/v2/Cas3v2BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3DomainEventBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/v2/Cas3v2BookingServiceTest.kt
**Background**
1. Delivery of the new `POST /cas3/v2/premises/{premisesId}/bookings/{bookingId}/departures`.
2. This endpoint was modelled on the `POST /cas3/premises/{premisesId}/bookings/{bookingId}/departures` and so all functionality / integration tests and unit tests …
> CAS3 V2 Create Departure API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingDomainEventServiceTest.kt
This updates the `Cas1BookingDomainEventService` to stop using the deprecated function on `OffenderService` to retrieve the offenders NOMS number. In doing this we’ve simplified the code to remove duplication
> Remove deprecated upstream calls in Cas1 Booking

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/ApprovedPremisesUserPermission.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
- src/main/resources/static/codegen/built-cas1-roles.json
This will be used to determine if a user can enter any date when creating/updating an out of service bed. By default this is implicitly assigned to janitor
> APS-2663 - Add CAS1_OUT_OF_SERVICE_BED_NO_DATE_LIMIT

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3AssessmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1TaskService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3AssessmentTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3AssessmentServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1TaskServiceTest.kt
Ref: https://dsdmoj.atlassian.net/browse/APS-2476
- Add new CAS 3 DELETE endpoint to delete assessment allocation.
- Add new CAS 3 POST endpoint to reallocate assessments.
- Deprecate legacy functions which can be removed when CAS 3 UI is switched over to use the new end points.
To do once CAS 3 UI is using the new endpoints:
- Remove TasksTest
- Remove TasksController
- UserAccessService.userCanDeallocateTask() can be made CAS 3 specific
- Remove Cas1TaskService.deallocateTask()
- Remove any other CAS 3 de/reallocation logic from CAS 1 flow
> APS-2476 Add new CAS 3 DELETE and POST assessment allocation endpoonts

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/StaffMemberService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/StaffMemberServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementServiceTest.kt
Before this commit when retreiving keyworker details to persist on a booking we would use the staff code and premises code. This ensured the keyworker we were assigning belonged to the associated premises.
As we’re changing to allow any FUTURE_MANAGER to be assigned as a keyworker this restriction no longer makes sense, and we don’t want to be restricted by delius user to premises mappings.
This commit updates the logic to retrieve keyworker information using staff code only.
> APS-2658 - Retrieve keyworker details by staff code

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/givens/GivenATemporaryAccommodationPremises.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt
This [PR CAS-1726](https://dsdmoj.atlassian.net/browse/CAS-1726) is to:
- Prevent archive a premises if the archiving date is before premises start date
- Prevent archive a premises when its clashes with an earlier archive premises end date
> CAS-1726 Add validations to archive premises

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
> APS-2679 - Fix timeline mapping for placement app withdrawn

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt
This [PR CAS-1726](https://dsdmoj.atlassian.net/browse/CAS-1726) is to extend the validation message when archiving premises date overlaps
> CAS-1726 Extend validation message when overlap archiving premises dates

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3v2PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3ExtensionEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/v2/Cas3v2BookingService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2BookingTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/v2/Cas3v2BookingServiceTest.kt
**Background**
1. Delivery of the new `POST /cas3/v2/premises/{premisesId}/bookings/{bookingId}/extensions`
2. This endpoint was modelled on the `POST /premises/{premisesId}/bookings/{bookingId}/extensions` and so all functionality / integration tests and unit tests have …
> CAS3 V2 Create Extension API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/migration/Cas1BackfillApplicationDuration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/migration/Cas1BackfillApplicationDurationJobTest.kt
A small number of CAS1 applications have a NaN for duration override, as detailed on APS-2686.
This commit updates the duration backfill job to handle these NaN values by using the ap type’s default duration instead, which is the number that is currently presented to the assessor in these cases
> APS-2615 - Handle NaN in duration backfill job

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/migration/Cas1BackfillApplicationDuration.kt
The default timeout is 60 seconds. Given this is a one time job having the query run for a longer period of time is acceptable.
> APS-2615 - Increase duration backfill query timeout

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/CAS3PremisesUnarchiveEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3DomainEventBuilderTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3DomainEventServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt
This Pull Request introduces changes to handle the currentEndDate field in various functions and components related to the unarchiving of premises in the system. The change ensures better tracking and processing of the currentEndDate during domain event creation, service logic, and test cases.
Main Changes
- Added a currentEndDate field to the CAS3PremisesUnarchiveEvent data model.
- Updated Cas3DomainEventBuilder to include currentEndDate in event creation logic.
- Modified functionality in Cas3PremisesService and Cas3DomainEventService to handle the currentEndDate parameter when unarchiving premises.
- Updated integration and unit tests with necessary adjustments to reflect the inclusion of the currentEndDate field.
> CAS-1730: C3 BE Add end date to premises unarchive domain event

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3PremisesBedspaceTotals.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
This [PR CAS-1820](https://dsdmoj.atlassian.net/browse/CAS-1820) is to extend the Api endpoint bedspace totals to include premises end date
> Extend the Api endpoint bedspace totals to include premises end date

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt
This PR CAS-1729 is to enable the user to archive/unarchive premises/bedspace in the same day
> CAS-1729 Should be able to archive/unarchive premises/bedspace in the same day

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PlacementRequestSummaryTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementRequestTest.kt
* Move a transform function that was only used by tests from `main` into the corresponding tests
* Simplify the function to reflect that it’s only used when comparing placement requests pending match.
> Tidy Cas1PlacementRequestTest

- src/main/resources/db/seed/dev+test/01__temporary_accommodation_users.csv
- src/main/resources/db/seed/dev+test/02__approved_premises_users.csv
Seeding of the probation integration e2e test user intermittently fails, which rolls back the entire seed job.
This commit moves that seeding into a standalone seed file, so if that fails, other seeded users are still created
> Move probation integration e2e test user seeding

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3PremisesController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3BedspacesReference.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
This Pull Request introduces functionality to check whether a premises in the system can be archived. It includes enhancements in both controller and service layers, query logic updates, and corresponding integration and unit tests.
Main Changes:
- Controller Updates: Added a new endpoint GET /premises/{premisesId}/can-archive to assess if a premises can be archived, returning relevant affected bedspaces.
- Service Updates: Introduced a method canArchivePremises in Cas3PremisesService to determine archive eligibility based on bookings and voids within the premises.
- Repository Additions:
- Added two queries for filtering bookings and void bedspaces based on their statuses, dates, and other conditions.
- Model Changes: Introduced a new data class Cas3CanArchivePremises and …
> CAS-1877: C3 BE Check premises can be archived

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/reporting/Cas1RequestForPlacementReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1RequestForPlacementReportTest.kt
This commit splits the ‘duration’ column into separate ‘requested duration’ and ‘authorised duration’ in the request for placements report
> APS-2638 - Add requested & authorised date to RfP report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
This PR to fix an integration test Can archive bedspace returns 200 with Cas3ValidationResult when booking turnaround date is more than 3 months from today's date
> CAS-1920 Fix integration test

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
This [PR CAS-1877](https://dsdmoj.atlassian.net/browse/CAS-1877) is when a bedspace have a booking and void after 3 months only want to return the latest blocking date
> CAS-1877 Only return the bedspace with the latest blocking date

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3Bedspace.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/transformer/Cas3BedspaceTransformer.kt
This PR CAS-1968 change the start date property temporary to nullable until we run the migration process then all bedspaces will have createdAt date. Then will set the startDate property back to be not nullable
> CAS-1968 Change startDate property to be nullable in Cas3Bedspace

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3v2BedspaceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3BedspacesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/v2/Cas3v2BedspacesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/v2/Cas3v2DomainEventService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/transformer/Cas3BedspaceTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2BedspacesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/v2/Cas3v2BedspaceServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/transformer/Cas3BedspaceTransformerTest.kt
**Background**
1. Delivery of the new `GET /cas3/v2/premises/{premisesId}/bedspaces`
2. This endpoint was modelled on the `GET /cas3/premises/{premisesId}/bedspaces` and so all functionality / integration tests and unit tests have been ported over and refactored to use the …
> CAS3 V2 Get Bedspaces API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3v2BedspaceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3BedspacesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/v2/Cas3v2BedspacesService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2BedspacesTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/v2/Cas3v2BedspaceServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas3PremisesAndBedspace.kt
**Background**
1. Delivery of the new `PUT /cas3/v2/premises/{premisesId}/bedspaces/{bedspaceId}`
2. This endpoint was modelled on the `PUT /cas3/premises/{premisesId}/bedspaces/{bedspaceId}` and so all functionality / integration tests and unit tests have been ported over …
> CAS3 V2 Update Bedspace API

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3v2BedspaceController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3PremisesEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2BedspacesTest.kt
**Background**
1. Delivery of the new `PUT /cas3/v2/premises/{premisesId}/bedspace-totals`
2. This endpoint was modelled on the `PUT /cas3/premises/{premisesId}/bedspace-totals` and so all functionality / integration tests and unit tests have been ported over and refactored …
> CAS3 V2 Get bedspace-totals

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3ApplicationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
- src/main/resources/db/migration/all/20250917125404000__c3_rename_out_of_region_columns.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/factory/TemporaryAccommodationApplicationEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3ApplicationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3ApplicationServiceTest.kt
The Pull Request updates the naming for certain fields and database columns related to "out of region" probation regions and delivery units, replacing them with "previous referral" terminology throughout the codebase. Changes span service logic, database schema, entity models, factories, and tests to align with this updated terminology.
- Service logic: Adjusted methods to adopt "previous referral" fields instead of "out of region."
- Database schema: Renamed columns in the temporary_accommodation_applications table.
- Entity changes: Updated application-related models for new field names.
- Factory changes: Reflect changes in entity factories to match updated field names.
- Test updates: Modified both unit and integration tests to align with changes and ensure proper assertion checks.
> CAS-1910: C3 BE Set out of region fields for applications

- build.gradle.kts
[OSS Index provides an additional vulnerability database](https://dependency-check.github.io/DependencyCheck/analyzers/oss-index-analyzer.html). An auth key is now requried for this database, which we don’t currently have configured.  This commit disables this analyser to ensure dependency check runs continue to work.
> Disable ossIndex within dependencyCheck task.

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/transformer/Cas3VoidBedspacesTransformer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/transformer/Cas3VoidBedspacesTransformerTest.kt
Summary
This Pull Request adds a new field, costCentre, to the Cas3VoidBedspacesTransformer functionality and updates its associated test cases to ensure the new field is correctly handled.
Main Changes
- Code Changes:
- Added a new attribute, costCentre, to the toResponse transformation method in the Cas3VoidBedspacesTransformer class.
- Test Updates:
- Updated the Cas3VoidBedspacesTransformerTest to include assertions for the costCentre field in multiple test cases.
Adjusted a test entity to populate the costCentre field during setup.
> CAS-1911: C3 BE Set cost centre in api response

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/MigrationJobType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/migration/Cas3UpdateArchiveUnarchiveDomainEventTransactionJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/CAS3BedspaceArchiveEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/CAS3PremisesArchiveEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/migration/Cas3UpdateArchiveUnarchiveDomainEventTransactionJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/DomainEventTestRepository.kt
This PR CAS-2003 is create a migration job to populate transaction Id for archive/unarchive CAS3 domain events
> CAS-2003 Migration jobfor archive/unarchive CAS3 domain events

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/repository/TransitionalAccommodationReferralReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3ReportServiceTest.kt
* Refactor the `GET /cas3/reports/{reportName}` endpoint for the `referral` report type
* uses the `cas3-reports-with-new-bedspace-model-tables-enabled` feature-flag to determine whether to execute a query against the new `Bedspace model refactor` tables (or to execute against the tables currently queried in production when feature-flag off)
* executes the old or new query accordingly
* test coverage for the report against the new tables
> CAS3 V2 Application Referrals report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3FutureBookingsReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2ReportsTest.kt
* Refactor the `GET /cas3/reports/{reportName}` endpoint for the `futureBookings` and `futureBookingsCsv` report types 
* uses the `cas3-reports-with-new-bedspace-model-tables-enabled` feature-flag to determine whether to execute a query against the new `Bedspace model refactor` tables (or to execute against the tables currently queried in production when feature-flag off)
* executes the old or new query accordingly
* test coverage for the report against the new tables
> CAS3 V2 Future Manage reports

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3BookingGapReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2ReportsTest.kt
* Refactor the `GET /cas3/reports/{reportName}` endpoint for the `bookingGap` report type
* uses the `cas3-reports-with-new-bedspace-model-tables-enabled` feature-flag to determine whether to execute a query against the new `Bedspace model refactor` tables (or to execute against the tables currently queried in production when feature-flag off)
* executes the old or new query accordingly
* test coverage for the report against the new tables
> CAS3 V2 Booking gap report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3ReportsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3BedspacesEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/generator/BedspaceOccupancyReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/generator/BedspaceUsageReportGenerator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/model/BedspaceOccupancyReportData.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/model/BedspaceOccupancyReportRow.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/properties/BedspaceOccupancyReportProperties.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/repository/BedspaceOccupancyReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/givens/GivenACas3Premises.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/migration/Cas3VoidBedspaceJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2BedspaceOccupancyReportTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2ReportsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/reporting/generator/BedspaceOccupancyReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/reporting/generator/Cas3BedspaceUsageReportGeneratorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/reporting/util/Cas3ReportsTestHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3ReportServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
* Refactor the `GET /cas3/reports/{reportName}` endpoint for the `bedOccupancy` report type
* uses the `cas3-reports-with-new-bedspace-model-tables-enabled` feature-flag to determine whether to execute a query against the new `Bedspace model refactor` tables (or to execute against the tables currently queried in production when feature-flag off)
* executes the old or new query accordingly
* test coverage for the report against the new tables
> CAS3 V2 Bedspace occupancy report

- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3v2BedspaceSearchController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3BedspaceCharacteristicEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3BookingEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3PremisesCharacteristicEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/migration/Cas3MigrateNewBedspaceModelDataJob.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3BedspaceSearchResultBedspaceSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3BedspaceSearchResultPremisesSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3CharacteristicPair.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3v2BedspaceSearchResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3v2BedspaceSearchResultOverlap.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3v2BedspaceSearchResults.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/repository/Cas3BedspaceSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/v2/Cas3v2BedspaceSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/v2/Cas3v2BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/transformer/Cas3v2BedspaceSearchResultsTransformer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CharacteristicService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/factory/Cas3BedspaceCharacteristicEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/factory/Cas3BedspaceEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/factory/Cas3PremisesCharacteristicEntityFactory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/migration/Cas3MigrateNewBedspaceModelDataJobTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2BedspaceSearchTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/v2/Cas3v2VoidBedspaceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/v2/Cas3v2BedspaceSearchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/CharacteristicServiceTest.kt
**Background**
1. Delivery of the new `POST /cas3/v2/bedspaces/search`
2. This endpoint was modelled on the `POST /cas3/bedspaces/search` and so all functionality / integration tests and unit tests have been ported over and refactored to use the new data models
> CAS3 V2 Bedspace Search API
