ministryofjustice/hmpps-approved-premises-api

.github/workflows/ci.yml

This runs the linting and tests in Github actions. More complexity to come I'm sure, but this is a starter for 10.

Setup Github actions

---

src/main/resources/static/mini-manage-api-stubs.yml

This allows us to model the status of a booking, as well as details about the events. I’ve also added a stub `Cancellation` event, which may change as the service evolves.

Update the booking spec

---

src/main/resources/static/mini-manage-api-stubs.yml

Some suggested tweaks / changes to the interface between the UI and API components.
I also have some suggestions for the `Premises` entity which can follow on....

Suggested api changes

---

.gitignore

This is auto-generated by one of the gradle plugins

Add .trivyignore to .gitignore

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt

525 - get single premises by ID

---

helm_deploy/values-dev.yaml

This adds the HMPPS_AUTH_URL to the values-dev.yaml file to get rid of the error on boot.

Add HMPPS_AUTH_URL to dev

---

helm_deploy/approved-premises-api/values.yaml

I had `SPRING_DATASOURCE_URL` specified twice!

Remove duplicate env var

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PremisesTransformer.kt

Convert PremisesTransformer method to expression bodied member for consistency with other transformers

Convert PremisesTransformer method to expression bodied member

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ArrivalEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/BadRequestProblem.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt

Implement create Arrival endpoint + tests

527 - Create arrival endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/BadRequestProblem.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt

Change from map to array as specified in the ADR

Fix for ADR-0001

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/LostBedsTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
src/main/resources/db/migration/20220815104401__add_lost_beds.sql
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/LostBedsEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PremisesEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/LostBedsTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt

Implement POST /premises/{premises id}/lost-bed endpoint + integration tests.

546 - Create lost bed

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/Availability.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CapacityTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt

Add endpoint to get AP capacity per day, from today until the furthest-in-the-future Booking or Lost Beds

606 - Get AP Capacity endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt

Implement list Lost Beds endpoint + tests

547 - List lost beds

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CancellationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/CancellationTransformer.kt
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt

Implement create Cancellation endpoint + tests

602 - Add cancellation endpoint

---

build.gradle.kts

Update spring doc to latest version

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalReasonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NonArrivalReasonTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NonArrivalTransformer.kt
src/main/resources/db/migration/20220823160556__add_non_arrival_reasons.sql
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NonArrivalEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NonArrivalReasonEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/NonArrivalReasonTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt

Implement create Non Arrival endpoint for Bookings + tests
Added own table for the reasons, similar to how Cancellations work

611 - Create Non Arrival for Booking

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DepartureEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/DepartureTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt

Adds a POST endpoint: /premises/{premises id}/booking/{booking id}/departures

610 - Create departure

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

Addresses: 
- https://github.com/ministryofjustice/approved-premises-api/pull/54#discussion_r953597915
- https://github.com/ministryofjustice/approved-premises-api/pull/55#discussion_r953618103

Get booking by premises refactor

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/resources/static/mini-manage-api-stubs.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt

Rename /person/* paths

---

helm_deploy/values-dev.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/LoggingHandlerInterceptor.kt

**Fix logging in general in dev environment**
Because we didn't have the active profile set, the incorrect config was being selected in `logback-spring.xml`
**Add simple request logger**
Logs `{METHOD} {REQUEST URI} - {RESPONSE STATUS}`

Log requests

---

helm_deploy/values-dev.yaml

Community API & NOMIS.  HMPPS Tier and ARNS only have a dev but they seem to point at test environment upstreams too.

Change upstream dependencies to test environment

---

script/server

since [dc6b7223ee0fab716888f66091f0a94e16e45ebd](https://github.com/ministryofjustice/approved-premises-api/commit/dc6b7223ee0fab716888f66091f0a94e16e45ebd)

Developer environment is now 'Local' rather than 'Dev'

---

helm_deploy/values-dev.yaml

Put this back to its prior value in the dev environment

Correct Prisons API URL

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationSchemaEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ProbationOfficerEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/HttpAuthService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/resources/db/migration/all/20220913160138__applications.sql
src/main/resources/db/migration/local+dev/20220913164429__mock_probation_officers.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationSchemaEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ProbationOfficerEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ApplicationSchemaTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ApplicationTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/ProbationOfficerTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/JwtAuthHelper.kt

**Implement GET /applications + tests**
Returns all of the applications for the current user.  Json schema validation will follow in another PR.

717 - Get all applications for logged in user

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

**Implement GET /applications/{id} endpoint**
User must be the creator of the application to retrieve it

718 - Get single application

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/AuthorisableActionResult.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonSchemaService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ProbationOfficerService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ProbationOfficerServiceTest.kt

**Implement POST /applications endpoint**
This will automatically create an entry for the Probation Officer if one does not already exist.

752 - Create new application

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/BaseHMPPSClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/AuthorisableActionResult.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ShouldNotBeReached.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ValidatableActionResult.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/ValidationErrors.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonSchemaService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/JsonSchemaServiceTest.kt

**Implement PUT /applications/{id}**

716 - Update application

---

src/main/resources/static/api.yml

Add a GET /people/{crn}/behaviour-notes endpoint to the OpenAPI specification

Add Behaviour Notes endpoint specification.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/StaffMemberService.kt
src/main/resources/db/migration/local+dev/20220930100515__correct_team_codes.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt

Add GET /premises/{id}/staff endpoint

710 - Get staff endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/PrisonCaseNotesConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/prisonsapi/CaseNotes.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PrisonCaseNoteTransformer.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/CaseNoteFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CaseNotesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RandomData.kt
src/test/resources/application-test.yml

Implement GET /people/{crn}/prison-case-notes endpoint

757 - Get case notes

---

.circleci/config.yml

These should be coming to our channel

Configure Slack channels for alerts

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt

Don't cache failed Client responses

---

build.gradle.kts

Update com.fasterxml.jackson.core:jackson-databind and org.postgresql:postgresql due to CVEs

Dependency updates

---

helm_deploy/hmpps-approved-premises-api/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt

Add sample rate settings
Send exceptions to Sentry

Sentry changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

Fix for bug where missing move on category not detected properly + split out validation unit tests as combined test is what allowed this to sneak through

Fix for missing move on category

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ProfileController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/main/resources/db/migration/all/20221018170342__user_roles_and_qualifications.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserQualificationAssignmentEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserRoleAssignmentEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/UserTestRepository.kt

**Store roles & qualifications for Users**
Add two new tables for storing roles & qualifications
**Implement GET /profile endpoint**
This returns info for the logged in user for the frontend to use

Store roles & qualifications for Users

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AllocationQueryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/AssessmentTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

**Create and allocate an Assessment on submission of Application**
Finds the user who is an assessor, with all of the required qualifications (if any) who has the least non-submitted Assessments allocated to them.

793: Allocate assessments

---

doc/architecture/decisions/0005-reuse-api-for-cas1-and-cas3.md

This proposal seeks to document the decisions that have recently been made in relation to CAS1/2/3 setting out to reuse the same API.

ADR for CAS teams working together on the same API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/AssessRisksAndNeedsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/assessrisksandneeds/Needs.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NeedsTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NeedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NeedsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonNeedsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/NeedsTransformerTest.kt

**Implement GET /people/{crn}/needs**
Retrieves needs from ARNS and groups the `identifiedNeeds` into categories suitable for our frontend

820 - Needs endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
src/main/resources/db/migration/all/20220803121542__rename_characteristic_table_to_characteristics.sql
src/main/resources/db/migration/all/20220811100326__pluralize_characteristic_table_to_characteristics.sql

Pluralize characteristic table to characteristics and update entity accordingly to reference that table

Fix rename characteristic table

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/resources/db/migration/all/20221031150629__add_decision_to_assessment.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AssessmentEntityFactory.kt

Whilst thinking about which further endpoints we'd need for assessments realised that the current GET endpoint is missing a decision which would need to be a first class property so adding that here.

819 - assessment decision

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt

telephoneNumber is actually nullable

Fix for StaffUserDetails deserialization issue

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt

**Implement GET /assessments/{id}**
This endpoint returns the assessment if the user making the request:
- Is the allocated assessor
- Is a WORKFLOW_MANAGER
Otherwise, it will return a 403.

Implement get assessment by ID endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentClarificationNoteTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt

**Implement the POST /assessment/{id}/notes endpoint**
This adds a clarification note to the assessment

819 - Add clarification notes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/prisonsapi/Alert.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AlertTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AlertFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAcctAlertsTest.kt

Implement GET ACCT Alerts endpoint

822 - ACCT endpoint

---

doc/architecture/decisions/0008-add-first-class-citizen-fields-to-applications.md

This is a first draft of an ADR for hadling first-class citizen fields in Applications. I've spelt out some other possible options, as well as the way forward I've chosen. This is by no means set in stone, and I'd like to get as much feedback as possible before deciding on a way forward, so please, if you think this is rubbish, please tell me!

(797) ADR for first class citizen fields in Applications

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/OffenceAnalysisTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/OffenceAnalysisTransformerTest.kt

**Update all OASys responses to include assessmentState, dateStarted and dateCompleted**
**Update transformer for Offence Analysis**

OASys dateStarted/dateCompleted changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/prisonsapi/AdjudicationsPage.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AdjudicationTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AdjudicationFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AdjudicationTransformerTest.kt

`charges`->`adjudicationCharges`

Correct property name in Adjudications

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApOASysContextApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/oasyscontext/HealthDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NeedsDetailsTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/HealthDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/NeedsDetailsTransformerTest.kt
wiremock/mappings/ApAndOasys_GetHeath.json

Add section 13: Health to the selection endpoint
When requested, return question 13.1t - General health: any mental or physical health conditions?

923 - OASys Health section

---

src/main/resources/static/domain-events-api.yml

Adds:
- `deliusEventNumber`, and
- `applicationId`
to Domain Events. See individual commits for rationale and more details.

Add deliusEventNumber and applicationID to Domain Events

---

.circleci/config.yml

Rename preprod context

---

src/main/resources/static/api.yml

https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/195#discussion_r1012724085

Split out accept/reject endpoints for Assessments

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/oasyscontext/OffenceDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/OASysSectionsTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenceDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/OASysSectionsTransformerTest.kt
wiremock/mappings/ApAndOasys_GetOffenceAnalysis.json

This fixes an issue with missing offence details from the OAsys sections endpoint by renaming a property

Correct offence analysis

---

.circleci/config.yml

This will require manual approval.

Deploy to the new staging/test environment

---

helm_deploy/values-test.yaml

Copy of the dev variables and add in our hostname `approved-premises-api-test.hmpps.service.justice.gov.uk`

Add Test Helm charts

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/OffenderDetailSummary.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenderDetailsSummaryFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt

This property is no longer returned

Remove previousConviction from Community API response model

---

src/main/resources/db/migration/test/R__1_create_users.sql
src/main/resources/db/migration/test/R__2_create_rooms.sql
src/main/resources/db/migration/test/R__3_create_bookings.sql
src/main/resources/db/migration/test/R__4_create_applications.sql

This follows on from #319 and creates a bunch of rooms, as well as some additional bookings for the Temporary Accommodation service in the test environment.

Add test migrations for Temporary Accommodation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/CommunityApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/TeamCaseLoad.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/resources/application.yml
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ManagedOffenderFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/StaffUserDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/StaffUserTeamMembershipFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TeamCaseloadTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
src/test/resources/application-test.yml

This PR adds a new GET endpoint at `/people/team-caseload` which returns a list of Offenders (CRN, firstName, lastName) which are managed by anyone in any of the requesting user's Delius teams.

853 - Team Caseload Endpoint

---

helm_deploy/values-test.yaml

These were only added to the dev env originally

Add IP ranges of NCC pen testers to the test env

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt

We also need the name of the user who created an application, so adding this in

Add name to user response

---

src/main/resources/static/domain-events-api.yml

The Delius team will need to record this in Delius, we think by adding to the Residence NSI.

Add 'booking.extended' domain event

---

helm_deploy/values-test.yaml

This should help us figure out some issues that we’re having

Log SQL in test

---

.github/workflows/generate-ui-types.yml

Trigger generate-types workflow on the TA UI repo as well as AP UI repo

Generate types in Temporary Accommodation frontend

---

helm_deploy/values-test.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt

Reverts some debug changes that were made to help debug why allocated assessments were not appearing in the test environment

Revert assessment debug changes

---

src/main/resources/db/migration/test/R__1_create_users.sql
src/main/resources/db/migration/test/R__3_create_bookings.sql
src/main/resources/db/migration/test/R__4_create_applications.sql

The Application data in the Wiremock repo was outdated. This was fixed in the repo (https://github.com/ministryofjustice/hmpps-community-accommodation-wiremock/pull/15) but we forgot to update the migrations

Update test migrations with new Application data

---

Dockerfile

Make the appuser the owner of the /tmp/seed directory

Chown /tmp/seed in Docker image

---

Dockerfile
doc/how-to/run_seed_job_remotely.md
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SeedUsersTest.kt

- Correct script path in docs
- chmod script

Seeding changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/oasyscontext/RoshSummary.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/OASysSectionsTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/RoshSummaryFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/OASysSectionsTransformerTest.kt

Fixes for https://trello.com/c/5oRbfAPH/1006-bug-crossed-wires-in-oasys-fields

1006 - OASys issues

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-test.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DomainEventsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/JsonSchemaEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/StaffUserDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonLogicService.kt
src/main/resources/application.yml
src/main/resources/db/migration/all/20230202164753__extend_ap_application_schema.sql
src/main/resources/db/migration/all/20230202164754__application_schema.sql
src/main/resources/static/domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationJsonSchemaEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/StaffUserDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApplicationSubmittedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/resources/application-test.yml

Create an Application Submitted Domain Event when application is succesfully submitted.

991 - Application submitted event

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt

This will be needed for the allocations work

Allow workflow managers to access /users

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/GroupedDocuments.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DocumentFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/DocumentTransformerTest.kt

This reflects what we've encountered in Delius, in conviction-level docs so far.

Make Document.author nullable

---

src/main/resources/db/migration/all/20230208095645__update_ap_applications_json_schema.sql

This is an update to the last inserted schema rather than a new one because it addresses issues with the schema itself rather than representing a change to the model the schema validates.

Update AP Applications JSON Schema

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt

This updates the `/allocations` endpoint to return the new assessment when reallocating, as well as a 201 status

(1216) Return assessment data when reallocating

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RedisConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/deliuscontext/ManagingTeamsResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/resources/application.yml
src/main/resources/db/migration/all/20230209131036__store_delius_staff_code.sql
src/main/resources/db/migration/all/20230209144819__team_codes_for_ap_applications.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt
src/test/resources/application-test.yml

Record Delius team codes when creating an AP Application.  Only allow creation if at least one team is present for the calling user.

1226 - Record managing team

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt

This should help us investigate an issue in dev where a CRN with registrations is returning as error in the enveloped response.

Log for failed requests to registrations endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt

Reverts ministryofjustice/hmpps-approved-premises-api#427

Revert "Log for failed requests to registrations endpoint"

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/values-test.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
src/main/resources/application.yml
src/main/resources/static/domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApplicationAssessedAssessedByFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApplicationAssessedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/CruFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
src/test/resources/application-test.yml

Emit Domain Event when Assessment is accepted or rejected.

1105 - Application Assessed Domain Event

---

src/main/resources/db/migration/test/R__1_create_users.sql

This update is generated by the wiremock repo

Update repeatable test migration

---

src/main/resources/static/api.yml

This adds some new properties to the SubmitApplication model, as we will be passing these in from the frontend. Once the frontend work is done, we will make these required and remove the complex JSONlogic work to pull these varaibles from the application.

(1247) Add new properties to SubmitApplication

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

We were sending the wrong value for this

Fix for application submitted on in Person Arrived Domain Event

---

.gitignore

Ignore:
- `.DS_Store` files from Mac OS' Finder
- any Git patch files

Add to git ignore

---

src/main/resources/db/migration/local+dev/R__1_create_dev_users.sql

This adds all the available roles to the development users. I’ve also renamed the Delius username for `JIMSNOWLDAP` as it comes back from Delius as all uppercase.

Add all roles to all dev users

---

README.md

We want to force a dev deployment in order to reseed the database.

Document the different environments

---

build.gradle.kts

Upstream dependencies of ktlint need to be updated, in the meantime this is a workaround.  See https://github.com/pinterest/ktlint/issues/1391

Fix for ktlintFormat

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

- Switch away from temporary secret to proper secret in dev.
- Enable Domain Events in preprod/prod and point at secret.

Domain Events secrets update

---

src/main/resources/static/api.yml

Otherwise this will cause problems with the typing in the UI

Make applicationId required in Task

---

src/main/resources/static/api.yml

Some validation errors I noticed when trying out some contract testing that prevented me from validating the OpenAPI spec. They're all non-trivial, so shouldn't affect the generated code at all.

Fix Open API spec errors

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BedTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RoomTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BedTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RoomTransformerTest.kt

These are unique, human-readable codes used by Approved Premises for managing stock
and defined in the recent "surveys" for premises.

Expose Room.code and Bed.code via API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssessmentUtils.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PlacementRequestUtils.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/StringHelpers.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/StringHelpersTest.kt

This adds an endpoint to get a task of a particular type for an Application. Currently only Assessments or Placement Requests are supported

(1367) Add an API endpoint to get a task

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt

This should not happen in real life, as the UI should have caught this error before we get to this point, but this will help debugging if it does happen.

Return error if postcode district does not exist

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt

When the frontend does not send requirements (which it will do when there is no known release date) do not create a Placement Request.

1403 - Don't create a Placement Request without requirements

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt

This returns a status for a placement request depending on if there is an associated booking or booking_not_made

Add a status to a placement request

---

src/main/resources/static/api.yml

I missed this in the previous PR.

Make all fields required in booking confirmation

---

src/main/resources/static/api.yml

https://trello.com/c/ANgzvWOE/1064-openapi-specs-created-to-support-front-end-development

1064 - OpenAPI spec changes for turnarounds

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LostBedsEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUsageReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BookingsReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BedUsageReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/BedUsageReportProperties.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUsageReportGeneratorTest.kt

https://trello.com/c/GQxvkTmU/1007-download-a-report-on-all-bookings-voids-and-turnaround-times

1007 - Bedspace usage report endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUsageReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/BedUtilisationReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/BedUtilisationReportProperties.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt

https://trello.com/c/QQVYXWWI/1006-download-a-report-on-utilisation
Depends on some changes in 1007 so that's the base branch for now to avoid showing both sets of changes in this PR

1006 - Bedspace Utilisation report

---

src/main/resources/static/api.yml

This updates the list of placement criteria to match what we'll be asking for in the new designs.

Update list of placement criteria

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
src/main/resources/db/migration/all/20230518133742__remove_mental_health_support_from_placement_requirements.sql
src/main/resources/db/migration/all/20230518134358__add_notes_to_placement_requirements.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt

This PR removes the mental_health_support column from placementRequests and adds a new notes column.

Update placement request entity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NotifyGuestListUserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/EmailNotificationServiceTest.kt

PR #656 updates the version of uk.gov.justice.hmpps.gradle-spring-boot to 4.8.7, which includes new rules for ktlint. Most of the breaking changes have already been resolved by #662, however #631 has introduced some additional changes which don't currently fail ktlint but violate the incoming rules.

Format project with incoming ktlint rules

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/values-test.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/resources/application-test.yml

Send an email to the probation practitioner that created the original Application when a Booking is created

183 - Booking Made Notify Emails

---

src/main/resources/db/migration/all/20230602102511__add_cancellation_reasons_for_ap.sql

Add cancellation reasons for AP

---

.github/workflows/generate-ui-types.yml

repo is now `hmpps-community-accommodation-2-ui`

rename `supported-accommodation` for type generation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApplication.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt

This adds some additional fields to the Placement Applications API response so we can link to the applications and assessments and show the dates they were completed.

Add additional fields to Placement Applications

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt

This allows us to quickly get the decision of an assessment alongside an application

Return Assessment decision with the application

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/NonArrivalReasonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/resources/db/migration/all/20230619095005__add_non_arrival_legacy_reason_codes.sql
src/main/resources/static/domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NonArrivalReasonEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PersonNotArrivedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt

This PR adds Delius legacy reason codes to Non Arrival reasons & saves these as part of the non arrival domain event.

243 - Non Arrival legacy reason codes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt

Value actually being stored in the database is `inCommunity` but the transformer was looking for `in_community`

270 - Fix for In Community release type breaking Tasks

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt

We need to display the person’s CRN as well as their name in some cases.

Add CRN to task response

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/community/Conviction.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ConvictionTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OffenceFactory.kt

The offenceDate on our offences response also needs to be nullable because of this

offenceDate on convictions response from Community API can be null

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt

This is currently the default 30s

Set upstream timeout to 10s for all Clients

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

This should hopefully make debugging easier.

Improve error message when allocation fails

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DocumentsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CalendarService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/CalendarServiceTest.kt

Fixes issues with not being able to perform many actions despite having LAO qualification

Apply LAO qualification in more places

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt

This is required for the reallocate Tasks page on the UI

Allow LAO qualified users to get Application by Id

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt

This may be due to error or failing LAO

Filter out Bookings on Get Bookings for Premises endpoint that we cannot display person detail for

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/ApDeliusContextApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationDocumentsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt

- Create Application: if you pass LAO check
- Application appears in the list view (i.e. /applications in the UI): only if you created it
- Can access Application by its ID (i.e. through direct link to it /applications/{id}): if you pass LAO check or have the LAO qualification

276 - Application auth changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingSearchService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingSearchServiceTest.kt

> See [ticket #1334 on the CAS3 Trello board](https://trello.com/c/DBJ35e6B/1334-find-a-booking-journey-doesnt-log-the-user-out-if-a-booking-for-a-lao-exists).
Currently, if a user does not have LAO access, when they search for bookings the API will return a `403 Forbidden` response if one of the results is for a LAO offender. This will have the effect of logging the user out of the application on the frontend, making the booking search inaccessible.
Instead, these bookings should be filtered out when the API computes the response so that the user can successfully see bookings for which they have permissions.

Hide bookings for LAO offenders from bedspace search endpoint when user does not have LAO access

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/MDCHandlerInterceptor.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/BadRequestProblem.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt

- Fix MDC issues
- Log 400/500 reasons to aid live issue investigations

Logging changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingSummaryTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingSummaryTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt

If a booking is present, we return the booking in the PlacementRequestDetail object. We also add an applicationDate to the PlacementRequest object, which shows when the application was submitted.

Add additional data to PlacementRequest

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt

- Don't attempt to get forename/surname for submitting user by splitting, fetch from Community API
- Fix mix between key worker and submitting user info on departure event

Fix Booking Domain Event issues

---

helm_deploy/values-prod.yaml

Previously request of 512Mi, limit of 1Gi
Increased to request of 1Gi, limit of 1.5Gi
Also increase Xmx (max heap size) value to 1000m to allow the JVM to use this extra memory

Increase memory in prod

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementDateEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementDatesQueryTest.kt

Accepting a Placement Application is creating too many Placement Requests

Fix for too many Placement Requests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt

This allows us to specify the direction that the sortBy field sorts in.

Add a sortDirection query string

---

helm_deploy/values-prod.yaml

Person Arrived/Departed and events for manual Bookings are now disabled in prod

Enable feature flags to disable certain domain events in prod

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/values-test.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/AdjudicationsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/adjudications/AdjudicationsPage.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AdjudicationTransformer.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AdjudicationChargeFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AdjudicationFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AdjudicationsPageFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AgencyFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAdjudicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/AdjudicationsAPI.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/PrisonAPI.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AdjudicationTransformerTest.kt
src/test/resources/application-test.yml

https://dsdmoj.atlassian.net/browse/NN-5364

NN-5364: get adjudication data from AdjudicationsAPI instead of PrisonAPI

---

src/main/resources/db/migration/all/20230816092953__update_cancellation_reasons.sql

This retires the "Booking successfully appealed" reason and adds a new "Error in booking" reason

Update cancellation reasons

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt

This should have been added to the communityApiWebClient, not apDeliusContextApiWebClient

Add maxResponse to the correct place

---

.circleci/config.yml

This ensures both frontends are still working as expected after any changes have been made to the API.

Run UI E2E tests after dev deploy

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt

> See [ticket #1236 on the CAS3 Trello board](https://trello.com/c/wwIx6B4b/1236-delius-users-who-visit-the-service-for-the-first-time-are-given-the-default-role-of-cas3referrer).
There are over 13,000 CPPs as potential users of the Temporary Accommodation service, and collecting the information needed to seed everyone into the database is a prohibitively difficult task. It's therefore easier to seed all of the users for whom some other role is appropriate and allow the Temporary Accommodation service to assign the `CAS3_REFERRER` role to anyone who doesn't already have a CAS3 role assigned to them when they sign in for the first time.
This PR introduces this mechanism. It's applied when the `X-Service-Name` header for the current request is set to `"temporary-accommodation"`, so will not …

Assign default role of `CAS3_ASSESSOR` for users in Temporary Accommodation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserServiceUtils.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt

Endpoints to allow staff to delete a user and to update a user's roles and permissions.

337 we need screens to enable cru staff to manage user accounts and permissions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa.specification/UserSpecifications.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/resources/db/migration/all/20230904150610__add_active_flag_to_users.sql
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/UserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAUser.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt

User delete sets user isActive to false. Unit tests and integration tests.

Delete user flags that user with false for isActive

---

doc/architecture/decisions/0016-plan-for-sharing-cas3-arrival-and-departure-times.md

We'd like to decide on how CAS3 will share arrival and departure times with nDelius via Domain events.

ADR for plan on sharing CAS3 departure times

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/InmateDetailsCacheRefreshWorker.kt

This adds additional logging for the purposes of debugging the current issues we're having in production regarding repopulating the inmate details cache (see [Slack thread](https://mojdt.slack.com/archives/C03GF35FY7P/p1694779840911009)), where the messages are logged at `ERROR` level and tagged with `[CONSPICUOUS]` for easy searching.
This should help us determine whether this cache refresh worker is running as it should.

Use conspicuous logging for `InmateDetailsCacheRefreshWorker`

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/ApplicationReportGeneratorTest.kt

We attempted to fix this in #971, but this did not work as expected, partly because the integration tests weren't working correctly.

(Fix) Get premises type correctly

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/resources/static/api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt

This will allow a user to review an assessment easily when given an application.

(453) Add an assessment ID to an application

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserAllocationsEngine.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserAllocationsEngineTest.kt

The new allocations engine is not behaving as expected, because the SQL `IN` query was including qualifications and roles that were included in other rows. This now updates the criteria builder to do selective joins on each qualification/role and include / exclude them as necessary.
I’ve also updated the tests to be more robust and:
a) create a full corpus of users (not just ones with the roles we need) 
b) test that `getUserPool` only returns users with the required roles and qualifications.

(476) Fix allocations engine

---

helm_deploy/values-test.yaml

This will be needed for the test environment.

Add missing BASE_URL to test env for Nomis-User-Roles API

---

build.gradle.kts

We recently added some config to skip the OpenAPI generation task when running tests in IntelliJ, to try and speed up testing in development. However, before, we were skipping the OpenAPI generation task in the `withType` block directly. 
Weirdly, because of the [Grade build lifecycle](https://docs.gradle.org/current/userguide/build_lifecycle.html), doing it this way meant that we skipped the tasks for every task that was run, not just tests. This meant that if we tried to run the `openApiGenerate` task within Intellij, the task got skipped and just didn’t run. 
This adds an `onlyIf` conditional to skip all the OpenAPI generation tasks if the dependent task is a test type task and the task is being run from inside IntelliJ

Skip OpenAPI Generate task correctly

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesBookingSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/ApprovedPremisesOfflineApplicationsSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/resources/application.yml
src/main/resources/db/migration/all/20231026150308__add_event_number_to_offline_applications.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/OfflineApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

This made its way into prod before it was fully tested in preprod.

Revert domain events for manual bookings

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NomisUserTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/ApplicationsTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/NomisUserTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas2/ApplicationsTransformerTest.kt

This provides information about the "applicant" -- the Nomis User who created the application. This is needed for the "Application Summary" section at the top of the view of a submitted application.
The missing metadata and what's provided here:
- name: now provided
- email: now provided
- phone: not currently available
- referrer institution: we will provide this once we implement "Search for person by prison number"
We now present the available and useful Nomis user information within `SubmittedApplication.submittedBy`:
```
{
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"person": {
"crn": "string"
},
"createdAt": "2023-11-06T17:03:17.630Z",
"submittedBy": {
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"name": "Roger Smith",
"nomisUsername": "SMITHR_GEN",
"email": …
```

Add NomisUser representation to SubmittedApplication

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/SubmissionsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/StatusUpdateEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/StatusUpdateService.kt
src/main/resources/db/migration/all/20231108161708__create_table_for_cas_2_status_updates.sql
src/main/resources/static/_shared.yml
src/main/resources/static/cas2-api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2StatusUpdateTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/StatusUpdateServiceTest.kt

See individual commit messages / OpenAPI specs for details.

(629) New endpoint for CAS2 status updates on submitted applications

---

.circleci/config.yml

We need to use this image as the E2Es depend on it

Update playwright version to 1.39

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationTimelineNoteEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationTimelineNoteService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineNoteTransformer.kt
src/main/resources/db/migration/all/20231120095320__change_created_at_date_to_date_time.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApplicationTimelineNoteEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt

Also let’s rename the column to be clear about the intention

(Chore) Change application createdAtDate to datetime

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt

We need to use the more specific ApplicationStatus for AP so we get the correct types in the UI repo

Use ApprovedPremisesApplicationStatus for AP Applications

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt

Hotfix: nomis user roles client config

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventWorker.kt
src/main/resources/application-local.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventWorkerTest.kt
src/test/resources/application-test.yml

Retry using spring retry. Async done with Coroutines. Feature is off for now. Can be turned on by changing values in application=local.yml

Retry SNS event if fails

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/values-test.yaml

Add `ASYNC-ENABLED` environment variables

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventWorker.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventWorkerTest.kt

After approving #1224, I noticed that we didn’t need to get the domainTopic in both the service and the worker. This simplifies the calls to the worker by removing the `hmppsQueueService` from the Service and fetching the `domainTopic` when we initialize the `ConfiguredDomainEventWorker`. We can then set up the `publishEvent` in the worker classes, rather than passing it from service to worker.
I’ve also made some tweaks to the tests, using `mockkConstructor` to tighten up the expectations in the `ConfiguredDomainEventWorker` tests, and making the mock call expectations tighter using a `matchingPublishRequest` function.
I also noticed that the verifications in the `DomainEventServiceTest` were asserting that `mockHmppsTopic.snsClient.publish` was not being called, which would always …

Simplify DomainEvent-related classes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/BookingStatusMigrationJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
src/main/resources/db/migration/all/20231213121417__add_status_column_to_booking.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/MigrateBookingStatusTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingSummaryTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt

Refer [1742](https://trello.com/c/6XMIEPmD/1742-improve-booking-search-by-using-a-status-column) for more information.
This PR contains changes to introduce new `status` column in `bookings` table.  This PR contains 2 changes
1. The `status` column will be populated based on the below booking API :
``` 
/placement-requests/{id}/booking  --> confirmed
/premises/{premisesId}/bookings.  --> confirmed
/premises/{premisesId}/bookings(CAS3)  --> provisional
/premises/{premisesId}/bookings/{bookingId}/arrivals --> arrived
/premises/{premisesId}/bookings/{bookingId}/cancellations --> cancelled
/premises/{premisesId}/bookings/{bookingId}/confirmations --> confirmed
/premises/{premisesId}/bookings/{bookingId}/departures --> departed
```
2. Migrate existing CAS3 booking status.
The migration of …

[1742] - Add new booking status column and migrate CAS3 booking status

---

src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml

This was missed out in a previous PR

Add response headers to assessments endpoint

---

src/main/resources/db/seed/local+dev+test/cas2_application_data/data_A1234AI.json
src/main/resources/db/seed/local+dev+test/cas2_application_data/document_A1234AI.json

Adds one question and removes another. See commits for details.

Update CAS2 seeding fixtures

---

src/main/resources/db/seed/local+dev+test/cas2_application_data/data_A1234AI.json
src/main/resources/db/seed/local+dev+test/cas2_application_data/document_A1234AI.json

Updates seed data with various new questions and key name updates.
NB: should only be merged after https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/448.

Update CAS2 application seed data

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequirementsEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/PlacementRequestTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt

Added some additional regression tests for placement request dashboard in preparation for adding additional filter/sort params
Refactoring to prepare for more arguments being required

Placement Request Dashboard Regression Tests and Refactoring

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt
src/main/resources/static/_shared.yml
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-198
Add requestType filtering
Add sorting for risks, name and request type
This PR also introduces an enum type for a Placement Request ‘request type’ which is included in the model returned to API callers

Enhance Placement Request Dashboard Filtering and Sorting

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt

This completes work require for APS-196

/tasks/reallocatable filterable on ap area id

---

src/main/resources/db/migration/all/20240125122510__add_indexes_to_user_assignments_tables.sql

Searching for users via roles and qualifications is taking an inordinately long time. Adding these indexes should hopefully speed things up!

Add missing indexes to user assignments tables

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt

These should be in a certain order for our assessors.
```
More information requested
Awaiting decision
On waiting list
Place offered
Offer accepted
Offer declined or withdrawn
Referral withdrawn
Referral cancelled
Awaiting arrival
```
https://dsdmoj.atlassian.net/browse/CAS2-142

Re-order CAS2 Status updates

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/resources/db/migration/all/20240129114304__add_withdrawal_reason_to_placement_requests.sql
src/main/resources/db/migration/all/20240129130353__add_withdrawal_reason_to_placement_application.sql
src/main/resources/static/_shared.yml
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt

https://dsdmoj.atlassian.net/browse/APS-246
Also includes a logic change, allowing applicant to withdraw their own placement requests (previously this could only be done by a manager)

Add withdrawal reasons for placement requests and placement applications

---

detekt-baseline.xml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/UserServiceUtils.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt

This adds a new `CAS3_APPEALS_MANAGER` role that will be used to manage appeals in the system

(APS-237) Add Appeals Manager role

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt

If someone with permissions to see LAO offenders gets assigned an LAO offender, they can’t proceed, as they can’t click through to the assessment. As they’re able to view the assessment (and all the associated personal details) it follows that they should be able to see the details
I’ve only made the change for CAS1 at this point to avoid any unexpected issues on CAS3

(APS-259) Allow assessors with LAO to see full person

---

src/main/resources/db/migration/dev+test/R__8_create_cas3_application_and_assessment.sql

Refer [CAS-185](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-185) for more information.
This PR is to insert CAS3 applications in test, dev env for testing purpose. This helps for any analysis/research work in assessment and booking flow.
confirm:
advance?
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjust …

Pre-load CAS3 applications in test/dev env for testing purpose

---

src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml

Relates to https://dsdmoj.atlassian.net/browse/APS-270

Add additional application withdrawal reasons

---

src/main/resources/db/migration/all/20240202140831__update_cas1_booking_cancellation_reasons.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-268

Update CAS1 Booking Cancellation Reasons

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WithdrawableService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt

This adds a configurable `showAllBookings` option to the `allWithdrawables` service function. If true, we use the `UserAccessService` to see if the user can manage the booking. If they can’t we filter them out.
In reality, `currentUserCanManagePremisesBookings` for CAS1 only looks at a user’s role, so this will only return true for CRU or AP managers.
When using the withdrawAllForApplication, we set `showAllBookings` to true, because it doesn’t make sense to withdraw an application and not withdraw the associated bookings. This may change as the service evolves, but I think this makes sense as things currently stand.

(APS-273) Hide withdrawable bookings from non CRU users

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-311

Add isWithdrawn to PlacementRequest and PlacementApplication model

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

Refer [CAS-50](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-50) for more information.
This PR is to automatically close the CAS3 assessments after the booking is made successfully.
Business wants to close CAS3 assessment automatically after booking is done, So that a referral is no longer appears in the `Ready to Place` queue to avoid confusion or duplicate booking. We have separate story(cas-176) to reinstate assessment when the booking is cancelled.
The change is in `BookingService` to call an existing `AssessmentService.closeAssessment()` method to close the assessment automatically as part of booking creation.
Additionally, our requirement is not to fail the booking if the closure of assessment is failed for some reason, instead we complete …

[CAS-50]-Automatically close CAS3 assessments after booking is made

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt

These are the confirmed details for the More Information status.
Copy source to compare is here:
https://docs.google.com/document/d/17m4erVi3dtOxnWgYj_CcFQqYlBsL92yn-sI1vhXo3so/edit?pli=1

Add Status Details to More Information

---

detekt-baseline.xml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/values-test.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/AdjudicationsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonsApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/PrisonAdjudicationsConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/WebClientConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/adjudications/AdjudicationsPage.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AdjudicationTransformer.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AdjudicationChargeFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AdjudicationFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AdjudicationsPageFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/AgencyFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonAdjudicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/AdjudicationsAPI.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/PrisonAPI.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AdjudicationTransformerTest.kt
src/test/resources/application-test.yml
wiremock/mappings/AdjudicationsApi_GetAdjudicationsPage.json

Reverts ministryofjustice/hmpps-approved-premises-api#1437
We had tried to test it and the data on dev but did so when [ndelius was performing a regular update](https://mojdt.slack.com/archives/C6C1KGRME/p1707822758231049) so need to pull out and try again later.

Revert "Revert "Merge pull request #892 from ministryofjustice/NN-5366""

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt

Update labels for Cas2PersistedApplicationStatusDetail to be consistent with upper/lowercase.

Update labels for Cas2PersistedApplicationStatusDetail

---

src/main/resources/db/migration/dev+test/R__8_create_cas3_application_and_assessment.sql

This PR is to correct the json-schema version to latest schema version to avoid getting error when API validate latest schema.

[Chore]-CAS3 Seeded application to use latest schema version to avoid error in schema validation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestTransformerTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-328

Add withdrawal reason when returning Placement Request, Placement Application and Application Summary API Objects

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt
src/main/resources/static/cas3-domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3BookingCancelledEventDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3BookingConfirmedEventDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3BookingProvisionallyMadeEventDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3PersonArrivedEventDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/CAS3PersonDepartedEventDetailsFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/cas3/StaffMemberFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/DomainEventTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventBuilderTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt

Refer [CAS-196](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS/boards/1331?selectedIssue=CAS-196) for more information.
This PR is to include staffDetails(staffcode, staffRegion) into existing CAS3 domain events(refer below list), so that the nDelius shows the staff details correctly.
Below domain events are changed to include the additional staff details:
1. accommodation.cas3.booking.provisionally-made
2. accommodation.cas3.booking.confirmed
3. accommodation.cas3.booking.cancelled
4. accommodation.cas3.booking.cancelled.updated
5. accommodation.cas3.person.arrived
6. accommodation.cas3.person.arrived.updated
7. accommodation.cas3.person.departed
8. accommodation.cas3.person.departed.updated
Its been agreed with integrationTeam to send the nDelius's Staffcode and NDelius …

[CAS-196] - CAS3 domain events populated with Staff detail

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt

Update tests to ensure that if a placement application is directly withdrawn, placement applications on the same applciation are not also withdrawn

Enhance withdrawal cascade integration tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/TransitionalAccommodationReferralReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/TransitionalAccommodationReferralReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/TransitionalAccommodationReferralReportRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/TransitionalAccommodationReferralReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/ReportServiceTest.kt

This PR is to add new column `dateAccommodationRequired` and remove existing `nomisNumber` from CAS3 Referral report.

[CAS-211]-CAS3-ReferralReport-Add new dateAccommodationRequired column and remove nomisNumber

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-386

Workflow Manager should be able to withdraw placement applications

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationEmailService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestEmailService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/notification/EmailNotificationAsserter.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationEmailServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestEmailServiceTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-163
See the most recent comment on APS-163 for an explanation of when emails will be sent
This PR also includes some improvements to the existing Withdrawal Cascade integration tests

Request for Placement and Match Request Withdrawal Emails

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
src/main/resources/static/domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PlacementApplicationWithdrawnFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationDomainEventServiceTest.kt

This description now include the dates.

Improve request for placement domain event description

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementApplicationTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementApplicationTransformerTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-401

Add placement dates to Placement Application API Model

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-396

Only Workflow Managers (CRU) can cancel bookings

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/WithdrawalTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WithdrawableServiceTest.kt

Relates to APS-408
This is required by the UI to populate the confirmation after withdrawal is complete

Return Placement Req details when withdrawing PR

---

helm_deploy/values-preprod.yaml
helm_deploy/values-test.yaml

This PR is to correct the env property setup before as its not picking the value.

[CAS-195]-Correcting the env config value setup to download report for 3 months

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/ReportService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/ReportServiceTest.kt

This PR is to throttle the existing service call `offenderService.getOffenderSummariesByCrns()` with configured number of crns in each request.
This change is to fix the problem in CAS3 report where calling the service with more than 500 crns is failing as there is a restriction in number crn in each request by integration team. Please find the details here : https://mojdt.slack.com/archives/C03KVQUFSER/p1709284991241579
The change is to split the number of crns into subset of 400 crns and then call the `offenderService.getOffenderSummariesByCrns` service sequentially with 400 crns in each request and collect the response.

[CAS-245]-CAS3-Report-Throttle offender service call to get person info

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1PlacementMatchingOutcomesEntityReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/Cas1PlacementMatchingOutcomesReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/Cas1PlacementMatchingOutcomesReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/Cas1PlacementMatchingOutcomesReportProperties.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementMatchingOutcomesReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-472

Add CAS1 Placement Matching Outcomes Report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt

PR to fix bug in SQL for archive assessments .

[CAS3] - Fix issue in archive assessments pagination for multiple status

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntityReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1PlacementMatchingOutcomesEntityReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntityReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ApplicationReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/Cas1PlacementMatchingOutcomesReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/PlacementApplicationReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/ApplicationReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/Cas1PlacementMatchingOutcomesReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/PlacementApplicationReportRow.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementMatchingOutcomesReportTest.kt

Relates to https://dsdmoj.atlassian.net/browse/APS-502

Add 'tier' to various reports

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UserCaseSensitivityTest.kt

Removing an unused function and improve naming of getUserForUsername to better reflect side effects

User Service Tidy Up

---

helm_deploy/values-prod.yaml

Please don't merge, just seeking approval ready for go/no go

Enable new withdrawal logic in prod

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

We do this with most of the other first-class fields, so we should do it here too for consistency.

(APS-514) Set notice type when updating

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1FixPlacementApplicationLinksJob.kt

This is following the second run of backfill in pre-prod which considered additional applications due to previous fixes to the backfill logic

APS-348 Add additional manual fixes for PA to PR backfill

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/ApplicationWithdrawnFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt

APS-521 show application withdrawal reason in timeline events

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

This PR to validate the booking dates with bedspace enddate to make sure the bed is valid and available to book.

[CAS-200]-Validate bedspace enddate for cas3 booking

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationEmailService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationEmailServiceTest.kt

This is in preparation for making changes to these emails

APS-343 Use CAS1 Placement Application Email Service for all related emails

---

helm_deploy/values-dev.yaml

PR to enable CAS3 domain event in `dev` env
person.arrived.updated
person.arrived
person.departed
person.departed.updated

Enable cas3 arrival,departure and update domain events in dev env

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/resources/db/migration/all/20240402095208__add_sex_offences_columns_to_cas3_application.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

This PR CAS-281(https://dsdmoj.atlassian.net/browse/CAS-281) includes:
- Add new fields isHistoryOfSexualOffence and isConcerningSexualBehaviour to CAS3 application to use later for reports
- The isRegisteredSexOffender field is already added to the CAS3 application

[CAS-281] Capture sex offences and behaviour for MI

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/RoomService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/RoomServiceTest.kt

This PR is to update the error message thrown from bed-space end date validation to support UI.

[CAS-60]-CAS3-Updated the error message related to bed-enddate

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUsageReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/BedUtilisationReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/PlacementMetricsReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/ReferralsMetricsReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskDeadlineService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WorkingDayCountService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/WorkingDayService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentEmailService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementMetricsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferralsReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUsageReportGeneratorTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/BedUtilisationReportGeneratorTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/PlacementMetricsReportGeneratorTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/ReferralsMetricsReportGeneratorTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskDeadlineServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WorkingDayCountServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/WorkingDayServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentEmailServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt

This PR doesn't container any functional changes, instead it's refactoring the TaskDeadlineService and WorkingDayService (and tests) in preparation for adding more deadline calculation functionality

APS-563 Task Deadline & Working Day Service Improvements

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/PlacementApplicationEntityTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt

Now we’re returning completed tasks, we need to record what the outcome was and when that outcome was recorded.

(APS-602) Return task outcome and recorded at date

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt

We need this when displaying applications that are pending a placement request

(APS-603) Return releaseType in application summaries

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/resources/db/migration/all/20240410160408__add_duty_to_refer_outcome_id_columns_to_cas3_application.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

This PR to capture and store the duty to refer outcome entered in referral form into temporary_accommodation_application table.

[CAS-289]-Capture and store dtr outcome in cas3 application table

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt

This PR is rename and correct some of the integration test which is common for all type of cas3 reports

Renamed the cas3 specific integration test to reflect the recent changes

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DbExtension.kt

While digging into the running time of the tests, I saw a bunch of SQL queries that I didn’t expect to be running at the start of each test run. While digging into it I noticed that these weren’t actually SQL queries, but we were outputting an SQL query for each individual database table when attempting to restore the database to its original state. I’ve made a couple of tweaks to improve the logging so it’s clearer as to what’s going on and also only running `TableResults#insert` if there are any rows to insert.
I don’t think this will help performance much, but it’ll at least make it clearer as to what’s going on.

(Chore) Improve logging of database cleanup / restore

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/BedSearchRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt

This PR [CAS-323](https://dsdmoj.atlassian.net/browse/CAS-323) is to fix an issue with searching bedspace that returns bedspace from other Pdus
[CAS-323]: https://dsdmoj.atlassian.net/browse/CAS-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CAS-323 Searching bedspace returns bedspaces from other PDUs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/UpdateAllUsersPduFromCommunityApiJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UpdateAllUsersPduFromCommunityApiMigrationTest.kt

This PR CAS-322(https://dsdmoj.atlassian.net/browse/CAS-322) is to migrate user PDU from nDelius to the users table in CAS

CAS-322 Migrate user PDU from nDelius

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt

We are doing A LOT of shared setup / teardown here, especially in the filtering tests. This seems to be a significant contributor to our slow build times. I’m nested all the tests at one level now and made the filtering/pagination tests inherit from our `InitialiseDatabasePerClassTestBase` class, and things seem a lot quicker.
We could probs improve this further, but I think this addresses the vast majority of the problematic tests.

(Chore) Share database context in TasksTest

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt

Previously many functions called getOffenderDetailsIgnoringLaoQualification but did not capture the result. This was presumably to ensure the user has correct permissions to access the offender. This commit introduces a new function to replace these ambiguous calls

APS-638 Refactor PeopleController for clarity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt

APS-684 Add dates into booking changed event description

---

detekt-baseline.xml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DomainEventsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AppealDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt
src/main/resources/static/domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DailyMetricsReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DomainEventTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/DailyMetricsReportGeneratorTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventWorkerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentDomainEventServiceTest.kt

In preperation for changes in https://dsdmoj.atlassian.net/jira/software/c/projects/APS/boards/1328, I've made a couple of quality of life enhancements that should DRY up some of the work we do with Domain Events, as well as removing some code smells.
Some of this work impacts CAS2 and CAS3 (although it's mainly just a refactor), so I'd appreciate some eyes from other team members too!

(APS-673) Tidy up Domain Events

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/StaffMemberService.kt

in the context of retreiving a staff member ‘not found’ could refer to the qCode not being found, or the staff code not existing in qCode result. This commit adds a warning message to clarify when the later issue occurs

APS-723 - Add logging when staff member not found for qcode

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt

This test does lots of expensive setup/teardown for each test, so let’s share the database context between tests. There’s some slight tweaks I’ve had to make, but the data used in both report tests was pretty much identical

Speed up ApplicationReportsTest

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ReferralRejectionReasonEntity.kt
src/main/resources/db/migration/all/20240430170525__add_sort_to_referral_rejection_reasons_cas3.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ReferralRejectionReasonEntityFactory.kt

This [PR CAS-356](https://dsdmoj.atlassian.net/browse/CAS-356) is to add order by to referral rejection reasons to sorted them as user expected

CAS-356 Add order by to referral rejection reasons

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/resources/db/migration/all/20240430141414__add_referral_rejection_reason_detail_to_cas3_assessments.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationAssessmentEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentStateTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt

This [PR CAS-347](https://dsdmoj.atlassian.net/browse/CAS-347) will capture the referral rejection reason detail for temporary accommodation

CAS-347 Capture referral rejection reason detail

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntityReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/PlacementApplicationReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/PlacementApplicationReportRow.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationReportsTest.kt

APS-766 Add Parole Decision Date into Raw Placement App Report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PrisonReleaseTypeEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ReferralRejectionReasonEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ReferenceDataTest.kt

This [PR CAS-374](https://dsdmoj.atlassian.net/browse/CAS-374) is to refactor: 
- Referral Rejection Reasons
- Prison Release Types

CAS-374 Refactor Reference Data CAS3 endpoints

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas3UpdateUsersPduFromCommunityApiJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/Cas3UpdateUsersPduFromCommunityApiMigrationTest.kt

This [PR CAS-322](https://dsdmoj.atlassian.net/browse/CAS-322) is a migration job to migrate CAS3 users Pdu from nDelius to CAS

CAS-322 Migrate CAS3 users PDU from nDelius

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RequestForPlacementTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RequestForPlacementTransformerTest.kt

Ensures request for placement states returned by the RequestForPlacementService align with the state transition diagram https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4872569106/CAS1+Request+for+Placement+State+Transitions

APS-787 Request For Placement Status Fixes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PrisonReleaseTypeEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PrisonReleaseTypeTransformer.kt
src/main/resources/db/migration/all/20240508150201__add_abbreviation_to_prison_release_types.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PrisonReleaseTypeEntityFactory.kt

This [PR CAS-370](https://dsdmoj.atlassian.net/browse/CAS-370) is to add abbreviation to prison release types

CAS-370 Add abbreviation to prison release types

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/resources/db/migration/all/20240513120304__add_application_prison_release_types_table.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

This [PR CAS-370](https://dsdmoj.atlassian.net/browse/CAS-370) is to add prison release types when submit temporary accommodation application

CAS-370 Add prison release type to temporary accommodation application submit

---

src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

This [PR CAS-370](https://dsdmoj.atlassian.net/browse/CAS-370) is to fix an issue to generate array of UUID for prisonReleaseTypes in SubmitTemporaryAccommodationApplication

CAS-370 Fix issue for prisonReleaseTypes UUID array

---

doc/architecture/decisions/0023-begin-extracting-cas1-code-to-its-own-namespace.md

ADR-023: Begin extracting CAS1 code to its own namespace

---

src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

Adding a new value for 'Bail Placement' Sentence Type  - 'awaitingSentence'.
Added `awaitingSentence` as an Enum value for `SituationOption` in the API definition.
New value already covered in existing test (`ApplicationServiceTest`) which enumerates all possible values for SituationOption.

Added 'awatingSentence' to possible values for SituationOption enum

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt

This [PR CAS-377](https://dsdmoj.atlassian.net/browse/CAS-377) is to show the properties that have archived bedspaces or the property that was archived in the properties list

CAS-377 Show properties with archived bedspaces

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt

This casting causes issues after upgrading to spring boot 3 / hibernate 6

APS-365 Removed unnecessary casting in Task SQL

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentReferralHistoryNoteTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationAssessmentEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentReferralHistoryNoteTransformerTest.kt

This [PR CAS-367](https://dsdmoj.atlassian.net/browse/CAS-367) is to add the:
- Rejection reason
- Rejection reason details
- is withdrawn
to the last rejection note in the notes for the timeline history

CAS-367 show rejection reason and is withdrawn in the HPT timeline view

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml

Whilst not currently used in the API this is being added to allow for the UI to present this option

APS-903 - Add includePii option to CAS1 Reports API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1RequestForPlacementReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/RequestsForPlacementReportProperties.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1RequestForPlacementReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SimpleApiClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestDomainEventServiceTest.kt

Add CAS1 Request for Placement Raw Data Report
This commit provides a rewrite of the CAS1 RAW Placement App Report, adding and removing several fields, including ‘standard’ requests for placements and outputting the report as a CSV file.

APS-855 - Add CAS1 Request for Placement Raw Data Report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/ApplicationServiceTest.kt

When an application is submitted we acquire a pessimistic lock. Prior to this commit the lock would apply to any eagerly loaded relationship on the application, unneccessarily locking tables that would not be updated (e.g. reference data).
In the current version of the code this results in a minor performance issue, but we’ve found that when upgrading to the latest version of hibernate locking across these relationships is no longer possible, and the locks are not being acquired, leading to tests failing.
This commit reduces the scope of locking by introducing a new simplified version of the application entity that defines no relationships. Locking on this entity instead results in the required ‘select for update’ type lock, but only on the applications table itself e.g.
`Hibernate: …

APS-966 - Remove unnecessary table locks on app submission

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
helm_deploy/values-test.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/DomainEventUrlConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DomainEventsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationDomainEventService.kt
src/main/resources/application.yml
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/main/resources/static/domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/RequestForPlacementAssessedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/DomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationDomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/DomainEventHelpers.kt
src/test/resources/application-test.yml

Definition of the domain event and endpoint for retrieval added to API. 
Functions added to both save and get domain events for placement application decisions. 
Save function called in PlacementApplicationService- recordDecision DomainEventDescriber added.

APS-922 : Capture domain event for Placement Application Decisions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1OutOfServiceBedRevisionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/Cas1LostBedsToOutOfServiceBedsMigrationJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedRevisionTransformer.kt
src/main/resources/db/migration/all/20240627102659__allow_out_of_service_bed_revisions_to_have_no_created_by_user_id.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/OutOfServiceBedTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/MigrateCas1OutOfServiceBedReasonsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/MigrateCas1OutOfServiceBedsTest.kt

Run the on-demand migration with:
```
script/run_migration_job update_cas1_lost_beds_to_out_of_service_beds
```

APS-867: migrate CAS1 LostBeds to Cas1OutOfServiceBeds

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt

PersonSummary includes specific information on the type of person - regular, lao, not found or unknown. 
It supersedes 'personName' which was used to derive this information and is now deprecated.

APS-964 : Task API - add PersonSummary

---

script/development_database
script/test_database

docker-compose is deprecated
see https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2

use ‘docker compose’ instead of ‘docker-compose’

---

build.gradle.kts
script/remote_db

Using latest version, resolving potential issue raised by trivy (CVE-2024-1597)

Upgrade postgres driver

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationV2ReportRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationReportTest.kt

Full sample report is on the ticket https://dsdmoj.atlassian.net/browse/APS-1053

APS-1053 Add standard_rfp_arrival_date to CAS1 appv2 report

---

doc/how-to/preprod-database-refresh.md

Indicate how to check the database state in prod/preprod is the same before running the script

Improve database refresh docs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/WebClientCache.kt

This commit updates the error message to clarify the issue is related to refreshing the cache, and includes the URL being requested in the error message to make the requested value clearer

Improve error message when cache refresh fails

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt

Add a new user manager role.
This role and the existing janitor role are given access to user management end points.

APS-1027 Implement user manager role for user management.

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt

Make test class name Pascal case (is not instantiated).

CAS-365 Make class name Pascal case.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt

"Person transferred to another prison" added under "Referral Withdrawn".

CAS2-509 - Add new sub status under "Referral Withdrawn".

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt

CAS-365 - remove cast as text - required for Spring boot upgrade work.

CAS-365 - remove cast as text - required for Spring boot upgrade work.

---

build.gradle.kts

Introduce a function to reduce duplication of Open API Task Config

APS-1087 - Simplify Open API Task Config in Gradle

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/TimeZoneConfig.kt

This is useful when testing/verifying timezone behaviour

Log timezone on startup

---

src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

In this PR I propose an interface between the UI and API for searching for and booking CAS1 spaces.
The UI will post a set of `Cas1SpaceSearchParameters` to an CAS1 api endpoint at:
`/cas1/spaces/search`
The `Cas1SpaceSearchParameters` have this shape:
```json
{
"startDate": "2024-07-17",
"durationInDays": 84,
"targetPostcodeDistrict": "SE5",
"requirements": {
"apType": "normal",
"needCharacteristics": [
"single",
"enSuite",
"wheelchair"
],
"riskCharacteristics": [
"atRiskOfExploitation",
"arson"
],
"gender": "male"
}
}
```
where `needCharacteristics` is a list which may include the enum values:
```
- single
- enSuite
- wheelchair
- limitedMobility
- catered
```
and `riskCharacteristics` is a list which can include the values:
```
- atRiskOfExploitation
- arson
- posesSexualRiskToAdults
- …
```

APS-1068: Proposed OpenAPI spec for "find and book CAS1 space"

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt

This [PR CAS-451](https://dsdmoj.atlassian.net/browse/CAS-451) is for testing the increase the number of CRNs passed to approved premises and delius endpoint to 500 when calling `/probation-cases/summaries` and add a log for the CRNs list for each call

Increase the crn number when calling approved premises and delius endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt

This [PR CAS-451](https://dsdmoj.atlassian.net/browse/CAS-451) is add log for each call to Approved Premises Delius Api

Log information for calls to Approved Premises Delius Api for CAS3 booking report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt

This [PR CAS-451](https://dsdmoj.atlassian.net/browse/CAS-451) is to fix an issue in logs and add more logs for generating CAS3 booking report

Change call to get person info async and add logs for generating CAS3 booking report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ExceptionHandling.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/ServiceUnavailableProblem.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/SentryService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ExceptionHandlingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/MutableClockConfiguration.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/mocks/NoOpSentryService.kt

I tested this locally by configuring spring as follows:
```
datasource:
hikari:
maximum-pool-size: 1
connection-timeout: 3000
```
I then put a long Thread.sleep in a service function after db access had been bade and made a request from two different browsers. In the second browser I saw a 503 returned because a connection couldn't be retrieved.

APS-1120 - Return a 503 error on db connection issues/timeouts

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt

This [PR CAS-544](https://dsdmoj.atlassian.net/browse/CAS-544) is to improve the performance of bedspace search which include:
- Make the Booking entity dependencies lazy load
- Improve the query to search closest booking more efficient execution time 
This PR was tested with upgrade spring boot 3 branch to make sure that the changes are compatible

CAS-544 Refactor bedspace search to improve performance

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt

Add logs to CAS3 booking report to follow the execution of the report

CAS-451 Add logs to CAS3 booking report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt

This [PR CAS-451](https://dsdmoj.atlassian.net/browse/CAS-451) is to remove comments from CAS3 booking report generation process

CAS-451 Remove comments from CAS3 booking report generation process

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt

SQL changes to Placement request endpoint dashboard
Change join order of some tables and use EXISTS instead of COUNT(x) > 0

Rework placement request dashboard query for performance enhancements

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
src/main/resources/db/migration/all/20240828163944__update_cas1_space_booking.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/AssertJExtensions.kt

This commit makes various changes to the Cas1 Space Booking Data model in preparation for providing API endpoints to list bookings, retrieve a booking and mark a booking as arrived

APS-1212 - Update Cas1 Space Booking Data Model

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/DomainEventServiceTest.kt

Refactored the properties to its own config class to make testing easier
Refactore unit tests so we only use 1 service, and change the mockk response when we want a differerent answer, rather than having 2 mockk services.

refactor cas3 domain event service

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/PaginationUtils.kt

This makes PageCriteria to Pageable slightly more readable at the call site.
THis PR also deprecates getPageable in favour of getPageableOrAllPages

Replace getPageable with extension functions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt

This PR implements CAS1 Get Space Booking and makes some tweaks to the API definition to add some additional fields required by the UI (e.g. application id, assessment id).

APS-1222 - Implement get space booking api

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CAS1SubjectAccessRequestRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CAS2SubjectAccessRequestRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CAS3SubjectAccessRequestRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/SubjectAccessRequestRepositoryBase.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/subjectaccessrequests/SubjectAccessRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
src/main/resources/db/migration/all/2024091112120000__remove_records_with_incorrect_formatting.sql
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS1SubjectAccessRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS2SubjectAccessRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS3SubjectAccessRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt

includes:
- Fixing of null date requests
- Updating endpoint authorization
- use Map interface to expose as entries which serialises correctly to JSON  on endpoint

CAS-342 Subject Access Request - Local Testing Fixes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cache/preemptive/InmateDetailsCacheRefreshWorker.kt

To work around an issue where cache refresh logs were not appearing in app insights, all logs were output at an ERROR level (which did appear in app insights).
As part of the spring boot 3 upgrade there is no longer a specific slf4j appender for app insights, and as such, this should no longer be an issue.
This commit removes such ‘conspicuous’ logs and instead logs them at info level

CAS-593 - Remove ‘conspicuous’ logging

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/LostBedsTest.kt

> See [APS-801 on the Approved Premises Jira board](https://dsdmoj.atlassian.net/browse/APS-801).
This PR removes the CAS1-specific logic from the lost beds endpoints found in the shared `PremisesController` and introduces an error response to alert CAS1 API consumers to the new endpoint.
This PR is the second of a two-stage process to implement APS-801, as removing the CAS1-specific logic from the existing endpoints requires the frontend to make the switch in all environments first. The first PR (#1909) should be merged into `main` before this one.

[APS-801] Remove CAS1-specific logic from shared 'lost beds' endpoints

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/ReportsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt

https://dsdmoj.atlassian.net/browse/CAS-633
Upgrading this kotlinx-dataframe dependency resolves the commons-compress vulnerability issue associated with commons-compress when the gradle OWASP job is run.
Upgrading the version alone results in a vulnerability being raised with swagger-parser-safe-url-resolver-2.1.20.jar so this transitive dependency which is a referenced library in dataframe-openapi also needs to be excluded.

CAS-633 Upgrade dataframe library to 0.13.1

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReferenceDataController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1CruManagementAreaTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt

Merge after https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/2300

APS-1315 - Return CRU management area in Application API

---

src/main/resources/application-local.yml

This logs the request URL and method for local deploys to help debug issues

Log upstream request for local deploys

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt

Added new keyWorkerStaffCode filter option to the API
Employed the additional filter in the Entity's  SQL

APS-1367: Modify Space Booking Search to support filtering on key worker.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

Ref: https://dsdmoj.atlassian.net/browse/APS-1399
Make isWomensApplication required.

APS-1399 Make isWomensApplication required.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

Reverts ministryofjustice/hmpps-approved-premises-api#2364

Revert "APS-1399 Make isWomensApplication required."

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3FutureBookingsReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/FutureBookingsReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/TransitionalAccommodationReferralReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/FutureBookingsReportDataAndPersonInfo.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/FutureBookingsReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/FutureBookingsReportProperties.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/util/ReportingUtils.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ReportServiceTest.kt

This [PR CAS-643](https://dsdmoj.atlassian.net/browse/CAS-643) is to add future booking report to CAS3

CAS-643 Add future bookings report for CAS3

---

.circleci/config.yml

Related to https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/815

Update cas2 e2e artifacts locations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/FutureBookingsReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/FutureBookingsReportRow.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt

Change generated stream to be excel

CAS-643 Future bookings report CAS3

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3FutureBookingsReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/FutureBookingsReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/FutureBookingsReportRow.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt

This [PR CAS-643](https://dsdmoj.atlassian.net/browse/CAS-643) is to add start booking date to the report and remove active bookings

CAS-643 Add start booking date to the report and remove active bookings

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt

Added apCode to the response so the UI has all of the summary information it needs.

APS-1418: Update Cas1 Premises Summary endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3FutureBookingsReportRepository.kt

Change the future bookings report to populate the referral pdu instead of pdu premises

CAS-643 Change the future bookings report to populate the referral pdu

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/BedSearchController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt

Remove PDU property from bedsearch Api endpoint as it was replaced with PDU list

CAS-617 Remove PDU property from bedsearch Api endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/FutureBookingsCsvReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/FutureBookingsReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/util/CsvObjectListConsumer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt

This [PR CAS-643](https://dsdmoj.atlassian.net/browse/CAS-643) is to generate the future bookings report in Csv format

CAS-643 Generate CAS3 future report in Csv format

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3BookingGapReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/properties/BookingGapReportProperties.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ReportService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt

This [PR CAS-1193](https://dsdmoj.atlassian.net/browse/CAS-1193) is to generate booking GAP report

CAS-1193 Generate booking GAP report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/resources/db/migration/all/20241101141457__add_non_arrival_columns_to_cas1_space_booking.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt

Migration script to add the fields to the table.
Added the same fields to the entity.

APS-1471: Add non arrival information to Cas1SpaceBooking

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/resources/db/migration/all/20241101094511__add_space_booking_migration_column.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenABooking.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApplication.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApprovedPremises.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/Cas1SpaceBookingTestRepository.kt

This seed job doesn’t currently support adhoc bookings as that requires a change to the space booking model. This will follow in a subsequent commit/ticket.

APS-1447 - Add seed job to migrate bookings to space bookings

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1AutoScript.kt

This test user is used to test report and user management functionality. This commit ensure they only have the required roles to do this.

Give AP_USER_TEST_2 specific roles in dev

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1PlanSpacePlanningDryRunSeedJob.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

The seed job will invoke the planner for the given premise(s) and date range. The planner itself will log the plan at debug level

APS-1454 - Add seed job to invoke CAS1 space planner

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

Removed legacy non-arrival API
Has been replaced by CAS1 specific non-arrival api
Removed : 
- API definition
- Controller implementation
- Function in service 
- Unit Tests
- Integration tests

APS-1508: Removed legacy non-arrival code

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanRenderer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/planning/SpacePlannerTest.kt

* List unplanned days when attempting planning
* Log execution time for seed jobs

APS-1453 - Improve planning output

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt

Updated the timeline entry for Space Booking withdrawn events to provide information about the booking.

APS-1401 : Updated timeline entry for Space Booking withdrawn events

---

src/main/resources/db/migration/all/20241111145956__change_cas3_wheelchair_accessible_scope.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt

This [PR CAS-1203](https://dsdmoj.atlassian.net/browse/CAS-1203) is to change wheelchair accessible scope to be room level instead of premises and room

CAS-1203 Change wheelchair accessible scope for CAS3

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BedSearchService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/CharacteristicService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequirementsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
src/main/resources/db/migration/all/20241113144957__add_populate_property_name_for_cas3_premises_rooms_characteristics.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BedSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/planning/SpacePlannerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BedSearchServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt

This [PR CAS-1211](https://dsdmoj.atlassian.net/browse/CAS-1211) to add property name to temporary accommodation premises and rooms Characteristics

CAS-1211 Add Property Name to CAS3 Premises and Rooms Characteristics

---

build.gradle.kts

This is an unused test dependency

Remove Byte Buddy

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt

This is required to retrieve information when withdrawing a space booking

APS-1607 - Add endpoint to get a space booking without premise id

---

src/main/resources/db/migration/all/20241122134748__add_index_to_space_booking_placement_request_id.sql

Added Index `cas1_space_bookings_placement_request_id_idx` to `Cas1_Space_Bookings` on `placement_request_id`

APS-1593: Add index to Space Bookings for Placement Request Id

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

This commit removes some logic that relates to a booking cancellation reason that was deactivated in 08/2023 (see ca0e4c5a).
The logic leads to new placement request being created when a booking is cancelled with the reason ‘Booking successfully appealed’. Given that that current logic will return any placement request with a cancelled booking as ‘unmatched’ (regardless of the reason), this logic is redundant and would result in multiple placement requests for a given Booking.

APS-1301 - Remove unused CAS1 appeal logic

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt

Change Space Booking find by Premises and PlacementRequest to find by PlacementRequest only.
Cater for the possibility of multiple bookings satisfying search criteria rather than single record.

APS-1568: Change Space Booking find by Premises ad PlacementRequest

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementMatchingOutcomesReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementMatchingOutcomesV2ReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

This report is not currently in use and will be superseded by the space bookings placement report

APS-1711 - Deprecate Placement Matching Outcome Reports

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UpdateApplicationLicenceExpiryDateJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
src/main/resources/db/migration/all/20241202091859__add_license_expiry_date_to_approved_premises_applications.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1UpdateApplicationLicenceExpiryDateJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1616](url)
Added new column for license expiry date and created a migration job to update them in other environments.

Added licence expiry date to approved premises applications

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1438](url)

Removed genderForAp from ApprovedPremisesApplication.

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationReportsTest.kt

An earlier version of application reports included booking information. This is no longer the case so any logic creating bookings to test the application report can be removed.
This is in preperation for removing the CAS1 adhoc booking functionality, which was used by this test.

Simplify Application Reports Test

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonalTimelineTest.kt

Timeline events based on lao permissions - [https://dsdmoj.atlassian.net/browse/APS-1671](url)

Updated code to return timeline events based on lao permission.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingDomainEventServiceTest.kt

This is now in `Cas1BookingDomainEventService` with improved test coverage.
This is in preparation for recording changes to CAS1 space bookings
I've tested this locally for regular and offline applications and booking changed domain events are still generated without issue

Move CAS1 BookingChanged Domain Event Creation into `Cas1BookingDomainEventService`

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1616](url)

Added missing licence expiry date to api model.

---

build.gradle.kts
script/run_seed_from_excel_job
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/SeedFromExcelController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/RoomEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/ApprovedPremisesRoomsSeedFromXLSXJob.kt
src/main/resources/static/_shared.yml
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedFromXLSXApprovedPremisesRoomsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedScaffoldingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedTestBase.kt

We want the ability to be able to update approved premises room characteristic data from an Excel spreadsheet.  This commit adds the functionality to run seed jobs from xlsx files and populated rooms, beds and characteristics.

APS-1536 Add new seed from Excel job.

---

Dockerfile

Copy `run_seed_job_from_excel` script to `/app` and make executable.

APS-1536 copy run_seed_job_from_excel script to /app.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1SpaceSearchRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
src/main/resources/application-local.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt

Before this PR suitability search only returned a premise if 1 and only 1 room has a required characteristic

APS-1743 - Space search only returned a premise if it has 1 and only 1 room with the required characteristic

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/planning/SpacePlanningService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremiseCapacitySummaryTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Cas1PremiseOverbookingCalculator.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/planning/SpacePlanningServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesOverbookingRangeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremiseCapacitySummaryTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1672](url)
Due to the nature of the complex data setup needed for IT, the logic is mostly covered using unit tests. Working on the data set up needed.

Implemented premises overbooking summary range.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ReferralRejectionReasonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/Cas3ReferralRejectionSeedJob.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas3/Cas3ReferralRejectionSeedJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas3/Cas3ReferralRejectionSeedJobTest.kt

This [PR CAS-1261](https://dsdmoj.atlassian.net/browse/CAS-1261) is to create a seed job for CAS3 referral rejection

Create a seed job for CAS3 referral rejection

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/Cas3ReferralRejectionSeedJob.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas3/Cas3ReferralRejectionSeedJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas3/Cas3ReferralRejectionSeedJobTest.kt

This [PR CAS-1261](https://dsdmoj.atlassian.net/browse/CAS-1261) is to add system notes to rejection referral seed job

CAS-1261 Add system notes to rejection referral seed job

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt

Validates presence of date and time 
Validates that the date and time must be in the past.

APS-1706: Add validation to ensure arrivals can only be in the past

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CAS1SubjectAccessRequestRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/SubjectAccessRequestRepositoryBase.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/subjectaccessrequests/SubjectAccessRequestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/CAS1SubjectAccessRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/SubjectAccessRequestServiceTestBase.kt

Added functionality to include SpaceBookings in response to Subject Access Request API
Modified query for obtaining information for offlineApplications to include SpaceBookings

APS-1759: Add SpaceBooking information to Subject Access Request API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

This PR CAS-1325 is to update the Create Arrival validation message in BookingService when the booking premises is Temporary accommodation

CAS-1325 Update the Create Arrival validation message in BookingService for CAS3

---

src/main/resources/db/migration/all/20250107135009__add_prefix_cas3_to_lost_beds_tables_and_rename_them_to_void_bedspaces.sql

This PR CAS-1343 is to delete CAS1 lost beds from lost_beds and lost_bed_cancellations tables

CAS-1343 Delete CAS1 lost beds from lost_beds and lost_bed_cancellations tables

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/OfflineApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1BackfillOfflineApplicationName.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/MigrationJobService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1BackfillOfflineApplicationNameTest.kt

Ref: https://dsdmoj.atlassian.net/browse/APS-1719

Add migration job to backfill offline_applications.name.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/DomainEventUrlConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/DomainEventService.kt
src/main/resources/static/cas3-domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/repository/DomainEventTestRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ApplicationServiceTest.kt

This [PR CAS-1234](https://dsdmoj.atlassian.net/browse/CAS-1243) is to create CAS3 domain event for deleting draft referral

CAS-1234 Create CAS3 domain event for deleting draft referral

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementRequestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PlacementRequestServiceTest.kt

Removing deprecate code and using CasResult

Placement Request Tidy Up

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingCas1DomainEventServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1776](url)

APS-1776. Changed the booking changed domain event to incorporate space booking changes.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

This PR CAS-1238 is to prevent edit cas3 draft application if its deleted

CAS-1238 To prevent edit cas3 draft application if its deleted

---

src/main/resources/db/migration/all/20250116120157__update_non_arrival_reasons.sql

Active reasons after changes
```
Failed to arrive as planned
Arrested / In custody / Recalled (correct reason code to follow in subsequent commit)
Parole release not granted
Admitted to hospital (correct reason code to follow in subsequent commit)
Other - provide reasons
```

APS-1756 - Update CAS1 Non Arrival Reasons

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/AssessmentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/AssessmentTest.kt

This [PR CAS-1303](https://dsdmoj.atlassian.net/browse/CAS-1303) is to remove ReferralHistoryNotes from Cas3 assessment Api response

CAS-1303 Remove ReferralHistoryNotes from CAS3 assessment Api response

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingChangedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1731](url)

APS-1731 Updated booking changed description to include previous arrival and departure dates.

---

src/main/resources/db/migration/all/20250117123346__update_cas1_move_on_and_departure_reasons.sql

Some delius codes are currently unknown, so have been temporarily set to TBD. These will updated in a subsequent commit
Updated reasons on UI

APS-1756 Update CAS1 MoveOn, Departure & NonArrival Reasons

---

src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt

Update the Cas1SpaceCharacteristic API type to ensure it contains all enabled types

APS-1785 Ensure Cas1SpaceCharacteristic has all types

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt

When running seed jobs processing large CSVs there is no default progress reporting in the logs, making it hard to determine if the seed job is still running, and how far through processing it is. This commit adds a log line every 10,000 rows to help track progress.

Add seed job progress logs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/resources/static/domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingChangedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingCas1DomainEventServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1800](url)

APS-1800 Updated amend booking to change room characteristics.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1TimelineService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementDomainEventService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

This is in preparation for changes to the timeline response

Move common logic into CAS1TimelineService

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt

Tidy up guided by intellij inspections

CAS1 code tidy up

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PeopleController.kt
src/main/resources/static/api.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTimelineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PersonalTimelineTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1857](url)

APS-1857, Moved applications and people timeline end points to cas1 specific.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt

Before this commit we limited the number of threads available to the seed job dispatcher. Whilst this did limit how much we hit the database, it didn’t limit the number of co-routines that could be created and `enqueued` ready for processing.
When an import job was ran in pre-production with a large CSV file, a co-routine for each row was being created far quicker than they were being processed, leading to most of the CSV file being loaded into memory, leading to an out of memory exception.
This commit changes how we limit concurrency, using a sempahore to limit the number of co-routines being created at any one time, instead of limiting the number of threads available to the dispatcher. This limits how much of the CSV is prematurely loaded into memory.

Fix concurrent seed job processing memory issue

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/CasResult.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/EntityUtils.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt

This PR limits update, reject and accept actions on CAS1 assessments to the user currently allocated to that assessment

APS-1088 limit assessment modification

---

src/main/resources/db/migration/all/20250120104206__.sql

*Merge blocked until comms sent*
List after changes:
* AP Closure / Operational Reduction in Capacity (Non-FM)
* Staff shortage / Illness (Non-FM)
* Double room with single occupancy – risk (Non-FM)
* Double room with single occupancy – other (Non-FM)
* Incident not requiring FM repair
* Damage by resident requiring FM Repair
* Flood / Fire requiring FM repair
* Other unplanned FM works required
* Planned FM works required
* Planned Refurbishment (FM)

Update CAS1 Out of Service Bed Reasons

---

.circleci/config.yml

Reverted all the changes I did earlier today using `git revert f2eb0e84a c9030253e f8750f144 8580837cd 75cc0c938` 
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/2896
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/2895
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/2893

Revert all cas 3 config changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/TaskServiceTest.kt

* Move a tasks function from users service to tasks service
* Tidy up tasks integration tests
* Add a note on the TaskWrapper model around issue caused by extending user

APS-1863 Tidy up Tasks Logic

---

src/main/resources/db/migration/all/20250203164712__add_index_to_cas1_out_of_service_bed.sql

https://dsdmoj.atlassian.net/browse/APS-1880

Added index to cas1 out of service bed cancellations and revisions.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestBookingSummaryTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestBookingSummaryTransformerTest.kt

To support this we’ve had to move the Cas1SpaceCharacteristics type back into _shared.yml. In time we’ll move placement request code into a /cas1 endpoint

APS-1783 - Add criteria to placement request booking summary

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationAutomaticEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationV2ReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1RequestForPlacementReportRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationV2ReportTest.kt

This PR improves the formatting of various CAS reports
It does not functionally change the reports

Cas1 Report Tidy Up

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1UsersController.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1UsersTest.kt

https://dsdmoj.atlassian.net/browse/APS-1715

Refactor the getUser method to fallback to searching for the user in the system if not found in Delius

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestBookingSummaryTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OutOfServiceBedSummaryTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt

* return bookings at the same premise in arrival date order, ascending
* return characteristics for the booking

APS 1910 - Get space booking improvements

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt

https://dsdmoj.atlassian.net/browse/APS-1794

APS-1794 Added space booking count.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingDaySummaryService.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingDaySummaryServiceTest.kt

https://dsdmoj.atlassian.net/browse/APS-1887

APS-1887 Added exclude space booking id for day summary.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1ArsonSuitableToArsonOffencesJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1IsArsonSuitableBackfillJob.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1ArsonSuitableToArsonOffencesJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1IsArsonSuitableBackfillJobTest.kt

See https://dsdmoj.atlassian.net/browse/APS-1876 for the context

APS-1903 Add job to backfill arson suitable

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/domainevent/HmppsDomainEvent.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/model/domainevent/HmppsDomainEventTest.kt

This is the model of the messages that come from the domain event queue that the backend will subscribe to

CAS 1434 added HmppsDomainEvent with unit tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/resources/db/migration/all/20250210091646__add-new-reporting-columns.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesAssessmentEntityFactory.kt

PR No-1 for [https://dsdmoj.atlassian.net/browse/APS-1885](url)

APS-1885 Added new columns to ApprovedPremisesAssessmentEntity.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1934](url)

APS-1934 Update space booking bug fix.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/PrisonerSearchClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/client/restclient/RestClientConfig.kt
src/main/resources/application.yml

using the detail url in prisoner-offender-search.prisoner.updated we can get back the prisonId which is the prisonCode we will use in the prisoner locations table

CAS 1434 added prisoner search client

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1TimelineService.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTimelineTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1857](url)

APS-1857 Refactor space booking timeline to cas1.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/RequestResponseLoggingFilter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceSearchService.kt
src/main/resources/db/migration/all/20250211111817__add_index_on_space_booking_criteria.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceSearchServiceTest.kt

* Log response times locally to aid performance investigations
* Add missing index on foreign key
* Fix a bug that blocked the API starting locally if lots of applications existed in the database

APS-1934 Miscellaneous Optimisations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2PrisonerLocationEntity.kt
src/main/resources/db/migration/all/20250211104706__create_cas_2_prisoner_locations_table.sql

where the location of each prisoner is stored and their POM (staffId) as they are transferred between prisons

CAS 1434 added prisoner location table

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/JsonSchemaService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

* Simplify CAS1 premise existence check
* Lazy load schema version relatonships

APS-1943 CAS1 API Optimisations

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3FutureBookingTransformer.kt
src/main/resources/static/cas3-api.yml
src/main/resources/static/cas3-schemas.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/BookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3FutureBookingTransformerTest.kt

This [PR CAS-1442](https://dsdmoj.atlassian.net/browse/CAS-1442) is to add new CAS3 api endpoint to get future bookings for a premises

CAS-1442 Cas3 api endpoint to return current/future bookings for a premises

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UpdateAssessmentReportPropertiesJob.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1UpdateAssessmentReportPropertiesJobTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1942](url)

APS-1885 Update approved premises  assessment job.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingDaySummaryService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenABed.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingDaySummaryServiceTest.kt

Update the CAS1 Day Summary to exclude bookings departing today, and bookings with non arrival recorded

CAS1 Premises Day Summary Fixes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1ApplicationV2ReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1ReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1RequestForPlacementReportTest.kt

This PR adds two new reports that are variations of the existing applications and request for placement reports with additional PII fields.
This PR also adds a new role that is required to access these reports

Add Restricted CAS1 Reports that include PII

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PeopleController.kt

https://dsdmoj.atlassian.net/browse/APS-1914

APS-1914 Restrict cas1 personal timeline.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt

Changes to seed job:
* set arrival-date to day at random - between today and 7 days in the past
* set departure-date to day at random - between today and 3 months in the future

Changes to the space-booking seed job

---

script/run_seed_from_excel_directory_job
script/run_seed_from_excel_job
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/OAuth2ResourceServerSecurityConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/SeedFromExcelController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedXlsxService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedRoomsFromSiteSurveyXlsxJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyBedFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyDataFrame.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyPremiseFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyUtils.kt
src/main/resources/static/_shared.yml
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1PremisesFromSiteSurveyXlsxTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1RoomsFromSiteSurveyXlsxTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedXlsxScaffoldingTest.kt

This has been added to support bulk loading site surveys in local development to verify they're loadable. There's no reason this can't be used when applying site surveys in other environments

APS-1995 - Add method to seed XLSX from a directory

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementMatchingOutcomesV2ReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt

This PR also fixes the integration tests for the report, as we had previously incorrectly removed most of the report assertions for the report

APS-1999 Add placement matching outcomes v2 report with PII

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1971](url)

APS-1971 Send email notification for amended bookings.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/LocalAuthorityAreaEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedPremisesFromCsvJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedPremisesFromSiteSurveyXlsxJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyDataFrame.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SiteSurveyPremiseFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/TemporaryAccommodationPremisesSeedJob.kt

* Use case-insensitive Local Authority names
* Make 'Are there any additional restrictions' question optional
* Add local authority mappings

APS-1995 - Site survey import fixes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt

This PR adds the following fields to PlacementRequestDetail:
* spaceBookings
* legacyBooking

APS-1936 - Add Cas1SpaceBookingSummary to PlacementRequestDetail

---

.circleci/config.yml

see https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/pull/1231

Update cas3 e2e tests config

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingEmailService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingEmailServiceTest.kt

https://dsdmoj.atlassian.net/browse/APS-1993

APS-1993 Notify case manager when creating a booking

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementMatchingOutcomesV2ReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SimpleApiClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

This PR adds additional columns to the placement matching outcomes v2 report, and optimises the existing SQL

APS-2009 - Placement matching outcomes v2 report enhancements

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UpdateAssessmentReportPropertiesJob.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1UpdateAssessmentReportPropertiesJobTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1965](url)

APS-1965 Handle empty string when update assessments.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/ApplicationStateTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt

The existing `requirements` field has been deprecated

Add `Cas1NewSpaceBooking.characteristics`

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceSearchController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceSearchResultsTransformer.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceSearchResultsTransformerTest.kt

The UI team have confirmed that these are not being used

Remove unused fields in space search API

---

src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

Add special premise characteristics to API
This enables searching on premises, and creating bookings with the following characteristics:
* isSpecialistPremisesElliotHouse
* isSpecialistPremisesStJosephs

APS-2037 Support searching on mhap premises

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DocumentsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DocumentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt

This sevice has been created to help reduce the size of scope of the `OffenderService`

Create a DocumentService

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2v2/Cas2v2PeopleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OASysService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt

This sevice has been created to help reduce the size of scope of the `OffenderService`

Create an OASysService

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3VoidBedspaceEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/BookingTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/PremisesServiceTest.kt

This endpoint is no longer used being used by any CAS in prod
Endpoint usage this month:

Remove unused premises/{id}/summary endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementReportTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2010](url)

APS-2010 Added placement reports

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementReportRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementReportTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2039](url)

APS-2039: Split Report Date and Time Fields

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3BedspaceSearchController.kt
src/main/resources/static/cas3-api.yml
src/main/resources/static/cas3-schemas.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

This PR is to rename TemporaryAccommodationBedSearchParameters to Cas3BedspaceSearchParameters for CAS3 bedspace seach Api endpoint

CAS-1481 Rename Bedspace Search Parameters fro CAS3 Api endpoint

---

src/main/resources/db/migration/all/20250305164205__update_arson_offences_to_room_characteristic.sql

Update the scope to be `room` for consistency with the `isArsonDesignated` and `isArsonSuitable` characteristics

Update `arsonOffences` characteristic scope

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt

CAS1_ASSESS_PLACEMENT_REQUEST has been removed as it’s not required

Assessment Permission Tidy Up

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3PremisesSummaryTransformer.kt
src/main/resources/static/cas3-api.yml
src/main/resources/static/cas3-schemas.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PremisesSummaryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3PremisesSummaryTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/RandomData.kt

This [PR CAS-1385](https://dsdmoj.atlassian.net/browse/CAS-1385) is to add filter to CAS3 premises list to be filtered by postcode and address

CAS-1385 Add filters to CAS3 premises list to be filtered by postcode and address

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt

This [PR CAS-1385](https://dsdmoj.atlassian.net/browse/CAS-1385) is to fix an issue with get CAS3 premises query which is returning duplicated premises in pdus

CAS-1385 Fix issue return duplicated premises for pdus

---

helm_deploy/values-preprod.yaml

this will ensure messages go to #cas-events

APS-1824 - Update generic prometheus severity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3DepartureTransformer.kt
src/main/resources/static/cas3-api.yml
src/main/resources/static/cas3-schemas.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt

This [PR CAS-564](https://dsdmoj.atlassian.net/browse/CAS-564) is to create CAS3 booking departure api endpoint

CAS-564 Create CAS3 booking departure api endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1RemapBedCodesSeedService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1RemapBedCodesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenABed.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/SeedTestBase.kt

We have a requirement to update several beds codes in CAS1. This commit adds a seed job to facilitate that

APS-2097 - Seed Job to update Bed Codes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedRoomsFromSiteSurveyXlsxJob.kt

Log changes to make room updates standout from rooms with no changes

CAS1 Room Seeding Log Changes

---

.circleci/config.yml

* build step no longer cloning CAS3 UI feature branch (now cloning main branch)

Fix cas3_e2e_playwright_tests CI job

---

Dockerfile
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1SeedPremisesFromSiteSurveyXlsxJob.kt

Some minor fixes to premise seeding:
* Copy seed from excel dir script into docker build
* Include 'full address' in diff report
* Add a mapping for Newcastle Authority Area

Update Premises from Site Survey Fixes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1UpdateApprovedPremisesApplicationWithOffenderJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OffenderService.kt
src/main/resources/db/migration/all/20250313143707__add_unique_constraint_to_cas1_offender_crn.sql
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1UpdateApprovedPremisesApplicationWithOffenderJobTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2021](url)

APS-2021: Applications offender backfill.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/datasource/OffenderDetailsDataSource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas3/Cas3UpdateApplicationOffenderNameJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PersonRisksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/httpmocks/APDeliusContext.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas3/Cas3UpdateApplicationOffenderNameJobTest.kt

See individual commit comments for explanations of changes

Remove use of deprecated offender function

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Cas1UserRoleJsonFileGenerator.kt
src/main/resources/static/codegen/built-cas1-roles.json

[https://dsdmoj.atlassian.net/browse/APS-2107](url)
[built-cas1-roles.json](https://github.com/user-attachments/files/19311452/built-cas1-roles.json)

APS-2107: cas1 user role json.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas1-roles.json
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml

Ref: https://dsdmoj.atlassian.net/browse/APS-1916
Add `cas1_appeal_create` permission
Add `cas1_planned_transfer_create` permission
Add `change_request_dev` user role with above permissions

APS-1916 Add temporary change request role and permission.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt

PR NO 1 for - [https://dsdmoj.atlassian.net/browse/APS-2091](url)

APS-2091: Task expected arrival date.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/TaskEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/TaskService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementApplication.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnAssessment.kt

[https://dsdmoj.atlassian.net/browse/APS-2091 ](url)

APS-2091: Sort by arrival date

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/DomainEventUrlConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2v2/Cas2v2SubmittedApplicationReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas2v2/Cas2v2StartupScript.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2StatusUpdateService.kt
src/main/resources/application-local.yml
src/main/resources/application.yml
src/main/resources/db/seed/local+dev+test/cas2v2_application_data/document_A1234AX.json
src/main/resources/static/cas2-domain-events-api.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2ReportsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2StatusUpdateTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2SubmissionTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2v2/Cas2v2ApplicationServiceTest.kt

feat: adds a CAS2v2 domain event type

CBA-400-add-event-type-for-cas-2-v-2-applications-submitted

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3BookingGapReportRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3ReportsTest.kt

This [PR CAS-1500](https://dsdmoj.atlassian.net/browse/CAS-1500) is to fix some issues in the CAS3 bookings gap report which include:
- Fix the gap calculation in the report
- Include void in the gap calculation
- Include bedspaces that don't have booking during the report period

CAS-1500 Fix the gap calculation in the CAS3 bookings gap report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ChangeRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/main/resources/db/migration/all/20250312135921__rename_cas1_change_requests_decision_made_by_user_id.sql
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1ChangeRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1NewChangeRequestFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt

Ref: https://dsdmoj.atlassian.net/browse/APS-1916

APS-1916 Add change-request POST logic

---

src/main/resources/db/migration/all/20250324124006__split_staffordshire_and_stoke_pdu.sql

This [PR CAS-1524](https://dsdmoj.atlassian.net/browse/CAS-1524) is to split Staffordshire and Stoke pdu

CAS1524 Split Staffordshire and Stoke pdu

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3TimelineController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/DomainEventsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/domainevents/DomainEventDescriber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1DomainEventDescriber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3DomainEventBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ApplicationTimelineTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTimelineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ExpiredApplicationsScheduledJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTimelineTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/domainevents/DomainEventDescriberTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1DomainEventDescriberTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3AssessmentServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3DomainEventBuilderTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3DomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ApplicationTimelineTransformerTest.kt

* Improve readability in`DomainEventDescriber`
* Prefix CAS1 and CAS3 Services with CAS value and move into relevant packages

APS-2154 CAS1 Domain Event Improvements

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ChangeRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestRejectionReasonEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas1-roles.json
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1ChangeRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1ChangeRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-1907](url)

APS-1907: Reject change request.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ApplicationV2ReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementMatchingOutcomesV2ReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1ApplicationV2ReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2153](url)

APS:2153: Added user actual name.

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

Fix for a failing unit test in  the main branch.

Unit test fix.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1AssessmentsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/AssessmentClarificationNoteTransformer.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/AssessmentClarificationNoteTransformerTest.kt

End-points covered in this PR.
1. `POST -/cas1/assessments/{assessmentId}/notes`
2. `PUT - /cas1/assessments/{assessmentId}/notes`

Add cas1 assessment note

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2/UnsubmittedApplicationsReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2v2/ApplicationStatusUpdatesReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2v2/SubmittedApplicationReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2v2/UnsubmittedApplicationsReportRow.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2ReportsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2ReportsTest.kt

https://dsdmoj.atlassian.net/browse/CBA-456

moved the columns in cas2v2 reports

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/StatusUpdateServiceTest.kt

https://dsdmoj.atlassian.net/browse/CBA-469
Text changed as defined in JIRA ticket. Amended relevant unit test.

changed the text to suit the JIRA ticket CBA-469 and update unit test

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/reference/Cas2ApplicationStatusSeeding.kt

https://dsdmoj.atlassian.net/browse/CBA-469 misses one text change last time

text now reads The referrer withdrew the application.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1AssessmentsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt

End points covered in this PR
1. `POST /cas1/assessments/{assessmentId}/acceptance`
2. `POST /cas1/assessments/{assessmentId}/rejection`

Add cas1 accept/reject assessment

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2ApplicationService.kt

https://dsdmoj.atlassian.net/browse/CBA-542

removed check for noms number in Cas2v2ApplicationService

---

src/main/resources/static/cas2v2-schemas.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml

https://dsdmoj.atlassian.net/browse/CBA-546
Due to earlier changes we need the value of nomsNumber to be nullable.

made nomsNumber not required in models from yaml

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/cas2v2/SubmittedApplicationReportRow.kt

https://dsdmoj.atlassian.net/browse/CBA-547

In SubmittedApplicationReportRow made personNoms a nullable field

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2StatusUpdateService.kt

https://dsdmoj.atlassian.net/browse/CBA-550
Further to previous PR this sets the value in the Cas2v2StatusUpdateService.

setting the value in the service

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2v2/Cas2v2PeopleController.kt

https://dsdmoj.atlassian.net/browse/CBA-561

Added identifier to two not found problems in people search controller

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2035](url)

Emergency transfer space booking.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1RequestForPlacementReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PlacementApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1RequestForPlacementReportTest.kt

See https://dsdmoj.atlassian.net/browse/APS-2195

APS-2195 add request for placement last allocated to reports

---

src/main/resources/db/seed/local+dev+test/11__short_term_accommodation_create_omus.csv

already seeded this in prod and preprod

CAS-1587 added new omu email to table for dev seeding

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ChangeRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ChangeRequestTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas1-roles.json
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1ChangeRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1ChangeRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ChangeRequestTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2201](url)

Add get change request end-point

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1ChangeRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2059](url)

Add change request fields to summary

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/SeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/Cas3AssignApplicationToPduSeedJob.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/seed/cas3/Cas3AssignApplicationToPduSeedJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas3/Cas3AssignApplicationToPduSeedJobTest.kt

This [PR CAS-1533](https://dsdmoj.atlassian.net/browse/CAS-1533) to assign a assessment to a pdu. 
As the assessment pdu is linked to the pdu temporary accommodation application table this process will update the application with the new pdu

CAS-1533 Create a job to assign assessment to a pdu

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1ChangeRequestEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1CruManagementArea.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ChangeRequestTransformerTest.kt

This commit triggers all relevant emails for placement appeal creation, acceptance and rejection

Trigger emails for placement appeals

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationAssessed.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationExpired.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationSubmitted.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationWithdrawn.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/AssessmentAllocated.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/AssessmentAppealed.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingCancelled.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingChanged.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingKeyWorkerAssigned.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingMade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingNotMade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/Cas1DomainEventEnvelopeInterface.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/Cas1DomainEventPayload.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/EmergencyTransferCreated.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/FurtherInformationRequested.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/MatchRequestWithdrawn.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PersonArrived.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PersonDeparted.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PersonNotArrived.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PlacementAppealAccepted.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PlacementAppealCreated.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PlacementAppealRejected.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PlacementApplicationAllocated.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/PlacementApplicationWithdrawn.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/RequestForPlacementAssessed.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/RequestForPlacementCreated.kt

This will help with compile time checks in subsquent commits

Add marker interface for domain event payloads

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1ApplicationSeedService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BackfillActiveSpaceBookingsCreatedInDelius.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/Cas1SpaceBookingEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2131](url)

Add planned transfer approval

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1DomainEventsController.kt

Remove unneccessary layers of code as we no longer manage this via YML

Simplify CAS1 domain event controller

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2232](url)

Add auto resolve

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PersonTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ChangeRequestTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PersonTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2242](url)

Add change requests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
src/main/resources/static/api.yml
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt

Added below placement request endpoints
`
/cas1/placement-requests/{id}`
`/cas1/placement-requests/{id}/withdrawal`

Added placement requests endpoints

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ChangeRequestTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1SpaceBookingTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/Dates.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2243](url)

Add open change requests to api

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingActionsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ChangeRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingsActionsServiceTest.kt

The logic for these are current identical, this will diverge in subsequent commits/PRs

Add separate emergency & planned transfer actions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingActionsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingActionsServiceTest.kt

This commit updates the Space Booking Actions to only allow a change request of a given type to be created if there isn’t already an open change request of that type for the same placement

APS-2241 Don’t allow multiple change request same type

---

src/main/resources/db/migration/dev-truncate/R__0_truncate_cas2v2.sql

This matches the pattern already established for other CASs

Delete cas2v2 applications on deploy to dev

---

.dependencycheckignore
README.md
build.gradle.kts

As we’re now using github actions we can manage supressions via the github security functionality

Remove dependency check ignore file

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1ChangeRequestEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ChangeRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ChangeRequestTransformer.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ChangeRequestTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1SpaceBookingTransformerTest.kt

Also make expectedArrivalDate mandatory and remove lengthOfStay as it isn't required

Add `Cas1ChangeRequestSummary.placementRequestId`

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlacementChangeRequestCreatedTimelineFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/PlacementChangeRequestRejectedTimelineFactory.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PlacementChangeRequestCreatedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/PlacementChangeRequestRejectedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/PlacementChangeRequestCreatedTimelineFactoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/PlacementChangeRequestRejectedTimelineFactoryTest.kt

This is required to correctly render the timeline description

APS-2283 Add additional info to change request timeline entries

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PlacementReportRepository.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/DepartureReasonEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementReportTest.kt

If defined, show parent departure reason in the placement report

APS-2298 - Show parent departure reason in placement report

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas1SpaceBookingEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingCreateService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingUpdateService.kt
src/main/resources/db/migration/all/20250513104858__add_transferred_from_to_space_bookings.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenACas1SpaceBooking.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementEmailServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingActionsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingCreateServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2288](url)

Add transferred_from to space booking

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/config/NotifyConfig.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/EmailNotificationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2AssessmentNoteService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2EmailService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2StatusUpdateService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2ApplicationNoteService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2v2/Cas2v2StatusUpdateService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2/Cas2SubmissionTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas2v2/Cas2v2SubmissionTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/Cas2ApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/Cas2AssessmentNoteServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/Cas2EmailServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2/StatusUpdateServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas2v2/Cas2v2ApplicationServiceTest.kt

This is in preparation for some improvements related to logging emails

APS-2279 - Convert NotifyTemplates into an object

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingCancelled.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingChanged.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/BookingMade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingDomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingCreateService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingUpdateService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeOperations.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingCancelledTimelineFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingChangedTimelineFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/BookingMadeTimelineFactory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/domainevent/DomainEventUtils.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/springevent/BookingSpringEvents.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingCancelledFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingChangedFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/BookingMadeFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/events/EventTransferInfoFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingDomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingCreateServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeOperationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/BookingCancelledTimelineFactoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/BookingChangedTimelineFactoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/domainevents/BookingMadeTimelineFactoryTest.kt

Ensure relevant info is populated into the following domain events for emergency transfer, planned transfer and appeals:
* booking made (transferred to)
* booking changed (transferred from)
* booking cancelled (appeal change request id)
Example information captured for emergency transfer triggered from UI (we can't currently trigger appeal or planned transfer)
booking made domain event
```
"transferredFrom": {
"type": "EMERGENCY",
"booking": {
"id": "a5bc6a73-5817-4e12-8f97-b23b3290a643",
"premises": {
"id": "1dafc074-84e4-4c89-8eea-00c729f999d4",
"name": "SWSC Women Premise 1",
"apCode": "SWSCWOMEN1",
"legacyApCode": "Q049",
"localAuthorityAreaName": "Southampton"
},
"arrivalDate": "2024-12-12",
"departureDate": "2025-05-14"
},
"changeRequestId": null
},
```
booking made timeline payload …

APS-2267 - Populate Transfer Info in Domain Events & Timeline Payloads

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1ChangeRequestTransformer.kt
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ChangeRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1ChangeRequestTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2329](url)

Add request json

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/generator/DailyMetricsReportGenerator.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/reporting/model/DailyMetricReportRow.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/DailyMetricsReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/reporting/generator/DailyMetricsReportGeneratorTest.kt

This is just a refactor  of the exsiting IT assertions, which should work when we refactor the current report generation from Kotlin to use SQL.
[https://dsdmoj.atlassian.net/browse/APS-2304](url)

Refactor test

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/CharacteristicEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BedspaceSearchService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3BedspaceSearchTest.kt

This [PR CAS-1650](https://dsdmoj.atlassian.net/browse/CAS-1650) is to add the possibility to filter bedspaces based on Men only or Women only

CAS-1650 Add Men/Women only filter to bedspace search

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1BookingToSpaceBookingSeedJob.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/seed/cas1/Cas1BookingToSpaceBookingSeedJobTest.kt

This adds an additional layer of safety whilst we test this process in pre-prod.

Disable booking to space booking in prod

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3BedspaceTransformer.kt
src/main/resources/static/cas3-api.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3BedspaceTransformerTest.kt

This [PR CAS-1610](https://dsdmoj.atlassian.net/browse/CAS-1610) is to create a new Api endpoint for get bedspace in Cas3PremisesController

CAS-1610 Create CAS3 Get bedspace Api endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1OasysController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/OASysSectionsTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1OASysNeedsQuestionTransformer.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/cas1-schemas.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1OASysNeedsQuestionTransformerTest.kt

* Update CAS1 OASys Type naming for consistency
* Refactor `OASysSectionsTransformer` and remove duplication
This is in preparation for adding a CAS1 specific version of the Oasys answers endpoint

APS-2355 Remove OASys Transformer Duplication

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/events/cas1/model/ApplicationExpired.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/scheduled/Cas1ExpiredApplicationsScheduledJob.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ExpiredApplicationsScheduledJobTest.kt

PR No 1 for  [](url)https://dsdmoj.atlassian.net/browse/APS-2296.
Update the `Cas1ExpiredApplicationsScheduledJob`

Update expired applications job

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/Cas2ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2ApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2AssessmentNoteService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas2/Cas2UserAccessService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/NomisUserTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas2/TimelineEventsTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/NomisUserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas2/Cas2UserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/entity/cas2/Cas2ApplicationEntityTest.kt

We have added a set of abstract accessor methods to the cas application. This PR switches the CAS2 API to use them. The tests are unaltered as we want to ensure backward compatibility.  Future PRs will add tests to specifically test delius users as well as the nomis ones covered by existing tests
https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4603314478/CAS+ways+of+working+API+edition](https://dsdmoj.atlassian.net/browse/CBA-669
<hr />
{chore/feature}/CAS-{TICKET-NUMBER}-{description-separated-by-hyphens} (e.g. feature/CAS-123-add-booking-system)
the lines after explain what this PR is for
1. Put eyes emoji 👀 on Slack message to let the PR owner know you are checking the code
2. Complete a thorough code review adding comments if necessary
3. Approve or reject the review (resolving any …

Update Cas2 Applications to use abstracted getters

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ExpireUnsubmittedApplicationsScheduledJobTest.kt

Add some applications created within the 6 months threshold

APS-2296 Expire Unsubmitted Applications Coverage

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
src/main/resources/static/cas3-api.yml
src/main/resources/static/cas3-schemas.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3PremisesServiceTest.kt

This [PR CAS-1613](https://dsdmoj.atlassian.net/browse/CAS-1613) is to Create a new Api endpoint `POST /cas3/premises/{premisesId}/bedspaces` in Cas3PremisesController to create a bedspace

CAS-1613 Create Cas3 bedspace Api endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas2/Cas2ApplicationAssignmentEntity.kt

The prison assignment work happened after cas2v2 was branched and in this case the prison assignment will *only* be made by a nomis based POM. We talked this through with a CAS2 dev and it was decided that we would leave this on the first pass and look at migrating it to the cas2 user a later point.
{chore/feature}/CAS-{TICKET-NUMBER}-{description-separated-by-hyphens} (e.g. feature/CAS-123-add-booking-system)
the lines after explain what this PR is for
1. Put eyes emoji 👀 on Slack message to let the PR owner know you are checking the code
2. Complete a thorough code review adding comments if necessary
3. Approve or reject the review (resolving any comments)
4. Comment on Slack message to let the PR owner know you have finished your review (✅ or ❌)
1. Respond to any comments
2. Make code …

feat: note about users in application assignment entity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/TaskTransformer.kt
src/main/resources/static/_shared.yml
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/TaskTransformerTest.kt

Ref: https://dsdmoj.atlassian.net/browse/APS-2207
- add apType to Task in `_shared.yml`
- add property to `transformAssessmentToTask()` and `transformPlacementApplicationToTask()`
- assert new property in tests

APS-2207 Add apType to Task.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/jpa/entity/Cas2ApplicationNoteEntity.kt
src/main/resources/db/migration/all/20250612092230__add_cas2user_entity_to_cas2_note_application_entity.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/unit/service/Cas2AssessmentNoteServiceTest.kt

https://dsdmoj.atlassian.net/browse/CBA-691
This PR adds a the cas2 user entity to the cas2 app note entity. some earlier work is evident here with the creation of a cas user interface. the original author of the cas2 user entity is no long on project. Adding the cas2 user entity should be merged with the cas user interface in future work. 
<hr />
{chore/feature}/CAS-{TICKET-NUMBER}-{description-separated-by-hyphens} (e.g. feature/CAS-123-add-booking-system)
the lines after explain what this PR is for
1. Put eyes emoji 👀 on Slack message to let the PR owner know you are checking the code
2. Complete a thorough code review adding comments if necessary
3. Approve or reject the review (resolving any comments)
4. Comment on Slack message to let the PR owner know you have finished your review …

feat(bail): adds a cas2 user entity to Cas2ApplicationNoteEntity

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas3/TemporaryAccommodationPremisesSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
src/main/resources/db/migration/all/2025061709175000__add_start_date_to_temporary_accommodation_premises.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/TemporaryAccommodationPremisesEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/BookingTransformerTest.kt

This [PR CAS-1707](https://dsdmoj.atlassian.net/browse/CAS-1707) is to add start date to temporary accommodation premises table

CAS-1707 Add Start date to temporary accommodation premises table

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3PremisesSearchResultsTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3PremisesSummaryTransformer.kt
src/main/resources/static/cas3-api.yml
src/main/resources/static/cas3-schemas.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesSearch.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3PremisesSearchResultsTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3PremisesSummaryTransformerTest.kt

This [PR CAS-1702](https://dsdmoj.atlassian.net/browse/CAS-1702) is to create a CAS3 Premises Search Api endpoint

CAS-1702 Create CAS3 Premises Search Api endpoint

---

.dependencycheckignore.xml
build.gradle.kts

Also add the `.xml` extension to the file to trigger IDE validation

Fix broken dependency check xml

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/main/resources/static/cas1-api.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAnApprovedPremises.kt

This is the default pull request description template, providing guidance on the pull request process. Usage of this
template is optional but encouraged!
For more detail: https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4603314478/CAS+ways+of+working+API+edition
{chore/feature}/CAS-{TICKET-NUMBER}-{description-separated-by-hyphens} (e.g. feature/CAS-123-add-booking-system)
the lines after explain what this PR is for
1. Put eyes emoji 👀 on Slack message to let the PR owner know you are checking the code
2. Complete a thorough code review adding comments if necessary
3. Approve or reject the review (resolving any comments)
4. Comment on Slack message to let the PR owner know you have finished your review (✅ or ❌)
1. Respond to any comments
2. Make code changes
3. Comment on Slack message …

Cru management id filter

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2v2/jpa/entity/Cas2v2ApplicationEntity.kt

No Ticket.
This fixes the the SQL order by in the application entity to match the cas2 application
All tests pass

fix: switches the annotaion for order by in cas2v2 application entity

---

src/main/resources/db/migration/all/20250624151823__unassign_cas1_workflow_manager.sql

This is in preparation for its complete removal

Unassign CAS1 workflow manager from all users

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3BookingServiceTest.kt

This [PR CAS-1767](https://dsdmoj.atlassian.net/browse/CAS-1767) is to:
-  Add validation to prevent creating a booking before bedspace end date
- Tide up the create bookings tests
- Change the createBooking method for CAS3 to return CasResult

CAS-1767 Fix an issue when create a booking before bedspace start date

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1TasksController.kt
src/main/resources/static/codegen/built-api-spec.yml
src/main/resources/static/codegen/built-cas1-api-spec.yml
src/main/resources/static/codegen/built-cas2-api-spec.yml
src/main/resources/static/codegen/built-cas2v2-api-spec.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1TasksTest.kt

return a 404 if a request is made to retrieve a non-submitted placement application as a task

Unsubmitted placement apps are not tasks

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas3/Cas3BedspaceTransformer.kt
src/main/resources/static/cas3-schemas.yml
src/main/resources/static/codegen/built-cas3-api-spec.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3BedspaceTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas3/Cas3BookingTransformerTest.kt

This [PR CAS-1682](https://dsdmoj.atlassian.net/browse/CAS-1682) is to make bedspace start date not nullable

CAS-1682 Make bedspace start date not nullable

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/cas1/Cas1WithdrawPlacementRequestSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementRequestService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1RequestForPlacementService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingCreateService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1WithdrawableTreeOperations.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/AssessmentServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1AssessmentServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementRequestServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1RequestForPlacementServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingCreateServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeBuilderTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1WithdrawableTreeOperationsTest.kt

Despite the filename being `Cas1PlacementRequestService`, the class definition was `PlacementRequestService`. This commit fixes that

Fix Cas1PlacementRequestService mismatch

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas3/Cas3UpdatePremisesStartDateJob.kt

This Pull Request introduces updates to the Cas3UpdatePremisesStartDateJob to ensure transactional consistency when updating premises start dates by utilizing a TransactionTemplate. It also extends dependencies injected into the class.
Main Changes:
- Introduced TransactionTemplate for transactional handling during updates.
- Added BedRepository and TransactionTemplate as dependencies injected into the job class.
- Updated logic in execute method to wrap bedspace-related updates within a transaction, using the TransactionTemplate to handle consistency.
- Improved logging around premises updates or absence of relevant bedspace data.

CAS-1708: C3 BE Migration set start_date for premises, txn fix

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/controller/Cas2AssessmentsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2v2/controller/Cas2v2ApplicationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3ArchiveBedspace.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DeletePremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/DeleteRoomController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1SpaceBookingController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas3/Cas3ReportsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas3/Cas3VoidBedspaceEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/model/Cas3ValidationErrors.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/problem/BadRequestProblem.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/results/CasResult.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/DeserializationValidationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas3/Cas3PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/EntityUtils.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/seed/SeedCas1OutOfServiceBedTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas3/Cas3PremisesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/util/CasResultAssertions.kt

This [PR CAS-1625](https://dsdmoj.atlassian.net/browse/CAS-1625) is to:
- Add Cas3 Archive bedspace Api endpoint
- Add Cas3ValidationErrors to return more details in the validation error message
- Change BadRequestProblem to accept Map<String, ParamDetails>

CAS-1625 Add Cas3 Archive Bedspace Api endpoint

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/OffenderServiceTest.kt

These are functionally identical to `GetPersonInfoResult`, but instead provide a strategy.

Add tests for `GetPersonInfoResultWithStrategy`

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/ApprovedPremisesUserRole.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/resources/static/codegen/built-cas1-roles.json

Ref: https://dsdmoj.atlassian.net/browse/APS-2480
Add new `AP_AREA_MANAGER` role and assign `CAS1_VIEW_MANAGE_TASKS` permission.

APS-2480 - Add new AP Area Manager role.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/ApprovedPremisesUserPermission.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserPermission.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PremisesLocalRestrictionEntity.kt
src/main/resources/db/migration/all/20250717084501__add_cas1_premises_local_restrictions_table.sql
src/main/resources/static/codegen/built-cas1-roles.json

[https://dsdmoj.atlassian.net/browse/APS-2518](url)

Create table for premises local restrictions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/PlacementRequestsApi.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/PlacementRequestsApiDelegate.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/PlacementRequestsController.kt

This is being added until the UI has removed references to it from the code

Temporarily re-add legacy booking stub

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2v2/service/Cas2v2UserAccessService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2v2/integration/Cas2v2ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2v2/unit/service/Cas2v2UserAccessServiceTest.kt

https://dsdmoj.atlassian.net/browse/CBA-723

fix(bail): remove submitted application from prison visibility

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PremisesLocalRestrictionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/cas1/Cas1PremisesLocalRestrictionEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2518](url)

Add GET/DELETE endpoints for restrictions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/EntityUtils.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas3/Cas3PremisesTest.kt

This PR is to return the correct error type when is the Api returns bad request

CAS-1625 Return the correct error type when is bad request

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/Cas1Premises.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/cas1/Cas1PremisesLocalRestrictionEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1PremisesTransformer.kt
src/main/resources/db/migration/all/20250721163650__add_index_to_cas1_premises_local_restrictions.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1PremisesTransformerTest.kt

https://dsdmoj.atlassian.net/browse/APS-2519

Add local restriction to get premises

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/UserTransformerTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2523](url)
[https://dsdmoj.atlassian.net/browse/APS-2473](url)
`These permissions are restricted to non-production environments, as experimental permissions are not allowed in production`

Add experimental permissions to CRU member

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1BookingNotMadeReallocationJob.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/givens/GivenAPlacementRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/migration/cas1/Cas1BookingNotMadeReallocationJobTest.kt

Some older placement requests appear to have been duplicated. This commit adds some logic to find the most suitable of those duplicates

APS-2586 improve booking not made reallocation job logic

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/BookingServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2582](url)

Remove cas1 logic from date change

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1AssessmentService.kt

These commits have been cherry picked from an already approved PR https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/3951 to try and decrease the size of that PR which will not be merged for at least a few more days.

APS-2547 Placement Application & Assessments Tidy Up

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1TasksController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserAccessService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt

Ref: https://dsdmoj.atlassian.net/browse/APS-2480
This PR adds `CAS1_TASKS_LIST` permission to `CAS1_AP_AREA_MANAGER` role and refactors the existing CAS 1 task integration tests so we can adequately test the endpoint access using roles and permissions.

APS-2480 Add CAS1_TASKS_LIST to CAS1_AP_AREA_MANAGER

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/ApprovedPremisesUserRole.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/UserRole.kt
src/main/resources/static/codegen/built-cas1-roles.json
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementRequestsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/UsersTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1OutOfServiceBedTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PlacementRequestTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ReferenceDataTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceBookingTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1SpaceSearchTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1TasksTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/reporting/Cas1PlacementReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserAccessServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2580](url)

Remove deprecated cru roles.

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/BookingTest.kt

CAS1 no longer uses this endpoint and as such all tests should use CAS3 bookings.
This unblocks removing some CAS1 logic from the endpoint

Use CAS3 Bookings in Bookings Tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/Cas1ProfileResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ProfileController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ProfileTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2601](url)

Add GET CAS1 user profile endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/cas1/Cas1CapacityPerformanceTestJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1BookingManagementService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1OutOfServiceBedSummaryService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingCreateService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1SpaceBookingUpdateService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/cas1/Cas1NationalOccupancyTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1BookingManagementServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1OutOfServiceBedSummaryServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PremisesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingCreateServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1SpaceBookingUpdateServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/cas1/Cas1NationalOccupancyTransformerTest.kt

This commit renames various fields and functions in `Cas1PremisesService` in preperation for future changes.

Cas1PremisesService tidy

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/migration/BookingStatusMigrationJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/model/BedUtilisationReportData.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/model/BookingsReportDataAndPersonInfo.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/repository/BedSearchRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/repository/BedUsageRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/repository/BedUtilisationReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/repository/BookingsReportRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3BedspaceSearchService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/transformer/Cas3BedspaceSearchResultsTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/MigrationJobService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/factory/Cas3CandidateBedspaceFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/migration/MigrateBookingStatusTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/reporting/util/Cas3ReportsTestHelper.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3BedSearchServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3ReportServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/transformer/Cas3CandidateBedspaceTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/util/ReportsTestHelper.kt

Moves some cas3 specific code into the corresponding package

Move cas3 code into cas3 package

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/SubmitApprovedPremisesApplication.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/ApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ApplicationCreationService.kt
src/main/resources/db/migration/all/20250801114616__add_approved_premises_applications_duration.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1ApplicationCreationServiceTest.kt

This is currently always optional. Once the UI is populating this field we’ll make it mandatory if an arrival date has been specified

APS-2614 - Capture optional requested placement duration on application submission

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt

This [PR CAS-1625](https://dsdmoj.atlassian.net/browse/CAS-1625) is to modify limit past archiving bedspace date

CAS-1625 Amend limit archiving bedaspace date

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/ProfileResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/ProfileController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/UsersController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1ProfileController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1UsersController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/migration/UpdateAllUsersFromDeliusJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/AbstractUsersSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UpdateUsersFromApiSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/seed/UsersBasicSeedJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/UserService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/UserTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ProfileTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ProfileTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/UserServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2610](url)

Return unsupportedProbationRegion on user profile

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt

This [PR CAS-1731](https://dsdmoj.atlassian.net/browse/CAS-1731) is to archive the premises when the last online bedspace has been archived

CAS-1731 Archive the premises when the last online bedspace has been archived

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/RequestForPlacement.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/AssessmentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/ApprovedPremisesApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationServiceTest.kt

Rationale for this is described in the function’s javadoc

APS-2547 - Add function to create placement app automatic

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/transformer/Cas3PremisesTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt

This [PR CAS-1718](https://dsdmoj.atlassian.net/browse/CAS-1718) is to return the correct premises status when get a premises

CAS-1718 When get premises returns the correct premises status

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/CAS3BedspaceUnarchiveEvent.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/model/Cas3BedspaceArchiveActions.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventBuilder.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3DomainEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/DomainEventEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3DomainEventServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt

This [PR CAS-1829](https://dsdmoj.atlassian.net/browse/CAS-1829) is to add archive history to GET premises bedspaces api endpoint

CAS-1829 Add archive history to Get bedspaces endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt

This [PR CAS-1726](https://dsdmoj.atlassian.net/browse/CAS-1726) is to archive a premises without bedspaces

CAS-1726 Archive premises without bedspaces

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/SubmitPlacementApplication.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationService.kt
src/main/resources/db/migration/all/20250807124447__add_expectedArrivalFlexible_to_placement_application.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1PlacementReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1RequestForPlacementReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationServiceTest.kt

Part 1 &2 for  [https://dsdmoj.atlassian.net/browse/APS-2631](url)
- Added expected_arrival_flexible to placement applications.
- Updated service to persist the same.

Add expected_arrival_flexible column

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/Cas1KeyWorkerAllocation.kt

This helps unblock some UI work, and for now is always null

APS-2674 - Add Cas1KeyWorkerAllocation. keyWorkerUser

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesSearchTest.kt

This [PR CAS-1702](https://dsdmoj.atlassian.net/browse/CAS-1702) is to change the way that filter premises by status

CAS-1702 Change filtering by premises status

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/SubmitPlacementApplication.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas1/Cas1PlacementApplicationsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationService.kt
src/main/resources/db/migration/all/20250814112702__add_release_type_to_placement_application.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1PlacementMatchingOutcomesV2ReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1PlacementReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1RequestForPlacementReportTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/PlacementApplicationsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2629](url)

Add releaseType,sentenceType,and situation fields

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/SubmitPlacementApplication.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationServiceTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2629](url)

Deprecated placement type.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt

This PR CAS-1822 is to archive premises before premises bedspaces

CAS-1822 Archive premises before archiving bedspaces of the premises

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/ApprovedPremisesApplication.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationsTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/ApplicationsTransformersTest.kt

[https://dsdmoj.atlassian.net/browse/APS-2632](url)

Add release/sentence type to application.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt

This [PR CAS-1913](https://dsdmoj.atlassian.net/browse/CAS-1913) is to cancel scheduled archiving premises and associated bedspaces when cancel archive a bedspace in the premises

CAS-1913 Cancel scheduled archive bedspace in a premises scheduled to archive

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt

This PR CAS-1625 is to fix integration test to unblock pipeline

CAS-1625 Fix integration test

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1ReportService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/reporting/Cas1ApplicationV2ReportTest.kt

https://dsdmoj.atlassian.net/browse/APS-2708

Exclude personal characteristics

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/service/Cas3PremisesService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt

This PR CAS-1625 is to fix archive bedspace with turnaround integration test

CAS-1625 Fix archive bedspace with turnaround integration test

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/Cas1PlacementRequestDetail.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/api/model/PlacementApplication.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PlacementApplicationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/PlacementRequestDetailTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/RequestForPlacementTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/factory/PlacementApplicationEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/PlacementRequestDetailTransformerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/transformer/RequestForPlacementTransformerTest.kt

https://dsdmoj.atlassian.net/browse/APS-2631 (Part 3)

Return expected arrival flexible.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/migration/Cas1BackfillAutomaticPlacementApplicationsJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/cas1/Cas1PlacementApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas1/integration/migration/Cas1BackfillAutomaticPlacementApplicationsJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1AssessmentTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/cas1/Cas1PlacementApplicationServiceTest.kt

https://dsdmoj.atlassian.net/browse/APS-2723

Add Release Type info to auto placements.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/controller/Cas3PremisesController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/transformer/Cas3PremisesTransformer.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt

Change the code to use isPremisesArchived function to determine the premises status

CAS-1920 Change code to use isPremisesArchived to determine the premises status

---

src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/unit/service/Cas3PremisesServiceTest.kt

This PR CAS-1921 is to review uni tests:
- To remove duplicated code
- To create common functions

CAS-1921 Review archive/unarchive premises and bedspaces uni tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/PremisesEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesSearchTest.kt

This PR CAS-1975 is to not return upcoming properties when search for online premises

CAS-1975 Don't return upcoming properties in online premises in premises search

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/migration/Cas3UpdateBedspaceCreatedDateJob.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/jpa/entity/BedEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/migration/Cas3UpdateBedspaceCreatedDateJobTest.kt

This [PR CAS-1977](https://dsdmoj.atlassian.net/browse/CAS-1977) is to  populate created date for cas3 bedspaces

CAS-1977 Migration job to populate created date for cas3 bedspaces

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/reporting/model/TransitionalAccommodationReferralReportRow.kt

This PR is to move columns destinationRegion and destinationPdu after pdu column

CAS-1912 Move referral report columns

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/jpa/entity/Cas2UserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/jpa/entity/ExternalUserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/jpa/entity/NomisUserEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/migration/Cas2MergeMigrationJob.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/factory/ExternalUserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/factory/NomisUserEntityFactory.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2/integration/migration/Cas2MergeMigrationJobTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas2v2/factory/Cas2v2UserEntityFactory.kt

Reverts ministryofjustice/hmpps-approved-premises-api#4302

Revert "bug/CAS-1961-fix-created-at-dates-to-carry-from-origin"

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/transformer/ApplicationTimelineNoteTransformer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/integration/cas1/Cas1ApplicationTest.kt

Add `createdBySummary` to `Cas1TimelineEvent` returned from `ApplicationTimelineNoteTransformer.kt`.

APS-2770 Add createdBySummary to Cas1TimelineEvent

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/ApplicationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/unit/service/ApplicationServiceTest.kt

This PR fixes this issue: 
https://ministryofjustice.sentry.io/issues/6725030966/?alert_rule_id=15300595&alert_type=issue&notification_uuid=1174e712-2bae-486a-a0a5-7206d8c8f603&project=4503931792392192&referrer=slack

Acquire lock when we update cas3 application

---

src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/jpa/entity/Cas3VoidBedspaceEntity.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/cas3/integration/Cas3PremisesTest.kt

This [PR CAS-2046](https://dsdmoj.atlassian.net/browse/CAS-2046) is to fix an issue when check if a bedspace can archive and there are a void that is cancelled

CAS-2046 Fix issue can archive bedspace when a void is cancelled
